Synchronized the query builder library code.
Automattic/jetpack pull request #10082
Opened 2018-08-30 21:51 UTC by zinigor

This is a change that brings the query builder code into sync with WordPress.com code. There are no changes to the logic, just slight refactoring.

cc @gibrown for a review. This is a complementary diff to D17776-wpcom.

2018-08-30 21:53 UTC, nickdaugherty submitted a review, later dismissed
LGTM

2018-09-04 18:25 UTC, gibrown requested changes
So I think the build_filter() call got added in r163216-wpcom. Merging this will end up with the filter getting added to the query twice. Doesn't necessarily break anything, but makes the query less efficient.

The way this is used (I think everywhere) is like this: https://github.com/Automattic/jetpack/blob/master/modules/search/class.jetpack-search.php#L1125

@gravityrail do you know the background of why you needed this? Can we just specify the filter in that case instead? I know this is from a while ago, but seems like it would be better to not merge this into JP and to revert it on wp.com.

2018-09-04 19:46 UTC, gibrown commented
Per discussion in D17776 I think we should maybe deal with the change at line 275 separately.

2018-09-17 22:51 UTC, gravityrail commented
@gibrown too long ago now for me to remember the reason for adding that line of code, sorry.

2021-10-05 12:50 UTC, zinigor commented
This is probably too far gone to try to fix. If this file is still out of sync, we should start over.

2021-10-05 12:50 UTC, closed without merging