Update: Replace polldaddy shortcode with crowdsignal
Automattic/jetpack pull request #10098
Opened 2018-09-05 12:41 UTC by ice9js

As a first step for pabtAt-r-p2, this PR introduces a new `crowdsignal` shortcode which takes over the functionality of `polldaddy`. The latter will remain functional as an alias to `crowdsignal`.  

#### Testing instructions:

You should be able to embed polls/surveys and ratings through both `polldaddy` and `crowdsignal` shortcodes.

#### Proposed changelog entry for your changes:

Replaces `polldaddy` shortcode with `crowdsignal`.

2018-09-05 17:20 UTC, jeherve reviewed
What's your timeline for this? Would you like this to be included in the next release, scheduled to be released at the beginning of next month?

Other than that, I would recommend that we leave the `modules/shortcodes/polldaddy.php` as a stub, to avoid issues in some environments. See https://github.com/Automattic/jetpack/blob/master/modules/debug.php

Other than that, the changes seem to work well. 👍

2018-09-07 16:35 UTC, ice9js commented
>What's your timeline for this? Would you like this to be included in the next release, scheduled to be released at the beginning of next month?

Our current approach is to get everything in place before deciding on an exact launch date.  
I think I'd be most comfortable with making a few more PR's off this branch - for easier review as all other work is based on it - and merge everything before the launch.

We don't want to update any public references before the launch and I think it'll be easier to manage everything together.

>Other than that, I would recommend that we leave the modules/shortcodes/polldaddy.php as a stub, to avoid issues in some environments.

Done 😄

2018-10-14 09:47 UTC, dbtlr submitted a review, later dismissed

2018-10-15 09:39 UTC, jeherve commented
Is this ready for a review now?

2018-10-15 09:58 UTC, ice9js commented
Hey @jeherve! Yeah, it's ready.

2018-10-15 10:10 UTC, jeherve commented
Thanks! It looks like this will need a rebase before it can be tested and merged though.

Thank you!

2018-10-15 10:17 UTC, ice9js commented
I rebased the branch - should be all right now :)

2018-10-15 11:07 UTC, jeherve requested changes
This looks good, I only have a few remarks.

2018-10-15 15:34 UTC, ice9js commented on modules/shortcodes/crowdsignal.php
> +wp_oembed_add_provider( '#https?://poll\.fm/.*#i', 'https://api.crowdsignal.com/oembed', true );
Yeah, this is done as part of pMz3w-96r-p2.

2018-10-15 15:37 UTC, ice9js commented on modules/shortcodes/crowdsignal.php
> +wp_oembed_add_provider( '#https?://.*\.survey\.fm/.*#i', 'https://api.crowdsignal.com/oembed', true );
Thank you for asking this! This is exactly the reason why I added the other two as well.
I initially skipped `polldaddy.com` as those links will become deprecated but considering this again - we still need this compatibility.

I added the missing provider.

2018-10-15 15:40 UTC, ice9js commented on modules/shortcodes/crowdsignal.php
> +		return jetpack_preg_replace_outside_tags( '!(?:\n|\A)http://(polldaddy.com/poll|poll.fm)/([0-9]+?)/(.+)?(?:\n|\Z)!i', "\n<script type='text/javascript' charset='utf-8' async src='//static.polldaddy
Thanks for noticing this! Embed JavaScript will still be served from `static.polldaddy.com` but we should redirect to `poll.fm`.  
I also updated the expression to correctly match & replace both `polldaddy.com` and `poll.fm` links. For now I used `preg_replace` for better readability but can switch back to nested `jetpack_preg_replace_outside_tags` calls if you think performance impact will be too much.

2018-10-15 18:56 UTC, jeherve submitted a review, later dismissed
It seems the changes broke some of our shortcodes, when using a custom domain. Here is an example:

`[polldaddy type="iframe" survey="EB151947E5950FCF" height="auto" domain="jeherve" id="a-survey-with-branches"]`

<img width="1432" alt="screenshot 2018-10-15 at 20 56 20" src="https://user-images.githubusercontent.com/426388/46971618-ca399300-d0bc-11e8-83c3-54cd21aabd1b.png">

2018-10-16 14:59 UTC, ice9js commented
Thanks for spotting that! Should be taken care of now :)

2018-10-17 10:03 UTC, jeherve requested changes
I seem to have trouble displaying polls when they are added with just a link and rely on oEmbed. Here is the JS error I get:

<img width="1435" alt="screenshot 2018-10-17 at 12 01 38" src="https://user-images.githubusercontent.com/426388/47078919-9ff2ed00-d204-11e8-9cfa-62fe25fb8587.png">

I only inserted this in the editor:

`https://polldaddy.com/poll/7910844/`

2018-10-17 12:11 UTC, jeherve commented
The other shortcodes and embed methods appear to work well; for some reason only this seems to fail. I am afraid I don't have much more info about it. It is on an installation of WordPress that uses the latest Stable version of Core, and Jetpack with your branch.

<img width="832" alt="screenshot 2018-10-17 at 13 53 21" src="https://user-images.githubusercontent.com/426388/47084572-2105b080-d214-11e8-9aca-d65cc7e882ac.png">

It seems to fail because of the error above:

> Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

I have nothing else in the post content. Here is the output:

```html

<div class="entry-content">
<p><script type='text/javascript' charset='utf-8' async src='//static.polldaddy.com/p/7910844.js'></script><noscript> <a href='https://poll.fm/7910844'>View Poll</a></noscript></p>
</div><!-- .entry-content -->
```

This happens in Chrome.

2018-10-17 12:37 UTC, ice9js commented
For some reason I thought the issue was within the editor itself, not the published post. Indeed removing `async` from the `<script>` tag seems to have helped and that's what I went with for now.

Eventually this should be addressed in Crowdsignal itself, however due to pabtAt-1f-p2 that will probably take a while.

2018-10-17 13:13 UTC, jeherve approved these changes
This looks good to me now, I've tried all the formats I could think of and did not run into issues. I would love if someone else from your team could test and review as well, though!

Thank you!

2018-10-17 17:13 UTC, kraftbj commented
Once we're finally ready, we'll need to take over and manually apply the patches to D18089-code, including updating the build script to the new file paths while spreading it over a couple of commits.

2018-10-22 19:20 UTC, kraftbj commented
@ice9js - If everything is ready, could you have someone more familiar with the changeover give this a look? I'm manually marking the WP.com sync test as successful and I can work on doing the actual sync work once this lands.

2018-10-22 19:41 UTC, ice9js commented
@kraftbj - apologies for the delay there. We currently have our hands full with pabtAt-2q-p2.  
Once that's taken care of @dbtlr or @donnchawp will have a look later this week. We definitely still do want to get this out with the next release.

2018-10-22 19:51 UTC, kraftbj commented
@ice9js Understood. Tuesday the 30th is code freeze for anything not regressions, so trying to give y'all time to make sure this makes it in.

2018-10-22 19:52 UTC, ice9js commented
Thanks for the heads up!

2018-10-23 09:33 UTC, dbtlr commented
We're ready to go live with the next Jetpack release. What can we do to get this merged with wpcom?

2018-10-24 09:02 UTC, jeherve commented
@dbtlr Could someone on your team review and test this PR, so we can get this merged and included in the next release?

Thank you!

2018-10-26 08:28 UTC, dbtlr approved these changes
LGTM

2018-10-26 08:30 UTC, merged

2018-10-26 13:54 UTC, kraftbj commented
Noting that @donnchawp is handling the changes on the WP.com side to match this. I'll coordinate with him to make sure Fusion is tracking things once the dust settles.