Add target to Publicize and ShareButtons components
Automattic/jetpack pull request #10255
Opened 2018-10-02 12:04 UTC by Rahmon

Fixes #10244

Card component set the icon to 'external' when target is defined so I've set this prop in Publicize and ShareButtons components. 

#### Changes proposed in this Pull Request:

* Set target of Publicize and ShareButtons components
* Use external link icon instead of arrow

#### Testing instructions:

* Manually on Chrome
* yarn test-client and yarn test-gui

2018-10-11 11:22 UTC, jeherve requested changes
Could you add some `rel="noopener noreferrer"` there as well?
You can read more about why this is needed here: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

2018-10-16 10:40 UTC, Rahmon commented
Hi @jeherve. I've updated the PR.

2018-10-16 10:43 UTC, jeherve commented
Thank you! We'll take a look at it.

cc @Automattic/jetpack-design

2018-10-16 13:23 UTC, jeherve approved these changes

2018-10-16 13:37 UTC, rickybanister commented
That looks great @jeherve

2018-10-17 15:47 UTC, merged