Gutenpack: Expose Jetpack_Modules data
Automattic/jetpack pull request #10327
Opened 2018-10-16 06:38 UTC by sirreal

Closes #10243
Part of #10198

#### Changes proposed in this Pull Request:

* Exposes `Jetpack_Modules` global with the contents of the API response.

#### Testing instructions:

* Load the Gutenberg editor with Jetpack blocks available
* Observe the `Jetpack_Modules` global is loaded
* Calypso PR in progress

2018-10-22 10:55 UTC, sirreal commented
Github is a bit broken right now, but I'm going to attempt to request review.

This is the simplest way of exposing all the data that a block is likely to need from WP Admin.

2018-10-22 10:56 UTC, sirreal commented
Github is a bit broken right now, but I'm going to attempt to request review.

This is the simplest way of exposing all the data that a block is likely to need from WP Admin.

2018-10-22 11:21 UTC, sirreal commented
Github is a bit broken right now, but I'm going to attempt to request review.

This is the simplest way of exposing all the data that a block is likely to need from WP Admin.

2018-10-22 13:22 UTC, jeherve requested changes
I'm seeing the following warning on the editor page with your patch:

```
Warning:  Cannot modify header information - headers already sent by (output started at wp-admin/includes/template.php:2055) in wp-content/plugins/jetpack-dev/class.jetpack.php on line 5822
```

This seems to be caused by https://github.com/Automattic/jetpack/blob/09cafa10a64659f82250402a876c0039d9fb98d9/_inc/lib/admin-pages/class.jetpack-react-page.php#L299

2018-10-23 10:50 UTC, sirreal commented
I've rebased.

@jeherve I haven't been able to reproduce, what state is your site in and what steps are you taking when you see that warning?

2018-10-24 12:25 UTC, jeherve submitted a review, later dismissed
It works for me now, I am not quite sure what was wrong the first time around. ¯\_(ツ)_/¯

2018-10-26 21:24 UTC, oskosk submitted a review, later dismissed
Tests great. 🚢

2018-10-26 22:47 UTC, oskosk commented
I'm seeing the warning @jeherve mentioned... Similar
```
Cannot modify header information - headers already sent by (output started at wp-admin/includes/template.php:2053) in wp-content/plugins/jetpack-dev/class.jetpack.php on line 5849
```

And this other one:
```
Cannot modify header information - headers already sent by (output started at wp-content/plugins/gutenberg/lib/meta-box-partial-page.php:297) in wp-includes/option.php on line 920
```

2018-10-30 12:22 UTC, jeherve requested changes
Is this something we need to address in this PR, or maybe somewhere else when we tackle block availability?

2018-10-30 12:22 UTC, jeherve commented on class.jetpack-gutenberg.php
> -		if ( ! Jetpack::is_active() ) {
This seems problematic though, since we now have blocks available even when Jetpack is not connected to WordPress.com.

2018-10-30 16:01 UTC, tyxla approved these changes
This looks good and tests well 👍 🚢

2018-10-30 16:08 UTC, jeherve approved these changes
Looking good now. Merging.

2018-10-30 16:08 UTC, merged