Add support for SSO without a connection/confirmation.
Automattic/jetpack pull request #10483
Opened 2018-10-30 09:46 UTC by jaswrks

wip

2018-10-30 13:34 UTC, ebinnion requested changes
This seems reasonable. Would you write some tests for this please? 

https://github.com/Automattic/jetpack/blob/master/tests/php/modules/sso/test_class.jetpack-sso-helpers.php

2018-10-31 15:03 UTC, ebinnion submitted a review, later dismissed
I left a minor comment about the docblock. Besides that, this looks good to me and tests well. 👍

2018-10-31 15:19 UTC, jaswrks commented on modules/sso/class.jetpack-sso-helpers.php
> +	 * @since 6.8
Ah, thanks. Done.

2018-10-31 15:23 UTC, jaswrks commented
@ebinnion Should we adjust this line that pulls the current user ID?
To clarfy, should we set `user_id => 0` when it's a user that was intentionally not connected?

https://github.com/Automattic/jetpack/blob/60a18ad21721cfeefc8ac79123b11f3f52054a41/modules/sso.php#L630

I ask because I noticed a `missing_token` error whenever I was testing with a user who was already logged-in and found their way back to `wp-login.php?action=jetpack-sso` again.

2018-10-31 17:07 UTC, ebinnion commented
Ahh nice catch sir! Yes, we probably do need to change that. We can probably force it `user_id => 0` to use the blog token or we can first check to see if the current user has a token.

2018-10-31 22:18 UTC, jaswrks commented
Got it, thanks for confirming!

Also, does this look like a bug to you?
https://github.com/Automattic/jetpack/blob/7ce8c1a76257cde38e7372da992e2bc8ca3604f2/modules/sso.php#L606

Shouldn't it be `user_id => $user_id` instead of `wpcom_user_id`?

2022-03-02 09:10 UTC, closed without merging