Jetpack: Use settings search term as default module configuration URL
Automattic/jetpack pull request #10668
Opened 2018-11-19 15:51 UTC by brbrr

#### Changes proposed in this Pull Request:

* Updates `configure_url` to redirect to Jetpack Settings search term by default. Before this - it was redirecting to legacy pre-react configuration pages.

This change required by #10611 to provide flawless UX.

#### Testing instructions:

* Go to `wp-admin/admin.php?page=jetpack_modules`
* Find a module with 'Configure' button. 
* Make sure it redirects to `wp-admin/admin.php?page=jetpack#/settings?term=$MODULE`
* try some other modules. Some of them might redirect

#### Proposed changelog entry for your changes:

* Admin Page: Module configuration URLs now redirects to the relevant section in Jetpack settings

2018-11-29 17:09 UTC, jeherve submitted a review, later dismissed
While this works well, it causes issues for the modules that do not have any configuration options in the Jetpack dashboard.

- Custom CSS redirects to the customizer, where one can use the feature.
- Widgets redirects to the widgets dashboard page.
- Infinite Scroll has more options in Settings > Reading than in the JP dashboard. 

Before we flip the switch, we should consider what options would become harder to access with that change.

2018-12-03 16:58 UTC, brbrr commented
@jeherve good point. I went through all the configurable modules and updated some of the configuration URLs which miss some configuration options in Jetpack settings. I left untouched `sharing-buttons` & `publicize`, but I am not sure about that since Jetpack settings option redirects to WP.com for further configuration, which isn't really good UX.

2018-12-06 15:14 UTC, jeherve requested changes
This tests well. I just have one tiny suggestion for the Widgets module.

2018-12-06 15:14 UTC, jeherve commented on modules/widgets.php
> +	return admin_url( 'widgets.php' );
Maybe we could redirect to the customizer, since it's a newer interface to interact with widgets?

2018-12-06 16:35 UTC, jeherve approved these changes
Looking good. 👍

2018-12-07 07:02 UTC, merged