JITMs: add component to be used in the Jetpack Dashboard.
Automattic/jetpack pull request #10759
Opened 2018-11-30 19:53 UTC by jeherve

**Work in Progress, do not merge**

#### Changes proposed in this Pull Request:

JITMs: add component to be used in the Jetpack Dashboard.

#### Testing instructions:

* TBD

#### Proposed changelog entry for your changes:

* TBD

2018-11-30 20:00 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +		const ctaNewWindow = get( cta, 'newWindow', null );
`ctaNewWindow` seems to be be unused.

2018-11-30 20:01 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +										// target={ ctaNewWindow === false ? '_self' : '_blank' }
ah here's the usage of ctaNewWindow, commented out

2018-11-30 20:02 UTC, oskosk commented
`_inc/client/components/jitm/style.scss` is empty right now

2018-11-30 20:36 UTC, oskosk commented on _inc/client/state/reducer.js
> +	jitm
A comma here is ok if you want it.

2018-11-30 21:04 UTC, oskosk commented
`_inc/client/components/jitm/style.scss` is empty right now

2018-11-30 21:05 UTC, oskosk commented
I'm seeing the message encoded. Maybe we can use `lib/decode-entities/`.

![image](https://user-images.githubusercontent.com/746152/49314820-5b789380-f4ca-11e8-82b2-f5f5c729ed3c.png)

2018-11-30 21:15 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +										onClick={ this.trackLearnMore( feature_class ) }s
Tipo here, an extrac `s` at the end of the line.

Symptom was that `Button` gets rendered with and `s` prop.

```
warning.js:33 Warning: Unknown prop `s` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Button)
    in Button (created by Jitm)
    in div (created by Jitm)
```

2018-11-30 21:18 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +		const ctaNewWindow = get( cta, 'newWindow', null );
Fixed in #eaf26aaaf0613a8ae57692831f4b6ff4d30af416

2018-11-30 21:18 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +										onClick={ this.trackLearnMore( feature_class ) }s
Fixed in 63ad0ec97e39ed443462fa53383fae2d9d46e0f5

2018-11-30 21:36 UTC, oskosk commented
We can split this work in two PRs at least. This is how we've done a few things...

* One for Redux-related stuff (action, reducer selectors).
* Another one for introducing the component.

It would be cool to at least provide one or two unit tests for the redux piece of code. they're straightforward if you take another one as example. This usually speeds up work because we can easily merge the redux work if the tests pass.

2018-11-30 21:37 UTC, oskosk requested changes
I think I commented all of the previous things without using a Review.

2018-11-30 21:37 UTC, oskosk commented on _inc/client/components/jitm/index.jsx
> +		for ( const i of list ) {
let's use a more significant name here for `i`. even when it's straightforward, we should use `i` just on `for` loops, and/or standing for `index`.

2018-12-04 12:08 UTC, oskosk submitted a review, later dismissed
LGTM!

2018-12-05 17:44 UTC, jeherve commented
@AnnaMag @keoshi I'd be happy if you could give this a try when you get the chance! Thank you!

2018-12-07 13:31 UTC, oskosk approved these changes
LGTM!

2018-12-07 14:47 UTC, dereksmart commented on _inc/client/components/jitm/index.jsx
> +require( './../../../../scss/jetpack-admin-jitm.scss' );
What is this for?

2018-12-07 18:45 UTC, jeherve commented
Closing this in favor of #10889

2018-12-07 18:45 UTC, closed without merging

2018-12-07 18:49 UTC, jeherve commented
Previous changes will be reverted in #10890