Asset CDN: Fix json translation loading
Automattic/jetpack pull request #10982
Opened 2018-12-16 09:47 UTC by akirk

When the static asset CDN of Jetpack is loaded, the translations for Gutenberg don'tt load properly because the filename is generated for a wrong path.

Also fixes https://github.com/Automattic/wp-calypso/issues/29309

This has been extensively discussed in https://core.trac.wordpress.org/ticket/45528

#### Changes proposed in this Pull Request:

* This implements the filter that has been introduced into Core.

#### Testing instructions:

Prequisit: WordPress 5.0.2(alpha) or trunk

1. Set your WordPress to another language than English.
2. Activate Jetpack Static Asset CDN.
3. Potentially add a filter to your WordPress if it's running trunk (see #10102)
4. Create a new post to open Gutenberg and observe broken translations.
5. Activate the patch: Translations should now load after a reload.

#### Proposed changelog entry for your changes:

* Fixes loading of the Block Editor UI translations when Static Asset CDN is used (requires WordPress 5.0.2)

2018-12-17 09:13 UTC, jeherve commented
I am not quite sure how to test this. When running a development version of WordPress, the Asset CDN is not applied because that version of WP is not available in a tag. I can use the `jetpack_cdn_core_version_and_locale` filter to fake a stable release, like so:

```php
add_filter( 'jetpack_cdn_core_version_and_locale', function( $values ) {
	return array( '5.0.1', 'fr_FR' );
} );
```

But if I do so, the editor does not load at all for me because I am trying to load the block editor from the Alpha version of WP with some outdated JS from the 5.0.1 version of WP.

![image](https://user-images.githubusercontent.com/426388/50077344-69c1f180-01e4-11e9-9b05-bf691fc6e65f.png)

How did you manage to test this? Am I missing something here?

2018-12-17 12:32 UTC, jeherve commented
👍 So I should have a 5.0.1 + manually apply the patch in https://core.trac.wordpress.org/changeset/44209 ?

2018-12-17 12:40 UTC, akirk commented
Yes, exactly!

2018-12-17 13:49 UTC, akirk commented
@jeherve I updated the patch, the filter was missing two parameters which caused a fatal. Maybe that broke Gutenberg for you? I just tried with a trunk WordPress and 
```
add_filter( 'jetpack_cdn_core_version_and_locale', function( $values ) {
	return array( '5.0.1', 'de_DE' );
} );```
and it loads up fine for me.

2018-12-17 14:31 UTC, jeherve requested changes
It works well for me. There is just a tiny indenting issue!

2018-12-18 12:54 UTC, zinigor commented
@jeherve the indentation should be fixed now, thanks for testing!

2018-12-18 13:13 UTC, jeherve approved these changes
Working well. Merging.

2018-12-18 13:14 UTC, merged