Jetpack monitor verbiage update. changing USA centric idiom
Automattic/jetpack pull request #11008
Opened 2018-12-19 15:11 UTC by jeffgolenski

Jetpack monitor descriptive text in settings. Removing a USA-centric idiom, "keep tabs on."  Replaced with "Continuously watches"

Fixes https://github.com/Automattic/jetpack-com/issues/77

Before:
![image](https://user-images.githubusercontent.com/87168/39438288-3ccfd78e-4cac-11e8-9d8c-d747a113c59c.png)

After:
coming soon

#### Proposed changelog entry for your changes:

* no proposed changlog entry. Just a minor text update

Testing instructions:

1) Sync up with this branch
2) Navigate to security settings. Find Monitor card
3) Click / tap the i icon

2018-12-19 16:22 UTC, jeherve requested changes
This looks good, apart from a typo with continuously I think.

2018-12-19 16:22 UTC, jeherve commented on _inc/client/security/monitor.jsx
> +							text: __( 'We will contiously watch your site and receive alerts the moment downtime is detected.' ),
I think you meant "continuously" maybe?

2018-12-19 18:46 UTC, jeffgolenski commented
@jeherve good find. I was just having some difficultly with git and this brand, but sorted it out (don't mind all the commits). Can you give it another review?

2018-12-19 18:56 UTC, jeherve requested changes
Sorry, I'm nit-picking again.

2018-12-19 18:56 UTC, jeherve commented on _inc/client/security/monitor.jsx
> +							text: __( 'We will continuously watch your site and receive alerts the moment downtime is detected.' ),
Should it say "and you will"? Right now it sounds like "we" will receive the alerts.

2018-12-20 14:40 UTC, jeffgolenski commented
thanks. I'm having trouble with git right nowI thought I updated that

2018-12-20 15:09 UTC, jeffgolenski commented
Alright. @jeherve I think we're good. Can you give this another review?

2018-12-20 15:11 UTC, jeherve approved these changes
Looking good now! 🚢

2018-12-20 15:19 UTC, merged