Tiled gallery block: add wp-blob dependency
Automattic/jetpack pull request #11043
Opened 2018-12-27 08:19 UTC by simison

Adds `@wordpress/blob` dependency for Tiled gallery since the block depends to it as of https://github.com/Automattic/wp-calypso/pull/29559

## Testing

WIP

2018-12-27 09:44 UTC, sirreal submitted a review, later dismissed

2019-01-02 08:49 UTC, jeherve requested changes
> Hmm, I just realised this might add it to both view and editor side and we'd need it just at the editor. There doesn't seem to be a mechanism to declare them separately.

How about adding it here instead?
https://github.com/Automattic/jetpack/blob/1bebf03217db5de06800c3fc5d588312b4f85b77/class.jetpack-gutenberg.php#L472

2019-01-03 11:59 UTC, ockham commented
Rebased.

2019-01-03 12:09 UTC, ockham commented
>> Hmm, I just realised this might add it to both view and editor side and we'd need it just at the editor. There doesn't seem to be a mechanism to declare them separately.
>
> How about adding it here instead?
https://github.com/Automattic/jetpack/blob/1bebf03217db5de06800c3fc5d588312b4f85b77/class.jetpack-gutenberg.php#L472

I'll move it.

2019-01-03 12:15 UTC, ockham commented
> I haven't tested this but I suspect we can remove all other dependencies from the view side, apart maybe from `wp-i18n` that gets pulled from [constants file](https://github.com/Automattic/wp-calypso/blob/0233ccdc84055a610992d35e409c76b2981be6a3/client/gutenberg/extensions/tiled-gallery/constants.js#L6) (and not really used in [view.js](https://github.com/Automattic/wp-calypso/blob/0233ccdc84055a610992d35e409c76b2981be6a3/client/gutenberg/extensions/tiled-gallery/view.js)) but we'll need some further refactoring before we can cut out that last dependency.

Let's do that in a follow-up PR :+1:

2019-01-03 12:15 UTC, ockham approved these changes
:+1:

2019-01-03 12:35 UTC, jeherve approved these changes
Thank you! Merging now!

2019-01-03 12:35 UTC, merged