Adding support for more related posts and simplifying CSS
Automattic/jetpack pull request #11205
Opened 2019-01-25 18:49 UTC by roccotripaldi

- Backend now retrieves 6 related posts by default instead of 3, in order to support 4-6 posts in the editor.
  - Related Posts block now supports up to 6 related posts
  - The Related Posts block's output has been modified to utilize flexbox and a more semantically correct HTML, as long as the block is used

This commit was generated from D23362-code.

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

*

2019-01-28 11:28 UTC, jeherve requested changes
Not sure if you are still working on this PR, but I just had a few minor remarks about the changes so far.

2019-01-28 14:44 UTC, aldavigdis commented on modules/related-posts/jetpack-related-posts.php
> +						esc_html_x( 'In “%s”', 'in {category/tag name}', 'jetpack' ),
Those are called [English quotation marks](https://en.wikipedia.org/wiki/Quotation_marks_in_English). They are being used in WP Core and I sorta-kinda expected us to follow that convention.

Those being replaced are generally referred to as inch marks.

2019-01-28 14:51 UTC, jeherve commented on modules/related-posts/jetpack-related-posts.php
> +						esc_html_x( 'In “%s”', 'in {category/tag name}', 'jetpack' ),
👍 	TIL. Thank you!

2019-01-28 14:52 UTC, aldavigdis commented on modules/related-posts/jetpack-related-posts.php
> + 					<?php esc_html_e( $related_post['date'] ); ?>
I wonder if this is an effect of the divergence between WPCOM and Jetpack. This file had diverged substantially and I'm pretty sure this isn't one of the things I touched on.

2019-01-28 14:52 UTC, aldavigdis commented on modules/related-posts/jetpack-related-posts.php
> + 					<?php esc_html_e( $related_post['context'] ); ?>
See above.

2019-01-29 03:09 UTC, roccotripaldi commented
dropping in favour of https://github.com/Automattic/jetpack/pull/11220

2019-01-29 03:09 UTC, closed without merging