Adding support for alt text to Jetpack_PostImages
Automattic/jetpack pull request #11339
Opened 2019-02-13 15:43 UTC by aldavigdis

Adds an `alt_text` key to some `Jetpack_PostImages` functions such as `Jetpack_PostImages::from_thumbnail`, returning an empty string by default.

Fixes #11175.

Some functions such as `from_blavatar` will always return an empty string.

#### Testing instructions:

Fire up `yarn docker:wp shell` and try utilising some of the modified functions. Do we always get the alt text from those images?

Does this break any functionality that depends on `Jetpack_PostImages`?

#### Proposed changelog entry for your changes:

Jetpack_PostImages now supports alt text.

2019-02-13 15:45 UTC, aldavigdis commented
I'd be happy to see alternative solutions for blavatar and gravatar images.

2019-02-13 16:37 UTC, aldavigdis commented on class.jetpack-post-images.php
> +	 * @since 7.1
Is this the correct version number?

2019-02-13 19:49 UTC, lezama commented on class.jetpack-post-images.php
> +	 * @since 7.1
👍

2019-02-13 19:51 UTC, lezama commented
re running randomly failing tests

2019-02-13 19:57 UTC, lezama commented
Code looks good 👍

2019-02-14 21:05 UTC, lezama submitted a review, later dismissed

2019-02-15 14:51 UTC, jeherve requested changes
This works well. I have a few minor requests below.

I think it would also be good to add some unit tests for this. We have a decent coverage for that file already, and I think it would make sense to add something for that alt info.
https://github.com/Automattic/jetpack/blob/d545d4f5dfd9c77b01055a7adaab05ad76656dce/tests/php/test_class.jetpack-post-images.php

I ended up doing the following to help me test different scenarios on a live site:

```diff
diff --git a/functions.opengraph.php b/functions.opengraph.php
index c83937e6f..bf4c2b0b5 100644
--- a/functions.opengraph.php
+++ b/functions.opengraph.php
@@ -175,6 +175,9 @@ function jetpack_og_tags() {
 		if ( ! empty( $image_info['height'] ) ) {
 			$tags['og:image:height'] = (int) $image_info['height'];
 		}
+		if ( ! empty( $image_info['alt_text'] ) ) {
+			$tags['og:image:alt'] = esc_attr( $image_info['alt_text'] );
+		}
 	}
 
 	// Facebook whines if you give it an empty title
@@ -294,6 +297,9 @@ function jetpack_og_get_image( $width = 200, $height = 200, $deprecated = null )
 						$image['width']  = $post_image['src_width'];
 						$image['height'] = $post_image['src_height'];
 					}
+					if ( ! empty( $post_image['alt_text'] ) ) {
+						$image['alt_text'] = $post_image['alt_text'];
+					}
 				}
 			}
 		}
```

Once you have that you can check your posts's Open Graph Meta tags and see what results you get.
I think it would make sense to add this now that we have the alt info in some cases.

I say in some cases because, as the block editor becomes popular, in more and more cases we won't actually get the alt info because of this bug:
https://github.com/WordPress/gutenberg/issues/12913

This is annoying but I could not think of an easy work-around for that. Do you think that would be necessary, or should we ship that version 1 and hope the block editor gets fixed eventually?

2019-02-15 18:43 UTC, aldavigdis commented on class.jetpack-post-images.php
> +	 * @param int $thumb The Post ID of the media.
Yeah that's true, but I did consider this a replacement for inline code.

2019-02-22 13:15 UTC, aldavigdis commented
@jeherve — I worked on some of the tests, but some, like the gallery one seem to be broken in one way or another, so I skipped those. Perhaps we should create a follow-up ticket?

2019-02-22 13:16 UTC, jeherve commented
> some, like the gallery one seem to be broken in one way or another

If you found some issues with some of those tests then yeah, definitely open an issue about it, thank you!

Is this ready for another review?

2019-02-22 15:24 UTC, aldavigdis commented
@jeherve — Yes. I'm redoing the WPCOM diff in the meantime.

2019-02-22 16:32 UTC, aldavigdis commented
Note: As the unit tests are not synced over to WPCOM in this case, diff D24308 is still valid.

2019-02-22 17:25 UTC, jeherve commented
Cool, I'll give it another look in a bit.

Small tip: if your PR is ready to review, it is best to use the Status label to indicate that.

2019-02-22 18:38 UTC, jeherve approved these changes
This tests well now. Its application is limited in the block editor because of the Gutenberg issue I mentioned earlier, but it's still very useful for other images, and featured images. Merging.

2019-02-22 18:38 UTC, merged