Business Hours Block: add support for openingHours schema
Automattic/jetpack pull request #11358
Opened 2019-02-15 02:07 UTC by roccotripaldi

adds support for openingHours schema: https://schema.org/openingHours to the business hours block.

Fixes # https://github.com/Automattic/wp-calypso/issues/30594

#### Changes proposed in this Pull Request:

* Adds relevant html properties to the business hours block
* Folks can turn off schema properties with a fileter
* Allows folks to filter their business type for the schema - in a future iteration, perhaps we can include business type somewhere within the block editor
* a few minor iterations to the block's logic / output

#### Testing instructions:

* Get this branch going locally with docker, or try it out on Jurassic.ninja
* In your site's post editor, add a business hours block
* When you publish or preview, note the business hours mark-up. You should see something like this for the opening tag:
`<dl class="jetpack-business-hours " itemscope itemtype="https://schema.org/LocalBusiness">`
* You should see something like this for each hour:
`<span itemprop="openingHours" content="Mo 18:22-19:09">From 6:22 PM to 7:09 PM</span>`

#### Proposed changelog entry for your changes:

* none

2019-02-15 12:02 UTC, jeherve requested changes
That should be a nice improvement! I only have a few remarks.

2019-02-15 12:02 UTC, jeherve commented on extensions/blocks/business-hours/business-hours.php
> +			$itemtype
Should we escape this? It should always be a URL, right?

2019-02-15 20:40 UTC, roccotripaldi commented
Thanks for the review @jeherve ! I've addressed your feedback.

I'm going to mark this as in progress because it's not as straight forward as i initially thought.

The schema here doesn't pass for [google's structured data validator](https://search.google.com/structured-data/testing-tool/u/0/).

![screen shot 2019-02-15 at 3 33 50 pm](https://user-images.githubusercontent.com/2694219/52882891-1f52e780-3137-11e9-950a-0b394b021619.png)


- We'll definitiely need a business name, and i'll need to address that in a separate PR
- We'll also need an image!? I'm not sure why that's required.
- We should also have stuff like address and phone number, and @enejb has been working on that stuff. The trick is getting Enej's work and the work here to play nicely, and that may not be feasible.


My thoughts are if we are going to do this, we should do it well, and it may be difficult to get in for this release. What do you think? Is validation a blocker?

For the first release, maybe we can just provide a filter that allows folks to insert there own schema.org markup if they want to. For example:

```
$business_hours_content = apply_filters( 'jetpack_business_hours_content', $content, $attributes );
```

2019-02-15 20:42 UTC, jeherve commented
> My thoughts are if we are going to do this, we should do it well 

I agree. I think validation should be a blocker. I do like your approach about providing a filter to modify the content for now.

2019-02-15 23:00 UTC, jeherve approved these changes
This should be good to merge now, thank you! Merging.

2019-02-15 23:01 UTC, merged

2019-02-16 04:55 UTC, simison commented
What happens when search engines find partial (invalid) schema data? 🤔 Would they just ignore it all?