Use amp-mathml for beautiful math in AMP responses
Automattic/jetpack pull request #11375
Opened 2019-02-16 22:04 UTC by westonruter

There is an AMP component specifically for MathML: [`amp-mathml`](https://www.ampproject.org/docs/reference/components/amp-mathml). In AMP responses, the Beautiful Math module should re-use this.

Given a post with the following markup:

```
A mathematical formula is $latex i\hbar\frac{\partial}{\partial t}\left|\Psi(t)\right>=H\left|\Psi(t)\right>$ and it is something that should be rendered properly.
```

In a non-AMP response the result looks like:

> ![image](https://user-images.githubusercontent.com/134745/52905744-d1c1a200-323e-11e9-802e-5fcfe3edcc29.png)

With the changes in this PR, an AMP response now renders as:

> ![image](https://user-images.githubusercontent.com/134745/52905754-fe75b980-323e-11e9-89ff-cd203e6916ca.png)

Notice the superior quality of the mathematical formula due to vector-based rendering in AMP. This works in paired AMP and native AMP modes, as well as in classic mode:

> ![image](https://user-images.githubusercontent.com/134745/52905760-177e6a80-323f-11e9-9441-13c75b5d8083.png)

See #9730 for master issue on AMP compatibility.

#### Changes proposed in this Pull Request:

* Use `amp-mathml` in Beautiful Math module to render mathematical formulas in AMP responses.

#### Testing instructions:

* Activate AMP plugin.
* Create a post with the content shown above.
* View a post in AMP (either native, paired, or classic mode).

#### Proposed changelog entry for your changes:

* Use `amp-mathml` in Beautiful Math module to render mathematical formulas in AMP responses.

2019-02-18 11:35 UTC, jeherve requested changes
This tests well on my end. I only have a minor remark below.

I also noticed that `amp-mathml` does not seem to handle errors as well as Jetpack's Beautiful Math does. You can test it by adding `$latex \LaTeX&amp;s=X$` for example.
That should not be blocking though.

2019-02-18 11:35 UTC, jeherve commented on modules/latex.php
> +			array_merge(
What do you think about doing something like this instead?

```php
$url = add_query_arg(
	urlencode_deep(
		array(
			'latex' => $latex,
			'fg'    => $fg,
			'bg'    => $bg,
			's'     => $s,
		)
	),
	'//s0.wp.com/latex.php'
);
```

2019-02-18 12:39 UTC, westonruter commented
> I also noticed that `amp-mathml` does not seem to handle errors as well as Jetpack's Beautiful Math does. You can test it by adding `$latex \LaTeX&amp;s=X$` for example.
> That should not be blocking though.

I'm not able to reproduce this I think. In `master` I get the same error when I try `$latex \LaTeX&amp;s=X$`:

> ![image](https://user-images.githubusercontent.com/134745/52951470-2ae61e80-3382-11e9-8ada-dac0d440b9d6.png)

The `s=X` in the example on https://jetpack.com/support/beautiful-math-with-latex/ is supposed to be replaced by a number. If I instead supply 4 as follows:

```html
<!-- wp:paragraph -->
<p>$latex \LaTeX&amp;s=4$</p>
<!-- /wp:paragraph -->
```

Then I see:

> ![image](https://user-images.githubusercontent.com/134745/52951542-523ceb80-3382-11e9-9d11-cc93ec631df3.png)

2019-02-18 14:18 UTC, jeherve commented
> In `master` I get the same error when I try `$latex \LaTeX&amp;s=X$`:

Right, this error is expected here; it shows that the formula is incorrect. `amp-mathml`, however, just outputs the unparsed formula instead.

2019-02-26 02:19 UTC, westonruter commented
Something else that is different about the AMP version being proposed here: colors.

When I pick a dark color scheme for Twenty Seventeen, I get the following with non-AMP:

![image](https://user-images.githubusercontent.com/134745/53381712-79695f00-3926-11e9-82e0-b149300d5585.png)

In AMP however, the background is transparent but the colors are not inherited:

![image](https://user-images.githubusercontent.com/134745/53381731-8dad5c00-3926-11e9-8378-fb19319953a2.png)

This lack color inheritance would seem to be a deficiency with the component. Given that it is in an iframe, it would not be possible for the CSS to cascade.

Given that the colors are not inheriting and given that the functionality of Beautiful Math (colors and font size) are not support by `amp-mathml`, it seems best to just close this PR for now. 

Given that Beautiful Math normally just outputs an `img` the AMP plugin will automatically convert this into an `amp-img`, so I don't believe there is anything specifically needed to make the module AMP-compatible.

2019-02-26 02:19 UTC, closed without merging