Post Images: Return attachment info when using from_thumbnail
Automattic/jetpack pull request #11451
Opened 2019-03-01 17:13 UTC by kraftbj

The `Jetpack_PostImages` class returns no post image for an `attachment` post type. We should return the image.

I attached it onto the `from_thumbnail` group since the attachment's "featured image" is itself, which made more sense to me than the other groups, not to mention matches the intent (the `from_html` and `from_attachment` is kinda weird and, personally, something I would often opt out of using).

Fixes #11413 

#### Changes proposed in this Pull Request:
* If the post we're requesting is an attachment, return the attachment's src instead of an empty string.

#### Testing instructions:
* Upload an image and note the post_id.
* Run `Jetpack_PostImages::get_image( [the id] ); via `wp shell`
* See empty string returned.
* Apply patch.
* Run command again and see an array containing image information.

#### Proposed changelog entry for your changes:
* Jetpack Post Images: Provide the image itself when requesting an attachment's post image.

2019-03-04 11:19 UTC, jeherve requested changes
Nice catch! I just have a minor nitpick.

2019-03-04 11:19 UTC, jeherve commented on class.jetpack-post-images.php
> +		if ( 'attachment' === get_post_type( $post ) && wp_attachment_is_image( $post )) {
```suggestion
		if ( 'attachment' === get_post_type( $post ) && wp_attachment_is_image( $post ) ) {
```

2019-03-05 15:59 UTC, jeherve approved these changes
Looking good. 🚢

2019-03-05 17:33 UTC, merged

2019-03-05 20:57 UTC, kraftbj commented
Deployed to wpcom via r188460-wpcom