Adding filter for Sharedaddy ajax_action.
Automattic/jetpack pull request #11610
Opened 2019-03-19 15:18 UTC by dcooney

Enhancement #11565 

#### Changes proposed in this Pull Request:

* This PR simply makes the ajax action name (`get_latest_posts`) filterable to allow other plugins and scripts to renders ShareDaddy in Ajax. 

#### Testing instructions:
I tested the new filter on my local build and a customers site running Jetpack and the Ajax Load More plugin.
![image](https://user-images.githubusercontent.com/428624/54618003-acd86e80-4a38-11e9-8c41-0d7e0f7228dc.png)

#### Proposed changelog entry for your changes:
Adding `sharing_ajax_action` filter to allow for the rendering of ShareDaddy in other Ajax requests.

2019-03-19 16:47 UTC, jeherve requested changes
Thanks for the submission. I've made a few comments to improve the filter and how it will be documented.

2019-03-19 16:47 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_REQUEST['action'] ) && apply_filters('sharing_ajax_action', 'get_latest_posts') == $_REQUEST['action'] ) {
Could you split this into separate lines, and add a docblock as it's done here?
https://github.com/Automattic/jetpack/blob/216c8378ef24d6a1569232c2498767970a942872/modules/sharedaddy/sharing-service.php#L90

We use the docblock to automatically generate pages in the Jetpack codex:
https://developer.jetpack.com/

2019-03-19 16:47 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_REQUEST['action'] ) && apply_filters('sharing_ajax_action', 'get_latest_posts') == $_REQUEST['action'] ) {
You'll also want to add spaces inside the parenthesis, as per the WordPress coding standards:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage

2019-03-21 13:47 UTC, dcooney commented
@jeherve thanks. I've submitted a patch to my PR to incorporate your requests. I'm not sure if updating my remote branches updates this PR though.

2019-03-21 18:36 UTC, jeherve requested changes
Thanks for giving this another try. I've made a few suggestions below. Let me know what you think.

2019-03-21 18:36 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	 * @since 5.1.1
Since it's a new filter, you can use the next version of Jetpack here:

```suggestion
	 * @since 7.2.0
```

2019-03-21 18:36 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_REQUEST['action'] ) && $ajax_action == $_REQUEST['action'] ) {
How about doing something like this instead?

```suggestion
	if (
		defined( 'DOING_AJAX' )
		&& DOING_AJAX
		&& isset( $_REQUEST['action'] )
		&& $ajax_action === $_REQUEST['action']
	) {
```

This way we don't have a line that's too long.

2019-03-21 18:36 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	 * Filter the default ajax action name
I would suggest being more verbose here, so the message can be really helpful for those stumbling across the filter. You want to let them know exactly what the filter can be used for.

```suggestion
	 * Filter the Sharing buttons' Ajax action name Jetpack checks for, to allow the use of the buttons with your own Ajax implementation.
```

2019-03-21 18:36 UTC, jeherve commented on modules/sharedaddy/sharing-service.php
> +	 */
Here you are missing the parameter that can be modified with the filter:

```suggestion
	 * @param string $sharing_ajax_action_name Name of the Sharing buttons' Ajax action.
	 */
```

2019-04-05 17:16 UTC, dcooney commented
Thanks @jeherve Your suggestions are perfect.

2019-04-17 16:52 UTC, jeherve approved these changes
This should now be good to go.

2019-04-17 16:58 UTC, merged