Masterbar: remove Sites, Reader, and Account submenus
Automattic/jetpack pull request #11766
Opened 2019-03-29 15:45 UTC by jeherve

Fixes #11744

Closes #9098
Closes #9082
Closes #8288
Closes #8038
Closes #7642
Closes #7011
Closes #7009

#### Changes proposed in this Pull Request:

* Internal reference: p9Jlb4-ML-p2
* Related change on WordPress.com: D25769-code

The aim of this PR is to remove all drawer menus of the Masterbar, except for the Notifications.

Today, when you click on "My Site", "Reader", or on your avatar, a drawer menu opens up with sub-menus. This PR removes all those.

I also took that opportunity to fix all PHPCS warnings in the Masterbar module, and add it to the pre-commit hook.

#### Testing instructions:

* Go to Jetpack > Settings > Writing, and enable the "WordPress.com toolbar" feature.
* After refreshing, you should see the traditional masterbar, just like before:
![image](https://user-images.githubusercontent.com/426388/55244182-f72fcb80-5240-11e9-90ee-85dd2e076e8a.png)
* However, when clicking on any of the items you should be redirected to Calypso with no errors.

You can also take that opportunity to:

- Check for JavaScript errors on the page.
- Check if Tracks events are properly triggered when clicking on each link. You should see those events in your browser console after submitting `localStorage.setItem( 'debug', 'dops:analytics' );` to enable debugging tracks.
![image](https://user-images.githubusercontent.com/426388/55244364-5988cc00-5241-11e9-9e17-e4a70c5a9e6c.png)

#### Follow-up:

- Once this is merged and shipped, and after a few versions so that we know that the majority of our userbase has updated, we should be able to update 2 things:
- `wp-content/mu-plugins/admin-bar/masterbar-overrides/masterbar.js` to remove unneeded elements.
- remove `wpcom_jetpack_masterbar_logout` on WordPress.com; it handles the sync of the log out event in the masterbar.

#### Proposed changelog entry for your changes:

* WordPress.com toolbar: simplify toolbar by removing drawer menus.

2019-03-29 15:46 UTC, jeherve commented on bin/pre-commit-hook.js
> -		'_inc/lib/debugger/',
There are a lot of changes here, but in fact I just reorganized the list alphabetically as it is getting longer and is easier to parse that way imo. I also added `'modules/masterbar/',`

2019-03-29 15:46 UTC, jeherve commented on modules/masterbar/masterbar.php
> -		add_action( 'wp_logout', array( $this, 'maybe_logout_user_from_wpcom' ) );
We don't need this anymore since you can't log out via the Masterbar anymore.

2019-03-29 15:48 UTC, jeherve commented on modules/masterbar/tracks-events.js
> -	var eventName = 'masterbar_click';
All the changes in that file were made via Prettier.

2019-03-29 15:48 UTC, jeherve commented on sync/class.jetpack-sync-module-users.php
> -		add_action( 'wp_masterbar_logout', $callable, 10, 0 );
No need to sync this anymore since there is log out option in the Masterbar anymore.

2019-04-01 09:30 UTC, davemart-in submitted a review, later dismissed
LGTM! Thanks so much for tackling this @jeherve!

2019-04-01 11:06 UTC, jeherve commented
Tests keep failing here, and I think it may be caused by #11550.

Here is an example of a failing test:

https://travis-ci.org/Automattic/jetpack/jobs/513087165

```
modules/masterbar/tracks-events.js
  line 3    col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 5    col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 14   col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 47   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 58   col 13  'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 59   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 69   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 74   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 93   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 98   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 103  col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  ⚠  11 warnings
```

On the other hand, I can't just revert [my changes](https://github.com/Automattic/jetpack/pull/11766/commits/1ee7f9ef7ab780d93feeeda7b714f3e5cf27aeb0) because if I do so, the pre-commit hook stops me from committing:

```
husky > pre-commit (node v10.13.0)
Prettier formatting staged file: modules/masterbar/tracks-events.js
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

jetpack/modules/masterbar/tracks-events.js
    3:2  error  Unexpected var, use let or const instead  no-var
    5:2  error  Unexpected var, use let or const instead  no-var
   14:2  error  Unexpected var, use let or const instead  no-var
   47:3  error  Unexpected var, use let or const instead  no-var
   58:4  error  Unexpected var, use let or const instead  no-var
   69:4  error  Unexpected var, use let or const instead  no-var
   74:4  error  Unexpected var, use let or const instead  no-var
   93:3  error  Unexpected var, use let or const instead  no-var
   98:3  error  Unexpected var, use let or const instead  no-var
  103:3  error  Unexpected var, use let or const instead  no-var

✖ 10 problems (10 errors, 0 warnings)
  10 errors and 0 warnings potentially fixable with the `--fix` option.

COMMIT ABORTED: The linter reported some problems. If you are aware of them and it is OK, repeat the commit command with --no-verify to avoid this check.
husky > pre-commit hook failed (add --no-verify to bypass)
```

@sirreal In https://github.com/Automattic/jetpack/pull/11507/files#diff-09da0d159e00b7be64d6cb64598a2069, how come the file wasn't automatically updated by Prettier to use `let` or `const` instead of `var`? How do you think I should move on with this?

2019-04-01 15:36 UTC, sirreal commented
A reply in three parts 🙂:

In summary - jshint and eslint are serving different purposes and can't agree. The should exclusively:

- `eslint` -> `/_inc/client`, `extensions`, JS targetting `node` like webpack configuration.
- `jshint` -> js that's not in the `eslint` targets.

This is something that needs to happen, we can't continue using the same linters on all of the JavaScript in this repository.

---

`eslint` could probably apply changes that would resolve the `const` lints with `eslint --fix`, but the real problem is that `eslint` and `jshint` don't agree on what they're linting.

There are two different flavors of JavaScript in the Jetpack repository right now. That which is intended to be compiled into a bundle to be served to browsers, and that which is intended to be served directly without compilation.

I believe `jshint` is from the time when most or all of the code in Jetpack was shipped directly to browsers and still provides valuable information. By indicating that we're targetting `esversion: 5`, we exclude usage of things like `const`, which doesn't have [full support in browsers like ie11](https://kangax.github.io/compat-table/es6/#test-const). This also disallows `class`, `async/await`, `...spread`, and a variety of other syntaxes that aren't valid es5. This has value for these uncompiled files.

`eslint` as it is configured now is intended as a linter for modern JavaScript syntaxes that will be compiled by some tooling. This compilation includes a transformation that ensures our supported browsers will receive compatible syntax. Newer features will be transformed into a syntax that older browsers can understand.

---

To answer this specific question:

> @sirreal In https://github.com/Automattic/jetpack/pull/11507/files#diff-09da0d159e00b7be64d6cb64598a2069, how come the file wasn't automatically updated by Prettier to use `let` or `const` instead of `var`? How do you think I should move on with this?

Prettier is a formatter, so you'll see it changing things like indentation and quote types, but it will never change the abstract syntax tree. The following will be left [untouched by prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJT7AA6U++AbgIYBO+AHvgLz4UgvcDcVGgBs4MfAE8OXEOP6D8kKAGcxALyndVcqAF8qIADQgIAB1zQlyUE0YQA7gAUmCSynq0IOACaGQAI0Z6MABrUQBlEyCcKABzZBhGdDgjAAsYAFshAHUUnHglSLA4MJc8nFo88WRwJUsjaKU4RhgHQJj0+mRUeiFGowArJRYAIUCQ8Pp0uAAZaLgunr6QQZYw6JiRAEV0CHgF3uSQSMZGxmq-ej9xIWhfE0ZomCzvGBTkAA4ABiN7iEaswImar3OCnWjzIyMOAAR3QOChrXo7U6SG6ByMjXSOHiiUOSnWWx2e1Ri0OMEuzy8r2QACYjAl6DghOsAMIQdIdapQaAQkDoRoAFUurjRjR0OiAA), although a linter would complain that all the declarations should be `const` (and removed because they're unused):

```js
function f() {
  var x = "x";
  let y = "y";
  const z = "z";
}
```

A bit about the difference between prettier and linters [here](https://prettier.io/docs/en/comparison.html).

2019-04-01 20:19 UTC, sirreal commented
Did reverting the `const` changes fix the lint issues? (https://github.com/Automattic/jetpack/pull/11766/commits/5f8c300d0adcbf343e1bba824cb57a663a394884)

2019-04-01 20:32 UTC, sirreal commented
> It fixed jshint, yup, but to do that commit I had to force things with git commit --no-verify.

🤔 I think we'll need to get away from sharing `.eslintignore` to ignore files for prettier and eslint.

2019-04-17 17:51 UTC, kraftbj requested changes

2019-04-17 17:51 UTC, kraftbj commented on bin/phpcs-whitelist.js
> +	'sync/class.jetpack-sync-module-auth.php',
```suggestion
```

I believe this line needs to be removed. The file was removed and functions moved to the users module IIRC.

2019-04-17 17:59 UTC, kraftbj approved these changes

2019-04-17 17:59 UTC, merged