A/B test to monitor the impact of removing the bar above the connection banner
Automattic/jetpack pull request #12180
Opened 2019-04-26 20:30 UTC by eliorivero

This PR adds an A/B test to check if removing the green bar at the top of the connection banner displayed on Dashboard and Plugins makes a difference in the rate of connections initiated from this banner. It also adds a new parameter to the connection URL, `ab_connect_banner_green_bar`, which will have the value `a` for the version with green bar, and `b` for the version with no bar.

Fixes #11955

#### Changes proposed in this Pull Request:

* adds an A/B test. 1 is A and means the green bar is shown. 2 is B and means the green bar is not shown
* adds a `ab_connect_banner_green_bar` parameter to the connection URL for the Set up button in this banner. Its value is `a` for the version with green bar, and `b` for the version with no bar.
* adds a Jetpack_Option `ab_connect_banner_green_bar` to save what we initially displayed to the user and consistently always display the same.

#### Testing instructions:

* Start with a site that can be connected
* go to Dashboard or Plugins
* whether you see the sidebar or not, reload and you should see the same
* inspect the Set up button. It should have the `ab_connect_banner_green_bar` parameter with `a` if you're seeing the green bar, and `b` if you're not seeing the bar.

#### Proposed changelog entry for your changes:

*

2019-04-26 21:27 UTC, kraftbj requested changes
With the b option (no bar), the "Dismiss this notice" icon is not visible (but present, tool-tip loads when hover where it should be).

Is this variation between the two acceptable?

2019-04-26 22:09 UTC, MichaelArestad commented
@kraftbj good catch! We do need a way to dismiss this. Perhaps we can reuse the close button code that is in the A version, but make the X the usual close button dark grey.

2019-04-27 03:36 UTC, crunnells commented
@eliorivero I updated the CSS so that it changes the color of the dismiss icon depending on which A/B test is active. The selector is long, but it works! cc: @MichaelArestad

2019-04-29 16:23 UTC, eliorivero commented
Looks fantastic Chris.

<img width="431" alt="Captura de Pantalla 2019-04-29 a la(s) 13 22 54" src="https://user-images.githubusercontent.com/1041600/56910867-ee215c80-6a81-11e9-8768-21f94fd919c7.png">

2019-04-29 18:08 UTC, kraftbj approved these changes

2019-04-29 18:24 UTC, oskosk approved these changes
LGTM!

2019-04-29 18:42 UTC, merged

2019-04-29 18:42 UTC, MichaelArestad commented on scss/organisms/_banners.scss
> +.jp-wpcom-connect__container-top-text + .jp-wpcom-connect__inner-container .notice-dismiss::before {
Ha! This isn't too bad. Let's just make sure to remove it after the A/B test has run its course.