Memberships: Product creation fail message
Automattic/jetpack pull request #12226
Opened 2019-05-01 15:54 UTC by artpi

For some reasons, product creation fails for certain sites. https://github.com/Automattic/jetpack/pull/9802#pullrequestreview-231924433
The error message is terrible. We have captured extensive logs on wpcom side, but error is not returned properly.

This change is only executed on WPCOM side and its already merged there.
This PR syncs it.
No testing necessary.

2019-05-02 08:05 UTC, artpi commented
@kraftbj I don't think this needs cherry-pick. This code here is never executed in Jetpack. I am getting it into JP for Fusion's sake, but it makes no difference for the users and their sites. Its merged to wpcom where it makes sense.

2019-05-02 10:55 UTC, jeherve requested changes
While it works to avoid the first error, I think we would also need to update the Membership block itself to support use-cases when no product can be created. Right now, when running into this error you end up getting the following in the block editor:

```
Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `MembershipsButtonEdit`.
```

This seems to happen because `this.state.products` is an empty array.

2019-05-02 13:37 UTC, kraftbj commented
> @kraftbj I don't think this needs cherry-pick. This code here is never executed in Jetpack. I am getting it into JP for Fusion's sake, but it makes no difference for the users and their sites. Its merged to wpcom where it makes sense.

Understood it isn't needed, but I do like to keep any code related to a new feature in Jetpack going out at the same time, even if it doesn't run. If it is a bug fix for something unreleased that either fixes something seen or has no liability (in this case), rather cherry-pick than not.

Cherry-picking is not something we expect or want you, as the originating developer, to do. It's a quick thing on my side as I'm working through the beta week.

2019-05-03 12:26 UTC, artpi commented
@jeherve I added b1436c289029ba7e75e7c6c515463b1ace6bf23c which passes the error causing it to display:

![Zrzut ekranu 2019-05-3 o 14 18 01](https://user-images.githubusercontent.com/3775068/57137217-7a4bc080-6daf-11e9-8d65-54f353599b0e.png)

2019-05-06 09:13 UTC, jeherve approved these changes
The error message isn't especially helpful since it does not tell you what to do next, but it's better than the current version in `master`.

2019-05-06 09:49 UTC, artpi commented
> The error message isn't especially helpful since it does not tell you what to do next

That is because I honestly don't know why this error occurs on your site :D
Once we solve core issue, the message should not even be necessary.

2019-05-06 10:07 UTC, artpi commented
D27845-code is deployed.

2019-05-06 10:18 UTC, jeherve commented
@artpi Let's take that opportunity to bring the file in sync to solve those Fusion issues. See D27848-code.

2019-05-06 10:20 UTC, artpi commented
@jeherve Fusion PR is waiting patiently for when this right here lands.
See D27731-code

2019-05-06 10:31 UTC, merged

2019-05-06 10:32 UTC, jeherve commented
Cherry-picked to `branch-7.3` in 32f1e9508593de37200f3fc4c2262ec8390167e3