Gutenframe: Fix post content scrolling when floated sidebar is available.
Automattic/jetpack pull request #12279
Opened 2019-05-06 21:35 UTC by kwight

If a Jetpack site's block editor is iframed in Calypso, it is not possible to scroll content at screen widths that allow the sidebar to be displayed on the right. The issue does not exist for viewports that result in a 100% width if the sidebar is opened (such as mobile).

#### Testing instructions:
* Apply this branch to your Jetpack testing site.
* Make sure your testing site is opted in to Gutenberg, and does not have the Classic Editor plugin active.
* Using local Calypso on `master`, start a new post in Gutenframe: `http://calypso.localhost:3000/block-editor/post/:JPsite`. You can also use `wpcalypso.wordpress.com`, if your test site has an SSL certificate; secure sites can only iframe other secure sites.
* Make sure your viewport is at least 782px wide.
* Insert content that overflows the visible window, and verify you can scroll that content.

2019-05-06 21:57 UTC, obenland requested changes
This should fix Automattic/wp-calypso#32637 for Calypsoify'd block editors at least, but it won't help with regular uses of full screen mode.

@kraftbj It doesn't look like Jetpack has a generic stylesheet that it loads with the block editor, is that correct? If it does, that is where this should live.

It should also be said that this is a fix for a problem where we don't know or understand the cause, we only see the symptom.

2019-05-06 21:57 UTC, obenland commented on modules/calypsoify/style-gutenberg.scss
> +	body.is-iframed.is-fullscreen-mode .edit-post-layout__content {
Could we remove the `.is-iframed` selector to make it applicable for non iframed Calypsoify'd requests too?

2019-05-07 00:47 UTC, mmtr requested changes
After applying these changes, I cannot scroll when loading the block editor of my Jetpack site on WordPress.com.

I think we need to search a different solution for https://github.com/Automattic/wp-calypso/issues/3263

2019-05-07 01:28 UTC, mmtr submitted a review, later dismissed

2019-05-07 01:31 UTC, mmtr commented
Ok, so it seems that the scroll issue is present when the JP site is not running the latest version of the Gutenberg plugin. This PR fixes that scenario, but incorporates the issue to JP sites running the plugin.

2019-05-07 03:33 UTC, obenland approved these changes

2019-05-07 05:06 UTC, mmtr approved these changes

2019-05-07 08:28 UTC, brbrr approved these changes
Works as advertised with latest Gutenberg and the one shipped with 5.1.1

2019-05-07 09:12 UTC, jeherve approved these changes
LGTM. I was surprised that we were removing the CSS we had added in #12239, but it seems we now pull it from WordPress.com directly, so we don't need it anymore.

2019-05-07 09:12 UTC, merged

2019-05-07 09:13 UTC, jeherve commented
Cherry-picked to `branch-7.3` in 19112180e6a02c202bcdcd37c1630cba6b04d563