Memberships: Check plan before displaying the block
Automattic/jetpack pull request #12348
Opened 2019-05-13 14:55 UTC by artpi

This PR blocks the usage of a block (ahem) if you are on a free plan.

## Screenshots

<img width="683" alt="Zrzut ekranu 2019-05-13 o 16 45 22" src="https://user-images.githubusercontent.com/3775068/57631382-adf0cc80-759f-11e9-9e6c-3a15e817b6ca.png">

## Testing instruction

1. Make sure to check out the diff and 
2. Try to use a block on a site that is on a paid plan. You should get "connect stripe account" or - if you connected - product selection
3. Try to use on a free site. You should get "Uprade your site"

2019-05-13 18:18 UTC, davemart-in submitted a review, later dismissed
If we can remove the period in the button, I'm 👍LGTM!

2019-05-14 09:39 UTC, jeherve commented
Related discussion: p8hgLy-1tg-p2#comment-2615

2019-05-14 10:43 UTC, jeherve requested changes

2019-05-14 10:43 UTC, jeherve commented on extensions/blocks/membership-button/edit.jsx
> +							{ __( "You'll need to upgrade your plan to use the Membership Button", 'jetpack' ) }
```suggestion
							{ __( "You'll need to upgrade your plan to use the Membership Button.", 'jetpack' ) }
```

2019-05-14 10:43 UTC, jeherve commented on extensions/blocks/membership-button/edit.jsx
> +								{ __( 'Upgrade Your Plan.', 'jetpack' ) }
```suggestion
								{ __( 'Upgrade Your Plan', 'jetpack' ) }
```

2019-05-14 13:48 UTC, scottsweb commented
I haven't tested this PR but from looking at the screenshot I am happy for this to proceed. 

My only slight hesitation is seeing the term "memberships" and "plans" together, they could easily mean the same thing.

> You will need to upgrade your plan to use the membership button 

👏 This is a nice bit of clarification. When we are referencing 'plan' here, is it a Jetpack plan or a .com plan? or both?

2019-05-14 16:49 UTC, artpi commented
> artpi, Your synced wpcom patch D28126-code has been updated.

Fusion just mangled D28126-code . I attached there code that was not in JP repo and now it deleted it. I need to work on 3rd pr to land this.

2019-05-14 20:09 UTC, jeherve commented
> Fusion just mangled D28126-code 

That's to be expected unfortunately. Fusion has no way to know about the previous state of the diff right now, so it just reapplies the new diff it gets from the PR.  If you have changes to other files, I'd recommend making them in a separate diff if you can.

2019-05-22 07:48 UTC, jeherve submitted a review, later dismissed
This works well for me, but I wonder if we should add a link to recheck the status of your site in the block editor once you've purchased a plan, just like we have when you first add the block before it's connected to Stripe:

![image](https://user-images.githubusercontent.com/426388/58156443-6096ee00-7c76-11e9-844c-5ac885d72685.png)

What do you think?

This can be done in a next PR though, so approving this one for now.

2019-05-22 09:27 UTC, davemart-in submitted a review, later dismissed
🤘🚀

2019-05-22 15:19 UTC, jeherve approved these changes

2019-05-22 16:58 UTC, merged