Fix "View Full Site" and "View Mobile Site" for Wordpress Subdirectory Installations
Automattic/jetpack pull request #12414
Opened 2019-05-19 16:37 UTC by dstein64

When Wordpress is installed to a subdirectory, the "View Full Site" and "View Mobile Site" links do not work properly. Incidentally, the problem is masked when on a blog page, but present on the home page.

For example, suppose a blog is hosted at `https://somesite.com/blog`, with this URL set for both `WordPress Address` and `Site Address` in the Wordpress settings (i.e., the blog is intended to be accessed at the subdirectory). Under this scenario, the "View Full Site" link expands to `https://somesite.com/blog/blog?ak_action=reject_mobile`, which has an extra `blog/`. It should expand to `https://somesite.com/blog?ak_action=reject_mobile`. The double occurrence of `blog` is due to the omitted `$url` argument to `add_query_arg` combined with the call to `home_url`. The call to `add_query_arg` returns `/blog/?ak_action=reject_mobile` and that is passed to `home_url` which returns `https://somesite.com/blog/blog?ak_action=reject_mobile`.

The same thing happens for the "View Mobile Site" link.

The problem occurs on the blog's homepage, and results in a page not found. The same issue occurs on blog posts, where `blog/` is added to the URL twice, but it appears that Wordpress is robust to such malformed URLs.

#### Changes proposed in this Pull Request:

* This PR uses the approach proposed by @jeherve here: https://github.com/Automattic/jetpack/pull/11166#discussion_r251478911

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is a bug fix, not a new/modified feature.

#### Testing instructions:

* To replicate the issue, navigate on a phone to a Wordpress blog installed to a subdirectory, and click "View Full Page". The page will not be found (although futher navigations will load the full site, not the mobile one).
* With the changes in this PR, the problem is not present.

#### Proposed changelog entry for your changes:

* Fix "View Full Site" and "View Mobile Site" for Wordpress subdirectory installations

2019-05-20 17:16 UTC, jeherve commented
@BoleynSu Do you want to give this a try, see if it works for you?

2019-05-20 17:21 UTC, BoleynSu commented
I am sorry I do not have a subdirectory installation of wordpress, so I
cannot test it. If it is possible, I can test it later when I get
some time. However, I am not sure when it will be.

On Tue, May 21, 2019, 01:17 Jeremy Herve <notifications@github.com> wrote:

> @BoleynSu <https://github.com/BoleynSu> Do you want to give this a try,
> see if it works for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Automattic/jetpack/pull/12414?email_source=notifications&email_token=AAXVSKEZSVJ5UW55T4QIURLPWLMJHA5CNFSM4HN43SZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVZP5CQ#issuecomment-494075530>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXVSKA6Z2VBAXBKKWKOS7TPWLMJHANCNFSM4HN43SZQ>
> .
>

2019-05-20 21:06 UTC, jeherve requested changes
Thank you for the contribution.

This works well. I would only recommend escaping as late possible, so you could move `esc_url` and use it right as the anchor is being built / the link being outputted. This is a small detail right now, but could be important in the future if other things are added to the functions.

2019-05-20 21:26 UTC, dstein64 commented
@jeherve, a10b3c2da1f7bd870775b76bfb7d4991bf7fe264 adds the requested modification. I also split one of the modified lines as it grew beyond 100 characters. However, I'm not sure if there is a suggested limit, as I saw further down in the file a line that is almost 300 characters.

Thanks for reviewing.

2019-05-21 08:35 UTC, jeherve approved these changes
This looks good to me. 👍

2019-05-21 20:20 UTC, merged