Admin - REST API: introduce endpoint to get Activity Log data
Automattic/jetpack pull request #12440
Opened 2019-05-22 17:27 UTC by eliorivero

#### Changes proposed in this Pull Request:

This PR registers a new endpoint `/site/activity` that can be accessed with permission `jetpack_manage_modules`. Internally, this endpoint requests the `wpcom/v2/sites/$site/activity` as user.

#### Testing instructions:
* Go to the Jetpack admin page
* open the browser Console
* run
```js
fetch( Initial_State.WP_API_root + 'jetpack/v4/site/activity', {
	credentials: 'same-origin',
	headers: {
		'X-WP-Nonce': Initial_State.WP_API_nonce,
	},
} )
```

#### Proposed changelog entry for your changes:
Not necessary in this PR. Will add something in the PR for the corresponding UI.

2019-05-22 18:17 UTC, jeherve requested changes
This seems to work well in my tests. I only have two minor comments.

Also, do you know how much data we will need? Will we need to display more than 20 items? Should there be some kind of pagination handling in there?

For anyone else testing, I ended up breaking things down a bit more in the test query above to see the actual events:

```js
fetch( Initial_State.WP_API_root + 'jetpack/v4/site/activity', {
	credentials: 'same-origin',
	headers: {
		'X-WP-Nonce': Initial_State.WP_API_nonce,
	},
} )
	.then( data => data.json() )
	.then( data => console.log( data ) );
```

2019-05-22 18:17 UTC, jeherve commented on _inc/lib/class.core-rest-api-endpoints.php
> +		error_log( print_r( $response, true ) );
You'll probably want to remove that debug code.

```suggestion

```

2019-05-22 22:35 UTC, eliorivero commented on _inc/lib/class.core-rest-api-endpoints.php
> +			return new WP_Error( 'site_id_missing' );
Done

2019-05-23 09:30 UTC, jeherve approved these changes
Looks good to me! 🚢

2019-05-23 09:40 UTC, merged

2021-09-03 07:09 UTC, jeherve commented
See #20948 for the display of this data in the Jetpack dashboard.