Sync: Decouple is_active, is_dev_mode and is_staging methods
Automattic/jetpack pull request #12651
Opened 2019-06-11 15:32 UTC by tyxla

This PR starts decoupling the sync package from external classes by using filters and actions. This is a step towards allowing easier testing and independent packaging of the Sync package.

I'd like to get some feedback on this approach - if it's feasible, we could use it for decoupling the rest of sync and other big packages from the core Jetpack plugin.

**Question:** Should these 3 methods be part of the connection package @zinigor @mdawaffe?

#### Changes proposed in this Pull Request:
* Introduce new filters instead of several methods:
  * `Jetpack::is_active()`
  * `Jetpack::is_development_mode()`
  * `Jetpack::is_staging_site()`
* Introduce a method for initialyzing Sync in the main Jetpack class.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Part of the Jetpack DNA project - p1HpG7-70O-p2

#### Testing instructions:

* Checkout this branch.
* Smoke test incremental and full sync and verify everything works like it did before.

#### Proposed changelog entry for your changes:
* Sync: Decouple is_active, is_dev_mode and is_staging methods

2019-06-11 16:54 UTC, jeherve requested changes

2019-06-11 16:54 UTC, jeherve commented on packages/sync/legacy/class.jetpack-sync-actions.php
> +		if ( apply_filters( 'jetpack_sync_is_development_mode', false ) ) {
Could you add docblocks here and below?

2019-06-11 19:18 UTC, gravityrail requested changes

2019-06-11 19:18 UTC, gravityrail commented on jetpack.php
> +Jetpack::initialize_sync();
This feels like an anti-pattern. I don't want a whole glut of similar initialisation happening when the plugin file is loaded. Hopefully almost NO code gets loaded at first, just a few clean hooks that load everything else on demand.

2019-06-12 09:39 UTC, tyxla commented
As https://github.com/Automattic/jetpack/pull/12651#discussion_r292619794 mentioned, this feels a bit like an anti-pattern, so I'd like to explore other options. Closing for now.

2019-06-12 09:39 UTC, closed without merging