WIP: Proof of concept: namespace Jetpack class.
Automattic/jetpack pull request #12672
Opened 2019-06-12 20:40 UTC by lezama

😱

2019-06-13 08:50 UTC, tyxla requested changes
👏 Thanks for starting this. Feels like we're really dipping our toes into the really cool stuff now 😉

2019-06-13 08:50 UTC, tyxla commented on _inc/lib/admin-pages/class.jetpack-react-page.php
> +use \Automattic\Jetpack;
Could we avoid the leading backslash? It's unnecessary and in some cases (like testing) it can be helpful to NOT have it.

2019-06-13 08:50 UTC, tyxla commented on _inc/lib/admin-pages/class.jetpack-react-page.php
> +			'tracksUserData' => Tracking::get_connected_user_tracks_identity( $this->jetpack->connection_manager ),
Can we pass the connection manager in the constructor of `Jetpack_React_Page`?

2019-06-13 08:50 UTC, tyxla commented on class.jetpack-gutenberg.php
> +use Automattic\Jetpack;
Having the same full qualified class name like the namespace (`Automattic\Jetpack`) can be confusing - do you think we should define the class as `Automattic\Jetpack\Jetpack` or `Automattic\Jetpack\Plugin` or `Automattic\Jetpack\Main` instead?

2019-06-13 08:50 UTC, tyxla commented on class.jetpack-gutenberg.php
> +	 * @deprecated 7.1.0 Use \Automattic\Jetpack\jetpack_register_block() instead
I'd love to avoid leading backslashes in every instance where we refer to namespaces or namespaced classes/functions/constants/entities.

2019-06-13 08:50 UTC, tyxla commented on class.jetpack.php
> +use Automattic\Jetpack\Jetpack_Data;
Does it make sense to keep `use` blocks ordered 🔤 alphabetically?

2019-06-13 08:50 UTC, tyxla commented on class.jetpack.php
> +	public $connection_manager;
Can we keep this private or protected? It should not be accessible externally.

2019-06-13 08:50 UTC, tyxla commented on class.jetpack.php
>  class Jetpack {
I wonder if we should make the `Jetpack` class `final`. Doesn't seem like we'll want to extend it. I remember Woo [does the same](https://github.com/woocommerce/woocommerce/blob/f6d9faa0623d1085eacc94dee2ad75750d916ed4/includes/class-woocommerce.php#L16).

2019-06-13 08:50 UTC, tyxla commented on class.jetpack.php
> +		return self::init()->connection_manager->get_connected_user_data( $user_id );
Oh, those static calls 😞

2019-06-13 08:50 UTC, tyxla commented on packages/connection/src/Manager.php
> +		\Jetpack::load_xml_rpc_client();
Could we not introduce additional `Jetpack` references to the connection package? I think we should create an IXR client package, and then consume it here.

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/composer.json
> +			"Automattic\\Jetpack\\": "src/",
Hm, different namespaces within a small package....shouldn't we be using the same namespace? I think we could use the `Automattic\Jetpack\Tracking` namespace for all of these, just like we do for the connection package.

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/src/Tracking.php
> +	const PACKAGE_VERSION = '1.0';
Another source of truth for versioning...I know `filemtime` has caused trouble in the past, but it's a more reliable way to both leverage browser caching and bust the cache automatically. Could we have a wrapper around it that would fall back to `time()` if `filemtime` fails, and avoid relying on such statically defined versions completely?

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/src/Tracking.php
>  		return jetpack_tracks_record_event( $user, $event_type, $data );
Are we missing `$this->` here?

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/src/Tracking.php
> +		if ( Jetpack::is_user_connected( $user_id ) ) {
Would be great to use the connection package for this.

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/src/Tracking.php
> +		if ( $user instanceof WP_User && 'wptests_capabilities' === $user->cap_key ) {
`\WP_User`?

2019-06-13 08:50 UTC, tyxla commented on packages/tracking/src/lib/Client.php
> +		if ( ! $event instanceof Event ) {
I think `instanceof` works with the fully qualified name of the class, e.g. `Automattic\Jetpack\Tracks\Event`

2019-06-17 11:58 UTC, lezama commented
Thanks for looking at this @tyxla !

Main lesson learned: don't start from the trunk when doing big refactors, consider starting from the leaves :)

2019-06-17 11:58 UTC, closed without merging