Security: Downtime monitoring copy
Automattic/jetpack pull request #12731
Opened 2019-06-18 16:46 UTC by scottsweb

Update copy on downtime monitoring card:

> Receive notifications when your site goes offline.

Fixes #12588 

Please see the issue for a before and after

#### Testing instructions:
* Go to wp-admin/admin.php?page=jetpack#/security
* Check the copy on the downtime monitoring card

#### Proposed changelog entry for your changes:
* None

2019-06-18 17:22 UTC, jeherve reviewed
Approving, but I do have one question: is it okay that we don't mention that you'll get a notification when your site comes back online as well?

2019-06-18 17:22 UTC, jeherve submitted a review, later dismissed

2019-06-19 08:02 UTC, scottsweb commented
Good point, before we merge I will get a second copy review.

@obi2020 would you mind taking a look at this one with me again? Thank you

2019-06-19 14:52 UTC, obi2020 commented
Proposed: `Get alerts if your site goes offline. We’ll let you know when it’s back up, too.`

It's a bit long, but here's what it looks like in the space:
<img width="1135" alt="Screen Shot 2019-06-19 at 10 49 07 AM" src="https://user-images.githubusercontent.com/3373750/59775929-f7f45e80-927f-11e9-92f3-71b97b0465f8.png">

Also, will copy be changed on the settings page, too? i.e. When you click `Configure notification settings` you see the following, which also has the copy we're replace `Monitor your site's downtime`
<img width="623" alt="Screen Shot 2019-06-19 at 10 48 08 AM" src="https://user-images.githubusercontent.com/3373750/59776061-2d00b100-9280-11e9-9089-0191028602d3.png">

2019-06-19 15:06 UTC, scottsweb commented
Thanks @obi2020, I like your changes here. I will update this PR.

The second screen is Calypso and we will need to make a separate set of PRs on that repository. I am making a note of all the ones that need carrying over and will start that once the Jetpack side is looking good.

2019-06-19 17:39 UTC, jeherve requested changes

2019-06-19 17:39 UTC, jeherve commented on _inc/client/security/monitor.jsx
> +									"Get alerts if your site goes offline. We’ll let you know when it's back up, too."
We have two types of apostrophes here. Maybe we can stick to `’`?

```suggestion
									'Get alerts if your site goes offline. We’ll let you know when it’s back up, too.'
```

2019-06-20 09:33 UTC, jeherve approved these changes

2019-06-20 09:34 UTC, merged