Change from SSH to HTTPS
Automattic/jetpack pull request #12818
Opened 2019-06-21 20:26 UTC by MichaelArestad

This will work for everyone and not just folks who have a public SSH key set up.

2019-06-21 20:55 UTC, jeherve requested changes
I think I would rather invite people to set an SSH key instead; it make everything way easier once that's done, and we know Automatticians are already familiar with the concept.

Maybe we could add this requirement about that section, with a link to https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account ?

2019-06-24 15:45 UTC, MichaelArestad commented
> it make everything way easier once that's done

How so?

2019-06-24 15:50 UTC, jeherve commented
It's only that you won't have to type your GitHub password, or save your GitHub password in your keychain. It's also a bit safer that way. It does not require too much extra work for Automatticians since everyone already has an SSH key set up.

It's also more practical for anyone who ends up having to use any of our releasing tools, as they all rely on SSH.

2019-09-25 08:17 UTC, jeherve approved these changes

2019-09-25 19:18 UTC, merged