Mobile: Hide edit post link in content
Automattic/jetpack pull request #12867
Opened 2019-06-26 15:42 UTC by donpark

#### Changes proposed in this Pull Request:

Adds an `edit_post_link` filter to return empty string if request is from an WordPress mobile app.

Hides edit post link in post content if client is a WordPress mobile app.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

See trac link in D29686-code

#### Testing instructions:

1. Use a browser that lets you change User-Agent easily. Chrome, for example, has User agent settings under Three Dot menu > More tools > Network conditions.
2. View a post you have edit permission to using Chrome browser with default User-Agent.
3. Verify that Edit link is displayed.

<img width="772" alt="screenshot_726" src="https://user-images.githubusercontent.com/127594/60194410-25945700-97ee-11e9-9d93-6c51ba85701c.png">

4. Add wp-iphone/1.0 or wp-android to User-Agent string and refresh the page.

<img width="773" alt="screenshot_725" src="https://user-images.githubusercontent.com/127594/60194427-2b8a3800-97ee-11e9-98ad-b9b0a94e0334.png">

5. Verify that Edit link is no longer displayed.

#### Proposed changelog entry for your changes:

Hide edit post link in post content if client is a WordPress mobile app.

2019-06-26 20:44 UTC, jeherve requested changes
Do you think it would make sense to shorten this into something like:

```php
if ( Jetpack_User_Agent_Info::is_mobile_app() ) {
	add_filter( 'edit_post_link', '__return_empty_string' );
}
```

Should we also consider moving this out of the Minileven module, so it can be applied regardless of the theme you are using, and even if the mobile theme feature / module is not enabled on your site?

2019-06-27 00:31 UTC, donpark commented
> Do you think it would make sense to shorten this into something like:
> 
> ```
> if ( Jetpack_User_Agent_Info::is_mobile_app() ) {
> 	add_filter( 'edit_post_link', '__return_empty_string' );
> }
> ```

Ha. Yes, init-per-request mindset is still a stranger to me.

> Should we also consider moving this out of the Minileven module, so it can be applied regardless of the theme you are using, and even if the mobile theme feature / module is not enabled on your site?

Can you suggest the ideal place for this code? I just followed where `wp-mobile.php` function names pointed to.

2019-06-27 12:49 UTC, jeherve commented
> Can you suggest the ideal place for this code? I just followed where wp-mobile.php function names pointed to.

It may be best to place it in `class.jetpack.php`. That file is already way too big, but it's really the only place where it fits well right now. You'll actually find other edit post link changes in there (look for `point_edit_post_links_to_calypso`) :)

2019-06-27 22:56 UTC, donpark commented
Result of my test against my wpsandbox.me site using the latest:

Without this patch:

<img width="395" alt="screenshot_736" src="https://user-images.githubusercontent.com/127594/60306149-fec04880-98f3-11e9-9bf5-bebb1f274b50.png">

With this patch:

<img width="387" alt="screenshot_735" src="https://user-images.githubusercontent.com/127594/60306165-097add80-98f4-11e9-9d53-bf7d041d9a9e.png">

2019-07-04 17:36 UTC, jeherve approved these changes
This works well for me. 👍

2019-07-04 17:36 UTC, merged