Travis: Run php:compatibility check
Automattic/jetpack pull request #12947
Opened 2019-07-03 18:38 UTC by brbrr

For some reason, we run PHPCS compatibility checks only on pre-commit hooks, which could be ignored. Running them in Travis could help us maintain backward compatibility even better.  

#### Changes proposed in this Pull Request:

* run PHPCS compatibility in travis

#### Testing instructions:

* Not much. check "Previous" travis jobs? 
*

#### Proposed changelog entry for your changes:

* n/a

2019-07-03 19:44 UTC, jeherve requested changes
It looks like the tests are failing for that one:

```
ERROR: You must supply at least one file or directory to process.
Run "phpcs --help" for usage information
Script composer install && vendor/bin/phpcs -p -s --runtime-set testVersion '5.3-' --standard=PHPCompatibilityWP --ignore=docker,tools,tests,node_modules,vendor --extensions=php handling the php:compatibility event returned with error code 3
```

2019-07-04 13:03 UTC, brbrr commented
Fixed it. Also, I added a check to make sure that phpcs actually behaving, to prevent silent exits

2019-07-04 16:38 UTC, jeherve submitted a review, later dismissed
This seems to work well. I only have one minor nitpick, I'll commit it now.

2019-07-04 16:38 UTC, jeherve commented on tests/run-travis.sh
> +		if $PHPCOMP_EXEC; then
indenting is now a bit off here.

```suggestion
	if $PHPCOMP_EXEC; then
```

2019-07-04 16:38 UTC, jeherve submitted a review, later dismissed

2019-07-04 16:58 UTC, brbrr commented
Tests are obviously failing :D 
I wonder what would be the best way to address these phpcs warnings/errors? just raise minimum compatible php version in `php:compatibility` script, or try to fix these?

2019-07-04 17:00 UTC, jeherve commented
Well now that Jetpack's PHP requirements have been upped to PHP 5.6, we can do the same for our checks I think. No need to keep looking at previous versions.

2019-07-05 08:53 UTC, zinigor approved these changes

2019-07-05 09:09 UTC, merged