Connection Manager: Prevent notice on empty Jetpack blog token
Automattic/jetpack pull request #12948
Opened 2019-07-03 19:19 UTC by gititon

This PR prevents a notice when the Jetpack blog token is empty.

2019-07-03 21:04 UTC, jeherve requested changes
Tests seem to be failing right now.

I also tried to set a real value for `JETPACK_BLOG_TOKEN` and then I deleted my site's `blog_token` Jetpack option to get into a situation close to some of those Atomic sites. When on Master, that seems to work; if I head over to Tools > Site Health > Info and look at my site's site info, I have a blog token set there; it picks it up from `JETPACK_BLOG_TOKEN`. When I check out this branch, however, no token is set at all.

2019-07-03 23:03 UTC, gititon commented
> Tests seem to be failing right now.
> 
> I also tried to set a real value for `JETPACK_BLOG_TOKEN` and then I deleted my site's `blog_token` Jetpack option to get into a situation close to some of those Atomic sites. When on Master, that seems to work; if I head over to Tools > Site Health > Info and look at my site's site info, I have a blog token set there; it picks it up from `JETPACK_BLOG_TOKEN`. When I check out this branch, however, no token is set at all.

Hi Jeremy,

Using this branch, I
1) copied my Jetpack `Blog Public Key` as reported by Tools -> Site Health -> Info
2) Set it as my JETPACK_BLOG_TOKEN via `define( 'JETPACK_BLOG_TOKEN', '<my-token>' );` in wp-config.php
3) Deleted the option by ssh'ing into my Jetpack sandbox and `wp jetpack options delete blog_token --allow-root`
4) The value of `Blog Public Key` changed to `Potentially Malformed Token.` 

I switched to master, disconnected and reconnected Jetpack, ensured the `blog_token` value was restored in Tools -> Site Health -> Info, and repeated the same steps above. I got the same result, `Potentially Malformed Token.`

2019-07-04 09:35 UTC, jeherve approved these changes
This seems to work well for me. Merging!

2019-07-04 09:36 UTC, jeherve commented
> I got the same result, Potentially Malformed Token.

Yes, that's because the token you can use as `JETPACK_BLOG_TOKEN` has to be the full token, not just the public part of it.

2019-07-04 09:36 UTC, merged

2019-07-04 09:36 UTC, jeherve commented
Cherry-picked to `branch-7.5` in f1a8da225b3d66752cc29915650d80459a22fbba