Sync: Fix PHPCS errors in Updates module
Automattic/jetpack pull request #12995
Opened 2019-07-08 13:58 UTC by tyxla

Committing changes on sync these days has been a pain with all the lint errors. We often had to commit with `--no-verify` and that's not great. And after #12945, even that's no longer a good option. 

So, I've decided to fix all the phpcs errors and warnings in the sync package.

This PR does it for the Updates sync module.

#### Changes proposed in this Pull Request:
* Sync: Fix PHPCS errors in Updates sync module

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Part of Jetpack DNA

#### Testing instructions:
* Shouldn't be necessary, but if you are into it, perform some smoke testing of full sync and incremental sync.

#### Proposed changelog entry for your changes:
* Sync: Fix PHPCS errors in Updates sync module

2019-07-08 18:26 UTC, zinigor requested changes
Just one nitpick and then we're good :)

2019-07-08 18:26 UTC, zinigor commented on packages/sync/src/modules/Updates.php
> +	 * @var string
Ouch, it's not a string :)

2019-07-08 18:34 UTC, gititon approved these changes
Nice!

2019-07-08 18:39 UTC, gititon submitted a review, later dismissed
See Igor's comment

2019-07-09 09:11 UTC, tyxla commented on packages/sync/src/modules/Updates.php
> +	 * @var string
💥

2019-07-09 09:11 UTC, tyxla commented on packages/sync/src/modules/Updates.php
> +	 * @var string
```suggestion
	 * @var array
```

2019-07-09 09:17 UTC, zinigor approved these changes
Looks great now, thank you!

2019-07-09 16:35 UTC, merged