Enable related posts for AMP
Automattic/jetpack pull request #13028
Opened 2019-07-11 05:05 UTC by gravityrail

Fixes #9556

Currently the related posts block is disabled for all AMP requests because they don't support client-side JS. However, the Gutenberg block does server side rendering. This patch reuses the Gutenberg code in kind of a brute-force way to enable Related Posts in AMP.

cc @westonruter

#### Changes proposed in this Pull Request:

* Enable Related Posts for AMP pages

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This adds Related Posts support to AMP pages

#### Testing instructions:

* Install and activate the AMP plugin (tested with v1.2)
* Enable Related posts
* View the AMP version of a page by appending ?amp
* Related posts should be displayed
* Try changing some settings (e.g. enable/disable thumbnails, enable/disable heading). Should work similarly to front-end

This is the most minimal, brute-force version I could create. It may create invalid AMP in other ways (e.g. too much CSS). Comments and corrections welcome.

#### Proposed changelog entry for your changes:

* Enable Related Posts for AMP pages

2019-07-11 05:22 UTC, westonruter commented on modules/related-posts/jetpack-related-posts.php
> +				$content .= "\n" . $this->get_amp_html();
Minor point, but there's nothing AMP-specific about this method. Probably better named `get_server_rendered_html()` with the other method called `get_client_rendered_html()`.

BTW, why not just always do server-side rendering?

2019-07-11 05:22 UTC, westonruter commented on modules/related-posts/jetpack-related-posts.php
> +	 * Render static markup based on the Gutenberg block code
Not: this should have `@return string Rendered related posts HTML.`

2019-07-11 05:27 UTC, westonruter commented
I enabled:

![image](https://user-images.githubusercontent.com/134745/61024094-5b464d80-a361-11e9-9aa5-43add4dddb58.png)

Rendering as:

![image](https://user-images.githubusercontent.com/134745/61024108-68fbd300-a361-11e9-9695-773c6c3a26fc.png)

When thumbnails are hidden:

![image](https://user-images.githubusercontent.com/134745/61024130-7d3fd000-a361-11e9-8a16-f32f85593380.png)

With heading hidden:

![image](https://user-images.githubusercontent.com/134745/61024148-8f217300-a361-11e9-9cf8-94f0da457bcc.png)

Here's the https://dev-westonruter.pantheonsite.io/2019/03/21/using-the-amp-plugin-to-protect-site-visitors-and-debug-security-vulnerabilities/

It looks good, except for the thumbnails being a bit off.

2019-07-11 05:33 UTC, westonruter commented
In Reader mode there is no styling, so either the styling needs to be added or the Related Posts should be omitted if `! current_theme_supports( 'amp' )`:
 
![image](https://user-images.githubusercontent.com/134745/61024522-bfb5dc80-a362-11e9-96f6-2ba9444ba1d0.png)

2019-07-11 05:35 UTC, westonruter commented
> It looks good, except for the thumbnails being a bit off.

It's not the thumbnail, it's the text link under the thumbnail, where there is a styling problem:

![image](https://user-images.githubusercontent.com/134745/61024628-0d324980-a363-11e9-851a-d13dd4e4c231.png)

2019-07-26 10:56 UTC, jeffersonrabb requested changes
Looks good - only change needed is the `$enqueue_script` logic.

2019-07-26 10:56 UTC, jeffersonrabb commented on modules/related-posts/jetpack-related-posts.php
> +		$enqueue_script = ! ( class_exists( 'Jetpack_AMP_Support' ) || Jetpack_AMP_Support::is_amp_request() );
Should be an AND operator, no?

```suggestion
		$enqueue_script = ! ( class_exists( 'Jetpack_AMP_Support' ) && Jetpack_AMP_Support::is_amp_request() );
```

Or alternatively:

```suggestion
		$enqueue_script = ! class_exists( 'Jetpack_AMP_Support' ) || ! Jetpack_AMP_Support::is_amp_request();
```

2019-07-26 10:56 UTC, jeffersonrabb commented on modules/related-posts/jetpack-related-posts.php
> +	public function get_client_rendered_html_unsupported() {
This is probably out of scope of this PR, but is Related Posts supposed to appear in the loop? The doc comment implies not, but I'm seeing them on a test homepage (both on this branch and `master`).

2019-07-29 11:57 UTC, jeffersonrabb submitted a review, later dismissed
Looks good.

2019-07-29 13:48 UTC, dereksmart commented
Added to 7.6 milestone as per request of @gravityrail

2019-07-29 21:30 UTC, jeherve approved these changes
This works for me, although the whole section looks pretty bad without any CSS. I don't know if we should ship this change now, without applying basic styles to the related posts.

2019-07-29 21:53 UTC, merged

2020-01-17 19:35 UTC, westonruter commented on modules/related-posts/jetpack-related-posts.php
> +		$rp_settings       = Jetpack_Options::get_option( 'relatedposts', array() );
@gravityrail I think this should have been `$this->get_options()` instead of `Jetpack_Options::get_option( 'relatedposts', array() )`. See #14386.