Connection Package: Create a readme
Automattic/jetpack pull request #13047
Opened 2019-07-13 23:15 UTC by roccotripaldi

Fixes confusion around wether this package is finished.

#### Changes proposed in this Pull Request:

* Adds some brief documentation that this package is not ready to go yet.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is purely a documentation change.

#### Testing instructions:
None required.

#### Proposed changelog entry for your changes:
None required.

2019-07-13 23:20 UTC, dereksmart requested changes

2019-07-13 23:20 UTC, dereksmart commented on packages/connection/README.md
> +This package will eventually give other plugins the ability to connect to WordPress.com
```suggestion
This package will eventually give other plugins the ability to create a secure two-way communication path between  the plugin and WordPress.com. 
* It currently relies on the full Jetpack plugin to work 
* It does not, nor will it come with UI

Follow the "Jetpack DNA" label to keep up with ongoing work.
```

2019-07-13 23:21 UTC, dereksmart approved these changes

2019-07-15 09:32 UTC, tyxla approved these changes
Good stuff! Thanks!

2019-07-15 09:33 UTC, merged