Upgrade nudge: Remove feature gate
Automattic/jetpack pull request #13081
Opened 2019-07-18 10:21 UTC by sirreal

#### Changes proposed in this Pull Request:

The feature is live on WordPress.com and will be part of the next
Jetpack release.

Remove the feature gating.

#### Testing instructions:

## Testing
- This change removes the need for this to test changes related to the nudge. ~You'll need to set the constant `define( 'JETPACK_SHOW_BLOCK_UPGRADE_NUDGE', true );`~
- With a site on a free plan, add the Simple Payments block.
- Make sure the block is available with the nudge.

#### Proposed changelog entry for your changes:

None.

2019-07-18 10:33 UTC, jeherve submitted a review, later dismissed

2019-07-18 10:40 UTC, ockham requested changes
Oh, hang on, I don't think the redirect works yet :sweat_smile:

2019-07-18 10:43 UTC, ockham commented
Calypso checkout only supports host-relative redirects, see https://github.com/Automattic/wp-calypso/pull/34440. This means that we can't redirect back to the JP site's wp-admin :slightly_frowning_face:

2019-07-18 10:45 UTC, sirreal commented
Thanks for catching that Bernie. This is blocked by necessary Calypso changes. Let's open a priority issue, we'll need to have that sorted for the next Jetpack release.

2019-07-18 11:46 UTC, ockham commented
I just tested this. Turns out Calypso actually redirects `/post/:jetpackSite/:postId` to `jetpackSite/wp-admin/post.php?post=:postId&action=edit`, so in theory, we can ship this.

However, there's obviously a chance that Calypso stops redirecting those URLs and instead enables its block editor for them.

Lazy YAGNI me is thinking to keep as-is :grimacing: And maybe add `redirect_to` validation/mangling to `checkout/checkout/index.jsx` as needed later?
In any case, would be good to have a stable API (qarg pattern for the redirect)

2019-07-23 13:41 UTC, simison commented
Wondering if this is good as-is for Jetpack or would it need to be more in line with Jetpack upgrade nudges.

I believe plan name at least should ideally be "Jetpack Premium" in this case as per guide in p6TEKc-2Lx-p2

2019-07-23 14:06 UTC, simison commented
>I just tested this. Turns out Calypso actually redirects /post/:jetpackSite/:postId to jetpackSite/wp-admin/post.php?post=:postId&action=edit, so in theory, we can ship this.
>
> However, there's obviously a chance that Calypso stops redirecting those URLs and instead enables its block editor for them.

@gwwar @vindl do you know if that redirect is designed to be permanent or temporary?

2019-07-23 16:56 UTC, gwwar commented
It depends on the site/plugins installed if we iframe or do a wp-admin redirect:

See the following for full behavior details:
PCYsg-lOu-p2
PCYsg-hNB-p2

2019-07-24 07:25 UTC, simison commented
@ockham what do you think about adding `?env=wp-admin` (or similar) URL arg to the Calypso post URL so that we can easily enforce the redirection when needed. Could be useful also when customers land on the page from Simple site's wp-admin?

2019-07-24 07:26 UTC, simison commented
Ah, I see from docs that `?platform=gutenberg-redirect` already exists so we can use that here. :thumbsup:

2019-07-24 15:48 UTC, gwwar commented
@simison do y'all mind adding the full flow path / what we intend to change here in the summary?

I'm not sure of what folks had in mind for changes, but we'd prefer folks to use the values returned from the opt-in API vs hard-coding links on the client. This makes future refactoring a bit easier to handle since there's less coupling of behaviors

2019-07-29 07:27 UTC, ockham commented
> I believe plan name at least should ideally be "Jetpack Premium" in this case as per the guide in p6TEKc-2Lx-p2

That should be the case already, per #13065 (might need a rebase).

2019-07-29 07:51 UTC, simison commented
Rebased and upgraded the screenshot.

2019-07-29 08:01 UTC, simison commented
> I'm not sure of what folks had in mind for changes, but we'd prefer folks to use the values returned from the opt-in API vs hard-coding links on the client. This makes future refactoring a bit easier to handle since there's less coupling of behaviors

Customer should land in the same place they left from. So if they're in Calypso block editor, they should end up in Calypso after checkout. If they're in wp-admin, they should land back exactly in the same place.

This regardless if we're talking about Jetpack or simple site.

Exact flow is: _Clicks upgrade nudge in the editor → Checkout → Editor_.

Currently we land folks on Calypso also for simple sites if they started from wp-admin, so feels like the mechanism could be generic enough to work for both Jetpack- and Simple sites.

2019-07-29 09:32 UTC, ockham commented
> It depends on the site/plugins installed if we iframe or do a wp-admin redirect:
> 
> See the following for full behavior details:
> [PCYsg-lOu-p2](https://href.li/?https://wp.me/PCYsg-lOu)
> [PCYsg-hNB-p2](https://href.li/?https://wp.me/PCYsg-hNB)

@gwwar Thanks for these resources!

Curious, what about having that Gutenberg Opt-In endpoint return a concrete editor URL (much like it does for opt-out anyway)? That would require including the post ID in the request, but I think it'd make the endpoint much more handy for our use case if we could rely on it to return a ready-made URL rather than having to build it ourselves.

2019-07-30 07:19 UTC, ockham commented
Considering this again, I might've been barking up the wrong tree with my previous https://github.com/Automattic/jetpack/pull/13081#issuecomment-515919323.

At this point, I'm not sure if the opt-in API is relevant to us at all, since we already _know_ that the user is using the block editor when they encounter our upgrade nudge, since it is tied to a given block.

@gwwar I'll try to clarify the situation about the redirect here. Not adding this to the PR desc since the PR isn't really changing anything -- but maybe it should :grimacing: 

The question we're pondering here is about a (post-checkout) [redirect route](https://github.com/Automattic/jetpack/blob/91c567666cab72637132378cedd3ae7fd32984d9/extensions/shared/upgrade-nudge/index.jsx#L79-L85) that we pass to Calypso checkout when clicking the 'Upgrade' button. Calypso checkout currently only accepts server-relative URLs (on WP.com -- typically something like `?redirect_to=/post/:site/:postID`, url-escaped), which has been sufficient for this feature as long as we've been using it only on WP.com.

Since we're now about to enable the feature on Jetpack, we've been wondering about how to deal with that redirect for self-hosted sites (e.g. `https://example.com/wp-admin/post.php?post=123&action=edit`) . There are several ways to go about this:

1. Change Calypso checkout to accept complete URLs as `redirect_to` targets. To prevent abuse, we'd also need to add validation (e.g. is it a Jetpack site? Is it and editor route?) This kind of validation could become relatively complex. On the plus side, it allows us to continue to use the `redirect_to` qarg.
2. Change Calypso checkout to accept parts like host and post ID, and have Calypso assemble the URL. I'm not a big fan of this, since it's kind of an arbitrary API added in addition to the `redirect_to` mechanism (and a sleuth of more indirect post-checkout redirect mechanisms found in Calypso :roll_eyes: ). The qargs might be ugly (`redirect_host`, `redirect_post_id`), and might not be too future-proof after all. On a sidenote, it also raises the question whether we'd continue to use `redirect_to` for WP.com sites, or if we would also use the new 'ugly' scheme.
3. Change nothing :sunglasses: As I [found out](https://github.com/Automattic/jetpack/pull/13081#issuecomment-512782479), redirecting to `/post/example.com/123` on Calypso actually redirects to `https://example.com/wp-admin/post.php?post=123&action=edit` if `example.com` is a Jetpack site (via `/block-editor/post/example.com/123`, IIRC). Soooo we could leave things as they are, continue to pass server-relative URLs as `redirect_to` target, and rely on Calypso for the redirect.

The most relevant criterion is that we pass the redirect target in a stable format that doesn't need changing across Jetpack releases, and that will continue to exinst in Calypso, thus putting the burden of accomodating for changed 'actual' redirect targets on Calypso.

I kind of prefer option 3., since it's temptingly simple. However, there's a problem with this:
- It relies on the assumption that the route will continue to redirect to Jetpack wp-admin, when in reality we might at some point allow users to use the block editor for their Jetpack sites from within Calypso (I'm not up to date with any plans in that regard).
- This is actually just one way to put the larger, more conceptual problem: The user might be editing a post within different environment (albeit always from within a block editor) when encountering and clicking the ugrade nudge: wp-admin and Calypso come to mind, specifically. A one-size-fits-all redirect URL might simply not be appropriate; instead, we might need to take that current environment into account. One way to accomodate for that we've been thinking about was to still consider the (server-relative) redirect URL as the 'canonical' format, but possibly add a query arg indicating the environment. Is this something that our Calypso block editor routing already happens to support?

(I'm only mentioning posts here, but pages and CPTs work alike.)

2019-07-30 07:50 UTC, ockham commented
> Ah, I see from docs that `?platform=gutenberg-redirect` already exists so we can use that here.

I checked the docs (PCYsg-hNB-p2), and IIUC, there's a `platform` qarg you can use to ask the endpoint what the preferred editor is for either `?platform=web` or `?platform=mobile`. The response then contains a `editor_web` field, for which one possible value is `gutenberg-redirect`, which means

> Redirect to the WP Admin block editor. Used in ineligible Jetpack sites for Gutenframe.

So it looks like we can't use syntax like `?platform=gutenberg-redirect` to force anything here :thinking:

2019-07-30 07:54 UTC, simison commented
@mtias mentioned that block-editor routes are in need of some work and we'll likely need iteration there no matter what.

@ockham what do you think about relying on current working redirect and adding some trust to it with:
- adding a test so that we'd hopefully notice when behavior would change/break?
- adding a pre-route or query argument as a safeguard so that we can build custom redirection if needed after the fact. Note that we cannot go back in time and update the URL in Jetpack that already shipped to customers?

2019-07-30 08:17 UTC, ockham commented
> @mtias mentioned that block-editor routes are in need of some work and we'll likely need iteration there no matter what.
> 
> @ockham what do you think about relying on current working redirect and adding some trust to it with:
> 
> * adding a test so that we'd hopefully notice when behavior would change/break?
> * adding a pre-route or query argument as a safeguard so that we can build custom redirection if needed after the fact?

Using the current redirect is kind of my preferred solution, too, but it has the shortcoming of being ignorant of the 'source' environment, i.e. from where it was actually called. Adding another route fragment (is that what you mean with pre-route?) or query arg would give us a degree of freedom to mitigate that issue. (It might still me somewhat awkward to pass e.g. `env=wp-admin`, and have Calypso construct a totally different route from the `/block-editor/post/example.com/123` we're passing as `redirect_to` arg. Still trying to assess how much better/worse that would be compared to the other options I was listing.)

> Note that we cannot go back in time and update the URL in Jetpack that already shipped to customers.

Yep, that's what I hoped to express with 

> The most relevant criterion is that we pass the redirect target in a stable format that doesn't need changing across Jetpack releases, and that will continue to exinst in Calypso, thus putting the burden of accomodating for changed 'actual' redirect targets on Calypso.

:slightly_smiling_face:

2019-07-30 09:20 UTC, simison commented
>Adding another route fragment (is that what you mean with pre-route?)

I meant a completely new route that just redirects to `/block-editor/post/example.com/123` that then (currently) redirects back to `example.com/wp-admin/post.php?p=123` but more important than that is the sentiment that we have something to catch it in case we need.

I.e. we agree on the sentiment, the rest are implementation details. :-)

2019-07-30 11:28 UTC, ockham commented
I had another thought.

I'm starting to think I had my wires crossed after all. If we cut back to the bare minimum of what we know, it's pretty simple: We're editing the post in a (self-hosted) Jetpack site's block editor, and _that's_ what we want to redirect to, post-purchase.

Scenarios where that editor is iframed by Calypso can be deemed an extension on top of that behavior that we shouldn't need to worry about -- it's that consumer's responsibility to take care that things work as they should in such a setting (not Jetpack's).

The fact that the Calypso URL (`/block-editor/post/example.com/123`) redirects back to `example.com/wp-admin/post.php?p=123` should be deemed circumstantial, and potentially subject to change.

By consequence, I think that this means that the 'correct' way forward is to use the full, current Jetpack URL as `redirect_to` arg, and add logic to Calypso checkout to validate/sanitize it.

2019-07-30 16:25 UTC, gwwar commented
For what you need a reference to the referrer or redirect query param likely makes sense.

For additional context on current flows:

Starting from WordPress.com/block-editor:
- We check editor preferences
- If the site is compatible the Jetpack site can use the WordPress.com iframe
- If the site has incompatible plugins, it will be redirected to wp-admin
- If the site has incompatible plugins and it is an atomic site it will be redirected to wp-admin with additional styling (Calypsoify)

If folks start from wp-admin, it's a no-op. (No redirects occur)

There's also an iframe check method in https://github.com/Automattic/jetpack/blob/84a41926cbb52bb492eab7a51e71077e1a62cdaa/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L53 if y'all happen to need it.

2019-08-01 11:34 UTC, ockham commented
> By consequence, I think that this means that the 'correct' way forward is to use the full, current Jetpack URL as `redirect_to` arg, and add logic to Calypso checkout to validate/sanitize it.

#13165

2019-08-05 11:21 UTC, ockham commented
Rebased to include #13165. Can we get a :+1: please? :smile:

2019-08-05 11:23 UTC, jeherve approved these changes

2019-08-05 11:26 UTC, ockham approved these changes

2019-08-05 11:29 UTC, merged

2019-08-05 11:29 UTC, ockham commented
That was fast! Thanks a lot @jeherve!

2019-08-05 12:30 UTC, sirreal commented
Thanks everyone for getting this shipped!