Fix styling of Calypsofied "add contact form" button.
Automattic/jetpack pull request #13111
Opened 2019-07-22 22:07 UTC by jeffstieler

Fixes https://github.com/Automattic/wc-calypso-bridge/issues/460.

#### Changes proposed in this Pull Request:

* Fix styling of the "add contact form" button on Calypsoified pages

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No

#### Testing instructions:

* Enable the contact form module
* Add New post, product, etc
* Ensure page is Calypsoified (`?calypsoify=1`)
* Verify "add contact form" button styling looks good

Before:
<img width="342" alt="Screen Shot 2019-07-22 at 4 04 07 PM" src="https://user-images.githubusercontent.com/63922/61668691-bd288080-ac9a-11e9-8637-db2f9fdd051a.png">

After: 
<img width="357" alt="Screen Shot 2019-07-22 at 3 56 40 PM" src="https://user-images.githubusercontent.com/63922/61668707-c4e82500-ac9a-11e9-99ca-fc7ab90861ef.png">

#### Proposed changelog entry for your changes:

* Probably doesn't need a changelog entry

2019-07-29 08:34 UTC, jeherve requested changes
I can't seem to be able to reproduce the bug on the latest stable:

![image](https://user-images.githubusercontent.com/426388/62033519-71229200-b1ec-11e9-8822-fa7773b298ec.png)

Does it happen in a specific browser? Is this limited to a specific post type?

2019-07-29 17:53 UTC, jeffstieler commented
> Does it happen in a specific browser? Is this limited to a specific post type?

It occurred for me in Chrome on the Product post type.

2019-07-31 16:18 UTC, jeherve commented
> It occurred for me in Chrome on the Product post type.

It's odd, I still can't reproduce. Is there any other CSS that may bleed over on the site where you are testing?

2019-07-31 16:19 UTC, jeherve approved these changes
While I can't reproduce the issue, this does not seem to introduce any new problems either. Approving for now, but I'd be happy if someone else who can actually reproduce the problem could review this. 👍

2019-08-13 15:12 UTC, kbrown9 commented
I wasn't able to reproduce this bug. I tried Chrome and Firefox with Product posts.

@jeffstieler  The Contact Form icon now looks smaller than the Media icon. 
Please see the before/after screenshots below. In your screenshots, the icon size looked fine. Can you check if there's any other CSS on your site that might be affecting the icon and button?

### Before PR:

![Screen Shot at August 13th 2019 - 12 34 07 am](https://user-images.githubusercontent.com/50059399/62951819-a6b4a700-bdb8-11e9-9829-3b09025872c3.png)

### After PR:

![Screen Shot at August 13th 2019 - 12 30 19 am](https://user-images.githubusercontent.com/50059399/62951885-c1871b80-bdb8-11e9-9a02-4b2cab910067.png)

2020-07-27 12:41 UTC, jeffstieler commented
Following up on old PRs - closing this since it couldn't be repro'd.

2020-07-27 12:41 UTC, closed without merging