Add module that creates a permanent revision from a significantly modified autosave
Automattic/jetpack pull request #13148
Opened 2019-07-30 09:49 UTC by jsnajdr

When the editor does an autosave repeatedly, create a permanent revision from the old
autosave if the new one is significantly different. Makes losing edited content less
likely.

Adapted from a WP.com patch (D30389-code), converted the code to a Jetpack module and
added (optional) recording of StatsD events using the new `jetpack_stats_statsd` action
(that will be hooked into on WP.com).

Fixes an issue reported in Calypso repo: Automattic/wp-calypso#20265

#### Testing instructions:
(adapted from D30389-code)
This module creates a permanent revision if new autosave's content length is more than 250 characters smaller or bigger than the old one's.

- edit a draft or published post in various editors (Classic or Block)
- add one character and wait for autosave. Check that permanent revision was not created. (best done with revisions page opened in a second browser tab) You see a revision for the post content before you started editing, and an autosave revision with the one new char.
- add 250+ characters and wait for autosave. Check that permanent revision was created from the previous autosave (+1 char edit)
- start editing again from a fully saved state. Add 250+ characters and wait for autosave. Check that permanent revision was not created: the content before the autosave already has a revision and the one created during autosave would be an identical one.

#### Proposed changelog entry for your changes:
* Writing: more reliable autosaves that save a permanent revision before large changes

2019-07-30 17:03 UTC, jeherve requested changes
Since you are adding a brand new file, could you add it to the PHPCS whitelist?
https://github.com/Automattic/jetpack/blob/5a2bb2b2423a42a59ced3674f30339605fbc7fd5/bin/phpcs-whitelist.js

That will allow you to get some recommendations on commit, and to fix any PHPCS issues on the file.

2019-07-30 17:22 UTC, jsnajdr commented
@jeherve The PHPCS whitelist add is already in 65edf255

2019-07-30 20:50 UTC, donpark approved these changes
LGTM

Works like WPCOM version of the patch. BTW, I'm not a Jetpack code owner so you'll need ✅ from @jeherve .

2019-07-31 09:00 UTC, jeherve commented
> @jeherve The PHPCS whitelist add is already in [65edf25](https://github.com/Automattic/jetpack/commit/65edf255f20e2522587b38d73ba177e0bc97659f)

Excellent! Do you think you could now fix the issues that pop up? You should see them in your editor, or when running `vendor/bin/phpcs -w modules/autosave-revisions.php`.

2019-07-31 13:29 UTC, jsnajdr commented
> Do you think you could now fix the issues that pop up?

Yes! 🙂 This PR will be most likely closed and we'll ship the code to Atomic via a different route. Let's keep in open while other options are evaluated.

2019-08-12 07:17 UTC, jsnajdr commented
We shipped this to Atomic as part of wpcomsh instead, can be closed. Thanks everyone for cooperation.

2019-08-12 07:17 UTC, closed without merging