Settings: Allow language change even if WPLANG is defined as constant
Automattic/jetpack pull request #13154
Opened 2019-07-30 18:08 UTC by donpark

`wp-admin` users can change site language even if `WPLANG` constant is defined in `wp-config.php`. This PR allows Calypso user to do the same in the general settings page (`/settings/general/`).

Fixes https://github.com/Automattic/wp-calypso/issues/33440

#### Changes proposed in this Pull Request:

Removes `defined( 'WPLANG' )` checks from Jetpack's Core Data API endpoints used by Calypso to change site settings.

#### Testing instructions:

1. Test with a Jetpack site whose `wp-config.php` contains the line `define('WPLANG', '');`
2. Navigate to URL: https://wordpress.com/settings/general/{site_slug}.
3. Check that error message no longer appears.

*Before:*
<img width="855" alt="58593747-97de3f80-8220-11e9-8211-e2b65f0a0d8c" src="https://user-images.githubusercontent.com/127594/62153603-ca0c2c00-b2b9-11e9-8c95-7d53380f247d.png">

*After:*
<img width="772" alt="screenshot_815" src="https://user-images.githubusercontent.com/127594/62153695-02ac0580-b2ba-11e9-8471-fbc8a6af0390.png">

4. Also check that site language can now be changed.
 
#### Proposed changelog entry for your changes:

* allow language to be changed even if `WPLANG` constant is defined.

2019-07-30 18:15 UTC, donpark commented
Core displays a notice after site language is change if `WPLANG` constant is defined:

<img width="762" alt="screenshot_814" src="https://user-images.githubusercontent.com/127594/62154039-c5944300-b2ba-11e9-979e-85b81e80f8b9.png">

I felt above message may confuse Calypso users so chose not to display a similar notice. Fact that it involves a lot more work to display the notice also contributed.

2019-07-30 20:07 UTC, gravityrail submitted a review, later dismissed
I have confirmed that this patch fixes the issue.

2019-07-31 00:56 UTC, donpark commented
Reason for most recent update: Core's `get_locale()` uses WPLANG as default if defined and non-empty. Otherwise `en_US` is used.

2019-07-31 10:23 UTC, jeherve requested changes
This handles empty strings for `WPLANG` well, but it does not handle valid strings.

For example, if I set `WPLANG` to `fr_FR`, here is what happens today with `master`:

![image](https://user-images.githubusercontent.com/426388/62204489-87b41f00-b38d-11e9-80fd-ce9ae196794a.png)

And here is what happens with your branch:

![image](https://user-images.githubusercontent.com/426388/62204507-93074a80-b38d-11e9-8ad4-da114b58c412.png)

That is not correct here, since my interface language is actually french, not English.

Maybe when `WPLANG` is defined and not empty, we should send the value back to WordPress.com so it can be displayed in Calypso.

2019-07-31 15:55 UTC, donpark commented
> For example, if I set `WPLANG` to `fr_FR`, here is what happens today with `master`:
> ... 
> That is not correct here, since my interface language is actually french, not English.

That may be a problem in Calypso, not in JP endpoint. With same setup, `lang_id` returned by remote Jetpack endpoint is French as remote site's wp-admin displays:

<img width="832" alt="screenshot_819" src="https://user-images.githubusercontent.com/127594/62226148-94754a80-b36e-11e9-9612-95b80674fa83.png">

wp-admin:

<img width="543" alt="screenshot_822" src="https://user-images.githubusercontent.com/127594/62226906-ce931c00-b36f-11e9-8247-b798dfe2c121.png">

But Calypso continues to display English as site language.

<img width="594" alt="screenshot_821" src="https://user-images.githubusercontent.com/127594/62226371-fafa6880-b36e-11e9-9985-7c52be3295d8.png">

Since this PR is about the endpoint, perhaps I should update the test plan to use WPCOM Console so we can at least fix the JP endpoint behavior to match that of wp-admin.
 
Meanwhile I'm going to look into why Calypso is misbehaving. I also noticed several `/me/setttings` requests being made repeatedly when Settings page reloads, all failing with `reauthorization_required` that is ignored by Calypso.

> Maybe when `WPLANG` is defined and not empty, we should send the value back to WordPress.com so it can be displayed in Calypso.

Did you test with latest version? That's is what is being done now.
```
$value = get_option( 'WPLANG' );
if ( empty( $value ) && defined( 'WPLANG' ) ) {
	$value = WPLANG;
}
$response[ $setting ] = empty( $value ) ? 'en_US' : $value;
```

2019-07-31 16:22 UTC, donpark commented
Hold on. I may be looking at wrong API response.

2019-07-31 18:07 UTC, donpark commented
OK. I was looking at the wrong endpoint. End point that matters is and it was returning `en_US` as `lang_id`:
https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{site_id}/rest-api/?http_envelope=1&path=%2Fjetpack%2Fv4%2Fsettings%2F&json=true

Tracking that why turned into a head-scratcher because:

1. `WPLANG` *option* was not set and
2. invoking `get_option( 'WPLANG' )` from `wp shell` returns `false` but
3. same function call in the endpoint code was returning `en_US` as value.

Replacing the call with `get_option( 'WPLANG', '' )` removed the mystery value and Calypso started displaying same language value as wp-admin with WPLANG constant defined as `fr_FR`:

<img width="608" alt="screenshot_823" src="https://user-images.githubusercontent.com/127594/62235999-00fa4480-b383-11e9-9679-548415d20985.png">

@jeherve I think something went wrong with your test setup because black warning notice only comes up if `error_const` is returned as `lang_id` value and, with this patch, `error_const` is never returned.

2019-08-01 13:09 UTC, jeherve commented
> I think something went wrong with your test setup 

Yes I am sorry, I pasted the same screenshot twice in my comment, that was a mistake.

2019-08-01 13:16 UTC, jeherve approved these changes
This tests well now. 👍

2019-08-01 18:59 UTC, merged