Add doc for remote debugging in vscode
Automattic/jetpack pull request #13211
Opened 2019-08-11 22:13 UTC by isabellachen

Related to #13180 

Add documentation for remote debugging in VSCode.

2019-08-15 09:48 UTC, brbrr commented on docker/README.md
> +- PHP Debug plugin installed in VSCode
Do you think we add a link to the "correct" plugin? I see 2 "PHP Debug" extensions available, adding a link should help figure out which one to install

 ```suggestion
- [PHP Debug](https://github.com/felixfbecker/vscode-php-debug) plugin installed in VSCode
```

2019-08-15 10:01 UTC, brbrr requested changes
Thank you for your contribution! This guide is really helpful. 

I left a few minor comments with some suggestions.

2019-08-16 15:34 UTC, isabellachen commented on docker/README.md
> +- The easiest Xdebug for Mozilla Firefox.
I've changed the link to point to 'Xdebug Helper' for Mozilla Firefox. It's the same as the one for Chrome, except for Firefox.

2019-08-16 15:48 UTC, isabellachen commented
@brbrr Thanks for the suggestions, I've committed them and added the link for the Mozilla extension.

2019-08-16 15:54 UTC, isabellachen commented
@brbrr Hmm, I rebased against the latest master, I probably shouldn't have done that -_- for this task...

2019-08-16 16:22 UTC, isabellachen commented
@brbrr I think I better make a new branch from master and copy over the text from the readme and make a new PR from there, otherwise there could be trouble...

2019-08-19 14:27 UTC, jeherve commented
I took care of the rebase for you (following steps similar to the ones described [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)), and pushed a few minor changes.

2019-08-19 14:39 UTC, jeherve commented on docker/README.md
> +- If you use Firefox, install [Xdebug Helper](https://addons.mozilla.org/en-GB/firefox/addon/xdebug-helper-for-firefox/) add-on.
I updated the add-on here as the old one you had previously recommended does not appear to be available in the Firefox add-on library anymore.

2019-08-19 14:40 UTC, jeherve approved these changes
I think this is useful info, it's going to be very helpful for folks using VS Code, thank you. I've made a few minor changes, but overall I think this is good to go.

@brbrr What do you think? Wanna merge this?

2019-08-19 15:25 UTC, brbrr approved these changes

2019-08-19 15:26 UTC, merged