Connection: adds a new `is_registered()` method
Automattic/jetpack pull request #13230
Opened 2019-08-14 20:44 UTC by roccotripaldi

Fixes it so various parts of the code base can see if the current site has
been registered ( has an ID and a token ).

This is part of an effort of breaking #13112 into smaller bits.

#### Changes proposed in this Pull Request:

* Adds a new `is_registered()` method to the Connection Manager in the connection package
* refactors the Provision API to use the new method
* refactors the jetpack_connection_status API method to use the new method

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

Enhances existing features.

#### Testing instructions:
* need to test the Provision flow ( ask for help from @ebinnion maybe )
* need to test the `jetpack_connection_status` ( ask for help from @zinigor maybe )

#### Proposed changelog entry for your changes:

* None

2019-08-14 21:07 UTC, gititon commented
Nice work! PRs like this will add up to make a big difference, since methods like the `is_registered()` function you added which lays out the criteria for being registered is so much clearer/self documenting than compound conditionals checking "random" ids, etc.

2019-08-14 21:08 UTC, gititon submitted a review, later dismissed

2019-08-15 08:12 UTC, tyxla requested changes
This looks great, thanks!

I'd just suggest using the shared connection manager object instead of creating a new one.

Also, it would be great to have some tests - but the way we're accessing the `\Jetpack_Options::get_option()` method might be a bit difficult to mock, so we could consider adding tests at a later point.

2019-08-15 14:00 UTC, tyxla submitted a review, later dismissed
This looks good to me! Thank you!

Left a couple of formatting nits, but feel free to ship once you're sure the provisioning change works as well.

2019-08-15 14:00 UTC, tyxla commented on packages/connection/src/Manager.php
> +	public function is_registered() {
Let's keep it as-is! `is_active()` is here too.

2019-08-16 21:30 UTC, lezama approved these changes

2019-08-16 21:31 UTC, lezama approved these changes

2019-08-16 21:31 UTC, merged