Connection: Add "connect in place" A/B test to plugins and dashboard
Automattic/jetpack pull request #13325
Opened 2019-08-26 14:01 UTC by tyxla

We've already implemented the "connect in place" A/B test in the general connection button on the Jetpack dashboard.

This PR adds the A/B test for the connection banner that appears on the plugins page and the WP admin dashboard.

#### Changes proposed in this Pull Request:
* Connection: Add "connect in place" A/B test to plugins and dashboard

Preview of how it works in that banner:

![](https://cldup.com/BD9feyOWRr.png)

![](https://cldup.com/ScXsjyw2PU.png)

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Part of the "Connect in place" project - p1HpG7-7nj-p2

#### Testing instructions:
* Checkout this branch.
* Run `yarn build` or `yarn watch`.
* Disconnect the site if it's already connected.
* Enable the `JETPACK_SHOULD_USE_CONNECTION_IFRAME` constant locally.
* Go to `/wp-admin/plugins.php` and try the connection flow.
* Make sure you're able to connect.
* Disable the `JETPACK_SHOULD_USE_CONNECTION_IFRAME` constant locally.
* Make sure the old connect button still works and looks well in all locations (wp admin dashboard, plugins dashboard, Jetpack dashboard)

#### Proposed changelog entry for your changes:
* Connection: Add "connect in place" A/B test to plugins and dashboard.

2019-08-26 14:47 UTC, jeherve approved these changes
This works well for me, although the extra step (clicking on "Set up Jetpack", waiting a bit, getting the "connect using WordPress.com" button instead, and then clicking again) feels a bit off.

2019-08-26 15:21 UTC, jeffgolenski requested changes
Let's try widening the iframe to the width of the content above it so it's not an awkward square block in a rectangle connection banner.

2019-08-27 12:49 UTC, simison commented
@jeffgolenski see p7rcWF-14z-p2#comment-2018 for instructions about the constant on JN.

2019-08-28 14:43 UTC, tyxla commented
Thanks, Jeff! We'll postpone this for the next release.

2019-09-19 10:41 UTC, jeherve commented
Removing from the 7.8 milestone for now since it's still in progress.

2019-09-25 10:16 UTC, tyxla commented
We've decided to go a different path, namely: redirect from the WP-admin dashboard and plugins page connection buttons to the Jetpack dashboard with the iframe loaded. This will provide a consistent experience, and will save the cost of having to refactor all those screens again to fit the new connection flow.

Closing this one.

2019-09-25 10:16 UTC, closed without merging

2019-09-25 11:10 UTC, keoshi commented
> redirect from the WP-admin dashboard and plugins page connection buttons to the Jetpack dashboard with the iframe loaded

@enejb told me about this just now, and I want to say: YAY!