[WIP] Slideshow block: Add image size selector
Automattic/jetpack pull request #13362
Opened 2019-08-29 14:22 UTC by mmtr

#### Changes proposed in this Pull Request:
 TBD

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
TBD

#### Testing instructions:
TBD

#### Proposed changelog entry for your changes:
TBD

2019-09-03 01:27 UTC, mmtr commented
The image selector is working after the last commit, but we still need to add a deprecated version of the block in order to support existing posts containing slideshow blocks (the block expect now images in `large` size but existing posts are using the `full` size).

2019-10-09 14:23 UTC, mmtr commented
> The image selector is working after the last commit, but we still need to add a deprecated version of the block in order to support existing posts containing slideshow blocks (the block expect now images in `large` size but existing posts are using the `full` size).

I don't think this is possible. The deprecation would be a block with `sizeSlug` defaulting to `full`, but we don't have any way of detecting if a block is deprecated in this case, since Gutenberg [removes attributes set with default values](https://github.com/WordPress/gutenberg/blob/867ef682bd3ca603811de2672fbee3d4bbf034ee/packages/blocks/src/api/serializer.js#L167-L170) when serializing a block. This means that both, a block inserted before the image selector is available and another one inserted with the image selector, would have the same attributes serialized (`sizeSlug` will be omitted), so Gutenberg will use the current version  of the block.

The consequence of leaving the block without handling deprecations is that blocks added before the image selector will still use full size images (which is ok) but the image selector will be set as "Large". Maybe not a big deal 🤷‍♂️.

2019-10-10 00:33 UTC, gwwar commented
> The deprecation would be a block with sizeSlug defaulting to full, but we don't have any way of detecting if a block is deprecated in this case, since Gutenberg removes attributes set with default values when serializing a block. 

This seem a bit silly that we can't detect this. 

Can we add a block version attribute here?  For example pick `1.0` for this update, and if it's missing the property we know images should be full, and then explicitly save the image size and block version on save. Later on if we make more updates to the block, we can bump the block version and we know which set of assumptions/transformations we need to make. I can defer to you though @mmtr if this seems like too much work.

Overall, this tests very well for newly created blocks.

2019-10-10 13:38 UTC, mmtr commented
> Can we add a block version attribute here? For example pick `1.0` for this update, and if it's missing the property we know images should be full, and then explicitly save the image size and block version on save. Later on if we make more updates to the block, we can bump the block version and we know which set of assumptions/transformations we need to make. I can defer to you though @mmtr if this seems like too much work.

We would have the same problem if that block version attribute was defaulting to a value (using the `default` property when defining the `attributes` in the block settings), since Gutenberg would set the default value when the attribute was missing. 

But this gave me an idea: if we don't define a default attribute value on the block settings but instead we set a default value programmatically based on the lack of the attribute + presence of images, we could differentiate newly created blocks without the attribute set from blocks created in the past by assuming that as of now is not possible to have a block with images and no size. If we find a block with images an no image size set, it'll mean it was created when the image selector was not available. I explored this approach in 41d406c061d2942e3f6958a23113ae25ac9a770c and it seems it works 🙂

2019-10-10 21:50 UTC, gwwar commented
> I explored this approach in 41d406c and it seems it works 

Nice, I'd definitely leave a comment though explaining that :D

2019-10-10 22:00 UTC, gwwar submitted a review, later dismissed
Thanks @mmtr ! This tests well for me. I also verified that old slideshows now correctly show "full" instead of "large" when a size attribute is now set.

2019-10-11 12:52 UTC, jeherve requested changes
It seems I can't change the number of seconds between each slide anymore. I get an error in the console whenever I try to move the slider:

```
Uncaught TypeError: Cannot read property 'props' of undefined
    at setAttributes (edit.js:211)
    at onChange (controls.js:75)
    at onChange (components.min.js:19)
```

2019-10-14 11:46 UTC, mmtr commented
> It seems I can't change the number of seconds between each slide anymore. I get an error in the console whenever I try to move the slider:
> 
> ```
> Uncaught TypeError: Cannot read property 'props' of undefined
>     at setAttributes (edit.js:211)
>     at onChange (controls.js:75)
>     at onChange (components.min.js:19)
> ```

Good catch! Fixed in a16c9ac but then I noted the preview was not rendering the right image size when the autoplay mode was on, so I refactored briefly how the URLs of the images are updated on c222943 which seemed to do the trick.

2019-10-14 12:14 UTC, jeherve approved these changes
This seems to work well on my end. It should be good to merge!

2019-10-14 12:50 UTC, merged

2020-03-13 14:05 UTC, noahott commented
Is it possible to use custom image sizes with the Slideshow block? I’ve created a number of custom image sizes with my theme but only see the default Thumbnail, Medium, Large, and Full Size options in the Image Size dropdown.

Thanks