Autoloader: Cover scenarios where composer/autoload_files.php might not exist.
Automattic/jetpack pull request #13504
Opened 2019-09-20 19:05 UTC by nerrad

Fixes #

#### Changes proposed in this Pull Request:

* Adds a check for if `autoload_files.php` exists before including.

This surfaced in failing tests in travis in the WooCommerce Blocks repo (see [example build fail here](https://travis-ci.com/woocommerce/woocommerce-gutenberg-products-block/jobs/237671098)).

- It looks like it was introduced in 2962a2c (from #12857).

There are scenarios where `composer install --no-dev` will result in no `vendor/composer/autoload_files.php` file so there needs to be a safety check before including it.

#### Testing instructions:

Testing involves

- Create a composer config basic entries in `composer_require` and with a PS4 autoloader config. 
Example:

```
"require": {
	"composer/installers": "1.7.0",
	"automattic/jetpack-autoloader": "dev-fix/autoloader-include-file-if-not-exist"
},
```
- Run `composer install --no-dev` (there should be no `autoload_files.php` file in `vendor/composer/`)
- Verify php app runs without errors.

(Note: I'm going to try this pull against one of our branches to confirm the fix and will post the travis build result here).

#### Proposed changelog entry for your changes:

* Check for `composer/autoload_files.php` before including.

2019-09-23 14:30 UTC, gravityrail submitted a review, later dismissed
LGTM 👍

2019-09-23 14:51 UTC, jeherve requested changes
Quick coding standard changes.

2019-09-23 14:51 UTC, jeherve commented on packages/autoloader/src/AutoloadGenerator.php
> +	    ? require \$autoload_file
```suggestion
		? require \$autoload_file
```

2019-09-23 14:51 UTC, jeherve commented on packages/autoloader/src/AutoloadGenerator.php
> +	    : [];
```suggestion
		: [];
```

2019-09-23 15:03 UTC, nerrad commented
> Quick coding standard changes.

Thanks :) . I recently switched from PHPStorm to VScode for my IDE, in PHPStorm it picked up switches between files and the relevant standards,  apparently VSCode doesn't, or I don't have it configured correctly 😕

2019-09-23 15:14 UTC, jeherve approved these changes
LGTM!

2019-09-24 06:39 UTC, merged

2019-09-24 06:42 UTC, jeherve commented
Cherry-picked to `branch-7.8` in a5fa5a0b57fa781471f5271a8a4a901a94451460