Admin Page: translate empty Stats chart's message
Automattic/jetpack pull request #13558
Opened 2019-09-27 08:34 UTC by jeherve

#### Changes proposed in this Pull Request:

* This should allow us to translate the message appearing in the Jetpack Dashboard's Stats graph when there are no stats available:

![image](https://user-images.githubusercontent.com/426388/65754804-1f29ba00-e112-11e9-93b0-ee67b0d01942.png)

#### Testing instructions:

* Start from a new site in Spanish
* Apply this branch.
* Ensure that the message is still displayed (it won't be translated just yet, but it should still be displayed in English).

#### Proposed changelog entry for your changes:

* Admin Page: translate empty Stats chart's message

2019-09-30 13:54 UTC, zinigor requested changes
This is a great catch, but I have one suggestion.

2019-09-30 13:54 UTC, zinigor commented on _inc/client/components/chart/index.jsx
> +					<span className="dops-chart__empty_notice">{ __( 'No activity this period' ) }</span>
Let's use context here please? Something like `_x( 'No activity this period', 'Notice in the empty statistics chart' )`.

2019-09-30 20:53 UTC, kraftbj commented
Updated the import to the `_x` function. Marking as approved, but will leave it for someone else to merge as a check of my edit.

2019-09-30 21:08 UTC, kraftbj approved these changes

2019-10-01 07:04 UTC, zinigor approved these changes

2019-10-01 07:04 UTC, merged