Update Jetpack button and card styles to match WordPress 5.3
Automattic/jetpack pull request #13729
Opened 2019-10-11 19:08 UTC by gravityrail

This is just an experiment I did to make the Jetpack buttons and borders look a bit closer to the "flat" styles coming in WordPress 5.3. They may, as a result, look a bit out of place on older versions of WordPress, but they _already_ don't match those versions, so I think this is a net win.

I am not a designer, so I was really just eyeballing this and trying to make it look "closer", not perfect.

This also lays the groundwork for integrating `@wordpress/component`s into our Jetpack admin pages without a style mismatch.

#### Changes proposed in this Pull Request:

* Update Jetpack styles to more closely match WordPress 5.3 styles.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Just slightly modifies styles

#### Proposed changelog entry for your changes:

* Update UI styles to fit in WordPress 5.3 core components

#### Screenshots

Here's a cropped before/after shot.

Before:

![myplan-current-cropped](https://user-images.githubusercontent.com/51896/66678061-e31d4b80-ec1f-11e9-8b9e-162869881ed4.png)

After:

![myplan-53-cropped](https://user-images.githubusercontent.com/51896/66678045-db5da700-ec1f-11e9-8df3-6c542d9b38c3.png)

A gallery of the WP 5.3 dash/posts, plus Jetpack before/after screenshots, is available here:

https://cloudup.com/czXdFjw6ykm

2019-10-14 09:53 UTC, keoshi submitted a review, later dismissed
This is looking good! Below are some of the things I've noticed:

### Set up Jetpack button

Not sure exactly what's the scope here, so don't know if this applies, but the green Jetpack button in the initial pre-connection banner has a border that the primary buttons in 5.3 don't (or are the same color as the bg to be exact). It also has the existing Jetpack `:active` styles, which make it look weird.

![jp-connect-button](https://user-images.githubusercontent.com/390760/66741552-b2caec80-ee6d-11e9-8a57-f038e314186f.gif)

### Buttons

`:focus` styles don't match what's in 5.3. Same goes for default buttons.

![image](https://user-images.githubusercontent.com/390760/66742508-b2335580-ee6f-11e9-9df8-7d912e94d2a4.png)

![image](https://user-images.githubusercontent.com/390760/66742572-de4ed680-ee6f-11e9-98f6-e94aa90af739.png)

```
box-shadow:
    0 0 0 1px #5b9dd9,
    0 0 2px 1px rgba(30, 140, 190, 0.8);
```

`:active` styles don't match what's in 5.3. Same goes for default buttons.

![image](https://user-images.githubusercontent.com/390760/66742789-5f0dd280-ee70-11e9-8970-e97ed424d65e.png)

![image](https://user-images.githubusercontent.com/390760/66742799-6634e080-ee70-11e9-9fde-4ddae967a8c4.png)

`background: #00669B`

### Double borders

At least the Site Stats block appears to have a double border. It seems to be caused by a parent and child elements where both have a border property.

![image](https://user-images.githubusercontent.com/390760/66741791-2f5dcb00-ee6e-11e9-9b1a-eafdc6f10627.png)

### Border radii

The change in border radius seems to have some side effects, where adjacent cards have an undesired dip inside where they should be flush instead.

![image](https://user-images.githubusercontent.com/390760/66742112-d5a9d080-ee6e-11e9-9577-fb4c4d8d7a4e.png)

### Margins

Some change in margins makes the external link detached from its card.

![image](https://user-images.githubusercontent.com/390760/66742335-54067280-ee6f-11e9-9b20-be2c33c96a9e.png)

2019-10-17 22:00 UTC, MichaelArestad commented
I did some pretty major changes:
* Updated button focus styles (only on primary/secondary)
* Removed the border radius on card
* Updated border colors on cards via box shadow (to avoid recoding everything)
* Updated card border colors on non-card components to match
* fixed a stats display bug (no more gap)

Suggestions for future updates and migration to WordPress components:
* One PR to import the components - then merge it in
* One PR per component - perhaps even more focused

I apologize for whoever has to review this, but it's ready for another review.

2019-10-17 22:14 UTC, MichaelArestad commented
Scratch that. Found a bunch more styles that need updating in signup flows etc.

2019-10-17 22:40 UTC, MichaelArestad commented
Should be good now. Items to review:
- [ ] Cards
- [ ] Buttons
- [ ] ButtonGroups
- [ ] Jetpack masthead
- [ ] Jetpack dashboard borders and buttons
- [ ] Jetpack settings
- [ ] Disconnected states
- [ ] JITM borders
- [ ] Settings group borders and buttons

2019-10-18 17:41 UTC, gravityrail commented
Button style on the connection iframe doesn't match Jetpack's new style:

<img width="638" alt="approve-button-style" src="https://user-images.githubusercontent.com/51896/67115674-a3acad00-f193-11e9-95e8-952c2579d7cc.png">

Since this is rendered on WPCOM, we could switch out button styles based on the jetpack_version flag passed in via the iframe URL.

2019-10-18 17:47 UTC, gravityrail commented
How do we feel about the iridescent green setup banner in this new style?

Might be out of scope for this ticket since the color is an unrelated style change.

<img width="1239" alt="setup-banner" src="https://user-images.githubusercontent.com/51896/67116106-9c39d380-f194-11e9-9f03-172c49ba15a6.png">

2019-10-18 17:47 UTC, gravityrail commented
Consider this comment a 👍 on this change (I can't leave an actual approval since I still own the PR)

2019-10-18 17:48 UTC, gravityrail commented
@keoshi can you take another look and verify that @MichaelArestad fixed the issues you saw?

2019-10-18 18:32 UTC, MichaelArestad commented
> How do we feel about the iridescent green setup banner in this new style?

We're going to leave it. At least for this PR.

2019-10-18 20:43 UTC, joanrho commented
@MichaelArestad  Tested all of the following on WordPress 5.3-RC1-46561 running Twenty Twenty/twentytwenty-master theme:
 
- [x] Cards
- [x] Buttons
- [x] ButtonGroups
- [x] Jetpack masthead
- [x]  Jetpack dashboard borders and buttons
- [x]  Jetpack settings
- [x]  Disconnected states
- [x]  JITM borders
- [x]  Settings group borders and buttons

These are all looking great, but I caught a few minor things:
1. "Show me" button text on the Stats page is a bit off (See #13783)
2. `dops-section-header` height alignment could be evened out (See #13781)
3. (might be a core design issue) The border-radius of the "Add New" button on the tops of the Posts, Media, Pages, Themes, Plugins, pages is 2px whereas the styles everywhere else in 5.3 all are border-radius: 3px. Screenshot: 
<img width="777" alt="Screen Shot 2019-10-18 at 2 42 35 PM" src="https://user-images.githubusercontent.com/204742/67126963-8be62080-f1b5-11e9-8ce3-d257d850bd27.png">

2019-10-18 21:10 UTC, keoshi commented
Can confirm that number 3 is a core issue that’s currently being worked on!

2019-10-23 14:07 UTC, jeherve requested changes
This looks good to me, but we'll need to add some of those CSS files back.

I also have a few other questions and remarks, but I don't think any of them are blockers.

*******

Should the non-active color be bright blue like this? 

![image](https://user-images.githubusercontent.com/426388/67400538-1233a580-f5ae-11e9-8a27-62aff3ef5841.png)
![image](https://user-images.githubusercontent.com/426388/67400561-1a8be080-f5ae-11e9-8c87-c472d7332451.png)

It does not seem in line with the rest of the CSS in wp-admin:

![image](https://user-images.githubusercontent.com/426388/67400734-5cb52200-f5ae-11e9-925c-91ee15d8cd08.png)

*******************

It seems there is a bit of padding missing here:
![image](https://user-images.githubusercontent.com/426388/67401110-f4b30b80-f5ae-11e9-8b69-a9b20f61f803.png)

******

Maybe that's just me, but it feels odd to go from the closed dropdown with shadows to the flat borders of the open dropdown:

![Screen Recording 2019-10-23 at 02 21 PM](https://user-images.githubusercontent.com/426388/67401185-12807080-f5af-11e9-9b72-d9e5f590f20b.gif)

*********

The blue border around the input fields seem to be bright blue. Is that the same color as Core?

![image](https://user-images.githubusercontent.com/426388/67401277-380d7a00-f5af-11e9-8c54-5ab771548ed8.png)

2019-10-23 16:36 UTC, MichaelArestad commented on packages/jitm/assets/jetpack-admin-jitm-rtl.css
> -/*!
Hmm. I thought these were generated during build so we didn't want to sync them. I didn't specifically remove this one (at least not intentionally). I'll add it back.

2019-10-23 19:19 UTC, MichaelArestad commented on packages/jitm/assets/jetpack-admin-jitm-rtl.css
> -/*!
Added

2019-10-24 09:45 UTC, jeherve approved these changes
Looking good now. Merging.

2019-10-24 09:46 UTC, merged