Business hours block - fix styling in editor and front end
Automattic/jetpack pull request #13728
Opened 2019-10-11 17:36 UTC by MichaelArestad

Fixes display of business hours. It was buggy on Twenty Twenty and this not only resolves that display issue, but hardens it in the future (probably) from breakage.

#### Changes proposed in this Pull Request:

* Changes the way the dd and dt were positioned. No longer relies on floats.

#### Before
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1123119/66672383-65efd780-ec1b-11e9-8bf7-b9ce656a6a23.png">
![image](https://user-images.githubusercontent.com/1123119/66672180-f4b02480-ec1a-11e9-9785-5567d45dcc26.png)

#### After
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1123119/66672211-02fe4080-ec1b-11e9-8de7-8f1abe3d19f4.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/1123119/66672185-f843ab80-ec1a-11e9-938c-534c3a8bb762.png">

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Fixes existing feature.

#### Testing instructions:

* [Install Twenty Twenty](https://github.com/wordpress/twentytwenty)
* Go to post-new.php
* Add a business hours block
* Make sure to check the preview (top inserter only)
* Publish and check the front end

#### Proposed changelog entry for your changes:

* Might need a changelog entry since front end styles and html were slightly modified?

2019-10-11 23:06 UTC, joanrho commented
Just tested and I can verify that it looks like your "After" screenshots, but there's a slight discrepancy between the text leading in the Editor view and published post/page view that still feels a bit off to me. This isn't different from the same visual discrepancy from other blocks, like the Contact Form, though, so I'm going to go ahead and approve this.

2019-10-11 23:06 UTC, joanrho submitted a review, later dismissed

2019-10-14 08:10 UTC, jeherve requested changes
This seems to break the layout when you have multiple opening hours within a single day.

**Before:**

- In the editor:
![image](https://user-images.githubusercontent.com/426388/66736857-b0b35e80-ee6a-11e9-9d6e-049b944afb93.png)
- On the frontend:
<img width="372" alt="screenshot 2019-10-14 at 10 07 15" src="https://user-images.githubusercontent.com/426388/66736847-a729f680-ee6a-11e9-80c2-dfc1a1a3a96d.png">

**After**

- In the editor:
![image](https://user-images.githubusercontent.com/426388/66736884-c163d480-ee6a-11e9-95c3-54ea11d00255.png)

- On the frontend:
![image](https://user-images.githubusercontent.com/426388/66736888-c6288880-ee6a-11e9-8b54-f68faf0cfe87.png)

2019-10-17 20:30 UTC, MichaelArestad commented
Hmm. Good catch. I'm wondering if we need to rethink styles and html a little bit. Will see what I can do.

2019-10-18 00:21 UTC, MichaelArestad commented
@jeherve Made some changes. Can you check my code?

(I'll be messing a little more with the styles tomorrow, but this might be good enough)

2019-10-18 15:10 UTC, jeherve requested changes
It does work better, although I think we're missing a bottom margin below the list now:
![image](https://user-images.githubusercontent.com/426388/67106026-281a2280-f1ca-11e9-863a-8cd506f42555.png)

2019-10-18 18:38 UTC, MichaelArestad commented
@jeherve I didn't make any changes that reduce the bottom margin. I think the change I made actually made it slightly larger. I could add a margin. @joanrho what do you think?

2019-10-18 19:00 UTC, MichaelArestad commented
Made more changes to match original mocks:

#### Editor
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1123119/67120724-18d5ad80-f1a7-11e9-91e7-ef4ed5362815.png">

#### Rendered
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1123119/67120735-20955200-f1a7-11e9-8c70-bf12fea3d68a.png">

#### Mobile
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1123119/67120771-330f8b80-f1a7-11e9-8717-08c7571a43d2.png">


CC @joanrho

2019-10-18 19:06 UTC, MichaelArestad commented
CC @thomasguillot

2019-10-21 09:43 UTC, jeherve approved these changes
This seems to work well for me. Merging.

2019-10-21 09:43 UTC, merged