Instant Search: Hook up default sort options
Automattic/jetpack pull request #13742
Opened 2019-10-13 22:38 UTC by gibrown

Connect options from the widget to the front end app:
- default sort when none is specified
- post type filters passed through, but not hooked up
- enabling load on scroll forced to be disabled. doesn't seem to be working yet

#### Testing instructions:
* Add define( "JETPACK_SEARCH_PROTOTYPE", true ); to your wp-config.php.
* Ensure that your site has the Jetpack Pro plan and Jetpack Search enabled.
* Add a Jetpack Search widget to the Search page sidebar and configure some filters.
* Try different default sort settings in the widget and verify that they are reflected on the front end.

2019-10-13 22:41 UTC, gibrown commented
This should fix #13643

2019-10-14 19:47 UTC, jsnmoon requested changes
This should be good to go with a small tweak for `props.initialSort`.

2019-10-14 19:47 UTC, jsnmoon commented on modules/search/instant-search/components/search-app.jsx
> +		this.props.initialSort = determineDefaultSort( this.props.options.sort );
We should refrain from assigning/re-assigning properties.

2019-10-14 19:47 UTC, jsnmoon commented on modules/search/instant-search/index.jsx
>  			initialFilters={ getFilterQuery() }
```suggestion
			initialFilters={ getFilterQuery() }
			initialSort={ determineDefaultSort( window[ SERVER_OBJECT_NAME ].sort ); }
```

2019-10-14 22:01 UTC, jsnmoon approved these changes

2019-10-15 14:49 UTC, merged