Fix logic for choosing between customizer and widgets.php
Automattic/jetpack pull request #13858
Opened 2019-10-28 17:36 UTC by chickenn00dle

This commit changes the logic for determining whether we are in the
customizer or widgets.php. Previously, when accessing widgets from
widgets.php, the logic failed to recognize this when the page
initialized with no widgets.

This ensures the correct element is selected, even when there are no
active plugins when the page loads.

Fixes #12302

#### Changes proposed in this Pull Request:

* removes an additional check for widget-control-actions class when initializing the widgets_shell variable
* instead check that widgets_shell is not undefined and empty before resorting to customize-controls ID

#### Testing instructions:
From https://github.com/Automattic/jetpack/issues/12302#issuecomment-538669241

* Go to the widgets page, remove all widgets from the widget area and refresh the page (imp step).
* Add a widget, hit visibility button, it doesn't work
* Refresh the page, hit visibility button, it works!

#### Proposed changelog entry for your changes:

* Fixes bug in widget visibility where visibility button did not work when widgets.php loaded with no active plugins

2019-11-19 15:23 UTC, jeherve commented
Noting that this was originally added to fix an issue on WordPress.com. See 6714-wpcom for more details.

That said, applying your patch on WordPress.com does not seem to break things. 👍

2019-11-19 15:27 UTC, jeherve requested changes
Could you bump the version of that file as it is enqueued here?
https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/widget-visibility/widget-conditions.php#L34

That will help ensure that everyone gets the updated version of the file loading on their site after the update.

Thank you!

2019-11-28 19:39 UTC, chickenn00dle commented
Apologies for the delay on this @jeherve!

I've bumped the version number :)

2019-12-02 09:33 UTC, jeherve approved these changes
This tests well. Merging.

2019-12-02 09:34 UTC, merged