Adds @chaosexanima to contributors! :)
Automattic/jetpack pull request #13879
Opened 2019-10-29 16:09 UTC by ChaosExAnima

Fixes #

#### Changes proposed in this Pull Request:

*

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

*

2019-10-29 16:13 UTC, jeherve requested changes
Cool!

You're part of the team, so you could add yourself in the first list above where you've added yourself. We can also take that opportunity to remove folks not in the team anymore.

I also think you could add yourself to the contributor list in the `readme.txt` file as well, so you'll appear as a plugin author on WordPress.org.

2019-10-29 16:17 UTC, ChaosExAnima commented
I updated `readme.txt` as well! I'm not sure who is a stale contributor, however?

2019-10-29 17:13 UTC, jeherve requested changes
Just a couple more changes.

2019-10-29 17:13 UTC, jeherve commented on readme.md
> +Jetpack is developed and maintained by various teams at Automattic. The Jetpack Crew responsible for coordinating everything is comprised of @brbrr, @dereksmart, @chaosexanima, @jeherve, @kbrownkd, @
```suggestion
Jetpack is developed and maintained by various teams at Automattic. The Jetpack Crew responsible for coordinating everything is comprised of @brbrr, @dereksmart, @chaosexanima, @jeherve, @kbrown9, @kraftbj, @mdawaffe, and @zinigor.
```

2019-10-29 17:13 UTC, jeherve commented on readme.txt
> +Contributors: automattic, adamkheckler, aduth, akirk, allendav, alternatekev, andy, annezazu, apeatling, azaozz, batmoo, barry, beaulebens, blobaugh, cainm, cena, cfinke, chaselivingston, chellycat,
```suggestion
Contributors: automattic, adamkheckler, aduth, akirk, allendav, alternatekev, andy, annezazu, apeatling, azaozz, batmoo, barry, beaulebens, blobaugh, cainm, cena, cfinke, chaselivingston, chellycat, clickysteve, csonnek, danielbachhuber, davoraltman, daniloercoli, designsimply, dllh, drawmyface, dsmart, dzver, ebinnion, egregor, eliorivero, enej, eoigal, erania-pinnera, ethitter, gcorne, georgestephanis, gibrown, goldsounds, hew, hugobaeta, hypertextranch, iammattthomas, iandunn, jblz, jasmussen, jeffgolenski, jeherve, jenhooks, jenia, jessefriedman, jgs, jkudish, jmdodd, joanrho, johnjamesjacoby, jshreve, kbrownkd, keoshi, koke, kraftbj, lancewillett, lschuyler, macmanx, martinremy, matt, matveb, mattwiebe, maverick3x6, mcsf, mdawaffe, MichaelArestad, migueluy, mikeyarce, mkaz, nancythanki, nickmomrik, obenland, oskosk, pento, professor44, rachelsquirrel, rdcoll, ryancowles, richardmuscat, richardmtl, roccotripaldi, samhotchkiss, scarstocea, sdquirk, stephdau, tmoorewp, tyxla, Viper007Bond, westi, yoavf, zinigor
```

2019-10-30 08:47 UTC, jeherve approved these changes

2019-10-30 08:48 UTC, merged

2019-10-30 08:48 UTC, jeherve commented
Cherry-picked to `branch-7.9` in 29feed6349de956300d428498950b23fd58d982d