Add connection authentication URL.
Automattic/jetpack pull request #14004
Opened 2019-11-08 20:18 UTC by zinigor

This PR adds a new method that generates an authentication URL for a certain user. The Jetpack standard method is made to use that method.

#### Changes proposed in this Pull Request:
* The code that has been previously generating an authorization URL is now split into several chunks. The generic code that should run in any code consuming the package is moved into the Manager class.
* The code that's specific to Jetpack needs is moved to separate filters, tailoring the URL to Jetpack's specific needs.
* Unit tests are added for one method, but they were slowing me down very much so I decided to use the existing code without coverage. I'd appreciate any ideas on how to test it without taking too much time developing a solution.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is part of the Jetpack DNA project for the Connection package.

#### Testing instructions:
This PR changes the way we generate a link to authorize the user, so the site needs to be registered first. You can get to that state by connecting a site and adding a user that hasn't been connected yet.

#### Proposed changelog entry for your changes:
* N/A

2019-11-12 17:11 UTC, kbrown9 requested changes
I manually tested these changes by:
1) Cherry-picking the commit from PR #14013 to fix an authorization problem.
1) Deactivating and reactivating Jetpack.
2) Connecting the site and primary user.
3) Connecting a secondary admin user.

Everything was successful.

I also ran the package unit tests, and all of them passed.

2019-11-13 16:37 UTC, dereksmart commented on packages/connection/src/Manager.php
> +		$secrets = $this->generate_secrets( 'authorize', false, 2 * HOUR_IN_SECONDS );
#14013 has been merged, this is clear for a rebase now

2019-11-13 17:18 UTC, dereksmart commented on packages/connection/src/Manager.php
> +	public function build_connect_url( $user = null, $redirect = null ) {
Agreed! Much more clear to name it explicitly. Let's make that change

2019-11-13 19:38 UTC, kbrown9 commented on packages/connection/src/Manager.php
> +	public function build_connect_url( $user = null, $redirect = null ) {
I changed the method name in e71eca8.

2019-11-14 20:41 UTC, zinigor commented on packages/connection/src/Manager.php
> +		$secrets = $this->generate_secrets( 'authorize', false, 2 * HOUR_IN_SECONDS );
Good catch, thank you, it's now fixed in one of the commits.

2019-11-14 20:41 UTC, zinigor commented on packages/connection/src/Manager.php
> +		wp_redirect( $this->api_url( 'authenticate' ) );
Thanks for reminding me of this one, this is a not yet used method, and I forgot to modify it when I added the URL generation method.

2019-11-14 23:05 UTC, dereksmart commented on packages/connection/src/class-manager.php
> +						'redirect' => rawurlencode( $redirect ),
I suspect we're changing to rawurlencode based on phpcs and WP Coding [standards](https://github.com/WordPress/WordPress-Coding-Standards/blob/master/WordPress/Sniffs/PHP/DiscouragedPHPFunctionsSniff.php#L49)

2019-11-14 23:11 UTC, dereksmart approved these changes
Looks clean, and I love the use of filters. I cycled connections of the site, and of secondary users, with no problems.

2019-11-14 23:59 UTC, kbrown9 approved these changes

2019-11-15 00:04 UTC, merged