Instant Search: formatting improvements for mobile
Automattic/jetpack pull request #14022
Opened 2019-11-13 22:54 UTC by bluefuton

Address feedback from @joanrho on the mobile experience when using the standard 'minimal' result format.

#### Changes proposed in this Pull Request:

On the smallest breakpoint:
* Move date above search results
* Hide the comment matches

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No - it's part of the Instant Search prototype and merges into `instant-search-master`.

#### Testing instructions:

Follow the setup instructions in https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md.

Check the results at different breakpoints. Example query: `/?s=card&blog_id=84860689`

#### Proposed changelog entry for your changes:

* Not required.

2019-11-14 02:22 UTC, bluefuton commented on modules/search/instant-search/components/search-result-minimal.jsx
> +				<div className="jetpack-instant-search__search-result-minimal-header">
Just adding a wrapper element here.

2019-11-18 16:27 UTC, gibrown requested changes
I feel like we should move the date between the title and the content? It feels odd to me floating above. Or maybe it just needs to be smaller. I guess another option is we could show the url rather than the date. When the date matters, it tends to be in the URL, and there are a lot of sites where date doesn't matter.

I think this also breaks margins on some other themes. 2015: http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentyfifteen

I use this on my site to quickly test other themes:
```
function filter_theme( $theme ) {
	if ( $_GET['theme'] ) {
		$theme = sanitize_key( $_GET['theme'] );
	}
	return $theme;
}
add_filter( 'stylesheet', 'filter_theme', 1 );
add_filter( 'template', 'filter_theme', 1 );
```

cc @keoshi

2019-11-18 16:36 UTC, keoshi commented
> I feel like we should move the date between the title and the content?

I agree. Moving the date, which is accessory information, between the title and content would bring more attention to the relevant info (matched terms in title/content). To the best of my knowledge, the date is never part of a search result, correct?

Google also does an interesting thing with dates, by including them in the content's block:

![image](https://user-images.githubusercontent.com/390760/69071021-19b96380-0a21-11ea-87e0-8d7e0bf6cd42.png)

I think that's overdoing it for our context, but cool to keep the blocks tidy nonetheless.

As for the URL, I don't think it's relevant if we show the date by itself, since you're already searching in a single domain (I'm assuming?) and it would just add a lot of `https://sitename.com/blah...` creating a repetitive pattern.

2019-11-19 15:42 UTC, gibrown commented
>  To the best of my knowledge, the date is never part of a search result, correct?

Correct, it should never be a part of the matching content.

> As for the URL, I don't think it's relevant if we show the date by itself, since you're already searching in a single domain (I'm assuming?)

So currently everything is for a single domain, but cross site search does work for VIPs in the existing Jetpack Search, and would be easy for us to implement and I could see us doing it early next year. It is probably a week of work.

When a result has no content, then we do use the path as a fallback:

<img width="851" alt="Screen Shot 2019-11-19 at 8 34 34 AM" src="https://user-images.githubusercontent.com/820871/69161234-1321ff00-0aa8-11ea-9d93-409135625931.png">

The other fallback we have is tags and categories:

<img width="835" alt="Screen Shot 2019-11-19 at 8 35 38 AM" src="https://user-images.githubusercontent.com/820871/69161277-23d27500-0aa8-11ea-9840-9779e5d8a75f.png">

So I think there could be something where we always show the path in these results, and then also show the domain when there are multiple sites.

2019-11-19 15:56 UTC, keoshi commented
That's great info to know, @gibrown — thank you!

2019-11-27 03:01 UTC, bluefuton commented
Some good feedback here about date placement (or substituting it with other things). Let's continue discussing that and I'll close out this PR for now.

I've created two PRs with changes from here that are ready to go:
* comment formatting improvements https://github.com/Automattic/jetpack/pull/14132
* use `<time>` element https://github.com/Automattic/jetpack/pull/14133

2019-11-27 03:01 UTC, closed without merging