WP.com Block Editor: Enqueue missing common styles on the front-end.
Automattic/jetpack pull request #14070
Opened 2019-11-18 20:50 UTC by kwight

Up to now, both the script and styles for the `common` module have been enqueued on the `enqueue_block_editor_assets` hook; this left out necessary styles for justified text from being displayed on the front-end.

This PR splits out the styles from `enqueue_scripts`, and enqueues them for both the editor and the front-end.

_Editor_
<img width="743" alt="Screen Shot 2019-11-18 at 12 48 25 PM" src="https://user-images.githubusercontent.com/349751/69092730-e1eef380-0a01-11ea-93ff-2a91afc300fd.png">

_Front-end_
<img width="696" alt="Screen Shot 2019-11-18 at 12 48 43 PM" src="https://user-images.githubusercontent.com/349751/69092743-e74c3e00-0a01-11ea-819a-4695fba3fa2f.png">

**Testing Instructions**
- Switch to this branch.
- Create a new post, add multiple lines of content to a Paragraph block.
- Format the content as "Justify", and verify it formats the content properly in the editor.
- Publish the post, and verify the text is justified on the front-end too.

2019-11-19 11:12 UTC, jeherve requested changes
Would there be a way to not load this on each and every front-end page as soon as Jetpack is connected to WordPress.com? Ideally we'd only use it when the buttons are used in a post that's being displayed.

If that's not an option, maybe we should move those common styles to a stylesheet that's already loaded on each front-end page by Jetpack, such as the concatenated `jetpack.css`.

2019-11-19 23:01 UTC, gwwar commented
> Would there be a way to not load this on each and every front-end page

@jeherve The current size of `http://widgets.wp.com/wpcom-block-editor/common.min.css` is only 670B. Can we please follow up on this in another issue? There more to think through with either alternative approach.

2019-11-20 00:24 UTC, kwight commented
> Would there be a way to not load this on each and every front-end page as soon as Jetpack is connected to WordPress.com?

Good point! @gwwar I can add a `has_block` check to keep this more tidy.

2019-11-20 12:24 UTC, jeherve commented
I'm afraid I'm still getting fatal errors:

```
Fatal error: Uncaught Error: Call to undefined function get_current_screen() 
```

> The current size of http://widgets.wp.com/wpcom-block-editor/common.min.css is only 670B.

I'm less worried about the file size, and more about the added CSS enqueue, especially coming from a module that can't be easily disabled by most site owners and when the enqueue is not hosted on the site so can't be handled by most concatenating / caching plugins. Some folks monitor the different enqueues on their site very closely, and will not be happy to see us adding a file without an easy way to dequeue it (short of doing it via code).

Since the file includes so little, wouldn't we better served by hosting it locally in Jetpack, and adding it to this list so it gets concatenated in `jetpack.css` for everyone:  https://github.com/Automattic/jetpack/blob/ade7b28c38feb1ccfbf661f2ce4f7b747fb4f023/class.jetpack.php#L53

As a result there won't be any additional enqueue, and we won't have to worry that the file is enqueued on all pages since `jetpack.css` is already enqueued on all pages.

2019-11-21 21:52 UTC, kwight commented
@jeherve With the latest updates, it'll only be enqueued if:

- the WordPress.com user is connected, and
- the user is in the block editor, or
- the front-end is displaying blocks that use the justify setting.

This way, it's only enqueued when truly needed, and we're not adding stuff to `jetpack.css` for those that'll never need it. Would that work for you?..

2019-11-22 14:05 UTC, jeherve approved these changes
This is just what we needed, thank you. It should be good to merge!

2019-11-23 00:44 UTC, gwwar commented
❤️ Thanks @jeherve and @kwight !

2019-11-25 09:29 UTC, merged