Instant Search: Improve UX for offline network state
Automattic/jetpack pull request #14189
Opened 2019-12-05 23:23 UTC by jsnmoon

Follow-up on #14125.

#### Changes proposed in this Pull Request:

* Shows a notice when the user attempts a search while offline.
* Renders cached results for offline searches if they've performed an identical search in the last 30 minutes.
* Adds a warning notice component.
* Fixes a styling regression with search result titles and dates.

> <img width="806" alt="Screen Shot 2019-12-05 at 4 16 14 PM" src="https://user-images.githubusercontent.com/4044428/70282362-c6fade00-177a-11ea-9414-dc14b7da24b2.png">

> <img width="806" alt="Screen Shot 2019-12-05 at 4 17 26 PM" src="https://user-images.githubusercontent.com/4044428/70282369-c9f5ce80-177a-11ea-84ec-ec0cf1d92841.png">

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* It's an enhancement for the currently unreleased Jetpack Instant Search.

#### Testing instructions:

1. Setup Instant Search as per instructions in the [readme](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions).
2. Enter a query and ensure the results render as expected.
3. Use your browser's developer console to simulate an offline network state.
4. Enter the same query from step 2 and ensure the cached results render along with a warning notice.
5. Enter a new query and ensure that a warning notice renders with no cached results.

#### Proposed changelog entry for your changes:
None.

2019-12-06 12:14 UTC, keoshi approved these changes
I'm biased here, but looks good to me! :)

One thing I'll point out is that this satisfies AA level standards:
![image](https://user-images.githubusercontent.com/390760/70322029-e8aea080-1820-11ea-9abd-08ac6d4c761e.png)

If we want to go for level AAA we should use `color: $studio-yellow-80;` in `&.jetpack-instant-search__notice--warning´ instead, but what we have feels great.

2019-12-06 18:43 UTC, gibrown requested changes
It tests out pretty well. I think we should add a Retry button inside the notice and shorten the messages a bit. Right now if you have cached results there is no way to retry once the device has gone online. It looks like right now we also have a way to trigger showing the "Load More" button when there are no results:

![Screen Shot 2019-12-06 at 11 31 08 AM](https://user-images.githubusercontent.com/820871/70347193-375a3b80-181d-11ea-8710-6957d80d752d.png)

This does let the user trigger a request, but having an explicit "Retry" button feels better.

2019-12-06 18:43 UTC, gibrown commented on modules/search/instant-search/components/search-results.jsx
> +							: 'etpack-instant-search__search-results-empty'
typo

```suggestion
							: 'jetpack-instant-search__search-results-empty'
```

2019-12-06 18:43 UTC, gibrown commented on modules/search/instant-search/components/search-results.jsx
> +					<Notice type="warning">
How about we add a button to these notices that just says "Retry" and then shorten this text to just say "It looks like you are offline."

2019-12-06 18:43 UTC, gibrown commented on modules/search/instant-search/components/search-results.jsx
> +						It looks like you're offline and the results below could be out of date. Please
Wordsmithing...

```suggestion
						It looks like you're offline and these results could be out of date.
```

2019-12-06 18:43 UTC, gibrown commented on modules/search/instant-search/components/search-results.jsx
> +						reconnect for live results.
```suggestion
```

2019-12-06 21:27 UTC, joanrho commented
Agree with @gibrown that we should shorten the message but don't think a "retry" button within the notice is a good idea—won't a browser refresh suffice? As for the shortened message, what do you think about something like:

>It looks like you're offline. Please reconnect to load the latest results.

If we can detect users are offline, can we render the disabled state for the "Load More" button?

2019-12-06 22:42 UTC, jsnmoon commented
I went ahead and darkened the text color and shortened the notice copies. I also went ahead and omitted rendering the `Load More` button instead of disabling it.

I'm currently leaning toward not having a retry button within the notice but would be happy going with whatever the consensus is.

2019-12-09 15:20 UTC, gibrown approved these changes
Ya, let's leave off the retry button. Move on to other things. Nice work.

2019-12-10 21:26 UTC, bluefuton approved these changes
🚢

2019-12-10 21:39 UTC, merged