Instant Search: trigger overlay on submit
Automattic/jetpack pull request #14248
Opened 2019-12-17 02:42 UTC by bluefuton

#### Changes proposed in this Pull Request:

In the current `instant-search-master`, the search overlay is triggered on focus. This PR instead triggers the overlay on form submit.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

No - this is part of the Instant Search prototype.

#### Testing instructions:

Follow the setup instructions in https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md.

Using the smallest breakpoint, verify that the filter icon appears next to the search box and successfully toggles the visibility of the sort controls underneath.

#### Proposed changelog entry for your changes:

Not required.

2019-12-17 02:46 UTC, bluefuton commented
Todo:
- [ ] update query string search on submit

2019-12-19 05:18 UTC, bluefuton commented
@jsnmoon any suggestions for switching focus to the overlay input when opening search results? The standard way (`.focus()` in `getResults()`) doesn't seem to do the trick. `document.activeElement` is correct but the input doesn't get the caret... 🥕

2019-12-20 00:43 UTC, jsnmoon commented
> @jsnmoon any suggestions for switching focus to the overlay input when opening search results? The standard way (`.focus()` in `getResults()`) doesn't seem to do the trick. `document.activeElement` is correct but the input doesn't get the caret... 🥕

Probably okay to punt for this PR, as discussed on Slack. Not sure why invoking `focus()` isn't doing the trick.

2019-12-27 00:34 UTC, jsnmoon requested changes
It'd be nice to keep using Hooks for the Overlay component. Otherwise, everything works as expected.

2020-01-06 00:49 UTC, bluefuton commented on modules/search/instant-search/components/overlay.jsx
> +class Overlay extends Component {
Good shout 👍

2020-01-07 00:03 UTC, jsnmoon approved these changes
Works as intended, LGTM with one change mentioned below.

2020-01-07 02:47 UTC, bluefuton commented on modules/search/instant-search/components/overlay.jsx
> +	const closeOnEscapeKey = event => {
Ideally yes, but it uses `toggleOverlay()` which is one of the props provided to the functional component. Is there a nice way around that?

2020-01-07 21:22 UTC, jsnmoon commented on modules/search/instant-search/components/overlay.jsx
> +	const closeOnEscapeKey = event => {
Good point, I forgot to consider that. In that case, it's probably fine to leave this as-is.

If we really wanted to drag this function out of `render`, I'd probably wrap the function:
```javascript
const closeOnEscapeKey = callback => event => { event.key === 'Escape' && callback() }
```

And invoke it like so:
```javascript
window.addEventListener( 'keydown', closeOnEscapeKey( toggleOverlay ) );
```

2020-01-07 21:36 UTC, bluefuton commented on modules/search/instant-search/components/overlay.jsx
> +	const closeOnEscapeKey = event => {
Ooh. I like that! Changed it 🙂

2020-01-07 21:46 UTC, jsnmoon approved these changes
Works as expected.

One strange thing I discovered that we should fix in a future PR:
1) Open your WordPress site at `/`.
2) Enter a query into the search input. Notice that the URL has been set to `/?s=hello`
3) Press Enter to spawn the overlay. 
4) Close the overlay by pressing Escape.
5) Notice that the URL has been reset to `/`.
6) Repeat steps 1-3. Close the overlay by pressing the Close button on the top right.
7) Notice that the URL has been preserved (`/?s=hello`).

2020-01-07 21:49 UTC, bluefuton commented
Thanks @jsnmoon! I'll make an issue for that so we don't forget.

2020-01-07 21:58 UTC, merged