Instant Search: Add search filtering inside overlay
Automattic/jetpack pull request #14319
Opened 2020-01-10 00:44 UTC by jsnmoon

<img width="1036" alt="Screen Shot 2020-01-09 at 5 13 05 PM" src="https://user-images.githubusercontent.com/4044428/72115158-560f8e80-3303-11ea-88a6-88430cc7aaec.png">

#### Changes proposed in this Pull Request:
* Adds search filtering inside the overlay. 
* Uses filter configuration from pre-existing Jetpack Search widget(s) active on the site.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No, this is technically restoring a feature we've previously had before we switched to the overlay approach. 

#### Testing instructions:
1. If you haven't already, set up Instant Search following the instructions in the [readme](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions).
2. Navigate to your WordPress site and enter a search query. 
3. TBD.

#### Proposed changelog entry for your changes:
* None.

2020-01-13 01:34 UTC, bluefuton commented
Great stuff. Works really well for filtering on my test site 👍 

When testing with a site with more posts (`blog_id=20115252`), I noticed a couple of things:

1. When selecting a post type, all of the others disappear (so I can't filter by multiple post types):

![2020-01-13 14-30-29 2020-01-13 14_31_04](https://user-images.githubusercontent.com/17325/72229207-b8bd9e80-3611-11ea-8d24-fd977df6a9b9.gif)

2. Only '2020' appears in the year filters for the query "post", but the posts shown in the unfiltered results are from multiple different years (2013, 2014, 2016):

<img width="1062" alt="Screen Shot 2020-01-13 at 14 33 34" src="https://user-images.githubusercontent.com/17325/72229220-cf63f580-3611-11ea-8eb0-37d3266e6e40.png">

2020-01-13 18:58 UTC, jsnmoon commented
> When selecting a post type, all of the others disappear (so I can't filter by multiple post types)

> Only '2020' appears in the year filters for the query "post", but the posts shown in the unfiltered results are from multiple different years (2013, 2014, 2016):

One important thing is that the API has complete control over which filters to show given a query; the interface merely passes through the API results. In other words, these defects existed prior to this PR.

The first defect is due to how our API design only accommodates conjunctive (`AND`) filters.

The second defect seems like a bug; it should definitely be showing the other years.

I'll spin up issues for the abovementioned bugs so we can push this PR forward.

2020-01-13 19:41 UTC, gibrown requested changes
It looks like this is adding the filters at the top of the whole sidebar rather than adding them to the widget in the sidebar.

<img width="1217" alt="Screen Shot 2020-01-13 at 12 03 01 PM" src="https://user-images.githubusercontent.com/820871/72286106-b0f5fe00-3601-11ea-9354-8fb9e8a9f874.png">

When the user configures their sidebar in the overlay we should be replacing the filter widget that is in that sidebar in place. Basically the same thing we were doing on the front end sidebar before we should be doing in the overlay so that the end user still has control over what is in their sidebar.

<img width="290" alt="Screen Shot 2020-01-13 at 12 42 15 PM" src="https://user-images.githubusercontent.com/820871/72286345-32e62700-3602-11ea-92c5-c97ab35a1a91.png">

Note that the hello widget should be above the other widget results and we should only be using the filters that are configured for that widget. Potentially there could be multiple widgets in the overlay sidebar

2020-01-14 01:12 UTC, jsnmoon commented
> It looks like this is adding the filters at the top of the whole sidebar rather than adding them to the widget in the sidebar. (@gibrown)

This is correct. I decided to implement this version first because it requires very little new code (net ~50 LOC added) and enables us to start polishing the filtering experience.

> When the user configures their sidebar in the overlay we should be replacing the filter widget that is in that sidebar in place. Basically the same thing we were doing on the front end sidebar before we should be doing in the overlay so that the end user still has control over what is in their sidebar.

> Note that the hello widget should be above the other widget results and we should only be using the filters that are configured for that widget. Potentially there could be multiple widgets in the overlay sidebar (@gibrown) 

While I understand the rationale for this approach, it introduces nontrivial challenges:

- (Tech) It will require us to portal into a DOM node mounted onto an existing Preact element tree. I've not seen this done before elsewhere in the React/Preact community; this is likely going against best practices. 

- (UX) The user will need to configure Jetpack Search widgets in at least two places for most sites: somewhere on the site and one within the overlay. To make things worse, there's no way to guarantee that the filters being shown on the site will match up with the filters being shown in the overlay. In other words, the following can occur:
    a. A user selects `2017` from a date filter attached to a widget rendered on the site.
    b. According to our current direction, this will spawn an overlay (see #14320).
    c. There's no indication that the search results inside the overlay are being filtered by `2017`. To make matters worse, the user can select another filter inside the overlay (e.g. `Page` post type), widening the discrepancy between the filter controls inside the overlay and filter controls on the site. 

@keoshi, your thoughts on this would be greatly appreciated. I don't feel comfortable continuing with implementation without some design consideration to the UX issue above.

2020-01-14 13:03 UTC, keoshi commented
> Only '2020' appears in the year filters for the query "post", but the posts shown in the unfiltered results are from multiple different years (2013, 2014, 2016):

@bluefuton Same thing happened to me initially but only because I'd set a maximum of 1 filter for the date. Setting a larger value here displays the entire range of years:

![image](https://user-images.githubusercontent.com/390760/72346575-30510380-36ce-11ea-8596-79b787aa139d.png)

![image](https://user-images.githubusercontent.com/390760/72346592-39da6b80-36ce-11ea-9607-7cc307ff6ea6.png)

2020-01-14 13:07 UTC, keoshi commented
> When the user configures their sidebar in the overlay we should be replacing the filter widget that is in that sidebar in place. Basically the same thing we were doing on the front end sidebar before we should be doing in the overlay so that the end user still has control over what is in their sidebar.

Agreed, @gibrown !

2020-01-14 13:21 UTC, keoshi commented
> (UX) The user will need to configure Jetpack Search widgets in at least two places for most sites: somewhere on the site and one within the overlay. To make things worse, there's no way to guarantee that the filters being shown on the site will match up with the filters being shown in the overlay.

Very good point, @jsnmoon!

Does the following scenario have any validity?

- Customers wants to expose some but not all filters in their site. They add a date filter (year) with a maximum of 2 values: `2020` and `2019`.
- Customer then uses the overlay to expose all filters, including 10 years, all post types, and all categories.

Still, I'd be tempted to offer faceting only in the overlay for a few reasons:

- It simplifies the process of adding JPS.
- It prevents the possibility of creating two different (and possibly incompatible) faceting sets of options.
- It hides all filtering complexity to a view dedicated to just that (overlay).

In sum, if we could configure JPS and all faceting options with just one widget inside the overlay and then replicate it automatically on the site sidebar (if they have one) that would be ideal. If not, I'd use the widget area in the overlay to expose those.

2020-01-14 22:15 UTC, jsnmoon commented
Barring any technical defects, I'd like to ship this PR out so we can iterate on trying the server-rendered overlay approach. cc @bluefuton

2020-01-14 22:16 UTC, bluefuton approved these changes
🚢 Ship it!

2020-01-14 22:19 UTC, merged