Calendly: Add CSS to adjust the Calendly block to the masterbar
Automattic/jetpack pull request #14381
Opened 2020-01-17 11:31 UTC by scruffian

Fixes #14365

#### Changes proposed in this Pull Request:

* This adds CSS to the frontend of the site to adjust the close button in the Calendly widget to the height of the master bar

#### Testing instructions:
* Add a Calendly block to a post and set the style to "link"
* Open the post in the front end
* Click on the button to open the widget
* Check you can see the close button:
<img width="1440" alt="Screenshot 2020-01-17 at 11 30 44" src="https://user-images.githubusercontent.com/275961/72609448-d5611b80-391c-11ea-9b58-83c185b287c6.png">

#### Proposed changelog entry for your changes:

* no changelog entry needed

2020-01-17 17:31 UTC, jeherve requested changes
What do you think about doing something like this instead?

```diff
diff --git a/extensions/blocks/calendly/style.scss b/extensions/blocks/calendly/style.scss
new file mode 100644
index 000000000..59e59483f
--- /dev/null
+++ b/extensions/blocks/calendly/style.scss
@@ -0,0 +1,3 @@
+.admin-bar .calendly-popup-close {
+	top: 47px;
+}
diff --git a/extensions/blocks/calendly/view.js b/extensions/blocks/calendly/view.js
new file mode 100644
index 000000000..fd92905ca
--- /dev/null
+++ b/extensions/blocks/calendly/view.js
@@ -0,0 +1,5 @@
+/**
+ * Internal dependencies
+ */
+
+import './style.scss';
```

It would allow us to use scss, while remaining consistent with the way the other blocks work.

2020-01-20 12:11 UTC, scruffian commented
Oh yeah that's a much better idea, thanks :)

2020-01-20 13:04 UTC, jeherve requested changes

2020-01-20 13:04 UTC, jeherve commented on extensions/blocks/calendly/calendly.css
> +.admin-bar .calendly-popup-close {
We can remove this now.

2020-01-20 13:04 UTC, jeherve commented on extensions/blocks/calendly/calendly.php
> +		wp_enqueue_style( 'jetpack-calendly-internal-css', plugins_url( 'calendly.css', __FILE__ ), null, JETPACK__VERSION );
This isn't necessary anymore.

2020-01-20 13:04 UTC, jeherve commented on extensions/blocks/calendly/view.scss
> +    top: 47px;
```suggestion
	top: 47px;
```

2020-01-20 16:03 UTC, scruffian commented
Sorry, I really messed that one up!

2020-01-21 09:54 UTC, jeherve requested changes
It seems we'll need to be more specific with the CSS for this to work:
![image](https://user-images.githubusercontent.com/426388/72794365-300bb780-3c3c-11ea-8480-2a9dc184c5b8.png)

2020-01-21 17:31 UTC, jeherve approved these changes
It seems to work well for me now 👍

2020-01-21 20:41 UTC, merged

2020-01-22 08:28 UTC, jeherve commented
r201920-wpcom