Calendly: Add a notice to explain how to use colors
Automattic/jetpack pull request #14434
Opened 2020-01-22 15:33 UTC by scruffian

#### Changes proposed in this Pull Request:

* Add a notice to the sidebar to explain how to use the Calendly color settings.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* p58i-8tn#comment-44505-p2

#### Testing instructions:
* Add a Calendly block to a post
* Confirm you see this notice in the sidebar:
<img width="297" alt="Screenshot 2020-01-22 at 15 31 44" src="https://user-images.githubusercontent.com/275961/72907732-51e46780-3d2c-11ea-872c-a53d98e58b23.png">

#### Proposed changelog entry for your changes:

* no changelog

This was suggested by @davipontesblog.
cc @lessbloat

2020-01-22 16:26 UTC, jeherve requested changes
Maybe we should only show the notice once we have a `url` set? I don't know if it's super useful to show it before the block actually displays anything.

![image](https://user-images.githubusercontent.com/426388/72912702-5153cd00-3d3c-11ea-86b8-07c0c2a3d0ac.png)

What do you think?

2020-01-22 17:18 UTC, scruffian commented
Good call, updated 👍

2020-01-22 19:14 UTC, jeherve approved these changes

2020-01-23 09:08 UTC, merged

2020-01-23 10:14 UTC, scruffian commented
r202020-wpcom