Gutenberg 7.2.0: replace legacy editor- classes with block-editor-
Automattic/jetpack pull request #14446
Opened 2020-01-23 18:07 UTC by chriskmnds

Gutenberg 7.2.0 & 7.3.0 removed legacy `editor-` classes in WordPress/gutenberg#19050 and WordPress/gutenberg#19489. This PR updates references to legacy classes found in these PRs and the Gutenberg repo.

These were refactored in the aforementioned PRs:

```
editor-warning
editor-warning__message
editor-media-placeholder
editor-block-list__block
editor-plain-text
```

These were found in Gutenberg with the newer format (possibly updated in other revisions - need to check):

```
editor-block-preview__content
```

#### Testing instructions:

No testing done yet.

#### Proposed changelog entry for your changes:

Not sure.

2020-01-23 20:11 UTC, kraftbj commented
Are these changes fine with the editor as it shipped in WP 5.2? Based on https://make.wordpress.org/core/2019/04/16/wordpress-5-2-field-guide/, it looks like G 5.4 shipped with WP 5.2 and the `block-editor` namespacing was added in G 5.3, so I think this is fine, right?

2020-01-24 08:04 UTC, chriskmnds commented
> Are these changes fine with the editor as it shipped in WP 5.2? Based on https://make.wordpress.org/core/2019/04/16/wordpress-5-2-field-guide/, it looks like G 5.4 shipped with WP 5.2 and the block-editor namespacing was added in G 5.3, so I think this is fine, right?

I believe so. This is the relevant PR that shipped with 5.3.0: https://github.com/WordPress/gutenberg/pull/14420

2020-01-29 15:16 UTC, chriskmnds commented
Updated the description with a few visible regressions that I was able to spot. cc @jeherve

2020-02-19 10:58 UTC, jeherve commented
@chriskmnds Do you think this would be ready for a review?

2020-02-19 11:12 UTC, simison commented
I believe this is good for testing and merging.

2020-02-20 17:33 UTC, jeherve requested changes
This seems to test well in WordPress 5.2 and 5.3, but I see this when using the Gutenberg plugin:
![image](https://user-images.githubusercontent.com/426388/74962044-6b51ff80-540f-11ea-80bd-ae951e402ec7.png)

2020-03-19 19:20 UTC, simison commented
@jeherve since this already fixed lots of things, let's merge and leave markdown fixea for a separate PR?

2020-03-20 10:59 UTC, jeherve approved these changes
Let's merge this as is for now!

2020-03-20 10:59 UTC, merged

2020-03-20 12:01 UTC, jeherve commented
r204563-wpcom