Blocks: Add support for Collections
Automattic/jetpack pull request #14454
Opened 2020-01-24 03:19 UTC by kraftbj

In Gutenberg 7.3, the block editor now supports "Collections". In the block picker, a Collection looks like a category, except blocks can also have a category.

The use case here is when do people think "I need a business hours block. I bet that's in the Jetpack category!"... probably not. They probably think of the function -- an embed, a widget, etc.

The problem is a block can only be in one category so devs have generally grouped them by the block provider.

Collections allow the block provider (Jetpack in our case) present all of our blocks together—like we have done with a custom category—while also listing it in a context-appropriate category.

** THIS PR IS INCOMPLETE. ** We'd need to adjust all of our blocks to conditionally pick a category for G 7.3+. I've already done the Business Hours block for the sake of an example.

For those running Gutenberg 7.3:
![2020-01-23 at 9 14 PM](https://user-images.githubusercontent.com/88897/73042071-6d7f6900-3e25-11ea-89b6-7c24ba947a79.png)

For those not running Gutenberg 7.3, it retains the original behavior:
![2020-01-23 at 9 15 PM](https://user-images.githubusercontent.com/88897/73042109-8daf2800-3e25-11ea-8ef5-f83145b92aad.png)

#### Changes proposed in this Pull Request:
* Adds a 'Jetpack' block collection.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* On a connected Jetpack site WITHOUT Gutenberg, add a new post. Verify all the blocks are in a Jetpack category when viewing the block inserter.
* On a connected Jetpack site WITH Gutenberg, add a new post. With this patch, the Business Hours block will be in a Jetpack collection (looks just like a category) AND the widgets category.

AS OF NOW, when running G 7.3, the rest of Jetpack's blocks will fail since we're not adding them to a `Jetpack` category. We'll need to update the other blocks before landing it, but opening the PR now to get opinions on the implementation.

I opted to need to update blocks since if we allow those blocks with other categories to be added to a collection and those with the 'legacy' Jetpack category, the inserter will have two "Jetpack" entries -- the category and the collection -- so that's not really an option. 

#### Proposed changelog entry for your changes:
* Block Editor: Blocks are now listed both as part of a Jetpack Collection and in their proper category. (Requires Gutenberg 7.3)

2020-01-24 09:25 UTC, scruffian commented
This might make sense to be done in tandem with this PR: https://github.com/WordPress/gutenberg/pull/19279

Since the categories are all set to change

2020-02-25 06:56 UTC, simison commented
When merged, we should confirm that re-organizing categories on wpcom is still functional: https://github.com/Automattic/wp-calypso/pull/37057

2020-02-25 06:58 UTC, simison commented on extensions/blocks/business-hours/index.js
> +	category: typeof registerBlockCollection === 'function' ? 'widgets' : 'jetpack',
I would centralize `@wordpress/blocks` import and typeof check into a helper function at `extensions/shared/block-category.js` and do `supportsCollections()` or similar.

2020-03-28 06:08 UTC, simison commented
Would be nice to get this in before code freeze on Monday evening in time for WP 5.4 release which supports thi feature. @lessbloat

2020-03-28 11:32 UTC, mtias commented
Perhaps:

- Calendly → Widgets
- Contact Info → Formatting
- Eventbrite Checkout → Widgets
- Form → Widgets
- GIF → Formatting
- Google Calendar → Embeds
- Map → Common
- Markdown → Formatting
- Open Table → Widgets
- Pinterest → Embeds
- Repeat Visitor → Widget
- Revue → Widget
- Slideshow → Common
- Star Rating → Formatting
- Tiled Gallery → Common

Register new category: _Earn_ or _Premium_.

- Ads
- Simple Payments
- Recurring Payments

2020-03-30 22:17 UTC, kraftbj commented
Rebased and not finished yet, but need to log off.

What categories for these blocks:
- Amazon
- Business Hours (Widgets in this PR right now)
- Instagram
- Mailchimp
- Podcast Player
- Related Posts
- Subscriptions

Still need to add the new category for Ads, Simple, Recurring Payments.

2020-04-02 20:02 UTC, apeatling commented
@kraftbj Let me know if you need any help getting this one finished off.

2020-04-02 20:42 UTC, obenland commented
#14598 has [a spreadsheet with suggested categories](https://docs.google.com/spreadsheets/d/1Oua0oDUhGJJtabatoBS3XBzZ6K3oUiB5-kSdWl00M-I/edit#gid=0) based on the discussion in p58i-8yl-p2. #14721 is the corresponding PR. It does away with the `'jetpack'` category regardless of whether collections are available or not, as suggested in that post. Should we do the same here?

2020-04-03 14:37 UTC, kraftbj commented
>  It does away with the 'jetpack' category regardless of whether collections are available or not, as suggested in that post. Should we do the same here?

I'm hesitant to do that since documentation notes you can find the JP blocks under "Jetpack" and existing users who aren't updated Core would lose that flow. When 5.4 is Jetpack's minimum, we can remove the fallback.

Thanks for the link to the spreadsheet.

2020-04-03 15:32 UTC, kraftbj commented
Updated the PR with the two new categories and updating all blocks with the spreadsheet.

OpenTable struck me as odd being "Earn" instead of "Marketing" or "Embed, but included it as is.

Pinterest also was the only "social" one and there isn't that category yet. I made it "embed" instead for now.

Podcast Player wasn't in the spreadsheet. Marked it as an embed.

Rating Star wasn't in the spreadsheet. Deferred to the suggestion in the comment above.

Related Posts is listed as the only one in a non-existent "blog" category. Marked it as Embed.

2020-04-03 15:44 UTC, kraftbj commented
Noting that the wp.com patch needs a little massaging for the maps block. Nothing major, but I'll wait until this has landed to work on it so it isn't overridden with future work in this PR.

2020-04-03 15:54 UTC, obenland commented
Pinging @davemart-in for review as this fixes 80% of #14598 for Ajax.

2020-04-03 16:24 UTC, jeherve requested changes
This looks good. However, in WP 5.4, clicking on the Jetpack category while another Jetpack collection is open triggers a JavaScript error and breaks the editor, maybe because we're trying the same block multiple times.

```
Uncaught TypeError: Cannot read property 'attributes' of undefined
    at createBlock (blocks.js?ver=423068d7079f57cf9f02458ccb4a6131:7448)
    at getBlockFromExample (blocks.js?ver=423068d7079f57cf9f02458ccb4a6131:7874)
    at blocks.js?ver=423068d7079f57cf9f02458ccb4a6131:7875
    at arrayMap (lodash.js?ver=4.17.15:639)
    at map (lodash.js?ver=4.17.15:9554)
    at getBlockFromExample (blocks.js?ver=423068d7079f57cf9f02458ccb4a6131:7874)
    at InserterMenu.render (dmp.js:19)
    at finishClassComponent (react-dom.js?ver=16.9.0:17177)
    at updateClassComponent (react-dom.js?ver=16.9.0:17132)
    at beginWork$1 (react-dom.js?ver=16.9.0:18643)
```

2020-04-03 16:36 UTC, kraftbj commented on extensions/shared/block-category.js
> +		title: 'Earn',
Good call. 79f97f037

2020-04-03 16:51 UTC, simison commented
>It does away with the 'jetpack' category regardless of whether collections are available or not, as suggested in that post. Should we do the same here?

In the plugin, the Jetpack category is also a great way to communicate value Jetpack is giving without hiding the blocks only into different categories.

On .com however that's not so important and the Jetpack category can be confusing. It could make sense to hide Jetpack for .com but leave it for Jetpack the plugin.

[There are helpers](https://github.com/Automattic/jetpack/blob/fa68e186d52784d3a83b6e27c1e06a73b295654d/extensions/shared/site-type-utils.js) for that in case you need.

2020-04-03 17:05 UTC, davemart-in commented
I'm seeing a fatal error when just clicking around. See: https://a.cl.ly/bLumEllP This is using a Jurassic Ninja instance.

2020-04-03 17:06 UTC, kraftbj commented
I haven't been able to duplicate that error yet, but I've been using the inline inserter. Still looking.

> On .com however that's not so important and the Jetpack collection in block picker can be confusing. It could make sense to hide Jetpack collection in .com, but leave it for the plugin.

We can do that in a follow-up PR IMO.

2020-04-03 17:23 UTC, simison commented
>We can do that in a follow-up PR IMO.

Absolutely 👍 Wasn't implying it should be done here. :-)

2020-04-03 17:28 UTC, kraftbj commented
@davemart-in Can you check it out again?

The contact form's child blocks weren't assigned to a new category yet (and Jetpack wasn't being registered anymore). The inline picker didn't have a problem, but the top inserter was trying to load a dynamic preview using blocks that didn't exist -- thus fataling. Fixed in 74f11dd.

2020-04-03 17:54 UTC, davemart-in commented
@kraftbj I'm still seeing the error unfortunately. I'm seeing [this under the JP beta section](https://a.cl.ly/JruW25qq). I assume that is the latest.

One other oddity: I'm not seeing simple payments in the earn collection or the Jetpack collection: https://a.cl.ly/mXuqezq7

2020-04-03 18:09 UTC, kraftbj commented
Click Update on the top. The branch has updated but your site isn't running it. 

I'll check out Simple Payments.

2020-04-03 18:09 UTC, jeherve commented
> I'm seeing this under the JP beta section. I assume that is the latest.

You'd have to click on Update at the top of the page to get the latest version.

> I'm not seeing simple payments in the earn collection or the Jetpack collection

That's to be expected as the block is only available to folks with a plan. You would have to purchase a plan, or enable block nudges like so:
`add_filter( 'jetpack_block_editor_enable_upgrade_nudge', '__return_true' );`

2020-04-03 18:11 UTC, jeherve submitted a review, later dismissed
I am not seeing the error anymore. It seems to work well!

I wonder if we should really be inserting our blocks before core blocks in core categories like Embeds?

![image](https://user-images.githubusercontent.com/426388/78391335-75f2dd80-75e6-11ea-830f-97ae45a35a04.png)

2020-04-03 18:13 UTC, davemart-in commented
Confirmed. That bug is fixed now @kraftbj. 👍 Thanks!

2020-04-03 19:00 UTC, simison commented
@jeherve there is separate script on wpcom that reorganises categories in case we want to do that only there: https://github.com/Automattic/wp-calypso/blob/master/apps/wpcom-block-editor/src/wpcom/features/reorder-block-categories.js

2020-04-06 07:31 UTC, jeherve requested changes
Let's add the textdomains here.

2020-04-06 07:31 UTC, jeherve commented on extensions/shared/block-category.js
> +		title: __( 'Earn' ),
```suggestion
		title: __( 'Earn', 'jetpack' ),
```

2020-04-06 07:31 UTC, jeherve commented on extensions/shared/block-category.js
> +		title: __( 'Grow' ),
```suggestion
		title: __( 'Grow', 'jetpack' ),
```

2020-04-06 12:07 UTC, jeherve approved these changes
This looks good to me now. I'd suggest merging this as is for the 8.4 release, and work on improving these collections in a future PR:
- Handle wpcom differently
- Have Jetpack blocks come after core blocks in core categories.

2020-04-06 13:54 UTC, jeherve commented
> Handle wpcom differently

To close the loop on this: #15310 

> Have Jetpack blocks come after core blocks in core categories.

I have been thinking about this some more, and I'm honestly not quite sure what we should aim for. Should Jetpack blocks be available before Core blocks in categories like Embeds?

![image](https://user-images.githubusercontent.com/426388/78564768-39f58d80-781d-11ea-9da2-021ca56f7c2e.png)

My first instinct was to say no, our blocks should come after Core's. Core's blocks would most likely be used more often; they were added to Core more often. On the other hand I can see why having our own blocks first should give us some extra visibility.

Furthermore, Core currently adds custom blocks before core blocks in core categories, which seems to indicate that they're okay wit this?

2020-04-06 14:16 UTC, davemart-in commented
> My first instinct was to say no, our blocks should come after Core's. Core's blocks would most likely be used more often; they were added to Core more often. On the other hand I can see why having our own blocks first should give us some extra visibility.

Could they just be listed alphabetically?

2020-04-06 14:34 UTC, jeherve commented
> Could they just be listed alphabetically?

I suppose it could be another option. Would we then change all block ordering to alphabetical as soon as Jetpack is active, or only in categories that include Jetpack blocks?

2020-04-06 14:42 UTC, merged

2020-04-06 14:48 UTC, kraftbj commented
Cherry-picked to `branch-8.4` via 9c91c106a .

2020-04-06 16:09 UTC, kraftbj commented
r205423-wpcom