OpenTable: Separate block registration from setting the availability
Automattic/jetpack pull request #14464
Opened 2020-01-24 15:30 UTC by pablinos

As with other blocks that rely on server-side rendering, we need to make
sure that the block is registered so that it is rendered in the frontend
of the site.

#### Changes proposed in this Pull Request:

This change registers the block during the `init` hook, but keeps the
setting of the block availability to the
`jetpack_register_gutenberg_extensions` hook.

This is a stop-gap solution until a more generalised change to block registration is completed, like we're working on in #14426

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is a fix to the new OpenTable block

#### Testing instructions:
* Enable beta blocks on your Jetpack site
* Check that you can still insert an OpenTable block
* Check that the block is rendered on the frontend when the post is published.

#### Proposed changelog entry for your changes:

No changelog entry is required.

2020-01-24 16:19 UTC, jeherve requested changes
I think you'll need to update the function name here:
https://github.com/Automattic/jetpack/blob/fix/opentable-block-registration/extensions/blocks/opentable/opentable.php#L71

2020-01-24 16:26 UTC, pablinos commented
Eurrgh! That was a Friday afternoon git fail.

2020-01-24 17:26 UTC, jeherve approved these changes
Should be good to go now! I'll let you handle D37730-code manually!

2020-01-24 20:03 UTC, merged

2020-01-27 08:10 UTC, jeherve commented
r202118-wpcom