Update/instant search input box styles
Automattic/jetpack pull request #14664
Opened 2020-02-13 13:26 UTC by keoshi

Related to issues reported in https://github.com/Automattic/jetpack/issues/14608; complementary PR to https://github.com/Automattic/jetpack/pull/14661

#### Changes proposed in this Pull Request:
* Update styling of main search box.
  * Better inheritance of `:hover` and `:focus` styles for accessibility.
  * Using `px` units instead of `rem` to better control the output.
  * Clearer separation of input and icon.
* Revert search icon back to 24px.
* Fix bug with Gridicon's viewBox values reported in https://github.com/Automattic/jetpack/pull/14629#issuecomment-585474931.

![jps-input-box](https://user-images.githubusercontent.com/390760/74439490-3d474b00-4e64-11ea-82cd-bed6a13327d5.gif)

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
1. Follow [these setup instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) to set up Jetpack Instant Search on your site.
2. Search your site to trigger the Jetpack Search overlay.
3. Ensure that the Jetpack Search input field shows the icon and that both work correctly on all devices.

#### Proposed changelog entry for your changes:
* None.

2020-02-13 20:38 UTC, gibrown approved these changes
This looks so good.

2020-02-14 00:57 UTC, jsnmoon reviewed
I don't see any `:focus` or `:hover` styling implied by the original PR description. Is this intentional?

2020-02-14 00:57 UTC, jsnmoon commented on modules/search/instant-search/components/search-box.scss
>  	background: #fff;
We might want to consider adding something to override this styling set by the 2020 theme:

```css
input[type="search"]:focus {
    outline: thin dotted;
    outline-offset: -4px;
}
```

`outline: none` applied to `input[type="search"].jetpack-instant-search__box-input` is a viable solution for this.

2020-02-14 11:15 UTC, keoshi commented
@jsnmoon The intention was not to override but to be in a better place to inherit whatever `:focus` and `:hover` styles might be set on the theme. We can add our own styles though, which would not be a bad idea at all. I'd rather tackle that once this PR has landed though, if that's ok — seems it would be easier that way.

2020-02-14 14:40 UTC, jeffgolenski requested changes
@keoshi I'm not sure if this is supposed to be handled in this PR, but the icon appears to be vertically off-center. The focus on the box looks good though.

2020-02-14 22:57 UTC, jsnmoon commented on modules/search/instant-search/components/search-box.scss
>  	background: #fff;
It's probably more appropriate to tackle this in a future PR referenced here: https://github.com/Automattic/jetpack/pull/14664#issuecomment-586216217.

2020-02-14 23:01 UTC, jsnmoon requested changes
It looks like the background for the icon doesn't quite cover the input when zoomed at 110%:
<img width="854" alt="Screen Shot 2020-02-14 at 3 59 22 PM" src="https://user-images.githubusercontent.com/4044428/74575110-04ca6e80-4f43-11ea-8615-59986bb4bf51.png">

Same happens when zoomed at 125%:
<img width="754" alt="Screen Shot 2020-02-14 at 3 59 12 PM" src="https://user-images.githubusercontent.com/4044428/74575114-05630500-4f43-11ea-8045-c192aa532a6f.png">

2020-02-17 14:09 UTC, keoshi commented
This has been reworked and could use another round of reviews! Updated the description above to reflect the latest changes.

2020-02-18 16:37 UTC, gibrown approved these changes
Looks good. I am seeing a narrower width for the search box now, but that may get fixed in #14661 so I think we should merge this.

2020-02-18 16:41 UTC, folletto commented
Design wise, solid improvement 👍

2020-02-18 18:11 UTC, jeffgolenski commented
@keoshi I did a quick screen recording. Everything looks and feels super smooth. My only ??? is the search button that appears in the input when I use keyboard navigation. When I hit `tab` it displays for a milisecond then disappears. I'm not sure it's needed for the functionality of instance search, but the disappearing act is probably something we want to address for a11y.

https://cloudup.com/cWiBND5DiUb

2020-02-18 23:26 UTC, jsnmoon approved these changes
Looks good! 

I pushed up a commit that fixes a transition focus bug causing this issue: https://github.com/Automattic/jetpack/pull/14664#issuecomment-587598863.

2020-02-19 14:41 UTC, keoshi commented
@jsnmoon Thanks so much for fixing that!! I ran into that issue a bunch of times but failed to report it — thanks for doing so @jeffgolenski. Team work! 🙌

2020-02-19 14:42 UTC, merged