Eventbrite: implement getValidatedAttributes
Automattic/jetpack pull request #14679
Opened 2020-02-14 14:25 UTC by scruffian

This implements getValidatedAttributes in the Eventbrite block, so it matches OpenTable and Calendly.

#### Changes proposed in this Pull Request:
* Validate the block attributes using getValidatedAttributes.
* There should be no functional changes, but this brings the blocks more into line with each other which should make it easier to share code between all blocks in the future.
* We'll also be able to validate style values once this PR merges: https://github.com/Automattic/jetpack/pull/14528

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:
* Add a new Eventbrite block
* Check that things continue to work as before.

#### Proposed changelog entry for your changes:

* no changelog

2020-02-14 15:10 UTC, Copons requested changes
I think you forgot to commit the `attributes.js` file 😅

2020-02-14 15:16 UTC, scruffian commented
Oops, you're right. It's there now 😬

2020-02-14 15:57 UTC, Copons approved these changes
LGTM, thanks!

2020-02-17 17:35 UTC, jeherve approved these changes
This tests well for me. 👍

2020-02-18 12:21 UTC, merged

2020-02-18 12:29 UTC, scruffian commented
r203002-wpcom