Instant Search: Properly handle numerical searches
Automattic/jetpack pull request #14692
Opened 2020-02-15 00:43 UTC by jsnmoon

Fixes #14671.

#### Changes proposed in this Pull Request:
* Fixes a bug that prevents purely numerical search queries in Jetpack Instant Search.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No, this is a bugfix.

#### Testing instructions:
1. Follow [these setup instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) to set up Jetpack Instant Search on your site. Please note that the Jetpack Search widget will need to be added to twice: once to your site sidebar/footer and once to the Jetpack Search Sidebar within the search overlay.

2. Search your site using only numbers, such as `123`.

#### Proposed changelog entry for your changes:
* No changelog necessary.

2020-02-15 00:46 UTC, jsnmoon commented
Just a heads up @gibrown: This PR merges to `master` and will need to be synced to WPCOM. I'd be happy to perform this sync via D38946-code; could you let me know when #14550 has been successfully synced?

2020-02-17 11:48 UTC, keoshi reviewed
I don't know if it's related to this PR in particular, but I can't seem to add spaces after numbers.

Typed: `2019 + space + roadmap`
Expected: `2019 roadmap`
Got: `2019roadmap`

Other than that this works great in my testing.

2020-02-18 16:17 UTC, gibrown approved these changes
WFM

2020-02-18 16:19 UTC, gibrown requested changes
Ya the spaces between numbers seems to be a problem.

2020-02-18 16:20 UTC, gibrown commented
I think we could merge this into the feature branch and then merge everything we have into master. For the merge to wp.com I'd like to get all of the UX refinements

2020-02-18 21:55 UTC, jsnmoon commented
> I don't know if it's related to this PR in particular, but I can't seem to add spaces after numbers. @keoshi 

> the spaces between numbers seems to be a problem @gibrown 

This seems to be happening because of [qss](https://github.com/lukeed/qss), our query string parser. Specifically, it's typecasting `"1 "` as `1` here: https://github.com/lukeed/qss/blob/master/src/index.js#L26. If this is a blocking issue, I'll look into spinning up a PR for that library.

2020-02-18 23:20 UTC, gibrown approved these changes
Let's merge this as is and open up a separate PR for the lib so we can fix the new issue. This is clearly already an improvement.

2020-02-19 22:26 UTC, merged

2020-02-20 22:17 UTC, jsnmoon commented
I opened a PR for the typecasting issue here: lukeed/qss/pull/8.