Change the selector to target blocks that have a warning class
Automattic/jetpack pull request #14732
Opened 2020-02-19 17:53 UTC by scruffian

#### Changes proposed in this Pull Request:
* This updates the CSS selectors used by the `with-has-warning-is-interactive-class-names` component, so that they still target the block in edit mode.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Bug fix

#### Testing instructions:
* Apply this patch on WPCOM (update with patch name when it's created
* Add a Calendly block on a free site
* Check that you can interact with the block, and add a URL
* Deselect the block
* Check that you can reselect the block

#### Proposed changelog entry for your changes:

* No changelog

2020-02-19 18:19 UTC, Copons commented
The change here works as advertised, but when I try to insert a link the block breaks with this error:

`This block has encountered an error and cannot be previewed.`

<img width="665" alt="Screenshot 2020-02-19 at 18 18 59" src="https://user-images.githubusercontent.com/2070010/74862611-58bec400-5344-11ea-9e82-17cce6ccff35.png">

2020-02-19 19:19 UTC, scruffian commented
@Copons thanks for the review. I think that bug is being caused by https://github.com/Automattic/jetpack/pull/14730

2020-02-19 19:22 UTC, Copons commented
> @Copons thanks for the review. I think that bug is being caused by #14730

I haven't had the chance to look at that yet, but in this case I'd probably note that this PR is dependent on that other one.
Otherwise, when the pointer event will let users be able to trigger the embed, they will end up with broken blocks.

2020-02-19 21:26 UTC, pablinos commented
> @Copons thanks for the review. I think that bug is being caused by #14730

It's being fixed by #14730!

This does fix the problem and I think it was caused by the wrapper div that was removed in WordPress/Gutenberg#19593

I've discovered the reason OpenTable wasn't affected by this, and fixed it in #14738, but this should be merged first

2020-02-20 18:06 UTC, jeherve requested changes
Do you think you could rebase this PR so we can test it with the fix that has now been merged?

Thank you!

2020-02-20 19:02 UTC, scruffian commented
Rebased ✅

2020-02-21 12:30 UTC, Copons approved these changes
Works for me! ✨ 

Unrelated to this PR, I've noticed that, when unavailable, the block outputs just a link.
Anchors being inline elements, they might not respect some theme styles setting the blocks' width and margins.

I've incidentally tried this diff on a site using the Maywood theme and it looks like this:

<img width="1670" alt="Screenshot 2020-02-21 at 12 14 16" src="https://user-images.githubusercontent.com/2070010/75034585-66d82600-54a5-11ea-8f11-0a4df7fa93a4.png">

The green box is the intended post content width (set with `max-width` and `margin: auto`), while the red box with the Calendly link is the screen's 100% width.

I think we should do something like this 🤔 
```jsx
{
  save: () => (<div><a href={ url }>{ url }</a></div> ),
}
```

2020-02-21 17:09 UTC, apeatling approved these changes
Works for me. I was able to add a calendly URL and see the correct embed. I deselected the block and reselected and was able to change all settings and interact with the block.

2020-02-21 18:19 UTC, jeherve approved these changes

2020-02-24 07:12 UTC, merged

2020-02-24 12:12 UTC, scruffian commented
r203259-wpcom