Ads module: Use vanilla JS instead of jQuery
Automattic/jetpack pull request #14770
Opened 2020-02-22 13:35 UTC by dero

For some(†) legacy themes the top ad is dynamically moved to a better
position using JavaScript. This commit rewrites the funcionality
to use vanilla JavaScript instead of depending on jQuery.

† twentyseventeen, twentyfifteen, twentyfourteen

#### Changes proposed in this Pull Request:
* Drop a small dependency on jQuery in favor of using vanilla JS.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is an iteration on the existing WordAds module.

#### Testing instructions:
* Go to WP Admin > Jetpack > Settings > Traffic.
* Enable Ads and make sure the _Top of each page_ is enabled.
* Go to WP Admin > Appearance > Themes and enable one of the themes that use this functionality: `twentyseventeen`, `twentyfifteen` or `twentyfourteen`.
* Go to the front-page of the site and observe the top ad being placed correctly.
* Make sure there are no JS errors raised in the browser's dev tools.

#### Proposed changelog entry for your changes:
* Replaces jQuery code in the Ads module by vanilla JS.

2020-02-24 18:48 UTC, kraftbj submitted a review, later dismissed
Worked as advertised in FF/Chrome.

2020-02-24 19:04 UTC, dbspringer requested changes
This generally seems to work (tested in Chrome/FF/Safari) except for twentyfourteen. Though it seems to be generating an error for the `article:first` selector. Does this method work if the selector is a pseudo class?

<img width="534" alt="Screen Shot 2020-02-24 at 1 06 20 PM" src="https://user-images.githubusercontent.com/273708/75182675-815d0a00-5706-11ea-9cd1-4d54f8015f46.png">

Thanks for taking a look at this!

2020-02-25 09:10 UTC, dero commented
@dbspringer Good catch, thank you. I didn't notice it's not a valid CSS selector.

`:first` is a jQuery selector that selects only the [first matched](https://api.jquery.com/first-selector/) element. That's what [`querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) does by default, so stripping it solves the issue and produces identical results in the vanilla JS implementation. Done in 96f89131228cd82de6d3f35189190f7e50d533dc.

2020-02-25 14:39 UTC, kraftbj commented
With the extra line added at the end, I removed them and ran PHPCBF while we were in the file (and since the PR has been generally reviewed). Spinning up a JN and testing *all* indicated themes.

2020-02-25 17:26 UTC, dbspringer approved these changes
Looks good, thanks for the quick fix 👍

2020-02-25 17:34 UTC, kraftbj approved these changes
I concur with the fine gentleman from San Diego (@dbspringer) and with this stamp, mark the PR as approved. Let it be merged.

2020-02-25 17:35 UTC, merged