Instant Search: Display filters selected outside of overlay
Automattic/jetpack pull request #14834
Opened 2020-02-27 23:04 UTC by jsnmoon

Fixes #14615.

#### Changes proposed in this Pull Request:
* Adds appropriate checkboxes for filters selected outside of the search overlay. 

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
1. Follow [these setup instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) to set up Jetpack Instant Search on your site. Please make sure to add the Jetpack Search widget to two locations: 
    1. once to your site sidebar/footer. Make sure to define some filters for this widget.
    2. once to the Jetpack Search Sidebar within the search overlay. Make sure to define different filters than the ones in your site sidebar/footer.

2. Click on one of the filter links in your site sidebar/footer. Ensure that the search overlay opens with your search results.

3. Check your overlay sidebar. Ensure that the filter you've selected in step 2 shows up as a selected checkbox in the overlay sidebar.

4. Resize your window to be narrower than 768 pixels. Ensure that the filters button appears underneath the overlay input.

5. Click on the filters button to spawn the mobile filter popover. Ensure that the filter you've selected in step 2 appears as a selected checkbox in the popover.

#### Proposed changelog entry for your changes:
* None.

2020-03-02 17:16 UTC, gibrown requested changes
I've only glanced at the code so far. Found some bugs and other pieces we probably should improve.

1. Filtering by a category that doesn't exist: http://gibrown.wpsandbox.me/main?blog_id=20115252&category=post-formats

<img width="1184" alt="Screen Shot 2020-03-02 at 10 06 35 AM" src="https://user-images.githubusercontent.com/820871/75699960-925dcc00-5c6e-11ea-9704-6c176c4bb842.png">

I'm not sure how common this will be, but we should probably handle it by displaying the filter that is applied even if we can't format it correctly.

2. Checkbox not checked for Posts: http://gibrown.wpsandbox.me/main?blog_id=20115252&post_types=post (maybe an existing bug, but I saw a number of weird cases like this that are hard to reproduce)

<img width="1064" alt="Screen Shot 2020-03-02 at 10 12 45 AM" src="https://user-images.githubusercontent.com/820871/75699884-6b06ff00-5c6e-11ea-9c22-fb2a2625da8f.png">
 
3. Double "clear filters" when there is a widget above the filters widget. I think we should probably keep it in the filters widget.

<img width="1145" alt="Screen Shot 2020-03-02 at 10 05 27 AM" src="https://user-images.githubusercontent.com/820871/75700077-be794d00-5c6e-11ea-983b-925f32ed2e09.png">

@keoshi probably need your feedback on some of these cases too.

2020-03-02 23:44 UTC, jsnmoon commented
> 1. Filtering by a category that doesn't exist: http://gibrown.wpsandbox.me/main?blog_id=20115252&category=post-formats

This is happening because of our use of `blog_id`. It shouldn't happen during regular use of Instant Search since we pull filter configurations from all Jetpack Search widgets defined on the site. 

I'd also advise against adding support for displaying filters not defined by any Jetpack Search widgets on the site. The logic we have in place for handling all of the site's filter configurations is complex as-is; adding support for deciphering any arbitrary filter value in the query string would significantly increase complexity and maintenance burden.

> 2. Checkbox not checked for Posts: http://gibrown.wpsandbox.me/main?blog_id=20115252&post_types=post

I'll look into this; I can reproduce this bug.

> 3. Double "clear filters" when there is a widget above the filters widget.

Removing `Clear Filters` from the preselected filters component should be a straightforward change. @keoshi, what do you think?

2020-03-03 12:37 UTC, keoshi commented
Not adding a review yet because I don't believe I can test this fully: the JPS widget configured outside of the overlay appears to be fetching content from the current site, not the `blog_id` I set the search results to (my blog that has lots more content). This might have to do with what @jsnmoon explains [here](https://github.com/Automattic/jetpack/pull/14834#issuecomment-593681102):

> This is happening because of our use of `blog_id`. It shouldn't happen during regular use of Instant Search since we pull filter configurations from all Jetpack Search widgets defined on the site.

I'll test again shortly by using the content I have on this test site.

2020-03-03 12:38 UTC, keoshi commented
> Removing `Clear Filters` from the preselected filters component should be a straightforward change. @keoshi, what do you think?

Yep, let's do that!

2020-03-03 12:50 UTC, keoshi approved these changes
Worked great in my limited testing with very little content on the test site. I really like how it reuses the existing overlay filters if they're already there. This is excellent!

Re: `Clear filters` button: I'd try to keep the top-most link if possible, as it will make things neater visually speaking.

2020-03-03 21:00 UTC, merged