Docs: add instructions to enable beta blocks on JN sites
Automattic/jetpack pull request #15068
Opened 2020-03-20 14:15 UTC by leogermani

Adds instructions on how to enable Beta blocks in a Jurassic Ninja site.

#### Changes proposed in this Pull Request:

* Changes the README for extensions, adding instructions on how to enable Beta blocks in a Jurassic Ninja site.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No, just documentation 

#### Testing instructions:

* Check if the instructions are correct and that it should be there

2020-03-20 14:54 UTC, jeherve requested changes

2020-03-20 14:54 UTC, jeherve commented on extensions/README.md
> +- In a Jurassic Ninja site, you must go to Settings > Jetpack Constants, and enable the `JETPACK_BETA_BLOCKS` there.
```suggestion
- In a Jurassic Ninja site, you must go to Settings > Jetpack Constants, and enable the `JETPACK_BETA_BLOCKS` option there.
```

2020-03-20 15:38 UTC, jeherve approved these changes

2020-03-20 18:01 UTC, merged

2020-04-15 16:27 UTC, kraftbj commented
r205883-wpcom