Search: Add search plan to my-plans page
Automattic/jetpack pull request #15095
Opened 2020-03-24 01:49 UTC by gibrown

Changes:
- Adds the search plan to the /my-plans page.
- Removes the feature card for search for pro plans (at some point we will probably remove it)
- Don't show the upgrade nudge if they already have a plan

<img width="1195" alt="Screen Shot 2020-03-23 at 7 37 31 PM" src="https://user-images.githubusercontent.com/820871/77379565-a0b77900-6d3e-11ea-9304-1d26181249f7.png">

To test:
- Go to wp-admin/admin.php?page=jetpack#/my-plan
- Use "Dev tools" at the bottom of the page to try different plans out (unfortunately you can't do combos: https://github.com/Automattic/jetpack/issues/15071)

@keoshi I just copied the image that we already have. Do we have a search image that is for the plan? I guess we'll want to use that in Calypso also.

2020-03-24 15:51 UTC, keoshi commented
I believe the existing pattern (for JP Backup) is to reuse the plan icon, which I've added on https://github.com/Automattic/wp-calypso/pull/40382

2020-03-25 11:04 UTC, keoshi approved these changes
LGTM!

2020-03-25 22:52 UTC, jsnmoon requested changes
I don't think this is working as intended. My site has a Jetpack Free plan and a Jetpack Search product purchased via the Checkout flow via Calypso.

With this change, the Instant Search card is missing:

<img width="1068" alt="Screen Shot 2020-03-25 at 4 49 27 PM" src="https://user-images.githubusercontent.com/4044428/77592832-aafd8280-6eb8-11ea-9092-b58883084b2a.png">

When I manually set my plan to Search, I get the following:

<img width="1068" alt="Screen Shot 2020-03-25 at 4 50 57 PM" src="https://user-images.githubusercontent.com/4044428/77592908-d2ece600-6eb8-11ea-9c46-b9788647be78.png">

2020-03-25 23:23 UTC, jsnmoon approved these changes
I just pushed a commit that fixes the bugs mentioned in my previous review. Please double-check my changes before merging!

2020-03-26 20:44 UTC, jsnmoon commented on _inc/client/my-plan/index.jsx
> +	const hasSearchProduct = !! find( props.purchases, purchase =>
I knew I forgot something; this needs an `import { find } from 'lodash';` for it to work properly.

2020-03-26 21:26 UTC, merged