Remove invalid type=text/html attribute from iframe for YouTube embed/shortcode
Automattic/jetpack pull request #15225
Opened 2020-04-01 01:18 UTC by westonruter

Recently I've been noticing AMP validation errors being raised when using a YouTube Embed block. For example:

> ![image](https://user-images.githubusercontent.com/134745/78086718-a67f1100-7373-11ea-95a5-7e89ef427d55.png)

The `type` attribute here is on the `amp-iframe`:

> ![image](https://user-images.githubusercontent.com/134745/78086694-96ffc800-7373-11ea-9ea6-b56b2ee46766.png)

The underlying block HTML is:

```html

<figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=6Lo7pVUCBeA
</div></figure>

```

And in the non-AMP version, this is the output HTML:

```html
<figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<span class="embed-youtube" style="text-align:center; display: block;"><iframe class='youtube-player' type='text/html' width='640' height='360' src='https://www.youtube.com/embed/6Lo7pVUCBeA?version=3&#038;rel=1&#038;fs=1&#038;autohide=2&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;wmode=transparent' allowfullscreen='true' style='border:0;'></iframe></span>
</div></figure>
```

It turns out the `iframe` element doesn't even allow the `type` attribute:

> ![image](https://user-images.githubusercontent.com/134745/78089179-6cb20880-737b-11ea-818a-53b022551890.png)

So it seems this attribute was added incorrectly.

See #14397 

#### Changes proposed in this Pull Request:

* Remove erroneous `type` attribute from `iframe` element for YouTube embed/shortcode.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Add a YouTube embed block
* Check whether the `iframe` element has a `type` attribute (it shouldn't).

#### Proposed changelog entry for your changes:

* Remove erroneous `type` attribute from `iframe` element for YouTube embed/shortcode.

2020-04-01 08:31 UTC, jeherve requested changes
Do you think you could update the failing test as well?

```
1) WP_Test_Jetpack_Sync_Post::test_embed_shortcode_is_disabled_on_the_content_filter_during_sync
$oembeded is NOT the same as filtered $this->post->post_content
Failed asserting that '<p>Check out this cool video:</p>
<p><span class="embed-youtube" style="text-align:center; display: block;"><iframe class='youtube-player' width='640' height='360' src='https://www.youtube.com/embed/dQw4w9WgXcQ?version=3&#038;rel=1&#038;fs=1&#038;autohide=2&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;wmode=transparent' allowfullscreen='true' style='border:0;'></iframe></span></p>
<p>That was a cool video.</p>
' contains "<p>Check out this cool video:</p>
<p><span class="embed-youtube" style="text-align:center; display: block;"><iframe class='youtube-player' type='text/html' ".
/tmp/wordpress-master/src/wp-content/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-posts.php:980
```

2020-04-03 15:35 UTC, jeherve submitted a review, later dismissed
This looks good to me, it should be good to merge.

2020-04-17 16:31 UTC, kraftbj submitted a review, later dismissed

2020-04-24 16:18 UTC, jeherve submitted a review, later dismissed
Rebasing to address issues with tests. It should work this time (hopefully :) )

2020-04-24 16:25 UTC, jeherve commented
r206422-wpcom

2020-04-24 16:33 UTC, kraftbj submitted a review, later dismissed

2020-05-01 16:26 UTC, kraftbj commented
@westonruter Sorry to ask you to do this -- can you rebase this against master? We had a bug with forked repos and our action to ensure our team had approved it that has been fixed upstream.

Thanks!

2020-05-01 16:46 UTC, kraftbj commented
Sorry about that, yes, please do rebase against master. Thank you!

2020-05-01 16:54 UTC, dereksmart approved these changes
Thanks for your patience Weston!

2020-05-01 17:01 UTC, merged

2020-05-01 17:02 UTC, jeherve commented
Cherry-picked to `branch-8.5` in e3f30925e084c7d9349ffd9fbcbe76df6a98ef86