Fix: Append all posts from IS response
Automattic/jetpack pull request #15368
Opened 2020-04-08 10:32 UTC by dero

Fixes #15352 

#### Changes proposed in this Pull Request:
* Avoid iterating over the `.length` property of a collection that's being altered in the loop.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is a bug fix related to the Infinite Scroll feature.

#### Testing instructions:
* Follow the steps under https://github.com/Automattic/jetpack/issues/15352
* Observe that all posts are loaded correctly.

#### Proposed changelog entry for your changes:
* Fixed a bug where some posts were omitted from infinite scroll.

2020-04-08 13:00 UTC, jeherve requested changes
Could you rebase now that #15366 is merged? That should fix the tests. Thanks!

2020-04-08 13:07 UTC, dero commented
@jeherve Done.

2020-04-08 14:02 UTC, jeherve approved these changes
This works well in my tests, but I'll let others jump in as well to make sure we're all good!

2020-04-08 14:58 UTC, kraftbj requested changes
On Jetpack 8.3 + Pena theme, when IS is set to "Load more posts in page with a button", an "Older Posts" button is visible and, when clicked, triggers the IS load.

With this PR, that same setting no longer shows the button but only loads on scroll -- ignoring the setting.

2020-04-08 15:43 UTC, dero commented
@kraftbj I'm seeing correct and identical behavior on Jetpack 8.4 (master) + Pena and Jetpack 8.4 (this fix) + Pena. The "Older Posts" button is displayed in both cases and more posts are loaded when the button is clicked.

Could you please make double sure the "Load more posts in page with a button" setting is enabled?

2020-04-08 21:58 UTC, kraftbj commented
I suppose maybe I refreshed too quickly before; not seeing it now.

2020-04-08 21:58 UTC, kraftbj approved these changes

2020-04-09 12:48 UTC, merged

2020-04-09 12:49 UTC, jeherve commented
Cherry-picked to `branch-8.4` in 71e202b6c8fb6dc0472f1eca502a4196542023bd