Add Scan Product to the plans page
Automattic/jetpack pull request #15381
Opened 2020-04-08 20:31 UTC by enejb

#### Changes proposed in this Pull Request:
* Refactors the way that the plans page displays the plans page. 
* Adds a single array that is defined in PHP that then gets used to display the products on the plans page. 
* This hopeful make for a smaller JS bundle size. since the prodct definitions don't live in the JS. 
* It make it much easier to add new products down the line. By just adding to the array. 
* It also make it possible easier for different hosts/ partners to offer different products. The products array can be filterable. 
 
#### Testing instructions:
Visit the Plans page. Does it work for you as before. 
Do you see the new Scan Product. 

#### Proposed changelog entry for your changes:
* Adds the new Scan Product to the Plans page.

2020-04-14 20:17 UTC, rcanepa commented
I don't feel comfortable enough to approve a PR like this yet but I tested it anyways. This is what I saw:

- I could upgrade my plan and buy products without problems.
- The UI looks fine on desktop and on mobile. I didn't see any change from the last version.
- From the code standpoint, it looks like a great improvement because the new approach is more generic and reusable, and we are shipping less code.

Awesome work @enejb !

2020-04-15 16:46 UTC, enejb commented
@jeherve I don't think we will be ready to ship Jetpack Scan in 8.5 but the change to remove Jetpack Scan Product will just be a matter or removing it from the jetpack class file.

2020-04-21 16:15 UTC, jeherve requested changes
This seems to work well overall. I only have a few questions


*********

Is the current layout temporary?
![image](https://user-images.githubusercontent.com/426388/79886867-0eb49600-83fa-11ea-80fa-be4f8e971bef.png)

I find it a bit odd to have a radio button in an area where I don't really have to choose between different solutions.

********

What would you think about adding an additional monthly/yearly picker at the bottom of the products? Right now it's kind of hard to switch when looking at Scan since you have to scroll to see one or the other:

![image](https://user-images.githubusercontent.com/426388/79887595-70293480-83fb-11ea-9f8c-c5ec648e4f7b.png)

2020-04-22 08:36 UTC, enejb commented on class.jetpack.php
> +	public static function get_products_for_purchase() {
I don't think this list should come from the api. 
The main reason being is that the each Jetpack Should version should know what features (product) it should be selling. 

I know a lot of those features are moving to the cloud but there is still some product features code in there. 

So it make sense to me that the product should be made available in here.

2020-04-22 08:40 UTC, enejb commented
> Is the current layout temporary?
I don't think so. The layout is consistent with the search one. I am also not a big fan of the radio button for the single feature. But that is the design that we have come up with :)

I don't think Scan should make it into the next version of Jetpack (8.5) but removing it will be as just removing it from the array. 

> What would you think about adding an additional monthly/yearly picker at the bottom of the products?

I think that could easily be done. But lets do it in a different PR if we get approval from design :) 

cc: @keoshi, @eeeeevon13  :)

2020-04-22 09:42 UTC, jeherve commented on class.jetpack.php
> +	public static function get_products_for_purchase() {
> I don't think this list should come from the api.

I moved this discussion here so others can chime in:

p1HpG7-8ZR-p2

2020-04-23 10:35 UTC, enejb commented
I talked to @jeherve and there is no design review needed since the design is staying the same. 
There is no hold on this since the PR is already pretty big and is holding us up from testing Jetpack Scan.

2020-04-23 15:32 UTC, rcanepa submitted a review, later dismissed
> Visit the Plans page.
> 
> - Does it work for you as before.
> - Does it look like before?
> - There should be no changes in that regard (expect for the new Scan Product)
> - Do you see the new Scan Product.

I reviewed this PR again and these things work as expected.

2020-04-27 11:53 UTC, jeherve submitted a review, later dismissed

2020-04-27 11:53 UTC, jeherve commented
This should be good to merge after a rebase!

2020-04-27 12:05 UTC, keoshi submitted a review, later dismissed
This looks good to me!

The only thing I'd note is that we're repeating the promo element inside the cards, making the entire layout more confusing than it should be since we can probably move that common element outside. That can surely be handled in a different PR, but the visuals on this one might help with this decision. cc @folletto @robertbpugh

2020-04-27 13:11 UTC, robertbpugh commented
I agree it is getting busy with all the promos, so we may want to explore a different design for that. But we can't move it outside, as Search has no discount, the Backup discount is still 70%, and Scan is 30% (the price is $7 / $70 as noted here under the pricing table: https://jetpackp2.wordpress.com/2020/04/02/jetpack-scan-pricing/ )

2020-04-28 11:44 UTC, jeherve approved these changes

2020-04-28 11:46 UTC, merged