Block: Instagram - Add a reset button to gallery settings
Automattic/jetpack pull request #15438
Opened 2020-04-14 03:00 UTC by glendaviesnz

Part of #15277

#### Changes proposed in this Pull Request:
* Adds a reset button the Gallery Settings in the sidebar

#### Testing instructions:

* Apply patch to local Jetpack dev env with beta blocks enables
* Add an Instagram gallery block
* Change some settings, and make sure the Reset button becomes enabled, and that clicking it resets the defaults
* Check that Reset button is disabled again once block is back to default settings

![2020-04-14 14 53 48](https://user-images.githubusercontent.com/3629020/79181538-acd7b780-7e60-11ea-97da-84e835fe4fa4.gif)

#### Proposed changelog entry for your changes:
* No changelog  entry needed

2020-04-14 10:26 UTC, Copons commented
What about using the [`RangeControl`'s `allowReset` prop](https://github.com/WordPress/gutenberg/blob/ce1a4d90f30f9afbae72ffe6987eb952ca9e2ba7/packages/components/src/range-control/README.md#allowreset) instead?

2020-04-14 14:45 UTC, scruffian commented
> What about using the RangeControl's allowReset prop instead?

I added a commit to take this approach. What do you think?

2020-04-14 20:50 UTC, glendaviesnz commented
@scruffian, @copons ... Having the reset for each slider seems to me to clutter the interface and add very little value. 

I was a bit dubious about adding a single Reset button for all 3, because in reality how often are people going to want to go back to our arbitrary defaults as apposed to just adjusting the slider to get a layout they are happy with? 

'Reset' is a little ambiguous as well, as I would expect it to return to what it was before I started tampering, but if they have already saved the block with other settings they will go back to our defaults rather than their previously saved settings.

I don't have a strong opinion on this, so happy for someone else to make the call either way  on which of the following, if either, is the preferred:

<img width="209" alt="Screen Shot 2020-04-15 at 8 49 14 AM" src="https://user-images.githubusercontent.com/3629020/79272876-279ee200-7ef6-11ea-800b-5b82173c62de.png">

<img width="208" alt="Screen Shot 2020-04-15 at 8 47 25 AM" src="https://user-images.githubusercontent.com/3629020/79272883-2b326900-7ef6-11ea-96ea-bd2bf30deba7.png">

2020-04-14 20:56 UTC, glendaviesnz commented
@scruffian There is a bug with the slider reset - if you click it twice you end up with an empty input:

![reset-bug](https://user-images.githubusercontent.com/3629020/79273297-e1964e00-7ef6-11ea-8ef8-bb33690e38a5.gif)

I won't worry about looking further into it until we decide if we are going to proceed with this.

2020-04-14 21:51 UTC, scruffian commented
Having a reset button per slider is simpler because it aligns with the way core works, and therefore its more likely to align with user expectation. It would be interesting to get another perspective though...

2020-04-14 22:05 UTC, Copons commented
I agree with @scruffian about aligning with Core.
At the same time I'm aware of the visual clutter. A design opinion might be useful here, @davemart-in! 🙂

2020-04-14 22:35 UTC, glendaviesnz commented
> Having a reset button per slider is simpler because it aligns with the way core works, and therefore its more likely to align with user expectation

I can see the value of a reset if you have a complex value/setting that might be hard to remember, eg. a color hex value, but for these simple digits i can't see any user expectation that they should be able to reset them ... I personally wouldn't provide any reset option at all in this scenario, but as mentioned above, very happy for someone else to make the call on this 😄

2020-04-15 02:19 UTC, apeatling approved these changes

2020-04-15 02:21 UTC, apeatling requested changes
Sorry, didn't mean to approve the review initially there. I agree that this should align with core and provide a reset button for each value.

I believe the empty value after clicking reset twice is expected. The first click resets to the `initialPosition` value, the second click unsets the value.

2020-04-15 02:54 UTC, glendaviesnz commented
> I agree that this should align with core and provide a reset button for each value.

In terms of aligning with core - they don't provide reset buttons for some of the simple sliders that are similar to these, eg. the column block column count:

<img width="278" alt="Screen Shot 2020-04-15 at 2 50 30 PM" src="https://user-images.githubusercontent.com/3629020/79293928-fbe91f80-7f28-11ea-8488-5e3828134187.png">

2020-04-15 10:38 UTC, scruffian commented
I think the reason why I'd like a "reset" personally is that I feel like whoever designed the block chose some defaults for me that are probably good choices. I want to play with the settings and see what it looks like with massive padding, or one column, but at the end of the day I probably want to just trust the designer of the block to choose some sensible defaults for me. The reset button gives me the comfort that these choices are sensible and will look nice, and makes it simple for me to go back to them without having to think to much. That's just me though!

2020-04-15 11:44 UTC, davemart-in commented
The double click reset thing behaves unexpectedly to me as well. 

My preference would be to remove the reset button(s) entirely. I agree with @glendaviesnz that these values are easy enough to simply adjust manually and don't really require a single reset button, let alone 3.

Glen & @Copons my suggestion would be to just close this issue.

2020-04-15 14:50 UTC, Copons commented
I feel the same way as @scruffian in that usually reset buttons makes me feel safe when experimenting.
At the same time, blocks are not "final", and folks who feel they have screwed it up can easily replace a messy block with a fresh new one to get the defaults.
So, yeah, I'm cool with closing this! 👍

2020-04-15 21:49 UTC, glendaviesnz commented
Decision made to close this for now.

2020-04-15 21:49 UTC, closed without merging