Blocks: Add p2tenberg entry point
Automattic/jetpack pull request #15467
Opened 2020-04-16 14:39 UTC by lezama

List of blocks that don't use the "post sidebar", no `wp-edit-post` dependency.
Useful for when using Gutenberg outside of wp-admin, frontend, comments, you name it.

Test:

TBD

2020-04-16 15:58 UTC, simison commented
I agree ideally these wouldn't ever be loaded for P2 if they're not needed but replicated entry-point feels little heavy-handed too, and prone to human error to keep these lists in sync.

Since all unwanted extensions are basically "plugins" (and not "blocks"), would it be possible to have a check inside the registration wrapper that checks for environments' compatibility (maybe if some function exists?) and bails out if the environment doesn't support the sidebar? That way you wouldn't need to make this P2-specific.

https://github.com/Automattic/jetpack/blob/f6f313d268c336491c8bca1afcf3e5d3663597ce/extensions/shared/register-jetpack-plugin.js#L18

2020-04-16 16:14 UTC, lezama commented
> would it be possible to have a check inside the registration wrapper that checks for environments' compatibility (maybe if some function exists?) and bails out if the environment doesn't support the sidebar?

I think that happens after we enqueue all the blocks assets here: https://github.com/Automattic/jetpack/blob/f6f313d268c336491c8bca1afcf3e5d3663597ce/class.jetpack-gutenberg.php#L685

`enqueue_script` doesn't do anything if all the dependencies aren't registered.

2020-04-16 16:39 UTC, jeherve requested changes
This does the trick for now. I don't think we need this bundle in Jetpack Stable though, so we could probably exclude the `editor-no-post-editor*` bundle files from the stable release here:
https://github.com/Automattic/jetpack/blob/90f7e1e4afa68277a461b53f91b0eb4fd68732cb/.svnignore
https://github.com/Automattic/jetpack/blob/22eb79096e972a9947f98e4a291e887bf6fdcf81/tools/build-release-branch.sh#L58

2020-04-21 13:08 UTC, lezama commented
@jeherve we will need this if we want to use p2tenberg with Jetpack coming to Atomic soon.

2020-04-21 16:33 UTC, jeherve requested changes
It looks like this now needs a rebase.

2020-04-21 20:52 UTC, lezama commented
@simison I am in troubles Phab side, whenever the bot that builds the blocks run extensions/index.json gets deleted from the Phab 🤷‍♂️

2020-04-22 13:07 UTC, simison commented
@lezama wild! I'm in no headspace to dig in help but maybe someone from Crew or Devops could look into it?

2020-04-22 13:19 UTC, jeherve commented
I'll take a look in a bit. 👍

2020-04-22 13:29 UTC, lezama commented
@kraftbj found a workaround, shipping the change to `index.json` on a separate Phab D42244

2020-04-22 14:52 UTC, jeherve approved these changes

2020-04-22 14:53 UTC, merged

2020-04-22 15:36 UTC, jeherve commented
r206267-wpcom