Search: Check for helpers before using them
Automattic/jetpack pull request #15586
Opened 2020-04-27 22:18 UTC by kraftbj

This is a very simple fix for #15570 that I feel safe for 8.5.

My initial thought is `load_php` for `Jetpack_Search` is including the Search Helpers file, but `load_php` for the instance search isn't. `set_filters_from_widgets` is being called for both classes, so calling `Jetpack_Search`'s which is using the helper class without checking if it is defined.

@gibrown What do you think about that? With code freeze tonight, this PR would/should stop a fatal but not really fix anything.

Fixes #15570

#### Changes proposed in this Pull Request:
* Checks for a class before use.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* See 15570.
*

#### Proposed changelog entry for your changes:
* Instant Search: Prevents a fatal in some circumstances.

2020-04-27 22:30 UTC, gibrown requested changes
Were you able to reproduce the fatal?

I wonder if we need to be loading the helpers in https://github.com/Automattic/jetpack/blob/339ff19241a81dce2eaeed470e85b90a2a889d83/modules/search/class-jetpack-instant-search.php#L25 

I am guessing there is some code loading ordering problem.

Just protecting this one call likely will not fix the problem since there are a lot of places those helpers are used.

2020-04-28 20:57 UTC, kraftbj commented
@gibrown How about something like this. I centralized the requires into a base function that both classes call. If there are other files needed for both classes in the future, they can be included there. If there are cases only needed in one or the other, that's possible too.

2020-04-28 21:49 UTC, gibrown submitted a review, later dismissed
This looks good to me. Thanks!

2020-04-30 15:59 UTC, jeherve submitted a review, later dismissed
I wasn't able to reproduce the issue, but this doesn't break anything, so let's merge it :)

I'll let you handle the wpcom side.

2020-04-30 16:18 UTC, kraftbj commented
> I'll let you handle the wpcom side.

Will do. This one needs a bit of manual work.

2020-04-30 16:36 UTC, jeherve approved these changes
Reapproving after a rebase to try to solve those Github shenanigans.

2020-04-30 17:24 UTC, merged

2020-04-30 17:25 UTC, jeherve commented
Cherry-picked to `branch-8.5` in e656c6575fbab27b47a1e82141918191f6ba92a3