Add related posts js to footer instead of header
Automattic/jetpack pull request #15599
Opened 2020-04-28 23:21 UTC by umhan35

The related post should be in footer like other js files.

#### Changes proposed in this Pull Request:

* change the $footer parameter to `true` in related post's `wp_enqueue_script`

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Enable related post
* Go to any post page and view source
* Scroll to bottom, the related post js should be there

#### Proposed changelog entry for your changes:

* Move related posts js to footer

2020-04-29 02:42 UTC, umhan35 commented
I followed the template.

2020-05-06 20:32 UTC, kraftbj requested changes
Thanks for the patch! Apologies about the PR template message -- in your case, it is meant to remind folks on the team to label the PR, but as a contributor, you're not able to do it.

Which themes did you test it on? With Twenty Twenty, changing the `in_footer` parameter to false resulted in the DOM not being injected with the Related Posts.

2020-05-18 01:45 UTC, umhan35 commented
@kraftbj I changed the optional `in_foot` parameter to `true`... not false...

I tested with Twenty Twenty.

2020-05-18 16:20 UTC, jeherve commented
This worked well for me on the frontend (the related posts were still inserted). The `[jetpack-related-posts]` shortcode also kept working, as well as the block.

The Related Posts stopped appearing in the customizer though; that view seems to be broken by your change.

2020-08-23 01:51 UTC, closed without merging