VideoPress Block: Tentative fix for unselectable block (GB 8.1)
Automattic/jetpack pull request #15958
Opened 2020-05-27 19:55 UTC by ockham

WIP.

Tentative fix for #15922 

The light wrapper pulls information from block context, which we might need to override here to get the correct data (`jetpack/videopress` rather than `core/video`).

#### Changes proposed in this Pull Request:
Use light block wrapper for VideoPress block in order to prevent it from becoming unselectable.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
TBD.

Can't really test locally, need to test the counterpart WP.com diff.

#### Proposed changelog entry for your changes:
Use light block wrapper for VideoPress block in order to prevent it from becoming unselectable.

2020-05-28 09:56 UTC, jeherve requested changes
I am afraid we can't use `__experimentalBlock` just yet, as we need the Video block to keep working on sites that run WordPress 5.3 without the Gutenberg plugin.

![image](https://user-images.githubusercontent.com/426388/83127245-37573c00-a0da-11ea-9819-71ac98fe9af8.png)

2020-05-28 10:14 UTC, ockham commented
Thanks @jeherve, I'll try making the import dynamic and guard it with a `try...catch`.

2020-05-28 12:32 UTC, ockham commented
BTW @jeherve how did you manage to get the VideoPress block to render not in fallback mode? :thinking:

2020-05-28 12:38 UTC, ockham commented
Ah nvm I hadn't enabled VideoPress in JP settings (and had to upload a new video after enabling it to have it properly processed by VP) :sweat_smile:

2020-05-28 14:13 UTC, ockham commented
Should work with older GB versions now :slightly_smiling_face:

2020-05-29 11:48 UTC, jeherve approved these changes
This works well in my tests. Merging.

2020-05-29 11:49 UTC, merged

2020-05-29 11:50 UTC, jeherve commented
Cherry-picked to `branch-8.6` in a6650da3111ed00722da4736090c650e3e449e04

@ockham I'll let you handle the WordPress.com side?

2020-05-29 11:50 UTC, ockham commented
> Cherry-picked to `branch-8.6` in [a6650da](https://github.com/Automattic/jetpack/commit/a6650da3111ed00722da4736090c650e3e449e04)

Awesome, thank you!

> @ockham I'll let you handle the WordPress.com side?

Yep, I'll take care of that :+1: