Instant Search: Start extracting translatable strings
Automattic/jetpack pull request #16080
Opened 2020-06-05 20:13 UTC by jsnmoon

Fixes #15754 (I think?)

#### Changes proposed in this Pull Request:
* Adds instant search JS/JSX files to the `languages:extract` gulp job.
* Invoke `wp_set_script_translations` for the bundled JS file for instant search.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No, this is a bugfix for enabling translations in instant search.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Run `yarn build-production` and ensure that instant search related strings are added to `_inc/jetpack-strings.php`. 
* (I'm not sure how to test translations; for example, I know there are certain terms used in the instant search interface that have been [translated](https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/ko/default/?filters%5Bterm%5D=relevance&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc), but I don't know how to get them to appear. Would love some direction or guidance on this from @Automattic/jetpack-crew!)

#### Proposed changelog entry for your changes:
* Fixed translation issues for Jetpack Search.

2020-06-08 16:09 UTC, jeherve requested changes
I am not sure this can be tested with this branch; I don't know if we can get a `jetpack-instant-search'` json file back from WordPress.org in the language pack until we ship this PR.

I **think** we could maybe test this by pushing this change to `trunk` and seeing if translations start working.

2020-06-08 16:09 UTC, jeherve commented on gulpfile.babel.js
> +			'modules/search/**/*.jsx',
I don't think that is needed here. The translations will be extracted from `_inc/build/instant-search/jp-search.bundle.js` by WordPress.org, and a new .json file matching `jetpack-instant-search` should be created and shipped alongside the language packs.

2020-06-08 16:10 UTC, jeherve commented
cc @akirk who will most likely know more about this than me. :)

2020-06-08 16:24 UTC, akirk commented
Because of our peculiar way of loading translations in Jetpack, I assume this won't work. You'll rather need to change the textdomain on the instant search files.

2020-06-08 17:25 UTC, jsnmoon commented
Talked with @akirk and @jeherve via Slack and figured out that the strings weren't being extracted from the Webpack bundle.

[Here](https://plugins.svn.wordpress.org/jetpack/trunk/_inc/build/instant-search/jp-search.bundle.js) is the bundle we've been publishing to the .org SVN. Note that the translation calls here were being optimized to:

```js
at("Search powered by Jetpack", "jetpack")
```

Unfortunately, translate.wordpress.org can only extract strings from JS files in the following format:

```js
Object(_wordpress_i18n__WEBPACK_IMPORTED_MODULE_4__[\"__\"])('Button allowing you to sell subscription products.', 'jetpack')
```

Adding the `DependencyExtractionWebpackPlugin` to the Search build configuration appears to fixes this issue, at least for the dev build:

```js
Object(_wordpress_i18n__WEBPACK_IMPORTED_MODULE_1__["__"])('Search powered by Jetpack', 'jetpack')
```

Unfortunately, the production build overly compresses the translate invocation and makes it impossible for the strings to be picked up by translate.wordpress.org.

I'll investigate and update the PR once I have a working solution.

2020-06-08 18:05 UTC, akirk commented
FWIW you can find the supported function call formats here: https://github.com/wp-cli/i18n-command/blob/master/src/JsFunctionsScanner.php#L187

2020-06-15 22:20 UTC, jsnmoon commented
@jeherve @akirk: It looks like the production build now compresses `__` calls to `Object(qe.__)("Relevance", "jetpack")`, which is supported by [the i18n scanner](https://github.com/wp-cli/i18n-command/blob/master/src/JsFunctionsScanner.php#L212).

However, there's one thing I still can't figure out: I ran `wp i18n make-pot .` on the latest master branch (d0d281021ee6cf05a9001663aa864207b59d5ef7) and found translatable strings from JS and JSX files in instant search. In other words, were translatable strings from the instant search bundle already available to translate.wordpress.org before this PR?

Any ideas on what might be happening here?

2020-06-16 08:30 UTC, akirk commented
> [...]  found translatable strings from JS and JSX files in instant search in languages/jetpack.pot. Does this mean translatable strings from the instant search bundle already available to translate.wordpress.org before this PR?

If you look into the [code we committed to the wordpress.org SVN](http://plugins.svn.wordpress.org/jetpack/trunk/), it misses the JS files you are referring to, i.e. http://plugins.svn.wordpress.org/jetpack/trunk/modules/search/instant-search/components/search-box.jsx 404s. Therefore they cannot be extracted on translate.wordpress.org. @jeherve I suppose we are not committing the whole Jetpack repo content for size reasons.

2020-06-16 08:39 UTC, jeherve commented
> I suppose we are not committing the whole Jetpack repo content for size reasons.

Indeed. We don't ship the blocks' or the React dashboard's unbuilt code either. We tend to only ship production code to WordPress.org.

This was sufficient with blocks since the translatable strings could be extracted from the built JavaScript bundle.

> found translatable strings from JS and JSX files in instant search in languages/jetpack.pot. Does this mean translatable strings from the instant search bundle already available to translate.wordpress.org before this PR?

I don't think so. You could search for those strings on translate.wordpress.org to be sure, but since we do not ship any `languages/jetpack.pot` file in the production Jetpack, those strings would not be available in SVN.

> It looks like the production build now compresses __ calls to Object(qe.__)("Relevance", "jetpack"), which is supported by the i18n scanner.

By "now", do you mean with the changes of this PR? If so, it seems like great news! We could merge this PR and push those changes in a Jetpack 8.7 Alpha to `trunk` today. That should allow us to confirm that the i18n scanner picks up the new strings right away.

2020-06-16 15:01 UTC, jsnmoon commented
> I suppose we are not committing the whole Jetpack repo content for size reasons. @akirk 

Gotcha, this is the part of our release process I wasn't aware of.

> By "now", do you mean with the changes of this PR? If so, it seems like great news! We could merge this PR and push those changes in a Jetpack 8.7 Alpha to `trunk` today. That should allow us to confirm that the i18n scanner picks up the new strings right away. @jeherve 

Yup, that's correct! Merging the PR makes a lot of sense.

2020-06-16 15:18 UTC, jeherve approved these changes
Let's give this a try!

2020-06-16 15:20 UTC, merged

2020-06-16 17:20 UTC, jeherve commented
Looks like W.org was able to find the strings! 🎉 👏 
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/fr/default/?filters%5Bterm%5D=_inc%2Fbuild%2Finstant-search%2Fjp-search.bundle.js&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I'll translate some now, and see if they get used properly.

2020-06-20 08:57 UTC, historiek commented
I translated most of the strings into Dutch some days ago as well. 

https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/nl/default/?filters%5Bterm%5D=_inc%2Fbuild%2Finstant-search%2Fjp-search.bundle.js&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

How can I get them reviewed / approved before the July Jetpack update becomes available for our site?

2020-06-20 17:48 UTC, gibrown commented
@akirk do you know if all of these strings went out to be translated in the translation bundle? Will we be able to get them all into the next release (code freeze June 29th)?

2020-06-20 17:54 UTC, akirk commented
They will be sent for translation on Monday and will be back around Thursday.