Renaming Simple Payments to Pay with PayPal Button
Automattic/jetpack pull request #16133
Opened 2020-06-11 09:48 UTC by eoigal

We are looking to rename the Simple Payments block to Pay with PayPal button - p2y3YZ-43P

This change shouldn't affect block behaviour. The changes here are only intended to change the use of public facing Simple Payments terminology to Pay with PayPal button.

This change will require changes to support articles. I've created the following articles that duplicate the existing Simple Payments support articles;

https://wordpress.com/support/pay-with-paypal-button/
http://jetpack.com/support/jetpack-blocks/pay-with-paypal-button/
https://jetpack.com/support/pay-with-paypal-button/
https://wordpress.com/support/pay-with-paypal-button-styling/

I intend to update the images and videos used in these articles to use the latest on frontend after the changes have been agreed on.

#### Testing instructions:
The Simple Payments block should now be called Pay with PayPal button - verify this by creating a post with block editor and adding a Pay with PayPal button. The block editor should look like this;
<img width="215" alt="icon" src="https://user-images.githubusercontent.com/5560595/84370950-e151c080-abd0-11ea-8696-447c621f7393.png">
<img width="321" alt="shortcut" src="https://user-images.githubusercontent.com/5560595/84370952-e1ea5700-abd0-11ea-8f55-1c22da66c301.png">
<img width="656" alt="esc-block" src="https://user-images.githubusercontent.com/5560595/84370955-e282ed80-abd0-11ea-8434-cbdcd8856290.png">
<img width="286" alt="block-description" src="https://user-images.githubusercontent.com/5560595/84370962-e3b41a80-abd0-11ea-8b0a-44c19fc3801c.png">

Also confirm that the Simple Payments widget is now named Pay with PayPal button;
<img width="408" alt="widget-form" src="https://user-images.githubusercontent.com/5560595/84371092-0c3c1480-abd1-11ea-8fca-6025c81c3592.png">
<img width="283" alt="widget-title" src="https://user-images.githubusercontent.com/5560595/84371093-0cd4ab00-abd1-11ea-86df-5e9fba52032a.png">

2020-06-11 15:32 UTC, mmtr reviewed
Thanks for preparing the support documentation, @eoigal! This works great.

But I think we missed one occurrence in the new Jetpack Setup Wizard that was recently merged in https://github.com/Automattic/jetpack/pull/15637.

https://github.com/Automattic/jetpack/blob/72a90143f45055aa5be1ea6cedd1d91e5ae6739e/_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js#L884

2020-06-11 15:38 UTC, mmtr commented
> This change will require changes to support articles. I've created the following articles that duplicate the existing Simple Payments support articles;


Just found out one more article we'd need to update: https://jetpack.com/support/jetpack-blocks/

<img width="875" alt="Screen Shot 2020-06-11 at 17 38 27" src="https://user-images.githubusercontent.com/1233880/84406858-63aaa680-ac0a-11ea-9141-01c916f7984b.png">

2020-06-11 21:52 UTC, gwwar commented
There's another usage in https://github.com/Automattic/jetpack/blob/72a90143f45055aa5be1ea6cedd1d91e5ae6739e/_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js#L884-L885

Though I don't think I've seen this wizard in action before

2020-06-11 22:01 UTC, gwwar commented
From testing instructions in https://github.com/Automattic/jetpack/pull/15637

we should be able to see the wizard with:
* Add the following to the end of wp-config.php: add_filter( 'jetpack_show_setup_wizard', '__return_true' ); (Not sure if we still need this step)
* Visit /wp-admin/admin.php?page=jetpack#/setup/features.

2020-06-12 14:30 UTC, mmtr submitted a review, later dismissed
LGTM

2020-06-15 10:56 UTC, jeherve reviewed
> Pay with PayPal button

We moved away from the word "button" in the block name for Recurring Payments and Simple Payments in #15061, following feedback from @mtias in p58i-8JL-p2

Should we stick with "Pay with Paypal" only for the block name?

2020-06-15 10:59 UTC, mtias commented
It does look like a really long name. The extra "button" text seems superfluos as @jeherve points out. Also curious why just "PayPal" was discarded as an option?

2020-06-15 11:05 UTC, artpi commented
> It does look like a really long name. The extra "button" text seems superfluos as @jeherve points out. Also curious why just "PayPal" was discarded as an option?

There are legal considerations: p2y3YZ-43P-p2

However I am curious @lessbloat @gwwar  - do we really need the "Button" part?

2020-06-15 15:25 UTC, eoigal commented
Removed use of `button` where I think its superflous in D44948-code

2020-06-15 22:58 UTC, gwwar commented
> However I am curious @lessbloat @gwwar - do we really need the "Button" part?

Not sure, I'm checking in with folks.

2020-06-16 00:24 UTC, kwight commented
@jeherve any suggestion for how best to apply these changes conditionally _after_ merge to master, but _before_ the plugin release? Meaning, we would merge the dotcom patch soon also, but not "flip the switch" before the release on July 7th?

I'd normally think a filter, but it's super awkward when dealing on a string-by-string basis. Would we be OK with a constant check that we then remove once the plugin is out?

```php
title: is_defined( 'WPCOM_PAY_WITH_PAYPAL_ACTIVE' ) ? __( 'Pay with Paypal' ) : __( 'Simple Payments Block' ),
```

2020-06-16 07:23 UTC, jeherve commented
> any suggestion for how best to apply these changes conditionally after merge to master, but before the plugin release? Meaning, we would merge the dotcom patch soon also, but not "flip the switch" before the release on July 7th?

Until now, we've just held off committing matching WordPress.com diffs until an hour before the release whenever a diff would introduce changes to block markup or other important changes like that. I keep a list of such diffs and usually commit them myself or coordinate with the PR author so they commit themselves on release day.

2020-06-16 07:24 UTC, jeherve requested changes
The tests appear to be failing right now.

2020-06-16 14:59 UTC, gwwar commented
We should be able to use "Pay with PayPal" without the button. I'll update related issues.

2020-06-16 19:33 UTC, gwwar commented
Let's also make sure that search teams for "Simple Payments" will still return the block, in addition to the new block name.

2020-06-17 23:10 UTC, gwwar commented on modules/widgets/simple-payments/admin-warning.php
> +				? 'https://wordpress.com/support/pay-with-paypal-button/'
We may want to update the doc permalink and this url to `https://wordpress.com/support/pay-with-paypal`

2020-06-17 23:10 UTC, gwwar commented on modules/widgets/simple-payments/form.php
> + * Display the Pay with PayPal button Form.
Just "Pay with Paypal"

2020-06-17 23:11 UTC, gwwar commented on extensions/blocks/simple-payments/index.js
> +		_x( 'payments', 'block search term', 'jetpack' ),
Nice, thanks for adding older search terms @mmtr !

2020-06-17 23:35 UTC, gwwar commented on extensions/blocks/recurring-payments/edit.jsx
> +			editedProductRenewInterval: 'one-time',
I think we want to keep the default to monthly, based on https://github.com/Automattic/wp-calypso/pull/42848#issuecomment-639594153

2020-06-17 23:42 UTC, gwwar submitted a review, later dismissed
Thanks @mmtr for continuing with this one! Overall this one tests well for me! So is the plan to merge this one, but hold off on the wpcom side until July 7th?

Some things to confirm before merge:
- I had some trouble getting the PayPal widget to display. (Was it linked to a higher plan than premium?) 
- I think we may need to rebase with master

### Pay with PayPal
<img width="755" alt="Screen Shot 2020-06-17 at 4 21 24 PM" src="https://user-images.githubusercontent.com/1270189/84961404-0bb3ea00-b0b9-11ea-92a5-fe7ab382d94e.png">
<img width="444" alt="Screen Shot 2020-06-17 at 4 21 58 PM" src="https://user-images.githubusercontent.com/1270189/84961411-10789e00-b0b9-11ea-9d4b-08e8fa4f984c.png">
<img width="276" alt="Screen Shot 2020-06-17 at 4 22 07 PM" src="https://user-images.githubusercontent.com/1270189/84961449-2dad6c80-b0b9-11ea-81e3-590b1afd9222.png">

### Payments + One time option
<img width="811" alt="Screen Shot 2020-06-17 at 4 33 53 PM" src="https://user-images.githubusercontent.com/1270189/84961444-28e8b880-b0b9-11ea-8e18-4b59d87f7a35.png">
<img width="302" alt="Screen Shot 2020-06-17 at 4 33 58 PM" src="https://user-images.githubusercontent.com/1270189/84961461-356d1100-b0b9-11ea-930b-3346b475fd9c.png">
<img width="554" alt="Screen Shot 2020-06-17 at 4 36 12 PM" src="https://user-images.githubusercontent.com/1270189/84961469-39992e80-b0b9-11ea-97e3-f28244fed37e.png">
<img width="1046" alt="Screen Shot 2020-06-17 at 4 37 33 PM" src="https://user-images.githubusercontent.com/1270189/84961471-3aca5b80-b0b9-11ea-8897-793ca8978c55.png">
<img width="988" alt="Screen Shot 2020-06-17 at 4 37 46 PM" src="https://user-images.githubusercontent.com/1270189/84961475-3c941f00-b0b9-11ea-9e15-f4a46ea50623.png">

2020-06-18 00:10 UTC, gwwar commented
This one also fixes https://github.com/Automattic/wp-calypso/issues/42860

2020-06-18 10:31 UTC, mmtr commented
> So is the plan to merge this one, but hold off on the wpcom side until July 7th?

Correct. I'm happy to make sure the diffs are updated so they can be applied cleanly on July 7.

> I had some trouble getting the PayPal widget to display. 

Yeah, I'm not able to find it as well (at least testing on a JN site). According to docs it should be in Appearance > Customize > Widgets on sites under a Premium plan or higher. @jeherve do you have any clue about what could be happening?

2020-06-18 12:46 UTC, jeherve submitted a review, later dismissed
This tests well for me, it should be good to merge.

> Yeah, I'm not able to find it as well (at least testing on a JN site). According to docs it should be in Appearance > Customize > Widgets on sites under a Premium plan or higher. @jeherve do you have any clue about what could be happening?

You would need to go to Jetpack > Settings and enable the Extra Sidebar Widgets there in order to see all the widgets Jetpack has to offer.

I don't think that's very user-friendly, especially since the toggle is only available if you search for it, but I think that's part of a larger discussion around the visibility of our features.

2020-06-18 18:00 UTC, gwwar commented
Oh thanks @jeherve! Name changes also look good in the widget:

<img width="1111" alt="Screen Shot 2020-06-18 at 10 56 47 AM" src="https://user-images.githubusercontent.com/1270189/85055718-dcea5200-b152-11ea-81f4-b45a4db9f71b.png">
<img width="316" alt="Screen Shot 2020-06-18 at 10 57 16 AM" src="https://user-images.githubusercontent.com/1270189/85055727-dfe54280-b152-11ea-87c4-cba2a1b29515.png">
<img width="392" alt="Screen Shot 2020-06-18 at 10 57 26 AM" src="https://user-images.githubusercontent.com/1270189/85055729-e1166f80-b152-11ea-9e70-dc14c0c7d91d.png">

2020-06-22 10:55 UTC, mmtr commented
I think we may want to hold off merging this PR until we have the Recurring Payments support docs renamed too, so we can update the links ([example](https://github.com/Automattic/jetpack/blob/f7ec966a2206e8a723a666c0c8cbd2a9cb557853/extensions/blocks/recurring-payments/edit.jsx#L381)) as well in this PR and therefore keep the uncommitted WP.com changes in one single diff.

2020-06-22 14:50 UTC, mmtr commented
> I think we may want to hold off merging this PR until we have the Recurring Payments support docs renamed too, so we can update the links ([example](https://github.com/Automattic/jetpack/blob/f7ec966a2206e8a723a666c0c8cbd2a9cb557853/extensions/blocks/recurring-payments/edit.jsx#L381)) as well in this PR and therefore keep the uncommitted WP.com changes in one single diff.

That example turned out to be the only link to the Recurring Payments support docs we have in the block. I created a duplicated version of it removing any Recurring usage and updated the link in 87b9503, so this should be good to merge now.

2020-06-22 17:40 UTC, jeherve approved these changes

2020-06-24 09:12 UTC, merged

2020-07-07 09:30 UTC, jeherve commented
r210097-wpcom