Remove widget sort option for instant search widgets
Automattic/jetpack pull request #16278
Opened 2020-06-24 20:19 UTC by jsnmoon

Fixes #15324.

#### Changes proposed in this Pull Request:
* Removes sort select when configuring Jetpack Search widgets with Instant Search enabled. Default sort order can be set site-wide via #16017 for Instant Search.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Apply this change to your local Jetpack installation.
2. Ensure that you have a Jetpack Search subscription for the site. 
3. Ensure that instant search has been enabled in Jetpack performance settings.
4. Navigate to a Jetpack Search widget in the customizer. 
5. Ensure that the "Default Sort Order" select input has been removed.
6. Try disabling instant search.
7. Repeat steps 4; the "Default Sort Order" select should be restored.
8. Try adding and removing the Jetpack Search widget with instant search enabled. Ensure that the widget behaves as expected.

### Before and After

Before:

<img width="408" alt="Screen Shot 2020-06-24 at 2 17 42 PM" src="https://user-images.githubusercontent.com/4044428/85623401-9c447a00-b625-11ea-9c6a-2d3aacd7b4dd.png">

After:

<img width="408" alt="Screen Shot 2020-06-24 at 2 18 23 PM" src="https://user-images.githubusercontent.com/4044428/85623388-95b60280-b625-11ea-8875-13acb2ab8f7d.png">

#### Proposed changelog entry for your changes:
* None.

2020-06-25 14:05 UTC, gibrown requested changes
never mind... i didn't see the full context...

2020-06-25 14:09 UTC, gibrown approved these changes
Works as expected. Looks good. i need more coffee already apparently...

2020-06-26 18:40 UTC, mdbitz approved these changes
Jetpack Crew Review - Verified Default sort order option not present when Instant Search is enabled.

2020-06-26 18:41 UTC, mdbitz commented
Triggered rebuild of Travis CI as the failure was a timeout.

2020-06-29 16:36 UTC, merged