Setup Wizard: Add Creative Mail Recommendation
Automattic/jetpack pull request #16828
Opened 2020-08-13 15:10 UTC by robertf4

#### Changes proposed in this Pull Request:

This PR adds a recommendation to the Setup Wizard for Creative Mail.

#### Jetpack product discussion

pbtFPC-Hb-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

TODO

#### Proposed changelog entry for your changes:

* Added Creative Mail recommendation.

2020-08-24 20:45 UTC, robertf4 commented
> It worked well. Would it be possible to add an indicator after clicking install to indicate that the plugin is installing?
> 
> The first time I tested, it took just long enough that I was doubting if I clicked it or if it was working.

Good call, I really should have added one to begin with. I've added a spinner in the middle of the install button during install.

2020-08-25 08:34 UTC, jeherve requested changes
This tests well. I only have 2 remarks.

2020-08-25 08:34 UTC, jeherve commented on _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
> +				isPaid: true,
Do we need this here? The plugin is free.

2020-08-25 08:34 UTC, jeherve commented on _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
> +					'https://jetpack.com/support/jetpack-blocks/subscriber-form-block-and-field/',
I've updated this link to be a bit more descriptive.

```suggestion
					'https://jetpack.com/support/jetpack-blocks/form-block/newsletter-sign-up-form/',
```

2020-08-25 08:35 UTC, jeherve approved these changes

2020-08-25 09:01 UTC, merged