Customizer: Disable display of accept cookie banner
Automattic/jetpack pull request #16832
Opened 2020-08-14 00:56 UTC by aaronrobertshaw

Fixes Automattic/wp-calypso#44126

#### Changes proposed in this Pull Request:
* Disable display of "Cookies & Consent" banner widget when in Customizer.

#### Does this pull request change what data or activity we track or use?
No changes. 

_While the cookies banner won't be displayed in Customizer anymore, if the user visits the frontend they'll still get the banner._

#### Testing instructions:
1. Apply this PR branch
2. Ensure you have a theme selected that can add widgets via the Customizer
3. Navigate to the Customizer
4. Either confirm "Cookies & Consent" widget has added or add it now
5. Confirm that the accept cookies banner is not displayed within Customizer
6. Switch to the frontend and confirm that the cookies banner is shown

#### Customizer
<img width="1245" alt="Screen Shot 2020-08-14 at 10 24 34 am" src="https://user-images.githubusercontent.com/60436221/90200856-8cbf0180-de1c-11ea-8aa3-9163c22f2e5e.png">

#### Frontend
<img width="1245" alt="Screen Shot 2020-08-14 at 10 24 39 am" src="https://user-images.githubusercontent.com/60436221/90200850-8af53e00-de1c-11ea-8381-c639ca5b5cdd.png">

#### Proposed changelog entry for your changes:
* Customizer: Disable display of accept cookies banner widget

2020-08-14 00:58 UTC, aaronrobertshaw commented
Related diff for WordPress.com D48127-code

2020-08-14 07:46 UTC, glendaviesnz commented
This tested well for me, before applying PR the cookie dismiss banner displayed in customizer and frontend, and with PR applied it only displayed on front end.

2020-08-14 08:21 UTC, jeherve requested changes
While this works, it makes it impossible to customize the widget. If I'm customizing the look of the widget, changing its text or button, I'd want to see what I'm doing.

Do you think we could still display it when someone is on the Widgets panel of the customizer?

2020-08-19 07:08 UTC, aaronrobertshaw commented
That's a good point regarding the inability to see any customizations made to the widget.

I've been looking into this and feel it should be possible to conditionally display the widget only when someone is on the Widgets panel of the Customizer. Unfortunately, I haven't found the key to solve this yet though.

We can bind on the `expanded` property of the Customizer's `widgets` panel making it easy to detect when we need to show/hide the widget within the preview. If we can trigger the selective refresh for the widget and find a way for it to be aware of whether we are within the Widgets panel or not while rendering, that should achieve the desired outcome. I'm just at a loss as to how to achieve that right now. I'm open to suggestions or better approaches if anyone has one.

```js
wp.customize.panel( 'widgets', function( panel ) {
	panel.expanded.bind( function( isExpanded ) {
		if ( isExpanded ) {
			console.log( 'Display the cookie banner widget' );
		} else {
			console.log( 'Hide the cookie banner widget' );
		}
	} );
} );
```

2020-08-19 07:26 UTC, jeherve commented
Would it be acceptable to always show the widget, but maybe make it clear it's not just a cookie notice but one of your widgets, one that can be edited, maybe with a little pencil icon that would open the widgets panel when clicked?

2020-08-19 09:50 UTC, aaronrobertshaw commented
@jeherve The widget currently gets the pencil icon edit button you mention though it does get partially hidden behind the Customizer's sidebar. I agree making it a more obvious that the widget is editable is probably the way to go. 

Here's a [tiny PR](https://github.com/Automattic/jetpack/pull/16890) to give that edit button a little nudge in the right direction so it sits over the widget itself.

I'll update the [issue](https://github.com/Automattic/wp-calypso/issues/44126) reporting the concern to get some feedback on whether others believe the proposed solution is sufficient.  I'm happy to abandon this PR if that's the case.

2020-08-19 23:09 UTC, aaronrobertshaw commented
After feedback, I'm abandoning this PR in favour of https://github.com/Automattic/jetpack/pull/16890

2020-08-19 23:09 UTC, closed without merging