Update story block buttons, icons and improve accessibility
Automattic/jetpack pull request #16852
Opened 2020-08-15 09:59 UTC by Tug

This PR updates the story block buttons, icons and improve accessibility.

WIP

Addresses part of #16591:
- Finish converting icons and buttons to block editor core components
- Make sure the player is accessible using keyboard shortcuts and VoiceOver
- Display captions under images and videos

#### Changes proposed in this Pull Request:
WIP

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
WIP

#### Proposed changelog entry for your changes:
Improve accessibility on the beta story block

2020-10-01 10:47 UTC, Tug commented on extensions/blocks/story/player/lib/shadow-root.js
> +function useHookWithRefCallback() {
This change is unrelated to this PR though it does improve the code so I'm leaving it here

2020-10-01 14:16 UTC, jeherve requested changes

2020-10-01 14:16 UTC, jeherve commented on extensions/blocks/story/player/components/overlay.js
> +					<DecoratedButton size={ 44 } label="Previous Slide" className="outlined-w">
While we're editing this, it may be good to have those strings translated?

2020-10-01 14:16 UTC, jeherve commented on extensions/blocks/story/player/components/overlay.js
> +					<DecoratedButton size={ 44 } label="Next Slide" className="outlined-w">
Same as above

2020-10-01 14:16 UTC, jeherve commented on extensions/blocks/story/player/player.js
> +				aria-label={ __( 'Play story' ) }
```suggestion
				aria-label={ __( 'Play story', 'jetpack' ) }
```

2020-10-02 02:31 UTC, aforcier requested changes
I don't know enough to do a deep code review, but I looked over everything and tested things.

I did find a few issues I added comments for.

Confirmed that:

✅ Autoplay works correctly (with sound muted) on browsers that disable audio autoplay
✅ Progress bar color is updated
✅ Site title no longer distorted for long titles
✅ Scrolling behavior is fixed for Twentytwenty theme, where it was happening
✅ Progress bar doesn't bleed outside the container anymore for long stories (I think this could use another pass later on though since right now it's just hiding the last few bullets, so it can look like the story is fully viewed when it isn't)
❓ Inspected stories in the Reader and confirmed the link title a11y warning is resolved, though there's an issue with the expand button still (see the comment)

Also tested that things still work correctly in the Reader overall.

I wanted to test this on WP.com just in case but I don't see the usual comment from matticbot with a WP.com diff - did something go wrong?

2020-10-02 04:23 UTC, aforcier commented on extensions/blocks/story/player/slide.js
> +				playVideoWithFallback( mediaRef.current );
I'm seeing an issue where on browsers that need to be muted, it's not possible to unmute the video while it's playing, unless you pause playback first.

I think the cause might be that we're calling this every time the mute button is pressed. If the video is already playing we try to `play()` again, which results in the same error - instead if the video is already playing we shouldn't try `play()` again and just unmute.

2020-10-02 23:20 UTC, aforcier approved these changes
Confirming that the issues I saw are resolved:

* Videos autoplay but muted on devices like iOS Safari that don't allow audio autoplay
* In the above situation, unmuting now works correctly
* The fullscreen icon has the `role=img` tag in the Reader
* The static output is fixed

Things look good from my end, deferring to @jeherve on any more feedback he may have.

2020-10-02 23:36 UTC, aforcier commented
Also following up on this:

> I wanted to test this on WP.com just in case but I don't see the usual comment from matticbot with a WP.com diff - did something go wrong?

I see the reference to p9dueE-wa-p2 now in the checks list. I tried running Fusion manually on this PR and it looks like there's a conflict. Perhaps this PR needs to rebase onto master? cc @Tug

2020-10-07 15:06 UTC, jeherve approved these changes
This tests well for me.

2020-10-08 06:58 UTC, merged