Build: Update vulnerable dependencies
Automattic/jetpack pull request #17074
Opened 2020-09-04 15:41 UTC by brbrr

#### Changes proposed in this Pull Request:

* add yarn resolutions to vulnerable dependencies

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

n/a
#### Testing instructions:

* Not needed. No major version updates for production dependencies

#### Proposed changelog entry for your changes:

* n/a

2020-09-07 15:43 UTC, jeherve approved these changes

2020-09-11 09:32 UTC, jeherve requested changes
This is going to need a rebase. Maybe we can take this opportunity to address p1599816159498100-slack-CBG1CP4EN ?

2020-09-17 12:28 UTC, jeherve approved these changes

2020-09-18 10:20 UTC, merged

2020-09-18 12:23 UTC, brbrr commented
r213857-wpcom