Photon: Fix PHP warning when Photonizing some URLs
Automattic/jetpack pull request #17093
Opened 2020-09-07 14:54 UTC by bisko

#### Changes proposed in this Pull Request:

* Fix an issue where some URLs would generate a PHP warning when trying to replace them with their Photon counterpart. 

#### Jetpack product discussion

N/a

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

The quickest way to test is via `wp shell` on the local Jetpack instance.

If you have a local Jetpack Docker instance: 

* `yarn docker:wp shell --url=http://<your test site URL>`
* Then in the shell context run: 
   ```
   \Jetpack_Photon::filter_the_content("<a href=\"https://test.com/foo.jpg#d\" ><img src=\"http://test.com/8.jpg\"/></a>\n\n\n<a href=\"https://test.com/foo.jpg#d\" ><img src=\"http://i0.wp.com/8.jpg\"/></a>");
   ```
* In the output you should see two photonized image `src` and links (`a href`), similar to:
   ```
   <a href="https://i2.wp.com/test.com/foo.jpg?ssl=1" ><img src="https://i0.wp.com/test.com/8.jpg?w=580" data-recalc-dims="1"/></a>\n
   <a href="https://i2.wp.com/test.com/foo.jpg?ssl=1" ><img src="http://i0.wp.com/8.jpg"/></a>
   ```

If you don't have a local Docker instance:

* Enable Photon
* Try to publish a post with the following content:
   ```
   <a href="https://test.com/foo.jpg#d" ><img src="http://test.com/8.jpg"/></a>
   <a href="https://test.com/foo.jpg#d" ><img src="http://i0.wp.com/8.jpg"/></a>
   ```
* Make sure the output is similar to the Docker case above.

#### Proposed changelog entry for your changes:

* Fix PHP warning when replacing URL with their Photon counterpart

2020-09-07 15:56 UTC, jeherve requested changes
Do you think you could add a test to cover this use-case in `tests/php/test_class.jetpack_photon.php`?

2020-09-09 14:07 UTC, bisko commented on tests/php/test_class.jetpack_photon.php
> +		$this->assertEquals( trim( $expected ), trim( Jetpack_Photon::filter_the_content( $sample_html ) ) );
`trim()` because IDE wants to add a new line at the end of the file, which gets added to the expected results :/

2020-09-09 14:07 UTC, bisko commented
> Do you think you could add a test to cover this use-case in `tests/php/test_class.jetpack_photon.php`?

Thanks for the nudge. Added.

2020-09-10 07:15 UTC, jeherve commented
I rebased to get rid of the unrelated test failures, but the tests are still failing wit the new addition:
https://travis-ci.com/github/Automattic/jetpack/jobs/383091048

2020-09-11 09:27 UTC, bisko commented
> I rebased to get rid of the unrelated test failures, but the tests are still failing wit the new addition:

Fixed both the failing test about this PR, as well as all the failing Photon tests. All should be passing correctly now.

2020-09-11 10:19 UTC, jeherve approved these changes

2020-09-11 10:20 UTC, merged

2020-09-11 10:20 UTC, jeherve commented
Cherry-picked to `branch-8.9` in 0d8a0ae3e0a4cd5db5abe0bdd4899acfff8c582f