Pay with PayPal: Add alternative shortcode output for email notifications
Automattic/jetpack pull request #17180
Opened 2020-09-16 13:37 UTC by mmtr

Part of https://github.com/Automattic/jetpack/issues/17161
Fixes 190-gh-dotcom-manage

#### Changes proposed in this Pull Request:
The `simple-payment` shortcode renders a PayPal button that it's initialized with a JS file. However, that doesn't work when rendered in a emails, so this PR changes the output of the shortcode when used on an email notification. In those cases, we simply display now a textual call-to-action that links to the post so folks can purchase from the website directly.

#### Jetpack product discussion
pbAPfg-OF-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
TBD

#### Proposed changelog entry for your changes:
Pay with PayPal: Add alternative shortcode output for email notifications

2020-09-16 16:32 UTC, jeherve requested changes

2020-09-16 16:32 UTC, jeherve commented on modules/simple-payments/simple-payments.php
> +				'<a href="%1$s" target="_blank">%2$s</a>',
```suggestion
				'<a href="%1$s" target="_blank" rel="noopener noreferrer">%2$s</a>',
```

2020-09-17 11:51 UTC, jeherve reviewed
Would it be possible to find a solution that works for both WordPress.com simple sites and other Jetpack sites out there? In the past, we've implemented things like r213058-wpcom or r171528-wpcom to customize the content of email notifications. Could we do something similar here?

2020-09-17 13:20 UTC, mmtr commented
> Would it be possible to find a solution that works for both WordPress.com simple sites and other Jetpack sites out there?

Maybe the current solution works for both? I think emails subscriptions for Jetpack sites are also sent from async jobs running in WP.com and using the `Subscription_Mailer` class (which is what the `\A8C\Display_context` library needs to determine if a post is being rendered in an email).

Let me double check that and confirm if that's really the case.

2020-09-17 14:01 UTC, mmtr commented
@jeherve I'm trying to confirm the above, but I'm having a hard time finding a way of making the Pay with PayPal block as available. The block requires a Premium plan but it seems that plan is no longer available (there are new plans now: Security and Complete), so the block is never registered. 

I guess the availability of the premium blocks has not been updated yet to take into account the new plans. Is there any way I can force the old plans to appear when upgrading?

2020-09-17 14:09 UTC, jeherve commented
Yes, the new plans make this complicated. We're fixing this in #17177, but cannot merge it just yet because the e2e tests also need fixing to account for the new plans.

To test this I'd recommend using an existing site with a Premium Plan, or adding a Premium plan via Store Admin via your test site.

2020-09-17 15:33 UTC, mmtr commented
I could confirm Jetpack emails subscriptions are sent from WP.com via the `Subscriber_Mailer` class, so this fix should cover both WP.com simple sites and Jetpack sites.

However I couldn't test the fix on a Jetpack site because the email is always sent through an async job from production, where the companion patch D49660-code is not available yet. I tried sandboxing everything (API, setting my sandbox address in `JETPACK__SANDBOX_DOMAIN`) but couldn't find a way of sending the email from my sandbox.

I guess we could merge D49660-code before merging this PR if we really want to verify the fix on a Jetpack site, but that will cause the WP.com/Jetpack codebases to be temporary out of sync.

2020-09-17 15:37 UTC, jeherve commented
> I guess we could merge D49660-code before merging this PR if we really want to verify the fix on a Jetpack site, but that will cause the WP.com/Jetpack codebases to be temporary out of sync.

Do you think we could give it a try? We're blocked from merging here in Jetpack for now anyway, because of the e2e test issues I mentioned earlier.

2020-09-17 20:56 UTC, kwight commented
I've deployed D49660-code, but haven't been able to get an email to show up automatically via production with a newish JN site.

First, I had problems subscribing: I think heavy caching means the JN site doesn't show up under my `https://wordpress.com/following/manage`. I thought I managed to get all the right settings done by API with the developer console (`WP.COM API POST v1.1/read/following/mine/new` and `WP.COM API POST v1.2/read/site/implicit-aardwolf.jurassic.ninja/post_email_subscriptions/new`), but posting a new post hasn't resulted in a subscriber email, so I also haven't truly verified the behaviour we want. FWIW, I was able to use the `send.php` script with that JN site and see what we want, but... not the same. 🤔

2020-09-18 10:32 UTC, mmtr commented
Just confirmed it works 🎉 . This is subscriber email I received after publishing a post in my Jurassic Ninja site:

<img width="655" alt="Screen Shot 2020-09-18 at 12 22 37" src="https://user-images.githubusercontent.com/1233880/93587159-bd5d0280-f9a9-11ea-8a12-2d842dfb697b.png">

Testing instructions for Jetpack sites:
- [Spin a JN site running this branch](http://jurassic.ninja/create/?jetpack-beta&branch=fix/pay-with-paypal-fallback-context).
- Set up Jetpack and continue using the Free plan.
- Add a Jetpack Premium to the JN site plan through Store Admin.
- Subscribe to the site using the [Subscriptions module](https://jetpack.com/support/subscriptions/):
  - Go to Jetpack > Settings > Discussion.
  - Activate the "Let visitors subscribe to new posts and comments via email" option.
  - Visit an already published post (the "Hello World!" post automatically created by JN is fine).
  - Subscribe to the site by leaving a comment and checking the "Notify me of new posts by email." option.
  - Confirm the subscription by clicking on the confirmation email you've received.
- Publish a post that contains a Pay with PayPal block.
- Check the email subscription and make sure it contains a "Visit the site to purchase" link replacing the non-functional PayPal button.

2020-09-18 14:50 UTC, jeherve approved these changes

2020-09-18 15:25 UTC, merged