Blocks: switch all blocks to be registered using new package
Automattic/jetpack pull request #17263
Opened 2020-09-25 11:54 UTC by jeherve

#### Changes proposed in this Pull Request:

* Following #17167, we can now switch all blocks to use the method introduced in the Blocks package.
* We can also deprecate the old method.
* There were old registration methods in `Jetpack_Gutenberg` that have been deprecated for more than a year already, and are not used in Jetpack anymore. I've removed them for good.
* I've updated the template used when creating new blocks via WP Cli, so it uses the new method as well.

#### Jetpack product discussion

* See Primary issue: #17099 

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Go to Posts > Add New
* In your browser console, check `Jetpack_Editor_Initial_State.available_blocks`: it should return all expected blocks, and no errors should appear in your logs.
* Tests should pass.
* You should be able to use blocks just like before.

#### Proposed changelog entry for your changes:

* N/A

2020-09-28 13:32 UTC, fgiannar approved these changes
Nice work! Tested using the instructions and works as expected 👍

2020-09-29 16:16 UTC, jeherve commented
@fgiannar Do you think you could give it another look? I had to rebase following a8b9e2eda97b7d7828697aee9e0dd09a79dd5f92.

Thank you!

2020-09-29 18:21 UTC, anomiex requested changes
Looks good to me other than one doc mistake.

2020-09-29 18:21 UTC, anomiex commented on class.jetpack-gutenberg.php
> + * @deprecated 9.1.0 Use Automattic\\Jetpack\\Blocks::Blocks::jetpack_register_block instead
Too many "Blocks" in there.
```suggestion
 * @deprecated 9.1.0 Use Automattic\\Jetpack\\Blocks::jetpack_register_block instead
```

2020-09-30 19:23 UTC, anomiex approved these changes
LGTM. Basic manual testing as suggested also seemed ok, although I didn't get too in depth with it.

2020-10-01 07:38 UTC, merged

2020-10-06 07:39 UTC, jeherve commented
r214736-wpcom