Added an additional GET parameter to profile sandbox requests.
Automattic/jetpack pull request #17297
Opened 2020-09-29 10:32 UTC by zinigor

The additional constant enables adding an XDEBUG_PROFILE constant to all sandbox requests to allow for easier profiling.

#### Changes proposed in this Pull Request:
* An additional constant added that sends an extra GET parameter with all sandbox requests.

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No tracking changes.

#### Testing instructions:
* Sandbox your Jetpack installation using the `JETPACK__SANDBOX_DOMAIN` constant.
* Enable Xdebug on your sandbox using `sudo xdebug enable`.
* Define the constant in a separate file that's loaded before jetpack
```
//define( 'JETPACK__SANDBOX_PROFILE', true );
```
* Create a post using a CLI command:
```
wp post generate --count=1
```
* Observe the sync request in the output log. Note that the URL listed in the output will be the original one, not the sandboxed one, so it will not have the profile parameter added.
* Observe a cachegrind output file in your sandbox `/tmp` folder. Be careful, these can be quite large.

#### Proposed changelog entry for your changes:

*

2020-09-29 10:42 UTC, jeherve requested changes, later dismissed
Do you think you could add some documentation explaining how this could be used? Maybe here? 
https://github.com/Automattic/jetpack/blob/95b9ac43f162f85adc396f45c59035ed7f0525b8/docker/README.md#L435

2020-09-29 10:42 UTC, jeherve commented on _inc/jetpack-server-sandbox.php
> +			l( 'WEHERE' );
```suggestion
```

2021-12-13 19:53 UTC, leogermani commented
> Do you think you could add some documentation explaining how this could be used? Maybe here?
> 
> https://github.com/Automattic/jetpack/blob/95b9ac43f162f85adc396f45c59035ed7f0525b8/docker/README.md#L435

Added

2021-12-15 10:03 UTC, vitozev reviewed
I did some functional tests and everything is working as expected, all the requests under monitoring went through my sandbox, and `cachegrind.out.*` profiling files were generated. Nice job!

2022-01-14 22:40 UTC, kraftbj submitted a review, later dismissed

2022-01-17 17:06 UTC, kraftbj approved these changes, later dismissed

2022-01-17 17:18 UTC, kraftbj approved these changes

2022-01-17 17:31 UTC, merged