WhatsApp Button: Fix incorrect button text color
Automattic/jetpack pull request #17311
Opened 2020-09-29 21:37 UTC by apeatling

When the WhatsApp button block is added to a parent block with a set text color it can on certain themes (Mayland as an example) override the fixed button text color. To avoid this the text color is now set inline so it cannot be overridden by strong styles on any parent block.

See: https://github.com/Automattic/view-design/issues/82

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Activate the Mayland theme
* Insert a Group block and set the text color to red
* Insert a WhatsApp Button block inside the group block and confirm that the text in the button is not read
* Confirm the same is true on the front end of the site.

#### Proposed changelog entry for your changes:

* Fixed issue with WhatsApp button where the incorrect text color would be used.

2020-09-29 23:07 UTC, glendaviesnz approved these changes, later dismissed
This tested well for me - correct colour display in editor and frontend regardless of group background setting

2020-09-30 05:54 UTC, jeherve requested changes
Since we're making changes to the save function, we'll need to add deprecation to the block to avoid block validation issues.

2020-09-30 17:47 UTC, apeatling commented
Rebased and added deprecation function. :+1:

2020-10-01 16:30 UTC, jeherve reviewed
When trying to edit an existing post (that was created in Jetpack 8.9.1) after switching to this branch, the block editor appears to fail, and I get the following JS error:

```
Uncaught (in promise) TypeError: Cannot read property 'countryCode' of undefined
```

```
var t, n = e.attr, r = e.className, o = n.countryCode, i = n.phoneNumber, l = n.firstMessage, s = n.colorClass, u = n.buttonText, p = n.backgroundColor, d = n.openInNewTab ? "_blank" : "_self", m = o && i ? o.replace(/\D+/g, "") + i.replace(/\D+/g, "") : "", b = w()(r, s ? "is-color-" + s : void 0, u.length ? void 0 : "has-no-text");
```

Are you able to reproduce this error?

2020-10-01 17:28 UTC, apeatling commented
@jeherve I didn't see that one, but let me try reproducing with the same environment.

2020-10-05 18:53 UTC, apeatling commented
Fixed.

2020-10-08 14:16 UTC, jeherve approved these changes
This tests well for me. 🚢

2020-10-08 15:04 UTC, merged

2020-11-10 10:25 UTC, jeherve commented
r216550-wpcom