External Media: Remove lodash dependency to fix js error
Automattic/jetpack pull request #17312
Opened 2020-09-29 22:14 UTC by creativecoder

Fixes #17289

#### Changes proposed in this Pull Request:

Just testing for now.

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

*

2020-10-07 23:05 UTC, creativecoder commented
Related PR: https://github.com/Automattic/wp-calypso/pull/46252

2020-10-26 03:33 UTC, creativecoder commented
Note that https://github.com/Automattic/wp-calypso/pull/46252 is merged, but the `@automattic/calypso-build` package still needs a release for the changes to be available through npm.

I've updated the description and marked this ready for review.

2020-10-26 03:57 UTC, creativecoder commented
PR for the update to `@automattic/calypso-build`

2020-10-26 16:52 UTC, jeherve commented
Noting that we won't be able to update `calypso-build` just yet, even when a 6.4.0 becomes available. We'll need to fix the issues that prevent us from updating to 6.3.0 first:
https://github.com/Automattic/jetpack/pull/16845

2020-10-27 20:52 UTC, creativecoder commented
> Noting that we won't be able to update calypso-build just yet

Ugh.. okay good to know. I'm wondering if we should prioritize that sooner rather than later given the severity of the related bug (https://github.com/Automattic/jetpack/issues/17289)

2020-11-04 14:33 UTC, jeherve commented
> yarn link the @automattic/calypso-build package from wp-calypso package you have locally to a local Jetpack development environment

How did you get this to work? I get the following message when I give this a try:

```
yarn link @automattic/calypso-build
yarn link v1.22.10
error No registered package found called "@automattic/calypso-build".
```

2020-11-05 23:11 UTC, creativecoder commented
> How did you get this to work?

@jeherve my process was

From packages/calypso-build directory in wp-calypso repo, run `yarn link` (note that you may first need to `yarn unlink` if you've done this previously). You should see a message

```
success Registered "@automattic/calypso-build".
info You can now run `yarn link "@automattic/calypso-build"` in the projects where you want to use this package and it will be used instead.
```

From jetpack repo root, run `yarn link "@automattic/calypso-build"`. You should see

```
success Using linked package for "@automattic/calypso-build".
```

2021-01-14 17:15 UTC, jeherve commented
Noting that this will also be fixed in Core, as per this PR:
https://github.com/WordPress/gutenberg/pull/27985

2021-05-25 19:51 UTC, creativecoder commented
Noting that this PR is still blocked by required upgrade of `calypso-build`. Most recent PR for that upgrade is https://github.com/Automattic/jetpack/pull/19374.

2021-06-10 12:14 UTC, jeherve commented
> Noting that this PR is still blocked by required upgrade of `calypso-build`. Most recent PR for that upgrade is #19374.

The update is now complete. 🎉

2021-06-10 12:14 UTC, jeherve requested changes
Do you think you could rebase, now that the Calypso build update is merged?

2021-06-10 17:18 UTC, creativecoder commented
This should now be ready to go

2021-06-11 15:10 UTC, merged

2021-06-11 16:37 UTC, creativecoder commented
wpcom-r227168