Replaced strval() with type casting (string) as part of issue #17432.
Automattic/jetpack pull request #17438
Opened 2020-10-09 14:22 UTC by annafoldvari

Fixes #

#### Changes proposed in this Pull Request:

* Replaced strval() with type casting (string) as part of issue #17432.

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

* Replaced strval() with type casting (string) as part of issue #17432.

2020-10-14 23:21 UTC, kbrown9 approved these changes
Thanks for the PR! 

This looks good to me. I manually tested by doing things that would run through the code changes (made XMLRPC requests, enabled the Protect module, viewed a Contact Form), and everything worked as expected.

2020-10-15 11:19 UTC, jeherve approved these changes

2020-10-15 11:23 UTC, jeherve requested changes

2020-10-15 11:23 UTC, jeherve commented on tests/php/modules/contact-form/test-class.grunion-contact-form.php
> +			'post_author' => (string) $author_id
This will cause issues with our linter:

```suggestion
			'post_author' => (string) $author_id,
```

2020-10-15 11:23 UTC, jeherve approved these changes

2020-10-15 11:27 UTC, jeherve commented
Internal reference: r215260-wpcom

2020-10-15 11:34 UTC, merged