Replaced intval() with (int) as part of issue #17432.
Automattic/jetpack pull request #17435
Opened 2020-10-09 12:52 UTC by annafoldvari

Fixes #17432.

#### Changes proposed in this Pull Request:

* Intval() functions replaced with type cast(int)

#### Proposed changelog entry for your changes:

* Intval() functions replaced with type cast(int)

2020-10-13 15:07 UTC, jeherve requested changes
Thanks for your contribution. I'd recommend some small changes.

2020-10-13 15:07 UTC, jeherve commented on packages/sync/src/modules/class-term-relationships.php
> +		if ( (int) $count === 0 ) {
Since we're touching that line, let's use Yoda conditions here:

```suggestion
		if ( 0 === (int) $count ) {
```

2020-10-13 15:07 UTC, jeherve commented on packages/sync/src/class-actions.php
>  				$schedule
Indenting seems to be off on this one:

```suggestion
		return (int) apply_filters(
			'jetpack_sync_cron_start_time_offset',
			$start_time_offset,
			$hook,
			$schedule
```

2020-10-13 15:07 UTC, jeherve commented on packages/sync/src/class-actions.php
> +			);
```suggestion
		);
```

2020-10-13 15:07 UTC, jeherve commented on packages/connection/src/class-manager.php
> +		$code_type = (int) ($code / 100);
We'll need spaces inside the parenthesises:

```suggestion
		$code_type = (int) ( $code / 100 );
```

2020-10-15 14:46 UTC, annafoldvari commented
Sorry I was away for a few days. It looks like all the issues have been resolved. Is there anything you would like me to do for this PR?

2020-10-15 16:04 UTC, jeherve commented
> It looks like all the issues have been resolved. Is there anything you would like me to do for this PR?

I just pushed 6bf606f26decfc6a90a33298bd0b7e39299ee94c to address some linting issues that would stop us from merging this.

2020-10-15 17:38 UTC, jeherve commented
Internal reference: D51191-code

2020-10-19 12:26 UTC, jeherve approved these changes
This looks good. Merging.

2020-10-19 12:27 UTC, merged

2020-10-19 12:43 UTC, jeherve commented
Internal reference: r215404-wpcom