Replaced floatval() with type cast (float) as part of issue #17432.
Automattic/jetpack pull request #17439
Opened 2020-10-09 14:36 UTC by annafoldvari

Fixes #

#### Changes proposed in this Pull Request:

* Replaced floatval() with type cast (float) as part of issue #17432.

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

* Replaced floatval() with type cast (float) as part of issue #17432.

2020-10-14 22:03 UTC, kraftbj submitted a review, later dismissed
Looks good.

2020-10-15 00:31 UTC, kbrown9 approved these changes
The changes look good to me! I manually tested a few of them (heartbeat, simple payments, presentations, and sync) and everything worked as expected. Thanks for fixing these!

2020-10-15 11:10 UTC, jeherve requested changes
This looks good. I only have minor comments about linting errors that will trip our pre-commit hooks.

2020-10-15 11:10 UTC, jeherve commented on class.json-api-endpoints.php
> +<p><strong>This endpoint is deprecated in favor of version <?php echo (float) $this->new_version ; ?></strong></p>
```suggestion
<p><strong>This endpoint is deprecated in favor of version <?php echo (float) $this->new_version; ?></strong></p>
```

2020-10-15 11:10 UTC, jeherve commented on modules/custom-css/custom-css/preprocessors/lessc.inc.php
> +				$val = isset($val[1]) ? (float) $val[1] : 0;
```suggestion
				$val = isset( $val[1] ) ? (float) $val[1] : 0;
```

2020-10-15 11:11 UTC, jeherve approved these changes

2020-10-15 11:15 UTC, jeherve commented
Internal reference: r215258-wpcom

2020-10-15 11:24 UTC, merged