Translatable aria-label for image compare block slider
Automattic/jetpack pull request #17501
Opened 2020-10-16 14:04 UTC by scottsweb

Adds an `aria-label` to the image compare block control so it is read by screen readers. 

I am a little concerned that existing blocks will show an invalid HTML/block recovery error due to this change, so feedback welcome on that.

Fixes #17278

#### Changes proposed in this Pull Request:

* Introduce `aria-label` on slider of image compare block

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* Pull down this PR
* Insert a new image compare block
* Test it with a screen reader in both the editor and front end
* Test an older image compare block if you have one

#### Proposed changelog entry for your changes:

* A11y improvements to image compare block

2020-10-16 14:12 UTC, scottsweb commented
![Screenshot 2020-10-16 at 16 11 49](https://user-images.githubusercontent.com/411945/96269179-50e61b00-0fca-11eb-977f-58b448f71bbc.png)

Example of issue for existing blocks.

2020-10-16 18:45 UTC, anomiex commented
I don't have an actual screenreader, but I see the `aria-label` property is being set on the control in some quick testing.

I don't know much about blocks yet, but I found https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/ that might help you with dealing with old versions in a better manner. I see a few other Jetpack blocks are already using that mechanism.

Also, one thing I'm curious about: why are you saving the text as part of the block and then reading it out again in view.js, instead of just doing `this.controller.setAttribute( 'aria-label', __( 'Slide to compare images.', 'jetpack' ) );` in view.js? Do you intend to let the author edit it at some point, or is there some other constraint I'm not aware of (which is very probable, please educate me)?

2020-10-19 07:42 UTC, jeherve requested changes
Block deprecations would indeed be the way to go here. However, it is worth considering that introducing translatable strings in saved content can cause some issues when switching languages on a site. You can learn more about this here: #15776

We should probably avoid this approach here if possible.

2020-10-19 08:47 UTC, scottsweb commented
Thanks for the pointers. I was stuck in the old model of passing a translated string from PHP into JS on the front end. This is now hugely simplified and applied to the render of the block only (works on both front and backend). It no longer throws a block error or invalid content for existing blocks either.

2020-10-19 14:04 UTC, anomiex submitted a review, later dismissed
LGTM.

2020-10-19 16:53 UTC, jeherve requested changes
While this will work, it will also increase the size of the `view.js` file that will be enqueued on all posts / pages where an Image Compare block is added. I wonder if it may not be best to take a different approach (like we discussed earlier) so we do not have to load `i18n` on the frontend of the site.

2020-10-19 18:00 UTC, anomiex commented
> I wonder if it may not be best to take a different approach (like we discussed earlier) so we do not have to load `i18n` on the frontend of the site.

Maybe I missed something, but I don't see any discussion of an alternative to the current approach yet. The PR originally did the wrong thing that #15776 was about, but now it's doing something different.

2020-10-19 18:04 UTC, jeherve commented
Sorry, I should have been clearer. Here are two examples: #16361 #17256

2020-10-19 20:01 UTC, anomiex commented
> Sorry, I should have been clearer. Here are two examples: #16361 #17256

Neither of those seems to really match what's going on here.

* #16361 removed the saving of default i18n strings, but in that case it was taking advantage of the shortcode's output using those defaults anyway. Its view.js only imports some CSS.
* For #17256, it seems not to have been saving i18n strings in the first place. The PR was about replacing the saved output with something that would by default be suitable for an email or the like, with a render_callback used to completely replace that in the website context.

But I think I get the idea. Is the suggestion to have the render_callback inject the i18n strings somehow where view.js can pick them up? I think the simplest way to do that for this case where the i18n is needed only in view.js would be to just call `wp_localize_script()` right after the call to `Jetpack_Gutenberg::load_assets_as_required()`?

2020-10-20 09:40 UTC, scottsweb commented
`wp_localize_script` isn't really an option here either as we do not enqueue any other assets as part of this block. My current thinking is to do something similar to `wp_localize_script` in `wp_head` or `wp_footer`, outputting a translated string from PHP, then having `view.js` grab that.

2020-10-20 09:51 UTC, scottsweb commented
Just pushed a demo of the approach described above, doesn't feel overly great but seems to work.

2020-10-20 14:18 UTC, anomiex commented
> `wp_localize_script` isn't really an option here either as we do not enqueue any other assets as part of this block.

The call to `Jetpack_Gutenberg::load_assets_as_required()` ([here](https://github.com/Automattic/jetpack/blob/37164e84ac0bd4d15ce4754d5f7bd332d9fadc86/extensions/blocks/image-compare/image-compare.php#L40)) calls `Jetpack_Gutenberg::load_scripts_as_required()` which calls `wp_enqueue_script()` to enqueue view,js, that's how view.js gets loaded.

2020-10-22 16:18 UTC, jeherve commented
> For #17256, it seems not to have been saving i18n strings in the first place. 

This specific commit may be more helpful:
https://github.com/Automattic/jetpack/commit/1dfc48f3e7416fac315aca77ae8c0c8a366b0aa8

Basically, we save the string as a default attribute of the block offered in your language when inserting the block, and saved in the post content as you add the block to your post / page. On the frontend, all the block does is displaying the content that was saved in the database. No translation happens on the fly on the frontend anymore, neither on the fly when saving or updating the block contents to the database.

Does this clarify things a bit?

2020-10-23 09:33 UTC, scottsweb commented
Happy to take another look. I got the impression from @anomiex that he had figured it all out and was going to take over the fix.

2020-10-23 13:47 UTC, anomiex commented
> Happy to take another look. I got the impression from @anomiex that he had figured it all out and was going to take over the fix.

I can if you want me to. But I wasn't trying to steal it from you, I was just trying to understand things, and help out by explaining things I did think I understand.

2020-10-23 15:19 UTC, scottsweb commented
That would be great @anomiex - I had a look at the latest example and it doesn't make sense to me that the translated string becomes part of the save.js file. I feel like the string should be part of the UI only, not the content. Block development is still new to me also so I may just have it all wrong.

2020-10-23 16:03 UTC, jeherve commented
> I feel like the string should be part of the UI only, not the content.

Right, that would be an option, but it would mean either loading `@wordpress/i18n` on the view.js file which is not ideal for the size of that file, or passing the string from PHP to JS, which can get a bit messy. By saving it as an attribute, all the work is done beforehand.

2020-10-23 17:58 UTC, anomiex commented
On the down side, saving it as an attribute means the i18n happens at the time the post is edited, rather than when the post is viewed. If the language is later changed or the i18n is updated, the post won't pick up the changed value. Or at least that's how it seems from looking at what happens with the simple-payments block. In that case they seem to want the text to be customizable by the post author so an attribute is necessary, but that seems unneeded here.

And in this case you'd still be passing the string from PHP to JS, you'd just be embedding it in the HTML as a data attribute instead of setting it more directly in a `<script>` tag.

2020-10-23 18:04 UTC, jeherve commented
> If the language is later changed or the i18n is updated, the post won't pick up the changed value.

Right, exactly.

2020-10-26 18:03 UTC, jeherve approved these changes

2020-10-27 09:20 UTC, merged

2020-10-27 09:22 UTC, scottsweb commented
Thanks for the assistance!

2020-10-27 11:28 UTC, jeherve commented
@scottsweb You should now be able to commit the WordPress.com counterpart. 👍

2020-10-28 10:33 UTC, scottsweb commented
r215957-wpcom