Instant Search: add role and label to dialog
Automattic/jetpack pull request #17574
Opened 2020-10-22 02:26 UTC by bluefuton

Part of https://github.com/Automattic/jetpack/issues/17554.

#### Changes proposed in this Pull Request:

* Add the role `dialog` to the Instant Search overlay and include a title that is only visible to screen readers.

A good reference: https://bitsofco.de/accessible-modal-dialog/.

#### Jetpack product discussion

Part of the Jetpack Search Product Quality project: p9xfpQ-12j-p2.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Apply this patch to your site with Jetpack Search enabled.
* Verify that the overlay has the correct `role` and `aria-labelledby` attributes applied.

#### Proposed changelog entry for your changes:

* Instant Search: accessibility improvements for the search overlay.

2020-10-26 20:45 UTC, jsnmoon commented
This needs a rebase -- `instant-search.scss` was deprecated when we [configured Webpack to build our stylesheets](https://github.com/Automattic/jetpack/pull/17574). Its replacement is here: https://github.com/Automattic/jetpack/blob/master/modules/search/instant-search/components/search-app.scss

2020-10-27 11:37 UTC, jeherve requested changes

2020-10-27 11:37 UTC, jeherve commented on modules/search/instant-search/components/overlay.jsx
> +				{ __( 'Search results' ) }
```suggestion
				{ __( 'Search results', 'jetpack' ) }
```

2020-10-27 11:41 UTC, jeherve approved these changes

2020-10-27 12:46 UTC, merged