Test Embed API: Update resolve-redirect route
Automattic/jetpack pull request #17578
Opened 2020-10-22 11:58 UTC by pablinos

While testing on a local dev site I noticed that the resolve-redirect
API call was being 301 redirected and would then fail as the `//` in the
URL parameter was being switched to a single `/`.

After a lot of debugging, I discovered that it was Cloudflare that was
seeing a URL like
`https://test.com/wp-json/wpcom/v2/resolve-redirect/https://calendly.com`
as invalid, and redirecting to a sanitised version.

#### Changes proposed in this Pull Request:

The solution was to make the URL parameter in the path optional, so that
it could be passed as a query parameter.

This change implements that so the old style of calling the endpoint will still work, but also we can swap to using a more
conventional URL format.

#### Does this pull request change what data or activity we track or use?
N/A

#### Testing instructions:

* Insert a calendly block
* Add a URL like https://calendly.com/paul-bunkham
* Click on the embed, and check that you don't get an error, and that the block can be previewed.

#### Proposed changelog entry for your changes:
Not sure one is required but maybe:
* Updated the `resolve-redirect` API endpoint so the `url` value can be passed as a query parameter.

2020-10-22 19:44 UTC, allilevine commented
I'm seeing this error on a premium Simple site with the patch applied:
<img width="670" alt="Screen Shot 2020-10-22 at 3 34 47 PM" src="https://user-images.githubusercontent.com/1689238/96922049-55547d00-147d-11eb-83c2-2c38752626cc.png">

The block embedded and loaded correctly on a self-hosted Jetpack site.

2020-10-26 20:08 UTC, allilevine requested changes
I rebased the patch but I'm still seeing that same error on premium simple sites. 🤔

2020-10-26 23:19 UTC, pablinos commented
Thanks for testing it @allilevine. I was having trouble applying the patch, so I gave it another rebase. I don't know if that fixed it, but it's working for me. Do you have the API sandboxed? I realise I should have put that in the testing instructions. Sorry!

2020-10-27 10:17 UTC, retrofox commented
Maybe I'm missing something but it works as expected to me, right now, without applying these changes.

<img src="https://user-images.githubusercontent.com/77539/97288235-59d5b880-1824-11eb-9c98-232a6b39da68.png" width="400px" />


**Simple site**
<img src="https://user-images.githubusercontent.com/77539/97287620-91903080-1823-11eb-8d03-8f83636cbfe3.png" width="500px" />

**Paid Simple site**
<img src="https://user-images.githubusercontent.com/77539/97287715-ac62a500-1823-11eb-9282-822a26e8436c.png" width="500px" />

**Atomic site**
<img src="https://user-images.githubusercontent.com/77539/97287966-fb103f00-1823-11eb-94ed-4bc37303026c.png" width="500px" />

2020-10-27 12:01 UTC, retrofox commented
> I'm seeing this error on a premium Simple site with the patch applied:

The problem arises when applying these changes partially (only client-side changes). If I try to test these changes compiling these files, instead of applying the patch for instance, I get the same issue.

2020-10-27 12:08 UTC, retrofox reviewed
LGTM. I suggest getting another 👀 here before to merge if it's possible.

@allilevine could you try to check that it works as expected?

2020-10-27 12:13 UTC, retrofox commented
Tested with EventBrite and it works well, too.

<img src="https://user-images.githubusercontent.com/77539/97300044-a88b4e80-1834-11eb-9fb7-e6682211a0bc.png" width="500px" />

2020-10-27 13:34 UTC, allilevine submitted a review, later dismissed
> Thanks for testing it @allilevine. I was having trouble applying the patch, so I gave it another rebase. I don't know if that fixed it, but it's working for me. Do you have the API sandboxed? I realise I should have put that in the testing instructions. Sorry!

Yep, I missed that. 🤦‍♀️ I sandboxed the API and now I don't see that error on simple sites.

2020-10-27 18:30 UTC, leogermani submitted a review, later dismissed
I could not really reproduce the error without this branch, but I can confirm it works after the changes, and the code looks clean. Also, there doesn't seem to be any potential backward compatibility issue.

2020-10-29 19:33 UTC, pablinos commented
> I could not really reproduce the error without this branch

Thanks @leogermani! It is a very specific case. My test site is tunnelled through Cloudflare, and that is 'correcting' the URL. I think this could be an issue for other sites that are using Cloudflare for DNS/caching.

2020-10-30 21:57 UTC, kraftbj approved these changes

2020-10-30 22:17 UTC, merged