Updated PHPCS: Modules, endpoints, and general files
Automattic/jetpack pull request #17619
Opened 2020-10-26 21:47 UTC by kraftbj

After #17406, updated the "requiredlist" files to match new PHPCS rules for packages and the debugger.

#### Changes proposed in this Pull Request:
* PHPCS

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
n/a

#### Proposed changelog entry for your changes:
* n/a

2020-10-26 21:48 UTC, kraftbj commented
After 9.1 branches off and #17406 merges, we need to update base branch to `master`, then this can be merged.

2020-10-27 18:15 UTC, anomiex commented
> After 9.1 branches off and #17406 merges, we need to update base branch to `master`, then this can be merged.

Once #17406 merges and its branch is deleted, Github will automatically set the base branch to master (or whatever we're calling it by then).

2020-10-27 18:42 UTC, anomiex submitted a review, later dismissed
Looks sane to me.

Of the files in this patch currently listed by Fusion as not being in sync and where we're removing `use` statements,

* _inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php reports no diff.
* modules/search/class-jetpack-instant-search.php shows no uses of those `use`s in the diff.
* modules/shortcodes/instagram.php reports no diff.

2020-10-28 13:52 UTC, anomiex requested changes
Needs a manual rebase after #17595. Otherwise should be good.

2020-10-28 16:04 UTC, anomiex approved these changes

2020-10-28 16:04 UTC, anomiex commented on modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
> -
Lost a newline here in the rebase. Probably doesn't matter.

2020-10-28 16:08 UTC, sergeymitr approved these changes

2020-10-28 18:55 UTC, merged

2020-10-28 18:56 UTC, kraftbj commented
r216013-wpcom