Alignment of delte_batch_metadata function
Automattic/jetpack pull request #17615
Opened 2020-10-26 18:28 UTC by mdbitz

Addition of post-trashed status and cleanup of cases. Introduces a new reset_deleted_metadata_mapping that can be used by extending classes to have custom cache deletion logic.

#### Changes proposed in this Pull Request:
* N/A - Cleanup of technical debt.

#### Does this pull request change what data or activity we track or use?
- NO

#### Testing instructions:

* On Master perform the following:
* Create several new posts that have a meta entry for new key "my-key".
* Open wp shell and execute
* `$store = new \Automattic\Jetpack\Sync\Replicastore();`
* `$store->delete_batch_metadata('post', [ Post IDs ], "my-key");
* Verify the meta was removed.
* Apply this PR / checkout branch
* Repeat the same steps

#### Proposed changelog entry for your changes:
* Jetpack Sync : Update of Replicastore functions with enhancements from WordPress.com implementation.

2020-10-29 16:09 UTC, anomiex requested changes

2020-10-29 22:53 UTC, mdbitz commented on packages/sync/src/class-replicastore.php
> +	private function reset_deleted_metadata_mapping( $type, $object_id ) {
Thanks, oversight on my end I was simply pulling the diff across vs thinking through usage. I should know better than to code while helping the kids with school :)

2020-10-29 23:00 UTC, mdbitz commented on packages/sync/src/class-replicastore.php
> +		$meta_key             = esc_html( $meta_key );
We allow for users to extend the meta allow list to any value. This is a precaution we needed to take on WP.com as it was causing issues during various down stream functionality. As this doesn't interact with site data there is no impact to remote sites, instead if a meta key had html in it they would simply be stored with a modified key on the replicastore.

2020-10-30 16:05 UTC, anomiex commented on packages/sync/src/class-replicastore.php
> +		$meta_key             = esc_html( $meta_key );
I'd still say that escaping before inserting into the DB is an antipattern. But I don't know anything about those downstream uses, so I won't try to block on it.

I note that if there are any existing meta keys that actually will get escaped, this won't delete existing unescaped versions anymore.

2020-11-09 14:41 UTC, mdbitz commented
Thinking about this more and the down stream implementation can be further modified. Going to close for now and revisit.

2020-11-09 14:41 UTC, closed without merging