Pay With PayPal: Handling price value
Automattic/jetpack pull request #17660
Opened 2020-10-29 20:39 UTC by retrofox

This PR handles negative values in the front-end when the block is dynamically rendered. 

Fixes https://github.com/Automattic/jetpack/issues/17641

#### Changes proposed in this Pull Request:

* Pay With PayPal: Handling error when the price gets a negative value.

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to create/edit a post/page/whatever
* Add a `Pay With PayPal` block
* Set a negative value for the price

<img src="https://user-images.githubusercontent.com/77539/97628715-d5de2500-1a0b-11eb-9434-da06759f0898.png" width="500px" />

* Save the post
* Go to the front-end page

**before**
Confirm to attempt to purchase the product, PayPal returns a 500 and the frontend displays `“We are sorry, there was a configuration problem. Please contact the site owner. Error:SP17”.` [issue](https://github.com/Automattic/jetpack/issues/17641)

**after**

* if the user is not logged id, the block doesn't render anything
* if the user is logged in, and it an admin, the block renders with some errors:

<img src="https://user-images.githubusercontent.com/77539/97628816-fdcd8880-1a0b-11eb-8803-3d532d5d7ade.png" width="500px" />

#### Proposed changelog entry for your changes:

* Pay With PayPal: Handling price negative error in the front-end.

2020-10-30 10:15 UTC, jeherve reviewed
I'm wondering if we should take this opportunity to handle display of the block for any kind of error. See this report for example:

p8oabR-za-p2#comment-4761

2020-10-30 10:15 UTC, jeherve commented on extensions/blocks/simple-payments/simple-payments.php
> +	}
Maybe we could take advantage of `Jetpack_Gutenberg::notice()` to display those errors?
https://github.com/Automattic/jetpack/blob/ebec0a8fb35ffac4766cce36646ebf01c5d56063/class.jetpack-gutenberg.php#L960-L971

2020-10-30 11:55 UTC, jeherve commented
> I'm wondering if we should take this opportunity to handle display of the block for any kind of error. See this report for example

I got one more piece of feedback about this:

> One thing to keep in mind is that if I click outside the block, without setting it up, everything turns red. While I understand that I need to set it up, I wonder if we could have a state that just says the block hasn’t been set up?

Maybe this could be handled here as well? What do you think?

------

p8oabR-za-p2#comment-4729

2020-11-02 15:18 UTC, kwight commented
Can we just not allow a negative value for this field?

2021-04-23 12:12 UTC, jeherve requested changes
This will now need a rebase before it can be reviewed. If that PR is not something you're working on anymore, maybe we could close it?

2021-04-23 13:14 UTC, retrofox commented
> This will now need a rebase before it can be reviewed. If that PR is not something you're working on anymore, maybe we could close it?

Yes. I saw we already did some enhancements in this block so rebasing and updating could get even trickier than start the fix from the scratch. Thanks for the ping.

2021-04-23 13:14 UTC, closed without merging