Pinterest: Fix typo in Pinterest URL regex
Automattic/jetpack pull request #17683
Opened 2020-11-02 05:20 UTC by aaronrobertshaw

#### Changes proposed in this Pull Request:
* Fix typo in URL validation regex preventing rendering Pinterest block on frontend.

#### Does this pull request change what data or activity we track or use?
No changes.

#### Screenshots

| Before | After |
|--------|------|
| <img width="981" alt="Screen Shot 2020-11-02 at 3 17 34 pm" src="https://user-images.githubusercontent.com/60436221/97832507-b5211280-1d1e-11eb-9ca7-d4c431141319.png"> | <img width="982" alt="Screen Shot 2020-11-02 at 3 18 00 pm" src="https://user-images.githubusercontent.com/60436221/97832517-bb16f380-1d1e-11eb-9d15-8b9629309305.png"> |

#### Testing instructions:
1. Create a new post
2. Add Pinterest block with following URL: https://in.pinterest.com/pin/412220172147844842/
3. Save post
4. View post on frontend and confirm no Pinterest block is rendered
5. Apply this PR
6. Reload the post on the frontend and confirm the Pinterest block now displays
7. For bonus points, add additional Pinterest blocks using `www` or alternative locale subdomain based URLs and ensure correct display

#### Proposed changelog entry for your changes:
* Fix Pinterest URL validation bug preventing rendering on frontend

2020-11-02 10:41 UTC, jeherve requested changes
Good catch!

Do you think you could add some unit tests for this, so we can ensure that this doesn't happen again in the future? You should be able to add one in `tests/php/extensions/blocks/`.

Thank you.

2020-11-02 17:48 UTC, sixhours commented
This is working for me in testing:

<img width="621" alt="Screen Shot 2020-11-02 at 12 20 42 PM" src="https://user-images.githubusercontent.com/2124984/97898866-797a4e80-1d06-11eb-9e25-14a44a63ce31.png">
<img width="391" alt="Screen Shot 2020-11-02 at 12 22 15 PM" src="https://user-images.githubusercontent.com/2124984/97898867-7a12e500-1d06-11eb-91ae-ff8b74eb973b.png">
<img width="787" alt="Screen Shot 2020-11-02 at 12 22 21 PM" src="https://user-images.githubusercontent.com/2124984/97898868-7a12e500-1d06-11eb-80e7-3f0a57ee54a0.png">
<img width="1054" alt="Screen Shot 2020-11-02 at 12 23 28 PM" src="https://user-images.githubusercontent.com/2124984/97898870-7aab7b80-1d06-11eb-89e0-a4cf62a1481c.png">

I'm not sure if the actual embed is meant to render in notifications or the Reader yet (I don't think so).

2020-11-03 01:13 UTC, aaronrobertshaw commented
> Do you think you could add some unit tests for this, so we can ensure that this doesn't happen again in the future? You should be able to add one in `tests/php/extensions/blocks/`.

I've added some tests to catch this in future.

2020-11-03 17:23 UTC, jeherve approved these changes
> I've added some tests to catch this in future. 

Thank you! I took the opportunity to simplify the test a bit in bd5869b833a40552008092d0a960cd0fea5cd4db. Other than that, it should be good to merge! 🚢

2020-11-04 05:21 UTC, aaronrobertshaw commented
@jeherve Thanks for improving the tests. I'll keep the data provider approach in mind for the future.

2020-11-04 05:22 UTC, merged