Upgrade Flow: Connecting Jetpack users
Automattic/jetpack pull request #17822
Opened 2020-11-16 23:18 UTC by sergeymitr

#### Changes proposed in this Pull Request:
If a Jetpack user is not connected to WP.com, clicking on the "Upgrade" button will lead them nowhere.
This PR introduces the changes to let such users register/authenticate on WP.com (if needed), and link their account to the Jetpack site.

#### Jetpack product discussion
p9dueE-1M4-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
TBD

#### Proposed changelog entry for your changes:
* Improved product upgrade flow for non-connected Jetpack users.

2020-11-17 02:45 UTC, ebinnion commented on class.jetpack.php
> +					add_filter( 'allowed_redirect_hosts', function( $domains ) {
Are anonymous functions allowed in our supported PHP versions?

2021-01-28 19:46 UTC, leogermani requested changes
Very well done. Works as expected in various situations

* not connected secondary user
* totally user-less connection

I also tested that the user is properly connected even If the checkout is not concluded,

I just found one small problem:

In the calypso screen that asks for the user authorization, if you give up authorizing and click "Back to __sitename__", you end up in an endless loop, because our new redirect sends us back to Calypso again.

2021-01-28 22:41 UTC, sergeymitr commented
> In the calypso screen that asks for the user authorization, if you give up authorizing and click "Back to sitename", you end up in an endless loop, because our new redirect sends us back to Calypso again.

That's a good catch, thanks @leogermani.
I've pushed the fix, please re-review.

2021-02-08 20:25 UTC, leogermani approved these changes
tested again and everything is looking fine!

2021-02-08 20:40 UTC, merged