TwentyTwentyOne: Add Content Options
Automattic/jetpack pull request #17951
Opened 2020-12-02 17:36 UTC by scruffian

This adds Content Options to TwentyTwentyOne.

Part of https://github.com/Automattic/jetpack/issues/17248

#### Changes proposed in this Pull Request:

* I removed the lines for comment link, author bio and tags, as these don't appear in the excerpt.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Switch to TT1
* Open the Customizer
* Open the Content Options panel
* Try changing the settings and making sure that the post content updates accordingly

#### Proposed changelog entry for your changes:
* Add Content Options to TwentyTwentyOne

2020-12-02 17:56 UTC, jeherve requested changes
It looks like the linter has some feedback on indenting, below.

2020-12-03 09:54 UTC, scruffian commented
@jeherve I think i've placated the linting gods for now...

2020-12-03 11:18 UTC, jeherve reviewed
The date and category options don't appear to work for me; do they work on your end?

2020-12-03 12:23 UTC, scruffian commented
Yes, you're right sorry, I had the wrong stylesheet slug. It's working for me now.

2020-12-03 12:45 UTC, jeherve approved these changes
Tests well for me now. Merging.

2020-12-03 12:45 UTC, merged

2020-12-03 12:46 UTC, jeherve commented
Cherry-picked to `branch-9.2` in fcc90c3f7c91da08a6e32df1d3f5c45e479e33fa

2020-12-03 12:49 UTC, jeherve commented
r217724-wpcom