Add semantic dates
Automattic/jetpack pull request #17971
Opened 2020-12-04 09:49 UTC by edent

Uses `<time>` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time - to ensure that the dates are semantic.

* Dates now use the correct semantic element

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

No,

#### Testing instructions:

* Go to 'Related Posts'
* Timestamps should now use the `<time>` element

#### Proposed changelog entry for your changes:

* Related Posts now uses the semantic time element for dates.

2020-12-04 16:03 UTC, brbrr commented
Thank you for your contribution! 

Although, I'm not sure we can use `<time>` as it is, since it is not supported in IE11. Here is the list of supported browsers https://make.wordpress.org/core/handbook/best-practices/browser-support/

2020-12-04 17:35 UTC, anomiex commented
https://caniuse.com/html5semantic suggests that IE11 supports it. It shows partial support, but with the note that "Partial support refers to only the <main> element (added later to the spec) being 'unknown'" which suggests all the rest of the HTML5 semantic tags (including `<time>`) are supported.

But even if not, it should treat it in the same way it does the `<span>` it's replacing here. I don't have IE11 handy to test it with, though.

2020-12-04 23:11 UTC, kraftbj approved these changes

2020-12-05 11:22 UTC, edent commented
As others have mentioned, most browsers - including IE11 - will treat `<unknown>` as an inline element. Effectively a `<span>`. As the CSS is based on the element's class, this should have no negative effect on older browsers.

2020-12-07 13:07 UTC, jeherve requested changes
While switching from `span` to `time` shouldn't cause any markup issues, we do lose some styling in the process:

- We no longer benefit from the CSS applied to paragraphs in the Related Posts.
- `time` is an inline element by default, so when we apply `.show()` [here](https://github.com/Automattic/jetpack/blob/f3eb42a8c23de8ab43b1a818eee9c42dcef50751/modules%2Frelated-posts%2Frelated-posts.js#L306), we end up with an inline element instead of a block one like the others in the post context.

As a result the dates now appear bigger than everything else:

![image](https://user-images.githubusercontent.com/426388/101353543-0d09e680-3894-11eb-9278-46c5621ae5d2.png)

I think we'll need to apply extra styling to fix that.

We'll also need to update the version number of the files enqueued, to ensure that cache is busted and that everyone benefits from the update.

2020-12-07 13:16 UTC, jeherve commented
@edent I've opened this PR to suggest a few changes on your patch:
https://github.com/edent/jetpack/pull/1

If you merge this PR, the changes will be applied here.

2020-12-08 17:35 UTC, jeherve approved these changes
This looks good to me, but I'll let someone else take a last look since some of the code is mine.

2020-12-08 17:35 UTC, jeherve commented
r217962-wpcom

2020-12-08 22:51 UTC, kraftbj approved these changes

2020-12-08 22:52 UTC, merged