Fix "Build artifacts" job
Automattic/jetpack pull request #18355
Opened 2021-01-14 22:33 UTC by anomiex

#### Changes proposed in this Pull Request:

When we removed .svnignore, that caused the job to start trying to
include all of node_modules and such in the artifact which is completely
not what we want.

We already have the logic to produce exactly what we do want for the
mirror repos, so refactor the existing script into "build" and "push"
parts so "Build artifacts" can use just the first part.

#### Jetpack product discussion

p1610657658129800-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

Not sure. I've currently disabled the "Build artifacts" workflow since it's breaking everything, but maybe it's possible to manually run it. Otherwise, try running the scripts manually and see that they do the right things.

#### Proposed changelog entry for your changes:

* None needed.

2021-01-14 23:14 UTC, kraftbj requested changes

2021-01-14 23:14 UTC, kraftbj commented on tools/build-jetpack.sh
> -    echo $CURRENT_VERSION > version.txt
We need to either bring this back OR change the "inform beta builder step"

2021-01-15 15:00 UTC, anomiex commented
Hmm. Version number pushed to Jetpack Beta isn't quite right, because it's not picking up the git version.

2021-01-15 15:01 UTC, kraftbj commented
@anomiex and what the beta server slurped up is wrong too. https://betadownload.jetpack.me/branches/fix_build-beta-artifacts/jetpack-dev.zip

2021-01-15 15:07 UTC, anomiex commented
Grr. It just arbitrarily slurped the first artifact instead of the one named "jetpack-dev".

2021-01-15 16:59 UTC, kraftbj approved these changes

2021-01-15 17:01 UTC, kraftbj commented
Testing thread: p1610723715188300-slack-CBG1CP4EN

2021-01-15 17:16 UTC, merged