Jetpack Recommendations: Add dashboard banner
Automattic/jetpack pull request #18359
Opened 2021-01-14 23:23 UTC by robertf4

Fixes #

#### Changes proposed in this Pull Request:

This PR adds a banner for the Jetpack Recommendations

TODO: screenshots

#### Jetpack product discussion

MT: p1HpG7-asW-p2
Design: p6TEKc-4cJ-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

TODO

#### Proposed changelog entry for your changes:

*

2021-02-08 10:22 UTC, folletto commented
I'll leave to @jeffgolenski for a more detailed review, but at a first glance there seem to be alignment problems:

<img width="421" alt="Screenshot 2021-02-08 at 10 13 05" src="https://user-images.githubusercontent.com/4389/107205913-50004b80-69f6-11eb-913d-95fa62205f9d.png">

1. Text, checkboxes, and buttons should have the same alignment left and right from the border. Should be 24px if I recall correctly.
2. Vertically it's ok, but I wonder (this is a different from the blueprints) if the two I highlighted should be swapped, making all the text together, instead of getting the paragraph closer to the buttons.

2021-02-08 18:10 UTC, jeherve requested changes
Looks like there are some linting issues that would need to be addressed before it's ready for review? You'll also need to rebase one last time to solve those CI issues currently appearing.

2021-02-11 15:08 UTC, jeherve requested changes
This seems to work. I have a few remarks:

********

I don't think the hover on the main button is correct:

![image](https://user-images.githubusercontent.com/426388/107646820-b1385100-6c7a-11eb-97b1-592b8c46159a.png)

Core seems to slightly change the background color only:

![image](https://user-images.githubusercontent.com/426388/107646862-bf866d00-6c7a-11eb-8fe6-1f625f7475fe.png)

*********

Should we hide JITMs on pages where the banner is displayed, to avoid overloading the page with too much information?

2021-02-12 16:59 UTC, robertf4 commented on projects/plugins/jetpack/class-jetpack-recommendations-banner.php
> +		if ( ! in_array( get_current_screen()->id, array( 'dashboard', 'plugins' ), true ) ) {
I'm following [the logic used for the setup wizard banner](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/class-jetpack-wizard-banner.php#L63). The reasoning for both is that they recommend plugins.

2021-02-15 12:29 UTC, jeherve approved these changes
This tests well for me. I suppose we could go for a somewhat cleaner solution to hide the JITMs, but that does the trick for now. Maybe in a follow-up PR you could add an exception [here](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/packages/jitm/src/class-jitm.php#L83-L90)? 🚢

2021-02-15 15:43 UTC, jeffgolenski commented
Apologies for the delay here @robertf4. 

My feedback is exactly what Erin prescribed above, along with a few other items as well

*Mobile*

<img width="416" alt="Screen Shot 2021-02-15 at 10 29 11 AM" src="https://user-images.githubusercontent.com/214813/107965793-edb8c500-6f78-11eb-8b42-a9c7a50d86a5.png">

Getting closer here! We sure just ensure the padding on both the left and the right is equidistant.

*Medium screens*
![Screen Shot 2021-02-15 at 10 28 19 AM](https://user-images.githubusercontent.com/214813/107965864-0d4fed80-6f79-11eb-8fed-d777f2c9d15e.png)

Tiny nitpick. For the medium breakpoint, we also need to ensure the left and right spacing is equidistant. It's slightly different right now.

*Extra large screens*

![Screen Shot 2021-02-15 at 10 27 59 AM](https://user-images.githubusercontent.com/214813/107965943-2f497000-6f79-11eb-8c97-665301905f97.png)

For any screen larger than a standard 15 inch, the layout gets quite discombobulated. 

* Let's ensure the banner has a max width assigned to `1200px` (and for good measure, let's assign a max width of 600px to `.jp-recommendations-banner__illustration-container`)

![Screen Shot 2021-02-15 at 10 39 47 AM](https://user-images.githubusercontent.com/214813/107966972-8d2a8780-6f7a-11eb-970d-e2631fcec637.png)

I think the max width of the container isn't ideal since all the other wp-admin box scale indefinitely, but I also personally believe wp-admin shouldn't scale like this on ultrawide screens. 

This would look really bad:

![Screen Shot 2021-02-15 at 10 40 57 AM](https://user-images.githubusercontent.com/214813/107967015-9a477680-6f7a-11eb-814d-6129dbe0d0c0.png)

2021-02-15 15:50 UTC, merged