Jetpack ES query builder: fix ignored weightings
Automattic/jetpack pull request #18395
Opened 2021-01-18 15:47 UTC by gibrown

Any weightings that were getting applied to the query with add_weighting_function() were not being added to the query. This fixes that bug and also adds a few checks to prevent adding weightings that we don't support (scripts and randomization). No place in Jetpack is using these and I doubt any customers are either, but we use it in a few places on wpcom and are planning some more.

This is a part of landing D51036. I've tested it manually there. Don't have any good test coverage yet, but it is fairly minor also.

2021-01-18 16:50 UTC, robfelty approved these changes, later dismissed
Tested changes using the Reader. Works as expected.

2021-01-18 16:50 UTC, robfelty commented on projects/plugins/jetpack/_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-builder.php
> +			$weighting_functions = $this->weighting_functions;
Looks good. Works now!

2021-01-20 20:03 UTC, kraftbj requested changes

2021-01-20 20:03 UTC, kraftbj commented on projects/plugins/jetpack/_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-builder.php
> +		//check for danger
```suggestion
		// check for danger.
```

2021-01-20 20:04 UTC, kraftbj commented
Original patch committed to wpcom in r219734-wpcom

2021-01-20 20:08 UTC, kraftbj commented
Inline doc linting fixed in r219754-wpcom

2021-01-20 20:13 UTC, kraftbj approved these changes

2021-01-20 20:13 UTC, merged

2021-01-20 22:49 UTC, gibrown commented
Thanks @kraftbj