Add Jetpack Constants
Automattic/jetpack pull request #18537
Opened 2021-01-25 20:59 UTC by kraftbj

Replaces https://github.com/Automattic/jetpack-beta/pull/72

Add the constants settings page here instead of the JN companion plugin.

Right now, when asking folks to test things like beta blocks, there is no built-in way for beta testers to do this without manually adjusting config files.

TODO: The review comment left in https://github.com/Automattic/jetpack-beta/pull/72#pullrequestreview-566956273

2021-01-27 17:51 UTC, jeherve requested changes
I think you'll need to move the `lib/RationalOptionPages.php` inside the plugin's folder.

2021-01-27 18:46 UTC, kraftbj commented
Thanks, I missed that when trying to merge up the branch from the old repo.

2021-02-02 22:01 UTC, kraftbj commented
I'm going to parse out separately improving this. I'm not a fan of the RationalOptionsPages tool used for the options page of Constants, so I'll want to rework that.

2021-02-18 08:03 UTC, jeherve requested changes

2021-02-18 08:03 UTC, jeherve commented on projects/plugins/beta/lib/RationalOptionPages.php
> +					call_user_func_array( 'add_settings_section', $params );
Let's bring in the changes from https://github.com/Automattic/companion/pull/44

2022-03-02 08:51 UTC, closed without merging