Jetpack: Normalize package names
Automattic/jetpack pull request #18546
Opened 2021-01-26 15:57 UTC by kraftbj

Normalizes package names to automattic/jetpack

#### Changes proposed in this Pull Request:

* n/a

#### Jetpack product discussion

* n/a

#### Does this pull request change what data or activity we track or use?

* n/a

#### Testing instructions:

* n/a
*

#### Proposed changelog entry for your changes:

* n/a

2021-01-26 16:07 UTC, kraftbj commented
This is fine on the Jetpack side. Marked as in progress since it'll need a little massage on the Fusion side.

2021-01-27 18:06 UTC, jeherve requested changes

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/_inc/lib/debugger/debug-functions.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/class.jetpack-bbpress-json-api.compat.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/class.jetpack-twitter-cards.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/class.photon.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/json-api-config.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/comments.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/comments/comments.php
> + * @package automattic/jetpackComments
```suggestion
 * @package automattic/jetpack

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/photon.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/publicize.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/theme-tools/devicepx.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/theme-tools/site-breadcrumbs.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/widgets/milestone.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/widgets/milestone/class-milestone-widget.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/widgets/milestone/milestone.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-admin.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-api.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-california-privacy.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-ccpa-do-not-sell-link-widget.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-cron.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-params.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/class-wordads-sidebar-widget.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/modules/wordads/php/networks/amazon.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/e2e/plugins/e2e-plan-data-interceptor.php
> + * @package automattic/jetpack-test-plugin-e2e-plan-data
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/e2e/plugins/e2e-plugin-updater.php
> + * @package automattic/jetpack-test-plugin-e2e-plugin-updater
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/php/3rd-party/test_class-jetpack-modules-overrides.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/php/general/test-class.jetpack-network.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/php/general/test_class.jetpack-user-agent.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/php/test_class.jetpack_photon.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on projects/plugins/jetpack/tests/php/uninstall/test_uninstall.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on tools/docker/config/wp-tests-config.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on tools/docker/mu-plugins/avoid-plugin-deletion.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on tools/docker/mu-plugins/debug.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-27 18:06 UTC, jeherve commented on tools/docker/mu-plugins/fix-monorepo-plugins-url.php
> + * @package automattic/jetpack.
```suggestion
 * @package automattic/jetpack
```

2021-01-28 00:21 UTC, ebinnion approved these changes
Assuming that the changes in `projects/plugins/jetpack/tests/e2e/plugins/e2e-plan-data-interceptor.php` and `projects/plugins/jetpack/tests/e2e/plugins/e2e-plugin-updater.php` are expected, this LGTM.

2021-01-28 07:21 UTC, jeherve approved these changes

2021-01-28 11:17 UTC, merged

2021-01-28 22:51 UTC, kraftbj commented
r220186-wpcom