Re-register Edit CSS sub page menu item
Automattic/jetpack pull request #18560
Opened 2021-01-27 14:54 UTC by tjcafferkey

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

*

2021-01-27 15:37 UTC, mmtr commented
@tjcafferkey this tested well on my premium site, but noted a couple of regressions:
- The "Edit CSS" submenu gets exposed on Free sites. Not sure how we were hiding it before, but we should keep the same behavior.
- I land on a page where the topbar is removed, and the site title in the sidebar gets bigger, breaking a bit the layout:
<img width="1270" alt="Screen Shot 2021-01-27 at 16 35 21" src="https://user-images.githubusercontent.com/1233880/106014451-cc716100-60bd-11eb-8491-21fa1ea4cb0d.png">

2021-01-27 15:49 UTC, obenland commented
Could you see if this works? `$GLOBALS['_registered_pages'][ 'admin_page_editcss'] = true;`

It's something that gets checked [down the stack from here](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/includes/menu.php#L341). Doing that helped with other instances of this, see D55890-code.

2021-01-27 17:03 UTC, cpapazoglou commented
> * The "Edit CSS" submenu gets exposed on Free sites. Not sure how we were hiding it before, but we should keep the same behavior.

What Obenland suggests should solve the problem. The menu item should not be shown in any plan. This page should be reachable only through the customizer custom css page (which probably has a plan gate)

>* I land on a page where the topbar is removed, and the site title in the sidebar gets bigger, breaking a bit the layout:

I couldn't reproduce this. It is probably irrelevant with this PR. Can you look into it further and report steps to reproduce?

2021-01-27 17:47 UTC, jeherve requested changes
You'll probably want to fix those PHPCS warnings, they will stop us from merging the PR.

2021-01-28 08:37 UTC, tjcafferkey commented
>Could you see if this works? $GLOBALS['_registered_pages'][ 'admin_page_editcss'] = true;

This seemed to do the trick 👍🏻 

>I land on a page where the topbar is removed, and the site title in the sidebar gets bigger, breaking a bit the layout

I was able to reproduce this, not sure why yet but removing the `&frame-nonce=` param from the URL resolves this (See screenshots below). It does feel like this could be something we can fix in a separate PR if required. What do you think?

**With `&frame-nonce=`**
![Screenshot 2021-01-28 at 08 33 52](https://user-images.githubusercontent.com/8639742/106111509-fe2d0b00-6143-11eb-9690-394376ca22e0.png)

**Without `&frame-nonce=`**
![Screenshot 2021-01-28 at 08 34 15](https://user-images.githubusercontent.com/8639742/106111516-008f6500-6144-11eb-910c-82d8ae1f6de7.png)

2021-01-28 10:23 UTC, jeherve approved these changes
This tests well for me. I'll merge this now, and I'll let you handle the WordPress.com counterpart.

2021-01-28 10:23 UTC, merged

2021-01-28 10:24 UTC, jeherve commented
Cherry-picked to `jetpack/branch-9.4` in 666f00e5a39426999a07eb81d78abe29cae3df6a