Audio Player: support load file when ready feature
Automattic/jetpack pull request #18761
Opened 2021-02-09 12:16 UTC by retrofox

Fixes #

#### Changes proposed in this Pull Request:

* Audio Player: support load file when ready feature

#### Jetpack product discussion

p1612872457005400?thread_ts=1612868861.488300&cid=CKZHG0QCR-slack-

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

With these changes, the media file will be initially loaded when a podcast block is added, so
* Create/edit a post
* Open the redux tool
* Add a podcast block
* set a valid RSS feed
* check that the duration is already populated in the media source

<img width="1792" alt="Screen Shot 2021-02-09 at 9 14 24 AM" src="https://user-images.githubusercontent.com/77539/107362242-44288e00-6ab7-11eb-8ea7-bd238a08f640.png">

#### Proposed changelog entry for your changes:

*

2021-02-09 12:22 UTC, pablinos reviewed
Just a couple of thoughts, but I think loading the audio when we can is a good idea.

2021-02-09 12:22 UTC, pablinos commented on projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js
> +						loadWhenReay={ true }
Typo here, I think it should be `loadWhenReady`

2021-02-09 12:22 UTC, pablinos commented on projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx
> +			}
Perhaps this could be:
```suggestion
			success: loadWhenReady && audio?.load
```

2021-02-09 22:14 UTC, pablinos commented
This works well. I've discovered that we can achieve the same result by setting the [`preload` attribute to `metadata` on the `audio` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload). I'd be inclined to go that way although apparently, it's only a suggestion and browsers may ignore it in certain circumstances. Not knowing what those circumstances are, I'm not sure whether to risk it. What do you think?

2021-02-10 11:56 UTC, jeherve commented
> we can achieve the same result by setting the [`preload` attribute to `metadata` on the `audio` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload). I'd be inclined to go that way although apparently

I personally like this idea. @mmtr may know more, but I believe that's the direction we went to with the VideoPress player a few years back; maybe we should do the same here.

2021-02-10 11:59 UTC, retrofox commented
> we can achieve the same result by setting the [`preload` attribute to `metadata` on the `audio` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload). I'd be inclined to go that way although apparently

Nice idea. Anyway, I think both ideas can live together. `loadWhenReady ` is a prop and `false` as default.


> I personally like this idea. @mmtr may know more, but I believe that's the direction we went to with the VideoPress player a few years back; maybe we should do the same here.

👍

2021-02-10 12:33 UTC, retrofox commented
I've left the `playWhenReady` property since it's `false` as default. The ability to load the file initially is something we may like to do. Added the `preload` property to the component, with `metadata` es default.  It works like a charm. Thanks, Paul.

2021-02-10 12:34 UTC, mmtr commented
> I personally like this idea. @mmtr may know more, but I believe that's the direction we went to with the VideoPress player a few years back; maybe we should do the same here.

The reasoning behind using `metadata` as default for the VideoPress player was to be aligned with the video block in Core: https://github.com/WordPress/gutenberg/blob/94cc72e3e5dce4b4d90c3f7b7ab0fea38a62bf2e/packages/block-library/src/video/block.json#L45-L51

2021-02-10 12:58 UTC, jeherve requested changes
This seems to test well, but you'll need to fix that linting error.

2021-02-10 13:01 UTC, retrofox commented
> This seems to test well, but you'll need to fix that linting error.

Oh no again!! :old: https://github.com/Automattic/jetpack/pull/18761/commits/1f597b950c1f2cd5445dc25952fa16f37b909c3d

2021-02-10 18:06 UTC, jeherve approved these changes

2021-02-10 19:21 UTC, retrofox commented
r220856-wpcom

2021-02-10 19:21 UTC, merged

2021-02-10 19:30 UTC, jeherve commented
Cherry-picked to `jetpack/branch-9.4` in 62b0c79bcc7bd9aa340d3c873bce677526e0293d