Podcast Helper: Allow filtering the number of tracks returned by get_track_list.
Automattic/jetpack pull request #18836
Opened 2021-02-15 23:52 UTC by kwight

This PR adds a filter to allow a variable number of tracks to be returned when getting a track list. The default remains at ten.

See: 474-gh-Automattic/dotcom-manage

#### Jetpack product discussion
pbAPfg-PF-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

#### Proposed changelog entry for your changes:
* A filter is now available to modify the number of tracks returned by a Podcast Helper track list.

2021-02-16 00:08 UTC, kwight commented
@jeherve Erm, I admit I'm at a loss as to how to test this (my local JP install is hosed at the moment). And testing on WP.com by inserting a podcast player, I'm only seeing five episodes getting pulled in (I at least expected to see ten).

2021-02-16 17:29 UTC, jeherve requested changes
This seems to work for me, although we will need to add a docblock before the filter. Here is an example:
https://github.com/Automattic/jetpack/blob/26db3e436ccca3e16a62d02d95e792a81f38a1e4/projects/plugins/jetpack/extensions/blocks/business-hours/business-hours.php#L157-L164

> I admit I'm at a loss as to how to test this (my local JP install is hosed at the moment). And testing on WP.com by inserting a podcast player, I'm only seeing five episodes getting pulled in (I at least expected to see ten). Any hints?

Here is how I tested this:
1. I used the filter, e.g. `add_filter( 'jetpack_podcast_helper_list_quantity', function() { return 25; } );`
2. In the post editor, I added the following in the console: 
```js
wp.apiFetch( { path: 'wpcom/v2/podcast-player?url=https://distributed.blog/category/podcast/feed/', method: 'GET', } ).then( res => { console.log( `We have ${ res.tracks.length } podcast episodes returned.` ); } );
```

Noting that in the UI, we do have a maximum set:
https://github.com/Automattic/jetpack/blob/5485111e6de594a9279bab856a63116b84762494/projects/plugins/jetpack/extensions/blocks/podcast-player/edit.js#L54

2021-02-16 22:24 UTC, kwight commented
@jeherve Ah, thank you! Comments are improved. 👍

2021-02-17 07:25 UTC, jeherve requested changes

2021-02-17 07:25 UTC, jeherve commented on projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php
> +		 * @param object $rss The SimplePie object built from core's `fetch_feed` call.
```suggestion
		 * @param int    $number Number of tracks fetched. Default is 10.
		 * @param object $rss    The SimplePie object built from core's `fetch_feed` call.
```

2021-02-17 07:26 UTC, jeherve approved these changes

2021-02-17 18:55 UTC, merged

2021-02-17 19:03 UTC, kwight commented
D57109-code is merged too, thanks @jeherve !