[In Progress] Button block: Add tests
Automattic/jetpack pull request #19002
Opened 2021-03-03 17:48 UTC by stacimc

Adds tests for the Button block.

#### Changes proposed in this Pull Request:

* Pulls settings out of the block into a `Controls` component for simplification/separate testing
* Adds tests

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Run tests from the `projects/plugins/jetpack` folder with:
```
yarn jest extensions/blocks/button/test/edit.js
yarn jest extensions/blocks/button/test/controls.js
```
* Manually test the Button block, including setting all of the color/border radius selections

#### Proposed changelog entry for your changes:

*

2021-03-04 02:49 UTC, ramonjd commented on projects/plugins/jetpack/extensions/blocks/button/test/edit.js
> +    __experimentalUseGradient.mockReturnValueOnce = gradientProps;
As per the Slack thread, try 
`__experimentalUseGradient.mockImplementation( () => gradientProps );`

2021-03-09 20:30 UTC, apeatling submitted a review, later dismissed
Works for me, nice!

2021-03-10 09:38 UTC, jeherve reviewed
This seems to generate block validation errors when editing posts with Subscriptions blocks:

<details>
  <summary>Click to expand!</summary>

```
Block validation: Block validation failed for `jetpack/subscriptions` (
{
    "name": "jetpack/subscriptions",
    "icon": {
        "src": {
            "key": null,
            "ref": null,
            "props": {
                "width": "24",
                "height": "24",
                "viewBox": "0 0 24 24",
                "fill": "none",
                "xmlns": "http://www.w3.org/2000/svg",
                "children": [
                    {
                        "key": null,
                        "ref": null,
                        "props": {
                            "x": "4.75",
                            "y": "6.75",
                            "width": "14.5",
                            "height": "10.5",
                            "rx": "1.25",
                            "stroke": "#069e08",
                            "strokeWidth": "1.5",
                            "fill": "none"
                        },
                        "_owner": null
                    },
                    {
                        "key": null,
                        "ref": null,
                        "props": {
                            "d": "M19 7L13.3609 12.2363C12.5935 12.9489 11.4065 12.9489 10.6391 12.2363L5 7",
                            "stroke": "#069e08",
                            "strokeWidth": "1.5",
                            "strokeLinejoin": "bevel",
                            "fill": "none"
                        },
                        "_owner": null
                    }
                ]
            },
            "_owner": null
        },
        "foreground": "#069e08"
    },
    "keywords": [
        "subscribe",
        "join",
        "follow"
    ],
    "providesContext": {},
    "usesContext": [],
    "styles": [],
    "title": "Subscription Form",
    "description": {
        "type": "p",
        "key": null,
        "ref": null,
        "props": {
            "children": "A form enabling readers to get notifications when new posts are published from this site."
        },
        "_owner": null
    },
    "category": "grow",
    "example": {
        "attributes": {}
    },
    "deprecated": [
        {
            "attributes": {
                "subscribeButton": {
                    "type": "string",
                    "default": "Subscribe"
                },
                "showSubscribersTotal": {
                    "type": "boolean",
                    "default": false
                },
                "className": {
                    "type": "string"
                }
            }
        },
        {
            "attributes": {
                "subscribePlaceholder": {
                    "type": "string",
                    "default": "Email Address"
                },
                "subscribeButton": {
                    "type": "string",
                    "default": "Subscribe"
                },
                "showSubscribersTotal": {
                    "type": "boolean",
                    "default": false
                },
                "submitButtonText": {
                    "type": "string",
                    "default": "Subscribe"
                },
                "backgroundButtonColor": {
                    "type": "string"
                },
                "textButtonColor": {
                    "type": "string"
                },
                "customBackgroundButtonColor": {
                    "type": "string"
                },
                "customTextButtonColor": {
                    "type": "string"
                },
                "submitButtonClasses": {
                    "type": "string"
                },
                "className": {
                    "type": "string"
                }
            }
        },
        {
            "attributes": {
                "subscribePlaceholder": {
                    "type": "string",
                    "default": "Enter your email address"
                },
                "showSubscribersTotal": {
                    "type": "boolean",
                    "default": false
                },
                "buttonOnNewLine": {
                    "type": "boolean",
                    "default": false
                },
                "submitButtonText": {
                    "type": "string",
                    "default": "Sign Up"
                },
                "emailFieldBackgroundColor": {
                    "type": "string"
                },
                "customEmailFieldBackgroundColor": {
                    "type": "string"
                },
                "emailFieldGradient": {
                    "type": "string"
                },
                "customEmailFieldGradient": {
                    "type": "string"
                },
                "buttonBackgroundColor": {
                    "type": "string"
                },
                "customButtonBackgroundColor": {
                    "type": "string"
                },
                "buttonGradient": {
                    "type": "string"
                },
                "customButtonGradient": {
                    "type": "string"
                },
                "textColor": {
                    "type": "string"
                },
                "customTextColor": {
                    "type": "string"
                },
                "fontSize": {
                    "type": "number"
                },
                "customFontSize": {
                    "type": "number"
                },
                "borderRadius": {
                    "type": "number"
                },
                "borderWeight": {
                    "type": "number"
                },
                "borderColor": {
                    "type": "string"
                },
                "customBorderColor": {
                    "type": "string"
                },
                "padding": {
                    "type": "number"
                },
                "spacing": {
                    "type": "number"
                },
                "className": {
                    "type": "string"
                }
            }
        },
        {
            "attributes": {
                "subscribePlaceholder": {
                    "type": "string",
                    "default": "Enter your email address"
                },
                "showSubscribersTotal": {
                    "type": "boolean",
                    "default": false
                },
                "buttonOnNewLine": {
                    "type": "boolean",
                    "default": false
                },
                "submitButtonText": {
                    "type": "string",
                    "default": "Sign Up"
                },
                "emailFieldBackgroundColor": {
                    "type": "string"
                },
                "customEmailFieldBackgroundColor": {
                    "type": "string"
                },
                "emailFieldGradient": {
                    "type": "string"
                },
                "customEmailFieldGradient": {
                    "type": "string"
                },
                "buttonBackgroundColor": {
                    "type": "string"
                },
                "customButtonBackgroundColor": {
                    "type": "string"
                },
                "buttonGradient": {
                    "type": "string"
                },
                "customButtonGradient": {
                    "type": "string"
                },
                "textColor": {
                    "type": "string"
                },
                "customTextColor": {
                    "type": "string"
                },
                "fontSize": {
                    "type": [...]

2021-03-10 20:41 UTC, anomiex commented
Needs a changelogger change file. In `projects/plugins/jetpack`, execute `vendor/bin/changelogger add` to create one interactively.

2021-03-11 11:22 UTC, jeherve submitted a review, later dismissed
Tests well for me now.

2021-03-12 21:36 UTC, stacimc commented
Rebased after merging in the button width options (#18809)

2021-03-15 17:33 UTC, jeherve requested changes
The tests seem to fail now:
https://github.com/Automattic/jetpack/pull/19002/checks?check_run_id=2098887487

2021-03-16 19:50 UTC, glendaviesnz commented
> The tests seem to fail now:
> https://github.com/Automattic/jetpack/pull/19002/checks?check_run_id=2098887487

@stacimc looks like the test failure is because the dependency tree that the jest test runner is using in the jetpack repo is older that the one that is used to compile the frontend client, and `UnitControl` is not available. Strange that it didn't fail locally for you though. 

The Jetpack crew have been working to get the dependencies updated, in the mean time you will probably either need to comment out the tests that are mounting this part of the component, or you might be able to mock `UnitControl` in the spec file with something like:

```
jest.mock( '@wordpress/components', () => ( {
	...jest.requireActual( '@wordpress/components' ),
	__experimentalUnitControl: () => <div>Mocked Unit Control</div>,
} ) );
```

2021-03-16 20:11 UTC, stacimc commented
> > The tests seem to fail now:
> > https://github.com/Automattic/jetpack/pull/19002/checks?check_run_id=2098887487
> 
> @stacimc looks like the test failure is because the dependency tree that the jest test runner is using in the jetpack repo is older that the one that is used to compile the frontend client, and `UnitControl` is not available. Strange that it didn't fail locally for you though.

My apologies -- there were a couple of PRs affected by this and I missed updating the status/comment on this one. Yes, this is being held up by the dependency update :( 

I like the suggestion of mocking it for now. I'll work on that and create a follow up to include removing the mock and adding additional tests for the width.

2021-03-16 20:52 UTC, stacimc commented
I've temporarily mocked out the width controls for now, follow up issue to fix at: 253-gh-Automattic/view-design

2021-03-17 17:51 UTC, jeherve approved these changes

2021-03-18 17:41 UTC, merged

2021-03-18 21:25 UTC, stacimc commented
Holding off on deploying this one, as it relies on #18809 (which needs to be deployed along with the release for the sake of Atomic sites).

2021-04-06 17:31 UTC, jeherve commented
r223840-wpcom