Update Monorepo.md
Automattic/jetpack pull request #19028
Opened 2021-03-04 21:45 UTC by sdixon194

Updates monorepo.md to include first time instructions per p1HpG7-bmx-p2

#### Changes proposed in this Pull Request:

* as above

#### Jetpack product discussion

N/a

#### Does this pull request change what data or activity we track or use?

N/a

#### Testing instructions:

* Go to monorepo.md
* Read the instructions

#### Proposed changelog entry for your changes:

* N/a

2021-03-04 23:24 UTC, kraftbj submitted a review, later dismissed

2021-03-05 08:17 UTC, jeherve requested changes

2021-03-05 08:17 UTC, jeherve commented on docs/monorepo.md
> +* From the root of the repo, run yarn install && yarn cli-link
```suggestion
* From the root of the repo, run `yarn install && yarn cli-link`
```

2021-03-05 08:17 UTC, jeherve requested changes

2021-03-05 08:17 UTC, jeherve commented on docs/monorepo.md
> +Once you’ve done that, it’s easy: run jetpack while anywhere in the Jetpack repo. To explore on your own, run jetpack --help to see the available commands.
```suggestion
Once you’ve done that, it’s easy: run jetpack while anywhere in the Jetpack repo. To explore on your own, run `jetpack --help` to see the available commands.
```

2021-03-05 08:17 UTC, jeherve approved these changes

2021-03-05 12:55 UTC, merged