Add Edit CSS menu item to appearance sub menu
Automattic/jetpack pull request #19090
Opened 2021-03-09 11:41 UTC by tjcafferkey

Fixes https://github.com/Automattic/wp-calypso/issues/50569

#### Changes proposed in this Pull Request:

* Adds "Edit CSS" menu item to the Appearance sub menu

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* TBC

2021-03-09 14:25 UTC, cpapazoglou commented on projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
> +		}
All Simple sites should open the `$customize_slug = 'https://wordpress.com/customize/' . $this->domain;`. We can remove the conditional.

2021-03-09 14:34 UTC, cpapazoglou requested changes
Thanks for working on this, it works great.

We can remove the `$customize_slug` as Simple sites should always load customiser inside WordPress.com, which will make code simpler too.

2021-03-09 15:32 UTC, cpapazoglou commented on projects/plugins/jetpack/changelog/add-edit-css-appearance-menu-item
> +Significance: enhancement
```suggestion
Significance: minor
```

2021-03-09 15:32 UTC, cpapazoglou commented on projects/plugins/jetpack/changelog/add-edit-css-appearance-menu-item
> +Type: added
```suggestion
Type: enhancement
```

2021-03-10 13:50 UTC, jeherve approved these changes
This tests well for me. 👍

2021-03-11 10:34 UTC, merged

2021-03-11 10:46 UTC, tjcafferkey commented
Deployed as part of r222552-wpcom

2021-03-16 12:19 UTC, jeherve commented
Cherry-picked to `jetpack/branch-9.5` in e76d69957441b2167abc23a1ffdaf2ba816a438c