Avoid creating jetpack-temp directory in WP root
Automattic/jetpack pull request #19162
Opened 2021-03-13 10:19 UTC by szepeviktor

Fixes #mypain

#### Changes proposed in this Pull Request:

Try to create jetpack-temp directory in wp-content in the first place.

#### Some background

I'd like to keep all installations highly clean: git + Composer + separate directory for WordPress core files.
So the document root contains 2 directories:

1. core
2. and wp-content

It needs 2 lines in wp-config.
https://wordpress.org/support/article/giving-wordpress-its-own-directory/

As of today Jetpack **writes** into core's directory (ABSPATH).
This PR prioritizes uploads and wp-content directory.

2021-03-13 10:48 UTC, szepeviktor commented
> Error: Project packages/backup is being changed, but no change file in projects/packages/backup/changelog/ is touched!

I've been pwnd! Could you help me phrase a line for the changelog?

2021-03-15 17:32 UTC, jeherve commented
> I've been pwnd! Could you help me phrase a line for the changelog?

You should be able to follow the instructions here:
https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#using-the-jetpack-changelogger

> Go to that project and use `vendor/bin/changelogger add` to add a change file.

2021-03-15 17:34 UTC, szepeviktor commented
Jeremy! That is SO HARD!!!

2021-03-15 17:42 UTC, szepeviktor commented
@jeherve Done 🍏

2021-03-15 17:53 UTC, jeherve commented
> Done 🍏🍏

Thank you! We'll take a look and review soon.

Internal reference: p1615830698055600-slack-CS8UYNPEE

2021-03-18 16:50 UTC, vianasw requested changes
Thanks for the PR. While we think that this could work, it would directly affect so many sites and we can't be sure if that it's not going to break anything. We think that an approach using a constant would work better in this case (i.e., if there is an install location constant define use that, otherwise fall back to what we have now).

2021-03-18 20:01 UTC, szepeviktor commented
All right.

👑

I leave it up to you.

BTW This is the _new_ constant: an immutable configuration.

```php
// Define constant values.
Config::init(
    [
        'version' => '1.0.0',
        'filePath' => __FILE__,
        'baseName' => plugin_basename(__FILE__),
        'slug' => 'plugin-slug',
    ]
);
```

https://github.com/szepeviktor/small-project/blob/master/src/Config.php

2023-07-31 06:59 UTC, szepeviktor commented
@jeherve Friendly ping 🏓

2023-07-31 08:58 UTC, jeherve commented
I'm afraid I have no news for you. The discussion above still applies:
https://github.com/Automattic/jetpack/pull/19162#pullrequestreview-615640514

2023-07-31 09:01 UTC, szepeviktor commented
Thank you for your response.

I close this PR.

2023-07-31 09:01 UTC, closed without merging