replace is_active to determine available xmlrpc methods
Automattic/jetpack pull request #19264
Opened 2021-03-23 14:04 UTC by leogermani

Fixes #

#### Changes proposed in this Pull Request:

*
TBD
#### Jetpack product discussion

TBD

#### Does this pull request change what data or activity we track or use?

TBD
#### Testing instructions:

* Go to '..'
*

2021-03-24 10:39 UTC, fgiannar commented on projects/packages/connection/src/class-manager.php
> +			add_filter( 'xmlrpc_methods', array( $this->xmlrpc_server, 'xmlrpc_methods' ) );
```suggestion
			add_filter( 'xmlrpc_methods', array( $this, 'xmlrpc_methods' ) );
```

typo?

2021-03-24 11:42 UTC, fgiannar requested changes
Hey Leo!

Great work here! Thanks for providing a handy script to test with!

Code looks good, logic is solid I believe.
I've found a typo (see inline comments).

I'm having a bit of trouble testing with the provided script. I seem to get `NULL` for unauthorized requests to a non connected site.
I've tried it via Postman though and works as expected.

2021-03-24 14:37 UTC, leogermani commented
@fgiannar Thanks for spotting the typo.

I've fixed it and also updating the broken tests. As soon as https://github.com/Automattic/jetpack/pull/18952 is merged, I'll move these tests into the Connection package, where they belong.

As for the testing script, I understand you managed to test it with Postman, right?

2021-03-24 21:26 UTC, leogermani commented
Updated the testing script with one that should work for all sites: 28d59-pb/#php

(also updated in the PR description)

2021-03-26 16:25 UTC, fgiannar approved these changes
Looks great, Leo! I tested using the provided instructions and everything works as expected! 💯

2021-03-26 16:41 UTC, merged