Business Hours Block: Site Editor Compatibility:  editing styles
Automattic/jetpack pull request #19532
Opened 2021-04-14 06:18 UTC by ramonjd

Fixes #19463

#### Changes proposed in this Pull Request:
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some styling issues with the Business Hours block when rendered in the site editor.

Most notably font sizes, padding and toggle switch disco positioning. 🕺 

From what I can tell the Site Editor is:
1. Not pulling in the common styles from the theme into the iframe.
2. Resetting the styles of a few controls,

This PR attempt to make more specific CSS declarations in the block itself so that the editing mode version of the block look kinda the same across the two editors.

<img width="1252" alt="Screen Shot 2021-04-10 at 2 37 06 pm" src="https://user-images.githubusercontent.com/6458278/114662482-17555900-9d3c-11eb-91a0-32d8ac2db974.png">

#### Jetpack product discussion
This is part of a [Jetpack FSE audit.](https://github.com/Automattic/view-design/issues/256)

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Business Hours block into the Footer template part.
3. Click on the blocks to enter editing mode
4. Compare the block in the two editors. Do they look okay? No major differences? Have you brushed your teeth lately.?

2021-04-15 06:21 UTC, andrewserong requested changes
Nice changes getting the overrides working here @ramonjd! It's testing well for me across Chrome and Edge, but I noticed an issue with `align-items: end` in FF. I _think_ if we switch it to `start`, it should fix it in each of them, if I'm not missing anything?

2021-04-15 06:21 UTC, andrewserong commented on projects/plugins/jetpack/extensions/blocks/business-hours/editor.scss
> +			align-items: end;
This is testing well for me in Chrome and Edge so far, but in Firefox setting to `align-items: end` results in the day text and toggle button being lower down within the element:

![image](https://user-images.githubusercontent.com/14988353/114822327-3cfa6500-9e05-11eb-846b-db85cd4e7811.png)

Swapping this out for `align-items: start` appears to fix it, though, and I think works the same in Chrome, Edge and Safari?

```suggestion
			align-items: start;
```

2021-04-16 02:24 UTC, ramonjd commented
Thanks @andrewserong for testing and for the suggestion.
FF:
<img width="706" alt="Screen Shot 2021-04-16 at 12 23 49 pm" src="https://user-images.githubusercontent.com/6458278/114962758-a7b3ab00-9eae-11eb-8a98-29f4b2236b8f.png">

Also double checked in other browsers. 👍

2021-04-16 03:25 UTC, andrewserong approved these changes
Looks good, thanks @ramonjd! That's testing nicely in FF, Safari, Chrome, and Edge for me now. 👍

It looks like CI is complaining that the PR isn't current, so this might just need a `git merge origin/master` to stop it from complaining.

2021-04-16 21:19 UTC, samiff approved these changes
LGTM 🚢

2021-04-19 00:44 UTC, merged

2021-04-19 00:44 UTC, ramonjd commented
r224441-wpcom