Story block: Add more media options to choose from in the editor
Automattic/jetpack pull request #19628
Opened 2021-04-22 15:52 UTC by Tug

#### Changes proposed in this Pull Request:
This change allows for selecting media in the story block from the same media sources as the gallery block and other visual blocks:

![image](https://user-images.githubusercontent.com/230230/115744649-0dae9f80-a393-11eb-8cb0-db6fad375c60.png)

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
- Apply this patch
- Navigate to a post containing a story
- Click on Select Media
- Notice Google Photos and Pexels are available and that we can mix media from different sources when editing a story

2021-04-30 02:17 UTC, aforcier requested changes
I gave this a try, and the first time media are added, it works great! However I ran into some issues when trying to change media several times in one session:

1. Start by adding an empty story block
2. Add media from any source
3. Tap on 'select media' again, and select at least one image from either Google Photos or Pexels
4. The new images are appended correctly, but the previous images become blank
5. Repeat step 3
6. Notice that the new selection was completely ignored

At step 4 I inspected the block, and it looks like this:

```
<!-- wp:jetpack/story {"mediaFiles":[{},{},{"alt":"lake and mountain","id":296,"type":"image","caption":"Photo by James Wheeler on \u003ca href=\u0022https://www.pexels.com/photo/lake-and-mountain-417074/\u0022 rel=\u0022nofollow\u0022\u003ePexels.com\u003c/a\u003e","url":"https://website.com/wp-content/uploads/2021/04/pexels-photo-417074.jpeg"}]} -->
<div class="wp-block-jetpack-story wp-story"></div>
<!-- /wp:jetpack/story -->
```

Interestingly, in the gallery block, once media has been added (from any source), it looks like the options for Google Photos and Pexels are removed, and you can only select media from your media gallery. Perhaps we should do the same?

2021-04-30 07:02 UTC, Tug commented on projects/plugins/jetpack/changelog/story-block-add-more-media-options
> +Story block: Add more media options to choose from in the editor
Type `other` is ignored as well. I can add the `Comment` prefix as well 👍

2021-04-30 11:24 UTC, Tug commented
@aforcier Thanks for finding and reporting this bug, I should have noticed 😞 . It's fixed now. I'll give it a more thorough round of testing before putting it back for review (need to test on WPCOM for instance)

2021-04-30 22:36 UTC, aforcier commented on projects/plugins/jetpack/changelog/story-block-add-more-media-options
> +Story block: Add more media options to choose from in the editor
Oh interesting, I didn't know that - is that written down somewhere? I didn't see it in [the instructions](https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#using-the-jetpack-changelogger), maybe they should be updated?

2021-05-01 00:24 UTC, aforcier commented
Hey @Tug , I gave this another try, on both Jetpack and WP.com.

Things are working smoothly and the bug seems to be fixed 🎉 I did notice though that the edit button is now text (it used to be a pencil icon before this branch), that seems a bit out of place?

<img width="902" alt="Screen Shot 2021-05-01 at 9 19 24 AM" src="https://user-images.githubusercontent.com/9613966/116765104-94800e00-aa5e-11eb-8bfb-717ab4537028.png">

2021-05-01 07:30 UTC, Tug commented
> I did notice though that the edit button is now text

I think that's the default media upload button on WPCOM. On self-hosted + jetpack site, it should still be a pencil icon

2021-05-04 02:08 UTC, aforcier commented
>I think that's the default media upload button on WPCOM (unrelated to this change). On self-hosted + jetpack site, it should still be a pencil icon

It looks like that may not be the case @Tug - those screenshots were from a self-hosted site. I checked again, this is a WPcom site before and after this branch:

![edit-icon-wpcom-beforeafter](https://user-images.githubusercontent.com/9613966/116941574-e5844200-acaa-11eb-9f96-0194ba276a82.png)

This is a self-hosted site:

![edit-icon-jetpack-beforeafter](https://user-images.githubusercontent.com/9613966/116941815-680d0180-acab-11eb-9846-52fcfe61af12.png)

Any idea what's going on?

2021-05-04 13:20 UTC, Tug commented
So it wasn't actually related to WPCOM vs self-hosted, but kind of: 
Jetpack is actually replacing this button with a custom one when 
- we have external services available for media upload (so google photos and pexels), it usually happens once you've connected your account with WordPress.com.
- it's not a gallery (we cannot use galleries as those are only for images)
The logic for this is defined [here](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/shared/external-media/index.js#L57).

This is so that the menu with the different sources to choose from can be injected.

We could either leave it as it is or try to update this component to try to re-use the `render` props of the original `MediaUpload` component.

@obenland what do you think? Can it be done without impacting other jetpack blocks?

2021-05-05 07:05 UTC, aforcier approved these changes
Per our discussion, let's not block this PR since keeping the pencil icon is not a straightforward change/involves other components beside the story block. We'll open an issue and look into that separately.

:shipit:

2021-05-05 07:15 UTC, Tug commented
Issue reported in https://github.com/Automattic/jetpack/issues/19742

2021-05-06 14:12 UTC, jeherve approved these changes

2021-05-06 17:15 UTC, merged

2021-05-07 07:51 UTC, Tug commented
Deployed on WPCOM with Changeset ID 225384