Subscriptions Block: Increase the priority of the subscriptions block…
Automattic/jetpack pull request #19760
Opened 2021-05-06 15:39 UTC by scruffian

… so that we can load patterns before the core ones load

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2021-05-06 21:22 UTC, apeatling approved these changes
Seems to continue to work with no issues. So giving it a 👍

2021-05-07 09:17 UTC, jeherve requested changes
You may have noticed the comment posted by a GitHub action at the top of your PR, and the action that keeps adding a "Needs Author Reply" label to your PR.

That's because your PR misses a changelog entry. I would recommend following the instructions in the comment to add one to your PR.

*******
You can learn more about the changelogger and how to use it here: p1HpG7-bqa-p2

2021-05-07 10:09 UTC, jeherve approved these changes

2021-05-07 10:23 UTC, merged

2021-05-07 12:55 UTC, scruffian commented
Deployed in r225410-wpcom