DocBlock for `jetpack_on_connection_ui_init` hook
Automattic/jetpack pull request #19846
Opened 2021-05-13 18:34 UTC by samiff

#### Changes proposed in this Pull Request:

* Quick follow up to https://github.com/Automattic/jetpack/pull/19820 to add a DocBlock for the `jetpack_on_connection_ui_init` hook.

#### Does this pull request change what data or activity we track or use?

* No.

2021-05-13 18:37 UTC, samiff commented
@jeherve When adding the `@since` part, how do you calculate which version to put there 🤔

2021-05-14 06:04 UTC, jeherve reviewed
> @jeherve When adding the `@since` part, how do you calculate which version to put there 🤔

That's something we've been discussing in p9dueE-2zB-p2
For now, and since we haven't completed that project, we still use Jetpack's version numbers for our docblocks.

2021-05-14 06:05 UTC, jeherve commented on projects/packages/connection-ui/src/class-admin.php
> +			* @since 1.0.2
```suggestion
			* @since 9.8.0
```

2021-05-14 17:07 UTC, jeherve requested changes
So much nitpicking, sorry! I'll commit this right away and approve.

2021-05-14 17:07 UTC, jeherve commented on projects/packages/connection-ui/src/class-admin.php
> +			*/
```suggestion
			 * Action called after initializing Connection UI Admin resources.
			 *
			 * @since 9.8.0
			 */
```

2021-05-14 17:07 UTC, jeherve approved these changes

2021-05-14 20:03 UTC, kraftbj approved these changes

2021-05-14 20:37 UTC, merged