Connection: disconnect user from wpcom before to do so locally
Automattic/jetpack pull request #19865
Opened 2021-05-17 14:26 UTC by jeherve

Fixes #19857

#### Changes proposed in this Pull Request:
We now attempt to make the request to disconnect the user from WordPress.com before we delete the connected data locally.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* TBD

2021-05-17 17:45 UTC, kbrown9 requested changes
I tested this using the provided testing instructions, and the user was disconnected as expected.

I think it would be nice to include a test that verifies that the local user token is not deleted when the remote disconnection fails. It would probably be an integration test, and the purpose of the test would be to catch the bug that is fixed by this PR. What do you think?

2021-05-18 14:23 UTC, jeherve commented
> I think it would be nice to include a test that verifies that the local user token is not deleted when the remote disconnection fails. It would probably be an integration test, and the purpose of the test would be to catch the bug that is fixed by this PR. What do you think?

That makes sense. I'm not quite sure how to best go about this though. I pushed 39e791c0914e44213d28df911e04c8bd5037de88, but I don't think it's very useful. Right now the disconnection attempt fails in the test by default because the external XML-RPC request fails.

What should I do here? Should I aim to mock the response of the `unlink_user_from_wpcom` method just like I did in the other test, or somehow mock the response of the XML-RPC request itself, and add different use-cases to my test, with different outcomes based on whether the XML-RPC request is successful or not? I've tried to do the latter in 8faeaf386266d1f47cd523d40a0106664a119b96, but that doesn't work. Maybe because `Manager()` doesn't use my mocked `Jetpack_IXR_Client`? I'm not sure how to work around that, I assume we want to limit the mocks we have in our integration suite?

2021-05-18 19:31 UTC, kbrown9 commented
> What should I do here? Should I aim to mock the response of the `unlink_user_from_wpcom` method just like I did in the other test, or somehow mock the response of the XML-RPC request itself, and add different use-cases to my test, with different outcomes based on whether the XML-RPC request is successful or not? I've tried to do the latter in [8faeaf3](https://github.com/Automattic/jetpack/commit/8faeaf386266d1f47cd523d40a0106664a119b96), but that doesn't work. Maybe because `Manager()` doesn't use my mocked `Jetpack_IXR_Client`? I'm not sure how to work around that, I assume we want to limit the mocks we have in our integration suite?

Good questions! I pushed commit 2902741, which mocks the response of the XML-RPC request with a success or fail code. What do you think of that general approach? If you switch the order of the disconnects, so that the local disconnect happens before the remote disconnect, the test `Automattic\Jetpack\Connection\ManagerIntegrationTest::test_disconnect_user with data set "failure" (false, 2)` should fail.

2021-05-19 15:42 UTC, jeherve commented
> What do you think of that general approach?

I like it, thanks for adding this all! This should now be ready for review then.

2021-05-19 16:14 UTC, sdixon194 approved these changes
this works for me! I'll hold off on merging until @kbrown9 can also take a look since the tests are added.

2021-05-19 16:22 UTC, kbrown9 commented on projects/packages/connection/tests/php/test_Manager_integration.php
> +	 * Intercept the disconnect user API request sent to WP.com, and mock success response.
I just noticed my own typo:
```suggestion
	 * Intercept the disconnect user API request sent to WP.com, and mock failure response.
```

2021-05-19 17:24 UTC, sdixon194 approved these changes

2021-05-19 18:35 UTC, kbrown9 approved these changes

2021-05-20 06:41 UTC, merged