Story block: Make stories available in the block inserter
Automattic/jetpack pull request #19875
Opened 2021-05-18 09:41 UTC by Tug

#### Changes proposed in this Pull Request:
This is the release PR for the story block. It just flips the switch and makes the block available from the inserter in production.

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* Run `yarn build-production`
* Load the editor, make sure the story block is available from the inserter and works as expected

2021-05-20 05:46 UTC, aforcier submitted a review, later dismissed
Working great! Tested with a production Jetpack build and on WP.com. :shipit: 🎉

2021-05-20 09:49 UTC, jeherve requested changes

2021-05-20 13:43 UTC, Tug commented on projects/plugins/jetpack/extensions/blocks/story/index.js
> +		inserter: true,
👍

2021-05-20 13:44 UTC, Tug commented
I have addressed your feedback @jeherve. Btw let's hold off the merge for a bit on this one as I'd like https://github.com/Automattic/jetpack/pull/19876 to land first.

2021-05-20 13:48 UTC, jeherve approved these changes
Ready to merge whenever you are ready to push the button.

2021-05-21 02:59 UTC, aforcier approved these changes

2021-05-24 07:56 UTC, Tug commented
As discussed on other channels with @aforcier let's not wait for #19876 which will need extensive testing before it gets merged.

2021-05-24 08:24 UTC, merged

2021-05-24 15:07 UTC, Tug commented
Deployed to WPCOM with changeset ID 226118