Gif Block: Fix issues in Widget Editor / Customizer
Automattic/jetpack pull request #20044
Opened 2021-06-08 17:48 UTC by apeatling

Fixes https://github.com/Automattic/jetpack/issues/19962

#### Changes proposed in this Pull Request:

* Fix an issue where the customizer would ask to redirect away when selecting a gif after searching

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Go to the customizer with a non block theme activated
* Edit a widget area and add a GIF block
* Search for a gif and select a thumbnail
* Confirm the thumbnail is selected, and the gif appears in the preview
* Confirm the customizer does not try to redirect away to another page.

2021-06-08 20:49 UTC, apeatling commented
This PR also includes an update to rendering the CSS and JS for blocks inside of the live customizer preview pane after autosaves. You can read a bit more about that here: https://github.com/Automattic/view-design/issues/275#issuecomment-857003756

2021-06-15 18:28 UTC, apeatling commented
I have reported the issue in Gutenberg regarding the CSS/JS not loading in the live preview: https://github.com/WordPress/gutenberg/issues/32706

The fix in this PR will allow us to continue and get all of our blocks working in the Customizer in the meantime, until a fix for this filters through.

2021-06-15 20:53 UTC, stacimc approved these changes
This tests well for me. I verified that I could see the redirect bug on master, then checked out this branch and confirmed:

- [x] Adding a new Gif block and searching for a gif works
- [x] A selected gif's thumbnail is visibly selected
- [x] A selected gif renders correctly in the preview, and the user is not prompted to leave the page
- [x] When the post is saved and the page is reloaded, the gif continues to load correctly in the preview
- [x] Gif displays correctly on the frontend of the site

For the asset enqueueing, I don't have any better suggestions and this solution is testing well for me (I also quickly tested using Image Compare block when inserting and when reloading the page). LGTM and will unblock other widget issues 👍

2021-06-15 20:59 UTC, stacimc requested changes
Actually, looks like there's just a failing unit test/ merge needed.

2021-06-15 22:38 UTC, stacimc approved these changes

2021-06-16 21:18 UTC, samiff approved these changes
I was able to reproduce the issue on JN with Gutenberg v10.8.2, and this PR resolved the issue of the preview not updating.

@apeatling Not quite sure why repro failed over at https://github.com/WordPress/gutenberg/issues/32706#issuecomment-862282902

2021-06-17 17:02 UTC, apeatling commented
Possibly only a dotcom issue? Maybe some overzealous kses? I'll merge this and do some digging.

2021-06-17 17:02 UTC, merged