Image Carousel: Show carousel enable toggle in media options.
Automattic/jetpack pull request #20056
Opened 2021-06-10 09:21 UTC by cpapazoglou

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2021-06-11 10:48 UTC, BogdanUngureanu commented
LGTM and works perfectly on a WoA! 🎉

2021-06-11 12:47 UTC, BogdanUngureanu approved these changes

2021-06-11 13:17 UTC, jeherve requested changes
That seems a bit confusing to me. The toggle doesn't really do anything on Jetpack sites. It will only appear when the feature is already on, and toggling it off will not disable the module, nor feature. If it did, the toggle would then disappear when toggling off the setting, and the toggle wouldn't be there for folks to enable the feature back afterwards.

2021-06-15 12:00 UTC, cpapazoglou commented
Thanks @jeherve for chiming in!

> That seems a bit confusing to me. The toggle doesn't really do anything on Jetpack sites. It will only appear when the feature is already on, and toggling it off will not disable the module, nor feature. If it did, the toggle would then disappear when toggling off the setting, and the toggle wouldn't be there for folks to enable the feature back afterwards.

Aha, that's true. For Jetpack self hosted sites & Atomic sites the `Enable Carousel` in `/wp-admin/options-general.php` toggle (even if visible) does nothing. 

The goal was to bring parity between Simple & Atomic sites. Simple sites do have this option and works as advertised. Is there a technical or business problem that hinders us from having the same behavior in Atomic & Jetpack sites?

2021-06-15 15:33 UTC, jeherve commented
> Is there a technical or business problem that hinders us from having the same behavior in Atomic & Jetpack sites?

I can think of 2 potential issues here.

1. We had moved away from having new Jetpack settings in various core wp-admin settings screens in the past, for different reasons: having the settings in the Jetpack dashboard helps highlighting the value of Jetpack, and avoids any confusion for folks who may see a setting in a core setting screen and who may not know that the setting is actually a Jetpack feature.
2. Technically, if the toggle were to disable the module, then the code that adds the toggle would stop running when you toggle the feature off, so you would never see the toggle when it's off. I don't know that it's a great user-experience.

I don't really have a solution here though, sorry. We cannot really have the code that manages the toggle being always loaded, whether you use the module or not; that defeats the purpose of the module.

2021-06-16 08:53 UTC, cpapazoglou commented
> > Is there a technical or business problem that hinders us from having the same behavior in Atomic & Jetpack sites?
> 
> I can think of 2 potential issues here.
> 
> 1. We had moved away from having new Jetpack settings in various core wp-admin settings screens in the past, for different reasons: having the settings in the Jetpack dashboard helps highlighting the value of Jetpack, and avoids any confusion for folks who may see a setting in a core setting screen and who may not know that the setting is actually a Jetpack feature.
> 2. Technically, if the toggle were to disable the module, then the code that adds the toggle would stop running when you toggle the feature off, so you would never see the toggle when it's off. I don't know that it's a great user-experience.
> 
> I don't really have a solution here though, sorry. We cannot really have the code that manages the toggle being always loaded, whether you use the module or not; that defeats the purpose of the module.

Your points make perfect sense! I am closing this as the options may be adjusted from `/wp-admin/admin.php?page=jetpack#/writing`.

2021-06-16 08:53 UTC, closed without merging