CarouselL prevent zoom transition slide
Automattic/jetpack pull request #20210
Opened 2021-06-29 05:48 UTC by ramonjd

Maybe kinda hopefully Fixes https://github.com/Automattic/view-design/issues/309

#### Changes proposed in this Pull Request

This PR hides previous and next slides in touch devices to prevent the flying transition after pinch, zoom and slide described in https://github.com/Automattic/view-design/issues/309

Here's how it looks with the changes:

https://user-images.githubusercontent.com/6458278/123742819-a57abd80-d8ef-11eb-8531-67f29004d291.MP4

With these changes we are losing previous and next image visibility. Is that acceptable?

Note the end of the video: this is browser navigation behaviour, over which we don't have much control.

#### Jetpack product discussion
p9Jlb4-2cI-p2

#### Does this pull request change what data or activity we track or use?
Nah.

#### Testing instructions

1. Create a carousel gallery and preview it in a touch device
2. Check that swiping through images works
3. Pinch and zoom and image and slide to the next image, making sure you don't trigger an edge-swipe browser navigation (keep your pointer finger/thumb clear of the edge of your device)
4. You should not see the flying transition

2021-06-29 19:57 UTC, apeatling commented
This feels like a bit too much of a regression in swiping to me. It makes it feel much less smooth. Is it possible to go from zero opacity to 100 opacity based on slide position?

2021-06-29 19:57 UTC, apeatling requested changes, later dismissed
This feels like a bit too much of a regression in swiping to me. It makes it feel much less smooth. Is it possible to go from zero opacity to 100 opacity based on slide position?

2021-06-30 02:37 UTC, ramonjd commented
> This feels like a bit too much of a regression in swiping to me. It makes it feel much less smooth. Is it possible to go from zero opacity to 100 opacity based on slide position?

@apeatling Thanks for the review! 

I think I found a more appropriate way to do this, removing transitions on prev/next image elements.

2021-06-30 06:00 UTC, andrewserong approved these changes, later dismissed
Works well, looks like a nice clean fix in the end, thanks for getting to the bottom of this one @ramonjd!

Tests nicely in Safari iOS and Chrome iOS. The double-tap transition to zoom in and out is still working nicely in Safari, and I can no longer see the weird zoom transition in the original issue:

https://user-images.githubusercontent.com/14988353/123909139-f48e2480-d9bb-11eb-833f-d9baaa6d9b55.MP4

Double checked in Safari, Chrome, FF and Edge that this doesn't affect the slide left / right transitions. LGTM!

2021-06-30 09:40 UTC, jeherve approved these changes

2021-06-30 09:48 UTC, merged

2021-06-30 10:35 UTC, jeherve commented
Cherry-picked to `jetpack/branch-9.9` in 57ed574bbf1119848313aa049e5c37d387062ef1

2021-07-01 20:08 UTC, apeatling commented
Great fix @ramonjd, thanks!