Admin page: remove a duplicated line
Automattic/jetpack pull request #20258
Opened 2021-07-05 02:52 UTC by kangzj

#### Changes proposed in this Pull Request:
Removed a duplicated line.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to a Jetpack connected site, make sure Jetpack menu items are correctly added.

2021-07-05 11:07 UTC, jeherve requested changes
Good catch. It looks like it was added in #15429, maybe during a rebase by mistake. 

This PR will need a changelog though.

2021-07-05 21:51 UTC, kangzj commented
> Good catch. It looks like it was added in #15429, maybe during a rebase by mistake.
> 
> This PR will need a changelog though.

Thanks @jeherve for looking into this. Changelog added.

2021-07-06 02:16 UTC, bluefuton approved these changes

2021-07-06 06:23 UTC, jeherve approved these changes

2021-07-06 06:23 UTC, merged