Update to latest Node 14
Automattic/jetpack pull request #20259
Opened 2021-07-05 04:00 UTC by kraftbj

Fixes https://nodejs.org/en/blog/vulnerability/july-2021-security-releases/

#### Changes proposed in this Pull Request:

* Updates to demand latest version of Node 14 to ensure everyone has updates versions and match Calypso.

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* `jetpack build plugins/jetpack` -- does it build?
*

2021-07-05 16:52 UTC, jeherve requested changes

2021-07-05 16:52 UTC, jeherve commented on .nvmrc
> +14.17.2
Looks like you'll need to update a few more places, like `.github/versions.sh`.

2021-07-06 10:27 UTC, jeherve submitted a review, later dismissed
This looks good to me. 

@anomiex Is `v14.17.2` available to you?

2021-07-06 15:36 UTC, anomiex commented
No, Debian's experimental package is still 14.17.0 at the moment. I'm starting to wonder if I should give up on using the distro package and start using nvm or volta or something, since I'm already using the package from experimental anyway.

One possibility so we don't have to wait on me to do that is that we could separate the "match Calypso" (i.e. update .nvmrc and versions.sh) and "force everyone to update" (i.e. update the range in package.json) parts of the PR.

2021-07-08 05:44 UTC, scinos commented
FYI, Calypso is jumping to 14.17.3 (https://github.com/Automattic/wp-calypso/pull/54373), as there was some problem with CircleCI images that forced us to revert the 14.17.2 update (https://github.com/Automattic/wp-calypso/pull/54275#issuecomment-875252037)

2021-07-08 14:33 UTC, jeherve submitted a review, later dismissed
Looks good to me. 👍

2021-07-09 20:39 UTC, kraftbj commented
@anomiex What say you? Should I split things or are you game for using `nvm`?

2021-07-12 13:40 UTC, anomiex commented
Depends on how soon you want this merged. I'll need to find time to figure out and set up a solution.

2021-07-14 15:11 UTC, kraftbj commented
@anomiex I'm in no particular rush. I'd like to keep things up to date, but anyone using Calypso would have already upgraded and that setup should still work for us.

The updates between major versions are more critical to figure out a timeline.

2021-12-13 19:03 UTC, kraftbj commented
Superseded by #20827

2021-12-13 19:03 UTC, closed without merging