Beta: Soft fail if Composer pkgs not installed
Automattic/jetpack pull request #20341
Opened 2021-07-12 21:07 UTC by kraftbj

#### Changes proposed in this Pull Request:

* Provide a soft fail if activating Beta without having `jetpack install plugins/beta`.

This is the same experience as Jetpack in the same situation.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* `jetpack clean plugins/beta` and clean everything.
* In Docker, activate Beta. See hard fatal.
* On this branch, same thing. See error message.
* `jetpack install plugins/beta`
* See the plugin work.

2021-07-13 10:05 UTC, jeherve requested changes
Looking good. I just have some minor indentation / textdomain suggestions.

2021-07-13 10:05 UTC, jeherve commented on projects/plugins/beta/jetpack-beta.php
> +						__( 'Your installation of Jetpack Beta is incomplete. If you installed Jetpack Beta from GitHub, please refer to <a href="%1$s" target="_blank" rel="noopener noreferrer">this document</a> to se
```suggestion
						__( 'Your installation of Jetpack Beta is incomplete. If you installed Jetpack Beta from GitHub, please refer to <a href="%1$s" target="_blank" rel="noopener noreferrer">this document</a> to set up your development environment.', 'jetpack-beta' ),
```

2021-07-13 10:05 UTC, jeherve commented on projects/plugins/beta/jetpack-beta.php
> +	 */
```suggestion
	 * Outputs an admin notice for folks running Jetpack Beta without having run composer install.
	 *
	 * @since 3.0.0
	 */
```

2021-07-13 10:05 UTC, jeherve commented on projects/plugins/beta/jetpack-beta.php
> +			/* translators: Placeholder is a link to a support document. */
```suggestion
				/* translators: Placeholder is a link to a support document. */
```

2021-07-13 10:05 UTC, jeherve commented on projects/plugins/beta/jetpack-beta.php
> +					/* translators: Placeholder is a link to a support document. */
```suggestion
						/* translators: Placeholder is a link to a support document. */
```

2021-07-13 16:24 UTC, anomiex reviewed
Seems ok to me, other than the stuff Jeremy pointed out already.

2021-07-14 08:38 UTC, jeherve approved these changes

2021-07-14 08:50 UTC, merged