Form Block: fix form alignment
Automattic/jetpack pull request #20540
Opened 2021-08-03 15:10 UTC by jeherve

Fixes #18933

#### Changes proposed in this Pull Request:

The button alignment options, Left - Center - Right, have an issue while in the editor to not display the buttons alignment correctly.

Able to replicate the issue for Right alignment only.  The Left and Center alignment worked while using the editor to align a forms button. (Tested on themes: Twenty Twenty One and Storefront)

**Note**: Although the editor for alignment may be off, on the live site is was working to align the button. 

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Go to a new 'Post'
* Make a new block for a form, select Contact Form or Newsletter Sign-up
* Edit the new form
* Click on the submit button for the form you selected
* Align the button left/center/right

![align-editor](https://user-images.githubusercontent.com/11654917/126931832-c2c6e5c2-8a89-4c2e-a15a-ae24480d51b4.gif)

2021-08-04 15:10 UTC, sdixon194 requested changes
This works, just a comment on the changelog entry.

Noticed it's not quite aligned right with the form block on the live site, but this seems to be an existing issue not introduced by this PR: 

![Screen Shot on 2021-08-04 at 11:06:03](https://user-images.githubusercontent.com/33553323/128205396-b43a9dd4-06be-46fe-b26d-43d3b8836039.png)

2021-08-04 15:10 UTC, sdixon194 commented on projects/plugins/jetpack/changelog/fix-contact-form-editor-width
> +Form Block: fix form button alignment
```suggestion
Form Block: fix form button alignment in editor
```

The alignment seems to have been working on the front end, it was just the editor that aligning right wasn't reflected, which is what this PR fixes.

2021-08-05 18:55 UTC, sdixon194 approved these changes

2021-08-06 17:42 UTC, merged

2021-08-06 17:49 UTC, jeherve commented
r229942-wpcom