Backup: update readme short description
Automattic/jetpack pull request #20708
Opened 2021-08-16 16:11 UTC by vianasw

We were exceeding the 151 characters limit for the short description
section on the Backup plugin readme.txt file.

#### Changes proposed in this Pull Request:
Changed short description section in the readme.txt file to conform to the 151 characters limit.

#### Jetpack product discussion
No

#### Does this pull request change what data or activity we track or use?
No
#### Testing instructions:
Check for typos.

2021-08-16 16:20 UTC, jeherve requested changes
I'm afraid that's still one character too long, so you'll get an ellipsis added to the end of it:

![image](https://user-images.githubusercontent.com/426388/129596232-79ba31f0-14e8-47e2-a4d9-98a9e0b9372c.png)

2021-08-16 16:26 UTC, vianasw commented
> I'm afraid that's still one character too long, so you'll get an ellipsis added to the end of it:
> 
> ![image](https://user-images.githubusercontent.com/426388/129596232-79ba31f0-14e8-47e2-a4d9-98a9e0b9372c.png)

I think I misunderstood the limit then. Let's see.

2021-08-17 08:25 UTC, jeherve approved these changes

2021-08-18 11:39 UTC, merged

2021-08-18 11:44 UTC, vianasw commented
Cherry-pick: a042d10c0b5bbf1a9f0983d727768cd9bc40e5ea