Search: Fix chosen filter options not visible when no results returned
Automattic/jetpack pull request #20700
Opened 2021-08-16 06:42 UTC by kangzj

Fixes #14179

#### Changes proposed in this Pull Request:
The PR proposed a solution where the frontend cache the Aggregations object, and then use to to still show the filters when there's no result. When the overlay open/closes, the cache would be cleared.

The patch only works when there's no result and there are filters in the URL, so it wouldn't affect normal search flow.

I considered to put the filter label in the URL, but which could potentially cause XSS issue or show unwanted content on the page.

Another solution would be checking the filters on the backend, which basically requires a re-write of a few frontend modules, not very ideal considering it's a temporary solution.

The ultimate solution would be changes from the Search API side, and return filters on all requests, which would need support from elastic search side.

#### Jetpack product discussion
pcNPJE-av-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to a site with Jetpack subscription
- Search something and then check one/more filter options
- Continue to enter the query until there's no results
- Ensure the filters are still visible for users to uncheck

![Screen Capture on 2021-08-16 at 18-40-54](https://user-images.githubusercontent.com/1425433/129521762-14d09db0-d791-45cb-ae24-5ada8748d338.gif)

2021-08-23 22:55 UTC, annacmc commented
I gave this a spin on desktop & mobile and in both cases it worked as expected for me 😄

2021-09-01 22:24 UTC, samiff requested changes, later dismissed
This worked well for me 👍 

Looks like there are a couple `modules/search/instant-search/store/test/reducer.test.js` tests failing here though, could you have a look @kangzj thanks!

2021-09-02 00:02 UTC, jsnmoon reviewed
This change works exactly as described, enabling users to deselect overly restrictive filters when there are no search results. 

Here's a UX improvement I'd like to propose, which should fully address #14179: What do you think about caching all the aggregations, all the time? Here's an example to illustrate what I mean:

<table>
<tr>
	<td> 
<img width="894" alt="Screen Shot 2021-09-01 at 5 40 51 PM" src="https://user-images.githubusercontent.com/4044428/131759306-17048bfa-3c63-40fe-b096-1198d57646d9.png">

We start with an empty query, which shows all possible aggregations for the site.

<tr>
	<td>
<img width="894" alt="Screen Shot 2021-09-01 at 5 40 57 PM" src="https://user-images.githubusercontent.com/4044428/131759353-2f02f230-3656-4c4e-80ea-ff2b7cf4c83b.png">

I enter a query for "home" and all aggregations that no longer apply are removed from the sidebar.
<tr>
	<td>
<img width="894" alt="Screen Shot 2021-09-01 at 5 40 59 PM" src="https://user-images.githubusercontent.com/4044428/131759724-e7ca619c-e8bc-4a9d-a1d7-4a067b9c7c4c.png">

Suggested change: Instead of removing the aggregations, what if we kept them and disabled checkboxes for buckets without any results? In other words, we would always show all aggregations, all the time.
</table>

One potential issue I see with this approach is that it could get unwieldy for month or year date filters. In order to allow site owners to deal with this, we could:

1. Add a class name to the SearchFilter container (e.g. `jetpack-instant-search__search-filter`).
2. Add a class name to individual filter options (e.g. `jetpack-instant-search__search-filter-bucket`).
3. Add an additional class name to individual filter options with 0 results (e.g. `jetpack-instant-search__search-filter-bucket--empty`).

This will enable site owners to manually hide the excess checkboxes via CSS when appropriate.

2021-09-03 04:29 UTC, kangzj commented
> Here's a UX improvement I'd like to propose, which should fully address #14179: What do you think about caching all the aggregations, all the time? Here's an example to illustrate what I mean:

Hi @jsnmoon thanks for the suggestions. I tried to cache all the aggregations before, it worked. But we'll have to consider more situations. For example, ordering, say if an option is selected we have to promote it to be visible because there are limitation on number of filter options etc. And also it could end up in a very long empty list which doesn't make a lot of sense. 
I'm sure there are a lot to improve for the current solution, but considering it's a temporary solution, I don't think we'll want to put that much time in, do we?

>  disabled checkboxes for buckets without any results

This is added.

And I had another thought about it, changed the following.
- We don't really need to put the cached aggregations in the state - a local variable works just fine. 
- Unit test added

Let me know what you think, thanks.

2021-09-08 00:25 UTC, jsnmoon reviewed
> I tried to cache all the aggregations before, it worked. But we'll have to consider more situations. For example, ordering, say if an option is selected we have to promote it to be visible because there are limitation on number of filter options etc. And also it could end up in a very long empty list which doesn't make a lot of sense. (@kangzj)

Fair points. In that case, shipping this implementation and continuing to iterate makes a lot of sense. I left a comment inline requesting one small change, but everything else looks good to go with this PR.

2021-09-08 00:25 UTC, jsnmoon commented on projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js
> +function mergeCachedAggregations( previousCachedAggregations, newAggregations ) {
Could we add a unit test for this function?

2021-09-22 18:41 UTC, samiff commented
@kangzj Were you hoping to get this PR into Jetpack 10.2? If so, the code freeze date is: 2021-09-28 Please add the `[Status] Needs review` label once it's ready for Crew to have a look 👍

2021-09-23 09:40 UTC, kangzj commented
> @kangzj Were you hoping to get this PR into Jetpack 10.2? If so, the code freeze date is: 2021-09-27

Hi @samiff thanks for the kind reminder. I'll still have to revisit this to make sure it works as expected. Will try to make it in 10.2. Thanks

2021-10-01 01:23 UTC, kangzj commented
Added unit test and rebased.

2021-10-04 23:18 UTC, jsnmoon reviewed
Looks good to me. Feel free to mark for crew review whenever you're ready.

I left some nitpicky suggestions for improving code readability.

2021-10-04 23:18 UTC, jsnmoon commented on projects/plugins/jetpack/modules/search/instant-search/lib/api.js
> +export function setAggregationCountToZero( newAggregations ) {
```suggestion
export function setDocumentCountsToZero( newAggregations ) {
```

2021-10-04 23:18 UTC, jsnmoon commented on projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js
> +			// - we use the cache to show filters if there are not results
```suggestion
			// For a new search requests (i.e. not pagination requests):
			// - Cache aggregations if query yields results
			// - Show previously cached aggregations if query does not yield any results
```

2021-10-04 23:18 UTC, jsnmoon commented on projects/plugins/jetpack/modules/search/instant-search/store/test/reducer.test.js
> +	test( 'could replace aggregation with cached aggregation when result is empty', () => {
```suggestion
	test( 'returns cached aggregations when no search results are available', () => {
```

2021-10-05 02:53 UTC, kangzj commented on projects/plugins/jetpack/modules/search/instant-search/lib/api.js
> +export function setAggregationCountToZero( newAggregations ) {
changed in d5c06c86c5

2021-10-05 10:26 UTC, jeherve approved these changes
This seems to test well for me. 🚢

2021-10-05 21:00 UTC, merged

2021-10-05 21:07 UTC, kangzj commented
🚢 r232807-wpcom