Triage: update issue forms and automate label updates
Automattic/jetpack pull request #20726
Opened 2021-08-17 15:32 UTC by jeherve

#### Changes proposed in this Pull Request:

GitHub recently updated their issue predefs, and now allow you to create issue forms. Those are interactive, rather than just relying on inline comments in the issue body placeholder, so there is more chance that they'll actually be used.

In this PR, I've done the following:
﻿- Add new GitHub issue form handlers.
- Remove old templates that will be replaced by our new setup.
- Listen to changes to issues in our Gardening action (issues opened or reopened).
- Gardening: add new task to automatically add labels to new issues, based on the standardized content of the new issues.

This should help us better triage new issues in the monorepo, and thus help make sure that plugin authors, regardless of the plugin, can get to their issues faster, without having to rely on manual triage.

#### Jetpack product discussion

* No

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Check for typos
* I'm not sure we can check the new task before this gets merged.

2021-08-17 16:06 UTC, kraftbj reviewed
small change, I'll commit it and approve it.

2021-08-17 16:06 UTC, kraftbj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +description: Report issues with one of our products
```suggestion
description: Report issues with one of our products.
```

2021-08-17 16:07 UTC, kraftbj submitted a review, later dismissed

2021-08-17 16:39 UTC, sdixon194 requested changes
Some typo changes.

2021-08-17 16:39 UTC, sdixon194 commented on .github/ISSUE_TEMPLATE/enhancement.yml
> +      description: If applicable, add screenshots, mockup, aminations and/or videos to help illustrate what the change could look like.
```suggestion
      description: If applicable, add screenshots, mockup, animations, and/or videos to help illustrate what the change could look like.
```

2021-08-17 16:39 UTC, sdixon194 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      description: If applicable, add screenshots, mockup, aminations and/or videos to help illustrate how the feature could be done.
```suggestion
      description: If applicable, add screenshots, mockup, animations, and/or videos to help illustrate how the feature could be done.
```

2021-08-17 17:37 UTC, sdixon194 approved these changes

2021-08-17 17:37 UTC, sdixon194 approved these changes

2021-08-18 07:47 UTC, merged

2021-08-18 07:51 UTC, jeherve commented
Here is the end result:

![image](https://user-images.githubusercontent.com/426388/129859119-72c336b6-eccf-44c2-9ce2-fa81f78f6cf3.png)

It looks like GitHub adds its own security entry since we have a [Security policy file](https://github.com/Automattic/jetpack/blob/master/SECURITY.md). Do you think I should remove the extra Security link I added at the bottom?

And a test issue: #20735 

The Gardening action appears to be working:

https://github.com/Automattic/jetpack/actions/runs/1142282250

![image](https://user-images.githubusercontent.com/426388/129859637-9b318ecb-fab6-4682-9876-a74fed1df441.png)

2021-08-18 10:52 UTC, kraftbj commented
I could be convinced either way, but I vote for removing it. Keeps it cleaner and one less thing to change if we ever move from H1.

2021-08-18 13:04 UTC, jeherve commented
👍 Done in #20738.