Sync: Defensive coding against E_NOTICE
Automattic/jetpack pull request #20921
Opened 2021-09-01 19:58 UTC by kraftbj

Fixes a series of E_NOTICEs thrown when testing on w.org:

```
E_NOTICE: Undefined index: pop in /home/wporg/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:47
```

```
E_NOTICE: Undefined index: encode in /home/wporg/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:66
```

```
E_NOTICE: Undefined index: encode in /home/wporg/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:73
```

#### Changes proposed in this Pull Request:

* Adds some checks.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Unclear how to reproduce, going off of log review.
*

2021-09-01 20:06 UTC, mdbitz requested changes
Thanks Kraft, can we have $encode default to true to match the default behavior of get_items_to_send?

2021-09-01 20:06 UTC, mdbitz commented on projects/packages/sync/src/class-rest-sender.php
> +		$encode = isset( $args['encode'] ) ? $args['encode'] : null;
default state for encode needs to be true

2021-09-02 10:58 UTC, mdbitz approved these changes
Verified and approved.

2021-09-02 16:11 UTC, anomiex reviewed
Looks ok at a quick read-through, but needs a version bump. Also I see there's a use of `$args['force']` on line 51 that might want similar treatment.

An alternative option (feel free to ignore) to handle defaulting in `$args` would be to do something like this at the top of the method:
```php
// Supply defaults.
$args += array(
    'pop' => false,
    'force' => false,
    'encode' => true,
);
```
Maybe more clear (since we can't use `??`), at the cost of maybe doing unnecessary initialization.

2021-09-03 13:46 UTC, mdbitz commented
Also note that I'm updating the Jetpack_Sync_Manager to send default values for these args: D66344

2021-09-03 15:29 UTC, merged

2021-09-03 17:04 UTC, sdixon194 commented
Cherry picked to release branch in 2ba49d0424272d0204f986a9924a31d8362888ac and released new version of Jetpack Sync