[WIPChange add "new plugin" menu item destination to calypso.
Automattic/jetpack pull request #20949
Opened 2021-09-03 13:54 UTC by cpapazoglou

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2021-09-08 14:03 UTC, cpapazoglou commented
@gavande1 we will need your review here since both me & Tom have worked on this!

2021-09-08 14:56 UTC, obenland commented
Can you help me understand why `admin_menu` doesn't work as a hook to change those submenu items?

2021-09-08 15:12 UTC, cpapazoglou commented
> Can you help me understand why `admin_menu` doesn't work as a hook to change those submenu items?

I am under the impression that we need to use `update_submenus` 

https://github.com/Automattic/jetpack/blob/7cc8664228b1ac51a738d3a2c99ca2d2e795a179/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php#L175

for menus that we want just to change their link. By using the `wpcom_plugins_submenu_update` specific hook we can avoid the implementation details. We wanted to establish a pattern here but now I understand that this might be an anti-pattern. We could probably still use `update_submenus` from wpcomsh in an `admin_menu` hook. @BogdanUngureanu, since you have worked on this, what's your take here?

2021-09-08 19:49 UTC, BogdanUngureanu commented
> I am under the impression that we need to use update_submenus

update_submenus() is useful in cases when you want to replace an existing submenu item and still keep the existing (especially core specific menus) active. This is useful when you want to keep the old interfaces available but not visible in the menu. Also, in several cases for core submenus, keep backwards compatibility with third-party plugins (many plugins are registering pages referencing core submenus - if the core pages are removed, those plugin pages will break as well).

In this case I think update_submenu() makes sense. 

> Can you help me understand why admin_menu doesn't work as a hook to change those submenu items?

I think it could work to register a hook on `admin_menu`, however, this would not be as solid as with a custom hook. Currently, we are manipulating the menus using a priority of `99998`. So, in this case, we would need to make the priority in wpcomsh to `99999` to be able to reregister the menu after the nav-unification manipulations are done. 

The problem with this is that if in the future we change this to a different priority, the implementation from wpcomsh might not work properly without modifying the priority in there as well. 

Personally I think we could expand on this further and have a more generic take on this by using instead a custom action and passing the entire Admin_Menu object as an argument. This way, you could have access directly to the update_submenus() and other methods the admin menu object has, allowing a more flexible API with the benefit of autocomplete. It's up to you to follow this or not (or if it's worth it). :) 
```
do_action('after_nav_unification_registered', $this); // $this will represent the Base_Admin_Menu object.
```

an implementation in wpcomsh would look like this:
```
function wpcomsh_add_my_submenu(Base_Admin_Menu $menu) {
    $menu->update_submenus(.....);
}

add_action( 'after_nav_unification_registered', 'wpcomsh_add_my_submenu' );
....
```

The only thing is that you have to find where to add the do_action:
-  Add it in Admin_Menu, after the reregister_menu is executed **or**
- Add it in Admin_Menu constructor as an action to `admin_menu` with a 9999 priority (right after the admin_menu). Sure, it's still coupled to 9998 priority of the reregister, but priorities would be defined in the same place.

2021-09-08 21:30 UTC, obenland commented
The Nav Unification architecture is almost as complex as the environments it runs in. I think if there's an opportunity to simplify it (or even to not increase its complexity) and make it more accessible to developers that are unfamiliar with its intricacies, it's probably worth the consideration.

If we believe that a third-party plugin should be able to do what wpcomsh is trying to do here, what changes—if any—would be necessary for that?

2021-09-08 21:41 UTC, obenland commented
Would overriding `add_plugins_menu()` in `Atomic_Admin_Menu` be an option for this functionality?

2021-09-09 08:20 UTC, cpapazoglou commented
> Would overriding `add_plugins_menu()` in `Atomic_Admin_Menu` be an option for this functionality?

It would probably be enough for changing a menu, yes. In our case though we want to handle this behavior with a blog-sticker in wpcomsh 741-gh-Automattic/wpcomsh. When the feature is finally launched, we can move the code back to Jetpack.

2021-09-10 12:51 UTC, gavande1 commented
I've tested it on my WoA site and Simple site. The solution works as expected. Great Job 🎉 

We'll probably need to add the same fix for the `Add New` button on the plugins list page as well. 

![](https://cloudup.com/cYeCB6ky7_j+)

2021-09-13 08:20 UTC, cpapazoglou commented
> I've tested it on my WoA site and Simple site. The solution works as expected. Great Job 🎉
> 
> We'll probably need to add the same fix for the `Add New` button on the plugins list page as well.
> 
> ![](https://camo.githubusercontent.com/be8959f5daff63f7c58ecb3bb1a6f74ecf8bebabf5e0637d3b39d4c2a4640405/68747470733a2f2f636c6f756475702e636f6d2f6359654342366b79375f6a2b)

This is the hook we can use `apply_filters( 'self_admin_url', $url, $path, $scheme );` for that case.

2021-09-13 11:11 UTC, cpapazoglou commented
> > I've tested it on my WoA site and Simple site. The solution works as expected. Great Job 🎉
> > We'll probably need to add the same fix for the `Add New` button on the plugins list page as well.
> > ![](https://camo.githubusercontent.com/be8959f5daff63f7c58ecb3bb1a6f74ecf8bebabf5e0637d3b39d4c2a4640405/68747470733a2f2f636c6f756475702e636f6d2f6359654342366b79375f6a2b)
> 
> This is the hook we can use `apply_filters( 'self_admin_url', $url, $path, $scheme );` for that case.

We will address this change in a separate PR (probably wpcomsh only) since it's not related to the admin_menu.

2021-09-13 16:25 UTC, jeherve requested changes

2021-09-13 16:25 UTC, jeherve commented on projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
> +		$submenus_to_update = apply_filters( 'wpcom_plugins_submenu_update', array() );
Could you add a docblock for this new filter? Here is an example:
https://github.com/Automattic/jetpack/blob/d4b7af2a663239fa37ffb564ac8d95715979749d/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L260-L270

2021-09-13 16:39 UTC, obenland commented
@cpapazoglou Have you tried making this work without the new filter?

2021-09-14 12:57 UTC, cpapazoglou commented
> @cpapazoglou Have you tried making this work without the new filter?

Thanks for the reminder! I followed @BogdanUngureanu [approach](https://github.com/Automattic/jetpack/pull/20949#issuecomment-915523176) and seems working as expected. It still requires a hook but it is far more generic.

New PR in progress here: https://github.com/Automattic/jetpack/pull/21074

2021-09-14 14:44 UTC, obenland commented
> It still requires a hook but it is far more generic.

Hm, that still feels off. Third-party plugins are able to use `admin_menu`, why aren't we?

2021-09-14 14:51 UTC, cpapazoglou commented
> > It still requires a hook but it is far more generic.
> 
> Hm, that still feels off. Third-party plugins are able to use `admin_menu`, why aren't we?

Third party plugins are usually (if not always) adding their own (new) menu items. Here we need to change a core menu item without disabling any functionality depending on that. From Bogdan's [comment](https://github.com/Automattic/jetpack/pull/20949#issuecomment-915523176)

>  update_submenus() is useful in cases when you want to replace an existing submenu item and still keep the existing (especially core specific menus) active. This is useful when you want to keep the old interfaces available but not visible in the menu. Also, in several cases for core submenus, keep backwards compatibility with third-party plugins (many plugins are registering pages referencing core submenus - if the core pages are removed, those plugin pages will break as well).

How would you approach this? Using `admin_menu` and manipulating the `global $submenu`?

2021-09-14 16:31 UTC, obenland commented
Yes, pretty much. I understand WordPress doesn't offer a menu manipulation API outside of the add_(sub)menu_item()` functions, so it might be a little less comfortable. You could consider breaking out `update_submenus()` into a utility function if that helps.

2021-09-27 02:29 UTC, samiff commented
@cpapazoglou Just a reminder that the Jetpack 10.2 code freeze is on September 28, 2021.

2021-10-05 08:54 UTC, cpapazoglou commented
Abandoning current implementation in favor of https://github.com/Automattic/jetpack/pull/21236/files

2021-10-05 08:54 UTC, closed without merging