Instagram Widget: Remove from legacy-widget block
Automattic/jetpack pull request #21050
Opened 2021-09-11 15:36 UTC by arcangelini

## Summary
With the new current widget block editor, the Instagram Widget does not configure properly. The current Instagram Gallery block already exists and offers the same functions. Rather than fixing the broken widget this PR removes it from the `core/legacy-widget` and adds the widget to the REST API to allow a block `transform:` to be created.

Fixes Automattic/wp-calypso#55344

#### Changes proposed in this Pull Request:
* Added filter to hide `wpcom_instagram_widget` from legacy-widget block
* Added widget_option to allow it to be displayed in the REST API. This will allow it to be "transformed" into the `jetpack/instagram-gallery` block

#### Jetpack product discussion
No discussions

#### Does this pull request change what data or activity we track or use?
No data changes

#### Testing instructions:
* Got to Appearance ⇢ Customize ⇢ Widgets
* Add a new block and select Legacy
* In the dropdown check to make sure the `Instagram (Jetpack)` option is gone
* Next search in the available blocks for "Instagram". You should no longer see a legacy block for Instagram.

2021-09-13 05:49 UTC, yansern submitted a review, later dismissed
Tested & working!

Before:
![image](https://user-images.githubusercontent.com/1287077/133030363-242b229d-c5f9-488a-a851-edac28bdddce.png)

After:
![image](https://user-images.githubusercontent.com/1287077/133030350-8c8572d2-6a52-4420-9a92-8b7845f44e2c.png)

2021-09-13 15:21 UTC, yansern commented
It looks like the E2E test needs to be updated.
![image](https://user-images.githubusercontent.com/1287077/133111225-f2b4a9e4-479b-4e66-b248-390c30139074.png)

2021-09-13 16:06 UTC, jeherve requested changes
This works well. I have 2 remarks though:

- I find the function name (`hide_from_legacy_block`) a bit confusing; I would personally find something like `hide_widget_in_block_widget_editor` maybe a bit clearer?
- Would it be possible to put the function in the class instead of on its own outside of the class in the same file? I feel it would be cleaner, and would avoid any potential conflicts with functions with the same name in a different plugin.

2021-09-14 14:26 UTC, arcangelini reviewed
Moved the filter into the _construct() and renamed the function

2021-09-15 15:29 UTC, arcangelini commented
OK, it took me a little digging to understand how to build the `transforms` but I got it and added it to the `instagram-gallery` block and tested it. Do we need to add any other messages?

![Screen Capture on 2021-09-15 at 17-17-04](https://user-images.githubusercontent.com/33258733/133463111-ea7b62fb-b562-4e1a-8782-f130a7b54455.gif)

2021-09-15 16:14 UTC, jeherve commented
> OK, it took me a little digging to understand how to build the `transforms` but I got it and added it to the `instagram-gallery` block and tested it.

Nicely done, thank you! 👏 

> Do we need to add any other messages?

Is it possible to port the number of columns and the count to the block, so those settings remain?

> Also, the original widget had a title as you can see, but the block doesn't have that option. Should I also add a `heading` block above and either group them or leave them separate? Thoughts?

Yeah, I think it would make sense to create a new heading block, and then group the heading and the Instagram block.

2021-09-16 21:42 UTC, arcangelini commented
I am 99% finished with this and have pushed the working version. I was able to grab all the original widget settings including the token ID. This will create 2 blocks, `core/heading` and the `jetpack/instagram-gallery`.

Here is the issue I can't seem to get around: these blocks need to be wrapped in a group to keep them together, but when I try to do so I get an error:

```
Cannot read properties of null (reading 'name')
```

This is what I have so far: [screenshot](https://d.pr/i/dK9lIJ)

2021-09-17 06:46 UTC, simison commented
> hese blocks need to be wrapped in a group to keep them together,

2021-09-17 06:59 UTC, arcangelini commented
@simison if you look at the screenshot that I took, when the heading and Instagram blocks are not bundled together in one group they have the propensity to end up in different footer columns. The two need to be nested in a group or column block to keep them together.

I am open to other suggestions because this has not been a very fun issue to solve for.

2021-09-17 09:19 UTC, simison commented
@arcangelini a solution is coming: https://github.com/WordPress/gutenberg/issues/32723

Meanwhile might make sense to get basic transform merged without heading, or by keeping heading separate block?

2021-09-17 10:17 UTC, arcangelini commented
The source of the issue is coming from [this check](https://github.com/WordPress/gutenberg/blob/64f1de6587425808b02a339f82d5fb95193c0011/packages/blocks/src/api/factory.js#L541-L550). If the block transforming TO does not match the block where it is defined it returns null. This check does not take into account the nested innerBlocks. So any attempt to programmatically add any parent block will break.

2021-09-17 12:19 UTC, arcangelini commented
Per @simison suggestion removed the header & group blocks in order to fix current issues. I am working to get the bug in Gutenberg fixed. Not sure on the timeline for that.

2021-09-17 14:20 UTC, jeherve submitted a review, later dismissed
This works well for me. 🚢 !

2021-09-20 14:37 UTC, arcangelini commented
Deployed on WPCOM: r231968-wpcom

The failing test has to do with a core block test that was updated in the diff.

2021-09-20 15:28 UTC, jeherve approved these changes

2021-09-20 15:33 UTC, merged