Contact Form: Add filters to allow Akismet to add custom form fields for better anti-spam effectiveness.
Automattic/jetpack pull request #21123
Opened 2021-09-17 16:53 UTC by cfinke

#### Changes proposed in this Pull Request:

This PR adds two filters:

* one to allow the HTML of a contact form to be modified
* one to allow the parameters that get sent to Akismet for the spam check to be modified (so any form fields that Akismet added via the first filter are included in the API request).

#### Jetpack product discussion
pd1A7D-1x

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
Because nothing uses these filters yet, adding them should not have any effect on the functionality of the contact form. Test that submitting a contact form works as expected, both with Akismet enabled and disabled.

2021-09-17 16:56 UTC, jeherve requested changes

2021-09-17 16:56 UTC, jeherve commented on projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
> +		 * @since 10.2
```suggestion
		 * @since 10.2.0
```

2021-09-17 16:56 UTC, jeherve commented on projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
> +		 * @since 10.2
```suggestion
		 * @since 10.2.0
```

2021-09-17 16:56 UTC, jeherve commented on projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
>  		return $r;
I think you could potentially put the filter on the return directly:

```suggestion
		return apply_filters( 'jetpack_contact_form_html', $r );
```

2021-09-17 16:56 UTC, jeherve commented on projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
>  		return $form;
I think you could potentially put the filter on the return directly:

```suggestion
		return apply_filters( 'jetpack_contact_form_akismet_values', $form );
```

2021-09-20 17:27 UTC, cfinke commented
I'm not familiar with the Jetpack development process, so it's unclear to me what still needs to be done here. Can this be assigned to someone on the Jetpack team so it can make it into the next release?

2021-09-21 08:44 UTC, jeherve commented
> I'm not familiar with the Jetpack development process, so it's unclear to me what still needs to be done here. Can this be assigned to someone on the Jetpack team so it can make it into the next release?

I'm happy to take care of it, but I was wondering if you wanted to give it a try on your own first, to get a bit more familiar with our tools? We try to provide information via the GitHub Actions comment posted in each PR; that comment is updated with new information every time you update your PR. This should consequently help you understand what still needs to happen.
https://github.com/Automattic/jetpack/pull/21123#issuecomment-921942563

2021-09-21 18:39 UTC, cfinke commented
I gave it a shot; let me know if there's anything I need to change.

2021-09-21 18:58 UTC, cfinke commented
It says that one test failed (`Tests / PHP tests: PHP 7.4 WP master (pull_request)`), but it's unclear to me exactly which testcase failed and why.

2021-09-23 17:20 UTC, jeherve approved these changes
This looks good to me. 🚢

2021-09-23 17:21 UTC, jeherve commented
> It says that one test failed (Tests / PHP tests: PHP 7.4 WP master (pull_request)), but it's unclear to me exactly which testcase failed and why.

That's alright, that's not a blocking test at the moment (see p9dueE-3io-p2 for more info). This should be good to merge now.

2021-09-23 17:35 UTC, merged

2021-09-23 17:54 UTC, cfinke commented
232209