Add missing documentation for $ip variable
Automattic/jetpack pull request #21217
Opened 2021-09-28 13:29 UTC by ypcs

Filter `jpp_allow_login` actually accepts two variables (boolean and ip
address), and IP address is currently missing from the documentation.

As this variable is currently undocumented, current publicly available
documentation at <https://developer.jetpack.com/hooks/jpp_allow_login/>
is also misleading.

#### Changes proposed in this Pull Request:
This is small fix to documentation.

2021-09-28 13:39 UTC, jeherve requested changes, later dismissed
Thanks for the contribution!

Could you add a changelog entry for your change, as explained here:
https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#jetpack-changelogger

Thank you!

2021-09-28 13:39 UTC, jeherve commented on projects/plugins/jetpack/modules/protect.php
> +		 * @param string ip IP address we're validating
```suggestion
		 * @param bool   $false Should we allow all logins for the current ip? Default: false.
		 * @param string $ip    IP address we are validating.
```

2021-09-28 14:29 UTC, ypcs commented on projects/plugins/jetpack/modules/protect.php
> +		 * @param string ip IP address we're validating
Thanks, fixed.

2023-03-10 06:14 UTC, kraftbj approved these changes, later dismissed

2023-03-10 06:16 UTC, kraftbj approved these changes

2023-03-27 17:16 UTC, zinigor commented
@ypcs sorry this got left for so long, we can't merge this anymore because it's not up to date with trunk. Would you like to rebase yourself? We can also apply your patch ourselves giving you credit for the commit.

2023-03-27 17:33 UTC, jeherve commented
Since we've had issues with the Build action on this old PR, I've created #29731 to merge this change without any more issues, finally.

Thanks for your contribution @ypcs!

2023-03-27 17:33 UTC, closed without merging