Storybook: add Jetpack Spinner
Automattic/jetpack pull request #21511
Opened 2021-10-22 16:18 UTC by keoshi

#### Changes proposed in this Pull Request:

* Add existing component to Storybook.
* Add `color` param to allow overriding the color easily.
* Add tests.
* Change the default color to black.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions for Storybook:

* Go to the Storybook folder `cd projects/js-packages/storybook`
* Run `pnpm install`
* Run `pnpm run storybook:dev`
* Storybook should open in your browser.
* Go to Playground → Jetpack Spinner → Docs and play around with the spinner.

#### Screenshot

![image](https://user-images.githubusercontent.com/390760/138488382-c2cec87f-ee06-4e64-92ea-f7bf691a24cd.png)

2021-10-26 18:57 UTC, sergeymitr requested changes
Great job, thank you!
I added a couple of minor suggestions, please take a look.

2021-11-02 15:44 UTC, keoshi commented
@sergeymitr Beautiful suggestions, thanks for those. Pushed some changes and would be cool if you can take another look. Thank you!

2021-11-03 11:33 UTC, fgiannar commented
@keoshi Looks great! Thanks for working on this!

I merged master and fixed the failed **Changelogger validity** tests, hope that's ok 😄 

Leaving it to @sergeymitr for a final review.

2021-11-03 14:52 UTC, sergeymitr requested changes, later dismissed
I noticed one minor thing, other than that everything looks awesome and ready to go!

2021-11-03 14:52 UTC, sergeymitr commented on projects/js-packages/components/components/spinner/stories/index.jsx
> +	moduleName: 'The Module Name',
This seems to be a leftover from the Footer component, I think we should remove it.

2021-11-04 19:55 UTC, leogermani commented
Ok, I went ahead and did a couple of things:

* Merged master and resolved conflicts
* removed unused argument (Sergey request)
* Added an option to use a color picker as a control for the color: 

![Captura de Tela 2021-11-04 às 16 22 16](https://user-images.githubusercontent.com/971483/140410056-ccc1d24b-2f90-43de-aad9-6a0490d76f62.png)

* Reverted the default color to white

This PR was changing the default color of the Spinner from white to black. This resulted in changes in the current UI:

![Captura de Tela 2021-11-04 às 16 32 21](https://user-images.githubusercontent.com/971483/140410390-23da6bea-c469-4255-928e-6e855f2b24eb.png)

I reverted it to white and changed the default background color of the Storybook story to a dark one so the spinner is still visible.

I would give a green light to this PR right away but feels like cheating, so please have a look - and make sure to test the spinner in action in the Connect Screen.

2021-11-05 16:07 UTC, sergeymitr approved these changes
Looks great!
@keoshi, @leogermani thanks for making the changes!

2021-11-05 16:08 UTC, merged

2021-11-05 16:09 UTC, keoshi commented
Thank you for pushing this across the finish line, @leogermani !

2021-11-05 16:15 UTC, leogermani commented
r234600-wpcom