IDC: build and display the new banner
Automattic/jetpack pull request #21822
Opened 2021-11-19 16:33 UTC by sergeymitr

#### Changes proposed in this Pull Request:
- build the new RNA IDC banner
- display the banner instead of the existing one
- remove the old banner's code [in progress]

#### Jetpack product discussion
p9dueE-3Mn-p2

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:
TBD

2021-11-24 15:41 UTC, anomiex reviewed
I only really looked at the changes to the Webpack and other build stuff. One small comment inline. Overall I like the dropping of gulp, from a build system perspective it seems a lot cleaner now. How was the change from the JS side of things?

2021-11-24 15:41 UTC, anomiex commented on projects/packages/identity-crisis/src/class-ui.php
> +			wp_set_script_translations( 'jp_identity_crisis_banner', 'jetpack' );
This should be unneeded, specifying the textdomain at line 60 should be having `Assets::register_script()` handle it.
```suggestion
```

2021-11-24 15:48 UTC, sergeymitr commented
Thanks @anomiex!

> How was the change from the JS side of things?

The only difference is that we still don't have Webpack building SCSS files directly, it's done through loading those files into JS files.
But we no longer have any separate styles in the package, so that's ok. We still have to solve this problem for the JITM package, but I didn't get to it yet.

2021-11-24 16:29 UTC, anomiex commented
> The only difference is that we still don't have Webpack building SCSS files directly, it's done through loading those files into JS files. [...] We still have to solve this problem for the JITM package, but I didn't get to it yet.

Webpack can build the scss files directly if you list them as the files for the entry point rather than a JS file, but it'll generate a JS file for the bundle even after mini-css-extract-plugin extracts all the built CSS. We could use something like https://github.com/Automattic/remove-asset-webpack-plugin or https://github.com/webdiscus/webpack-remove-empty-scripts to suppress that JS file.

2021-11-29 21:17 UTC, samiff requested changes
> Open the browser's dev console, enter localStorage.debug = "dops:analytics"; to see the tracking events.

I haven't played much with the tracking stuff before, I imagine I was supposed to be seeing the different events logged to my browser console? Wasn't able to get this to work, even tried `localStorage.debug = "*";` with no luck. I was able to see the correct t.gif events in the Network tab however. Any idea on why the debug wasn't working or where I can read more about how that is setup?

> Go through the connection process, confirm that you're redirected back to the Connection Manager page. IDC banners should disappear.

On reconnecting I ended up on Calypso plans page. Otherwise the other testing instructions worked well for me 👍  And looks like the webpack built CSS is working nicely.

2021-11-29 21:31 UTC, samiff commented
Ah, missed these two notices that came up in my error log:

```
[29-Nov-2021 21:01:29 UTC] PHP Notice:  Trying to access array offset on value of type bool in /usr/local/src/jetpack-monorepo/projects/packages/identity-crisis/src/class-ui.php on line 100
[29-Nov-2021 21:01:29 UTC] PHP Notice:  Trying to access array offset on value of type bool in /usr/local/src/jetpack-monorepo/projects/packages/identity-crisis/src/class-ui.php on line 101
```

```php
'wpcomHomeUrl'        => $idc_urls['wpcom_url'],
'currentUrl'          => $idc_urls['current_url'],
```

Probably from flipping switches in the Debug Tools, not sure if it'd come up naturally 🤷

2021-11-29 21:35 UTC, kbrown9 reviewed
I haven't tested yet so I'm not ready to approve this. I just have a few very minor comments about the code.

2021-11-29 21:35 UTC, kbrown9 commented on projects/packages/identity-crisis/src/class-ui.php
> +		$idc_data = Identity_Crisis::check_identity_crisis();
This looks like some leftover code (see line 35).

2021-11-29 21:59 UTC, sergeymitr commented on projects/packages/identity-crisis/src/class-ui.php
> +		// TODO: replace the `jetpack_disconnect` check with a non-admin IDC screen.
Good catch.
We're essentially removing the non-admin IDC screen with this PR, as it's not implemented yet.
However, we just discussed it with @kbrown9, and decided that it's safer to put off this PR until we implement that non-admin screen.

2021-12-29 21:37 UTC, samiff commented
With #22060 merged, could this be closed now?

2022-01-04 16:01 UTC, sergeymitr commented
Good point @samiff, closing it now.

2022-01-04 16:01 UTC, closed without merging