Add Boost and CRM Card to At a Glance
Automattic/jetpack pull request #21866
Opened 2021-11-24 04:51 UTC by cbauerman

| Design | Current Implementation |
| -------|--------------------------|
| <img width="636" alt="Screen Shot 2021-11-23 at 20 45 22" src="https://user-images.githubusercontent.com/2810519/143176637-e0e86fac-d281-4551-8e7b-5f7cfbd04afc.png"> | <img width="1046" alt="Screen Shot 2021-11-23 at 20 42 43" src="https://user-images.githubusercontent.com/2810519/143176652-a4c0ef6c-f9eb-4d4d-8521-b79309175ad5.png"> |

#### Changes proposed in this Pull Request:

* Rename `Performance` at-a-glance section to `Performance and Growth`
* Add new `PluginDashItem` component to add sibling plugins and their status to the at-a-glance dashboard
* Add `Boost` and `CRM` dash cards

#### Jetpack product discussion

p1HpG7-dHF-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

**TBA**

2021-12-20 19:03 UTC, monsieur-z approved these changes, later dismissed
PR tests well and code looks good 👍 

It's not ideal that after activating or installing one of the performance products, the other card shows the loading message as well, but I'm guessing this must be due to a lack of granularity when fetching plugins data.

2022-01-03 17:10 UTC, jeherve requested changes
I gave it another try, left some remarks below.

********

In Chrome, I'm seeing a layout issue like the one we had fixed in #22075 

![image](https://user-images.githubusercontent.com/426388/147957840-eb3c3744-8b3e-4e7f-bd40-db94f1507418.png)

********

Design-wise, is it okay to have different patterns for those cards? For example, in the screenshot below we have a card with a toggle in the card header as the CTA, and an "i" icon for more information, and then the new Boost and CRM cards with a CTA button and a "Learn More" link.

*********

I clicked and the CRM plugin was successfully activated, the card got refreshed (saw the 2 new cards flip to "Loading" for a moment), but the Boost status didn't change in the UI, even though the plugin is activated now:

![image](https://user-images.githubusercontent.com/426388/147958317-371692b1-a4b6-48b5-b69c-5d5144c1d62b.png)

However when I clicked the Boost card the CRM card finally got updated at the same time. Not sure why this happened?

https://user-images.githubusercontent.com/426388/147958450-fd47399b-c23b-479b-93aa-697694f3d7f0.mov

2022-01-03 17:10 UTC, jeherve commented on projects/plugins/jetpack/_inc/client/components/plugin-dash-item/style.scss
> +		border-left-color: #3895ba; // $studio-wordpress-blue-30
What do you think about importing those colors, from `_inc/client/scss/variables/_colors.scss`?

2022-01-03 17:22 UTC, cbauerman commented
>In Chrome, I'm seeing a layout issue like the one we had fixed in #22075
 
I believe this is because I made adjustments on this pr to address that issue instead of trying to fix the underlying issue. Should be an easy fix.

> Design-wise, is it okay to have different patterns for those cards? For example, in the screenshot below we have a card with a toggle in the card header as the CTA, and an "i" icon for more information, and then the new Boost and CRM cards with a CTA button and a "Learn More" link.

those aspects of the design are straight from p1HpG7-dHF-p2, though I did extrapolate for the design when the plugins are installed.

 > I clicked and the CRM plugin was successfully activated, the card got refreshed (saw the 2 new cards flip to "Loading" for a moment), but the Boost status didn't change in the UI, even though the plugin is activated now [...] However when I clicked the Boost card the CRM card finally got updated at the same time. Not sure why this happened? 

I will investigate this

2022-01-03 21:32 UTC, cbauerman commented
> I clicked and the CRM plugin was successfully activated, the card got refreshed (saw the 2 new cards flip to "Loading" for a moment), but the Boost status didn't change in the UI, even though the plugin is activated now [...] However when I clicked the Boost card the CRM card finally got updated at the same time. Not sure why this happened?

This seems to be because the response from the request to GET `/plugins` has not been updated, even after the POST `/plugins` returns a success. I did not experience this in my own testing, but it is not hard to imagine some sort of race condition occurring. I went ahead and added a 2500ms wait between the success and fetching the plugin data.

2022-01-04 08:48 UTC, jeherve approved these changes
This should be good to merge now!

As a note, for a follow-up PR maybe:
- The new component's readme is empty.
- We've tried to use hooks instead of classes for new components; while I think we can keep using classes for new AAG classes, for consistency with the existing cards, but maybe we could switch for `PluginDashItem`?
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/_inc/client/README.md#L8-L10

2022-01-04 08:48 UTC, merged

2022-01-04 16:48 UTC, cbauerman commented
> As a note, for a follow-up PR maybe:
> 
> * The new component's readme is empty.

Whoops :P

> * We've tried to use hooks instead of classes for new components; while I think we can keep using classes for new AAG classes, for consistency with the existing cards, but maybe we could switch for `PluginDashItem`?

I love hooks, I did not realize that was the direction of the plugin ( I was trying to be idiomatic ). I will follow up with a PR to refine `DashPluginItem`