JITM: new JS and CSS builder
Automattic/jetpack pull request #21874
Opened 2021-11-24 23:53 UTC by sergeymitr

Unblocks #21688

#### Changes proposed in this Pull Request:
- Make the package JS and CSS builder in line with other packages

#### Jetpack product discussion
p1636490736172600-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Run `jetpack build packages/jitm`, confirm that it builds well: `projects/packages/jitm/build/` directory was created and filled with JS and CSS files.
2. Connect Jetpack, confirm that the files get loaded: `jetpack-jitm/build/index.css` and `jetpack-jitm/build/index.js`.
3. Make sure that JITM functionality remains intact, the banners show up and look good.

2021-11-25 09:10 UTC, jeherve requested changes
Thanks for tackling this!

I gave it a quick test, and I'm afraid it doesn't quite work just yet. I left a few comments below about the issues I found.

Maybe we can also take the opportunity to remove obsolete tools from the gulp tasks in the Jetpack plugin?

2021-11-25 09:10 UTC, jeherve commented on projects/packages/jitm/src/class-jitm.php
> -				'nonce'                  => wp_create_nonce( 'wp_rest' ),
We still rely on those values in the JS at the moment, so we cannot just remove them I'm afraid.

2021-11-25 09:10 UTC, jeherve commented on projects/packages/jitm/src/class-jitm.php
> -			array( 'jquery' ),
Since our JavaScript still uses jQuery, we would have to declare it as dependency.

2021-11-25 09:10 UTC, jeherve commented on projects/packages/jitm/.gitignore
> +/build
I think you will also need to update the `.gitattributes` file to include that directory in production builds, and remove the previous `src/js/jetpack-jitm.min.js` file.

As you can see, the dist directory is currently not included in production builds:
https://github.com/Automattic/jetpack/actions/runs/1501782261

2021-11-25 18:51 UTC, jeherve commented on projects/packages/jitm/src/class-jitm.php
> -				'nonce'                  => wp_create_nonce( 'wp_rest' ),
I gave this a try in 94f07b26ea8a2ec49d092ec67cfac047d0b0343a

2021-11-25 18:52 UTC, jeherve commented on projects/packages/jitm/src/class-jitm.php
> -			array( 'jquery' ),
I added it back in 09c1086603baeebc16fb3dbbe1b7bd5e72551e86

2021-11-25 18:52 UTC, jeherve commented on projects/packages/jitm/.gitignore
> +/build
I updated this in 3c6c3569da66f16245818136982cf49f3019a8b6

2021-11-26 10:54 UTC, jeherve approved these changes
This tests well for me. I'll merge so we can move on with #21688. That said, since I made quite a few changes, @sergeymitr do you think you could take a look at it on Monday?

Thank you!

2021-11-26 10:54 UTC, merged

2021-11-26 13:57 UTC, jeherve commented
r235689-wpcom

2021-11-29 16:37 UTC, sergeymitr commented
Hi @jeherve, thanks for fixing and merging it!