Jetpack: 10.5-a.3
Automattic/jetpack pull request #22087
Opened 2021-12-14 15:54 UTC by samiff

#### Changes proposed in this Pull Request:

* Atomic-only Jetpack release version 10.5-a.3

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

n/a

#### Testing instructions:

* Review changelogs and JP readme.txt

2021-12-14 15:59 UTC, kraftbj submitted a review, later dismissed

2021-12-14 16:04 UTC, jeherve requested changes

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- JITM: allow sidebar JITMs marked as dismissible to be dismissed.
I don't think "JITM" is really helpful for most users. I would move this to "Other".

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- SSO: add filters for the error text when a local user cannot be found for a given WP.com account and for when SSO is disallowed when on a staging site.
I would say "Secure Sign On" instead of SSO here.

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- Cleanup jetpack version option on plugin deactivation.
I would rephrase this to something like

```suggestion
- General: ensure Jetpack options are properly deleted when the plugin is deactivated.
```

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- Subscription Block: add 'Success Message Text' to the block settings.
I would move this to the enhancements.

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- Admin Menu: add support for WPML menu structure.
I would move this to "Other", since only Atomic site owners (who don't get to see the changelogs) are concerned by this.

2021-12-14 16:04 UTC, jeherve commented on projects/plugins/jetpack/CHANGELOG.md
> +- I18n: ensure various strings in JavaScript UIs are marked for translation.
I would replace I18n by something more user-friendly:

```suggestion
- Internationalization: ensure that all text, including text added via JavaScript, can be translated.
```

2021-12-14 16:18 UTC, jeherve submitted a review, later dismissed

2021-12-14 17:19 UTC, jeherve approved these changes

2021-12-14 17:35 UTC, merged

2021-12-15 14:56 UTC, anomiex commented
r236637-wpcom