(WIP) Add "allow download" option for VideoPress video
Automattic/jetpack pull request #22175
Opened 2021-12-23 13:31 UTC by thedebian

Fixes Automattic/greenhouse#1062

#### Changes proposed in this Pull Request:
TBD

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
TBD

2021-12-28 10:12 UTC, thedebian commented on projects/plugins/jetpack/modules/videopress/class-videopress-attachment-metadata.php
> +		$allow_download = null === $allow_download ? null : (int) $allow_download;
This fixes an existing bug on Calypso, where checking one of the box would unset the other (or only updating the rating too).

2021-12-29 11:46 UTC, pgk requested changes
Tested well for me on both the media library and the editor! A few wee changes we can do for clarity.

2022-01-03 16:13 UTC, pgk approved these changes
lgtm!

2022-01-03 17:47 UTC, jeherve approved these changes
This tests well for me. 🚢

2022-01-03 18:45 UTC, merged

2022-01-04 08:38 UTC, thedebian commented
Changeset 237513