Update Dashboard Assistant style
Automattic/jetpack pull request #22255
Opened 2022-01-07 03:04 UTC by IanRamosC

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2022-03-03 21:16 UTC, monsieur-z commented on projects/plugins/jetpack/_inc/client/recommendations/prompts/checkbox-answer/index.jsx
> +		<div className="jp-checkbox-answer__container">
Simplify component to make it natively accessible.

2022-03-03 21:17 UTC, monsieur-z commented on projects/plugins/jetpack/_inc/client/recommendations/prompts/product-suggestion/test/component.js
> -
Link is no longer present.

2022-03-04 21:48 UTC, travisw submitted a review, later dismissed
Changes look good to me. I tried it a few times with a free and paid account and didn't notice any issues.
Impressive CSS work – I learned things just reading through it.

2022-03-07 14:03 UTC, jeherve requested changes
Looks like this is going to need a master update before we can merge.

2022-03-07 19:17 UTC, monsieur-z commented
@jeherve, I've merged master into this branch and fixed the conflicts.

This PR updates the `package-js/base-styles` package, which made one of the checks fail. I ran `tools/fixup-project-versions.sh` to fix it, as indicated. However, this seems to now cause an issue with the `wpcom` check, which is failing above. Running Fusion manually with this PR number seems to indicate there's an issue with the `pnpm-lock.yaml` file. Could you give me a hand fixing this?

2022-03-08 11:18 UTC, jeherve approved these changes
This looks good and tests well. Let's merge it! 🚢  I have one last remark, but this can be addressed in a follow-up PR!

> Running Fusion manually with this PR number seems to indicate there's an issue with the pnpm-lock.yaml file. Could you give me a hand fixing this?

The file is out of sync at the moment, hence why you ran into issues. Once others commit their own diffs and bring the file back in sync, it will be okay.

2022-03-08 11:20 UTC, merged

2022-03-08 14:01 UTC, monsieur-z commented on projects/plugins/jetpack/_inc/client/components/button/index.jsx
> +			'is-rna': rna,
Absolutely! I'll have it done in a separate PR.

2022-03-23 15:01 UTC, monsieur-z commented
> Great news! One last step: head over to your WordPress.com diff, D76016-code, and commit it. Once you've done so, come back to this PR and add a comment with your changeset ID.

@jeherve, I'm not sure exactly what to do: should I commit the WPcom diff even though the builds are failing?

2022-03-23 15:41 UTC, jeherve commented
@monsieur-z The tests should pass once you rebase that diff. 👍