Add class notice to the IDC container
Automattic/jetpack pull request #22266
Opened 2022-01-09 09:26 UTC by htdat

Related https://github.com/Automattic/woocommerce-payments/pull/3580

#### Changes proposed in this Pull Request:

When working in the WCPay PR above, I noticed that the IDC banner does not display in WooCommerce settings page such as: 

- wp-admin/admin.php?page=wc-settings
- wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments

That's because WooCommerce core (via its component woocommerce-admin) tries to stop admin notices tinkering before the WP core moves them below the page title _intentionally_ - [src](https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/src/Loader.php#L724-L739).

This PR is to allow the IDC banner for those pages by adding the `notice` class so that it can display under the admin page title. 

Note: the IDC banner does not display in the React-powered settings page, and we might not display it too. 

- wp-admin/admin.php?page=wc-admin
- wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview

#### Jetpack product discussion

The downside of this approach is that the IDC banner may not really on the top of each admin page. 

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* See the before and after rebuilding the Jetpack IDC package. 

![Markup on 2022-01-09 at 16:24:47](https://user-images.githubusercontent.com/10045087/148676686-b3a6cce2-f886-4214-8bf8-079cc12ae59c.png)

2022-01-13 12:54 UTC, jeherve requested changes

2022-01-13 12:54 UTC, jeherve commented on projects/packages/identity-crisis/src/_inc/style.scss
> +  border: none;
Tabs > spaces :)

```suggestion
	background: none;
	border: none;
```

2022-01-13 12:55 UTC, jeherve commented
I have not tested this myself, so I'm adding the "Needs Team Review" label so someone from your team can take a look. 👍

2022-01-13 14:37 UTC, htdat commented on projects/packages/identity-crisis/src/_inc/style.scss
> +  border: none;
Thank you 👍

2022-01-13 14:39 UTC, htdat commented
> I have not tested this myself, so I'm adding the "Needs Team Review" label so someone from your team can take a look. 👍

Thanks @jeherve! I think @sergeymitr will look into it - ref p1642030666001300/1639517545.011100-slack-CPBTESZMG

2022-01-13 16:39 UTC, sergeymitr commented
Hi @htdat.

I'm worried that the `notice` class name is too generic, and other plugins and themes might unintentionally break the styling.
It already affects the styling (see screenshot). We can fix that we know of, but we can't anticipate everything third-party plugins or themes will do.

Is there any other class name we could use?

The screenshot.
The grey outer border should not be there, it's added by `.notice`.
<img width="1650" alt="Screen Shot 2022-01-13 at 11 38 55 AM" src="https://user-images.githubusercontent.com/1341249/149371318-7b7608cc-ce57-40b3-bbcd-ff1cbc053df8.png">

2022-01-14 05:25 UTC, htdat commented
> I'm worried that the notice class name is too generic, and other plugins and themes might unintentionally break the styling.
We can fix that we know of, but we can't anticipate everything third-party plugins or themes will do.

I don't think third-party plugins or themes usually customize this class name as the current stlyes provided by WP core [src](https://github.com/WordPress/WordPress/blob/b4de570d3555cce5d386f2f10d1d49d2444f3a77/wp-admin/css/common.css#L1376) is quite enough.

> It already affects the styling (see screenshot). 

Can you try rebuilding the CSS file? My CSS change here is to override these effects.

> Is there any other class name we could use?

Only other options are `updated` and `error`, which is not as good as `notice` IMO. 

Ref: https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L1083 
I found out this from the ref here https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/src/Loader.php#L724-L739)

2022-01-21 15:06 UTC, sergeymitr approved these changes
Hi @htdat.

> Can you try rebuilding the CSS file? My CSS change here is to override these effects.

I tried again and everything looked fine. It does look like something went wrong with rebuilding CSS last time I tested.

🚢 👍

2022-01-21 15:11 UTC, jeherve approved these changes

2022-01-21 15:11 UTC, merged