Instant Search: add image alt text from API
Automattic/jetpack pull request #22295
Opened 2022-01-11 03:26 UTC by bluefuton

Fixes #19273.

#### Changes proposed in this Pull Request:
The Instant Search API now provides `image.alt_text` as a field we can request.

This PR adds the new field and switches to use it for alt text in the expanded and product result formats.

I've also reduced the fields fetched for the minimal result format (image fields are not needed).

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
TBC

2022-01-12 02:51 UTC, bluefuton commented on projects/packages/search/src/instant-search/components/search-result-expanded.jsx
> +								alt={ fields[ 'image.alt_text' ] }
I thought about keeping `title.default` as a fallback here, but it's complicated by the fact that `alt=""` is [valid alt text](https://www.w3.org/WAI/tutorials/images/decorative/). 

Feels best to rely on the alt text from the API in all cases.

2022-01-12 23:11 UTC, kangzj reviewed
This tests well and looks good to me 👍 
Some checks are failing, and the errors don't seem relevant to the PR - probably just need to rebase and have the checks re-run and see.

2022-01-13 01:55 UTC, bluefuton commented
The only required check failing is 'Linting / Changelogger validity (pull_request)':

<img width="993" alt="Screen Shot 2022-01-13 at 14 53 15" src="https://user-images.githubusercontent.com/17325/149251845-433e2480-eab5-45e1-87ce-486fef7f81ab.png">

@Automattic/jetpack-crew can you advise whether we need to use fixup-project-versions here?

2022-01-13 16:37 UTC, anomiex commented
> @Automattic/jetpack-crew can you advise whether we need to use fixup-project-versions here?

Well, you don't _need_ to, you could do the version bumps manually. 😀 But fixup-project-versions saves the trouble of figuring out all the details.

P.S. if you're on a Mac and that command is really slow, you might see p7H4VZ-3gs-p2 (or https://apple.stackexchange.com/questions/338415/php-incredibly-slow-since-upgrading-macos-to-10-14-mojave)

2022-01-14 14:31 UTC, anomiex commented
> Thanks @anomiex! Do we need to do this on every search PR in the future?

I usually run it on my PRs that touch any project, just before pushing. It doesn't take that long and it'll safely do nothing if nothing is needed.

In general for a composer package it's only needed if you're doing the first "minor" or "major" PR since the last time the package was released (which will generally be weekly, since packages used by Jetpack get released as part of the weekly Jetpack release for Atomic), unless the package is configured with a version number constant.

2022-01-17 01:48 UTC, kangzj commented on projects/plugins/jetpack/changelog/add-instant-search-alt-text-where-available#2
> +Significance: patch
Do you think keeping `projects/plugins/jetpack/changelog/add-instant-search-alt-text-where-available` is sufficient enough?

2022-01-17 01:51 UTC, kangzj submitted a review, later dismissed
Good job! It looks good and works well 👍

2022-01-24 17:37 UTC, jeherve requested changes
I'm afraid this is going to need a rebase now. :(

2022-01-28 17:00 UTC, jeherve approved these changes

2022-01-28 17:01 UTC, merged