Status: Add Visitor class
Automattic/jetpack pull request #22342
Opened 2022-01-13 19:50 UTC by kraftbj

Discussed in #22269

I added it to Status, but like @jeherve, I'm open to a better place for it.

#### Changes proposed in this Pull Request:

* See above.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* n/a
* Does the location make sense?

2022-01-14 09:44 UTC, fgiannar reviewed
Thanks for working on this @kraftbj !

I took this opportunity to add some unit tests, hope that's ok :)

I could see this class in the **tracking** package as well, populated in the future with various visitor related info, such as: device (device-detection package), geo, etc

2022-01-14 16:53 UTC, kraftbj commented
❤️ I love unit tests. Thank you @fgiannar!

That's a good point. The tracking package doesn't feel great since this isn't for the a8c Tracks system or a8c tracking. I don't know that Status is a slam dunk either, but thinking things related to the Visitor's status (e.g. IP, location, mobile device), etc could make sense?

2022-01-14 17:34 UTC, jeherve requested changes
> The tracking package doesn't feel great since this isn't for the a8c Tracks system or a8c tracking. I don't know that Status is a slam dunk either, but thinking things related to the Visitor's status (e.g. IP, location, mobile device), etc could make sense?

Maybe we would need a brand new package just for those things? Something like Visitor, as you named the class, or server-info?

*******

Could you run `tools/fixup-project-versions.sh` once again to update version numbers?

2022-01-14 17:34 UTC, jeherve commented on projects/plugins/jetpack/_inc/lib/plans.php
> +					'X-Forwarded-For' => (new Automattic\Jetpack\Status\Visitor())->get_ip( true ),
```suggestion
					'X-Forwarded-For' => ( new Automattic\Jetpack\Status\Visitor() )->get_ip( true ),
```

2022-01-14 21:59 UTC, kraftbj commented on projects/plugins/jetpack/_inc/lib/plans.php
> +					'X-Forwarded-For' => (new Automattic\Jetpack\Status\Visitor())->get_ip( true ),
1d7748564d

2022-01-14 22:02 UTC, kraftbj commented
> Maybe we would need a brand new package just for those things? Something like Visitor, as you named the class, or server-info?

Do we see a situation where we'd ever want that _without_ the rest of the Status package?

I'll let it sit for the weekend.

2022-01-17 09:36 UTC, fgiannar commented
> The tracking package doesn't feel great since this isn't for the a8c Tracks system or a8c tracking. I don't know that Status is a slam dunk either, but thinking things related to the Visitor's status (e.g. IP, location, mobile device), etc could make sense?

I mostly suggested the tracking package because usually contexts such as 'Visitor' or 'Visit' are related to tracking. My intuitive reaction, for example, would be to look for such functionality under the `tracking` package, however this might be just me :)

A brand new `Visitor` package, as Jeremy suggests, would also make sense to me, however we might want to avoid the overhead of creating a new package right away and leave this in `Status` for now until we decide.

2022-01-18 09:42 UTC, jeherve commented
> however we might want to avoid the overhead of creating a new package right away and leave this in Status for now until we decide.

Let's go with the new Class in the Status package then. 🚢

2022-01-18 09:42 UTC, jeherve approved these changes, later dismissed

2022-01-18 21:42 UTC, oskosk approved these changes

2022-01-18 21:53 UTC, merged

2022-01-19 18:46 UTC, anomiex commented
Don't forget to take care of D73018-code!

2022-01-19 23:45 UTC, kraftbj commented
Thanks for the reminder! I'll handle this early in my day tomorrow since it requires the package to be added to WP.com and not just a quick deploy :-D.

2022-02-07 13:09 UTC, jeherve commented
r239663-wpcom