Introduce Waf package
Automattic/jetpack pull request #22402
Opened 2022-01-19 03:04 UTC by miguelxpn

#### Changes proposed in this Pull Request:

* Introducing the WAF package with the rule engine.

#### Jetpack product discussion

pbuNQi-1T7-p2

#### Testing instructions:

* Run the package unit tests

2022-01-21 20:01 UTC, bhoop requested changes
Thanks for getting this started! Do you think it would make sense to add some functionality here to actually utilize the rule engine - i.e. have a simple rule for a specific request that we can use to confirm that this is all working? Maybe behind a wp_options flag that defaults to "off" but we could turn on manually in the database or with a wp-cli command?

2022-01-21 22:15 UTC, miguelxpn commented
> Thanks for getting this started! Do you think it would make sense to add some functionality here to actually utilize the rule engine - i.e. have a simple rule for a specific request that we can use to confirm that this is all working? Maybe behind a wp_options flag that defaults to "off" but we could turn on manually in the database or with a wp-cli command?

I think it makes more sense to have the code that handles requests in the plugin. That way we don't couple this package with the request handling and whoever consumes it can use it in their own specific way to handle the request.

> Do we need to do something with these two lines?

According to the monorepo [documentation](https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#creating-a-new-composer-package) the Crew team will add the composer.json file, so perhaps they will adjust it for us? I'll ask them and find out!

2022-01-24 14:05 UTC, jeherve commented
Hi team!

As you work on this functionality, I would recommend that you aim to merge this first PR as early as possible. It doesn't have to be all ready before you merge it. If we can merge a first, smaller PR, early on, and then iterate, feature by feature, in multiple small PRs, it will be easier to review for everyone.

Thank you!

2022-01-25 14:06 UTC, bhoop approved these changes
Per @jeherve's point, let's get this merged and start iterating on it.

2022-01-25 15:37 UTC, bhoop approved these changes
👍

2022-01-25 16:54 UTC, anomiex reviewed
Gave it a once-over from a monorepo structural perspective. Didn't review the actual code.

2022-01-25 16:54 UTC, anomiex commented on projects/packages/waf/composer.json
> +			"@composer install",
Remove this to match #22390
```suggestion
```

2022-01-25 16:54 UTC, anomiex commented on projects/packages/waf/package.json
> +		"install-if-deps-outdated": "pnpm install --no-prod --frozen-lockfile"
Remove this to match #22390
```suggestion
		"clean": "true"
```
Or just remove the whole file if there isn't going to be any JS in the package.

2022-01-26 01:29 UTC, miguelxpn commented on projects/packages/waf/src/class-multi-string-matcher.php
> +<?php // @codingStandardsIgnoreStart
This version has a fix that @bhoop wrote. We'll try to get the fix upstream, once it's there we'll remove the file from this package and import it from packagist.

2022-01-26 18:12 UTC, anomiex commented on projects/packages/waf/src/class-multi-string-matcher.php
> +<?php // @codingStandardsIgnoreStart
If you get a patch into their Gerrit system and it doesn't get attention, let me know and I can try to ping some people I know there.

2022-02-02 03:04 UTC, miguelxpn commented on projects/packages/waf/src/class-multi-string-matcher.php
> +<?php // @codingStandardsIgnoreStart
@anomiex I already got the patch on their Gerrit system and updated the PR to pull the dependency from composer. I think we can merge this as is now and then update it later once the patch lands if that's ok with you.

2022-02-02 17:18 UTC, jeherve approved these changes
Let's merge this! 🚢

2022-02-02 17:20 UTC, anomiex commented on projects/packages/waf/src/class-multi-string-matcher.php
> +<?php // @codingStandardsIgnoreStart
Fine with me

2022-02-02 17:29 UTC, merged