Fix: Lazy Loading images
Automattic/jetpack pull request #22566
Opened 2022-01-31 13:54 UTC by pyronaur

Fixes #22542

Sync Jetpack and Jetpack Boost lazy image status so that toggles in both dashboards always reflect the current status.

Modified the logic slightly. Because Jetpack is watching for filters and reflecting that to the dashboard, I decided to just use Jetpack plugin as the single source of truth instead of Jetpack Boost for the lazy images setting.

2022-02-01 00:05 UTC, thingalon requested changes
Minor thing to fix, but otherwise looks good. Hadn't thought of using a compatibility module. That's not a bad idea.

Don't forget to use the full Jetpack Monorepo PR template, to assure the gardening and labelling system you've thought about its questions.

2022-02-01 00:05 UTC, thingalon commented on projects/plugins/boost/compatibility/jetpack.php
> +function lazy_imasges_sync_status( $_unused, $new_value ) {
`imasges`

2022-02-01 12:56 UTC, pyronaur commented on projects/plugins/boost/compatibility/jetpack.php
> +function lazy_imasges_sync_status( $_unused, $new_value ) {
derp 🤪

2022-02-03 02:48 UTC, thingalon approved these changes
Let's do it.

2022-02-03 08:32 UTC, merged