Publicize: Add empty Composer package
Automattic/jetpack pull request #22607
Opened 2022-02-01 21:04 UTC by danielpost

This PR adds an empty shell package for Publicize. When #22511 is merged the updated files will go into this package.
#### Changes proposed in this Pull Request:

* Add an empty Composer package for Publicize.

#### Jetpack product discussion

p9dueE-4cw-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* N/A

2022-02-01 21:33 UTC, pablinos approved these changes
Looks good to me!

2022-02-02 11:34 UTC, jeherve requested changes
This looks good. 

I would suggest adding a `.phpcs.dir.xml` file like the one in `projects/packages/search/.phpcs.dir.xml`, so we can manage i18n once we start adding to that package.

2022-02-02 11:34 UTC, jeherve commented on projects/packages/publicize/composer.json
> +		"branch-alias": {
```suggestion
		"autotagger": true,
		"mirror-repo": "Automattic/jetpack-publicize",
		"textdomain": "jetpack-publicize-pkg",
		"changelogger": {
			"link-template": "https://github.com/Automattic/jetpack-publicize/compare/v${old}...v${new}"
		},
		"branch-alias": {
```

2022-02-02 11:34 UTC, jeherve commented on projects/packages/publicize/.gitattributes
> +phpunit.xml.dist  production-exclude
```suggestion
phpunit.xml.dist  production-exclude
.phpcs.dir.xml     production-exclude
```

2022-02-03 17:36 UTC, pablinos commented on projects/packages/publicize/.gitattributes
> +phpunit.xml.dist  production-exclude
Handled in ccddf8b

2022-02-03 17:36 UTC, pablinos commented on projects/packages/publicize/composer.json
> +		"branch-alias": {
Handled in ccddf8b

2022-02-03 17:38 UTC, pablinos commented
Thanks @jeherve! I've added that in ccddf8b. I'll try and sort out the failing checks now, but if you have time to take another look, that would be great.

2022-02-04 11:35 UTC, jeherve approved these changes

2022-02-04 11:46 UTC, merged