VideoPress: add title aria to player iframe
Automattic/jetpack pull request #22625
Opened 2022-02-02 16:14 UTC by jgcaruso

Fixes # 1097-gh-Automattic/greenhouse

#### Changes proposed in this Pull Request:

* title and aria-label attributes added to rendering of iframe for videopress/wpvideo shortcode uses
* oembed handled by wpcom D74271-code

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

nope

#### Testing instructions:

* apply pr
* add a `wpvideo` and `videopress` shortcode to a post
* publish the post then view the page
* inspect the source, both video iframes should now have `title` and `aria-label` attributes set on them
* If testing the `/video` block or oembed, D74271-code needs to be applied to wpcom sandbox with public-api sandboxed and Jetpack site needs to point to your sandbox as well (Jetpack pointing at sandbox may not be necessary)

2022-02-04 22:29 UTC, roundhill requested changes

2022-02-04 22:29 UTC, roundhill commented on projects/plugins/jetpack/modules/videopress/class.videopress-player.php
> +			return "<iframe title='video player' aria-label='video player' width='" . esc_attr( $videopress_options['width'] )
Shouldn't we localize these strings? And I had a look at YouTube, and they have `YouTube Video Player` so I'm thinking we could do `VideoPress Video Player`

2022-02-07 14:53 UTC, jeherve approved these changes

2022-02-07 20:52 UTC, roundhill approved these changes
Looks good!

2022-02-07 20:52 UTC, merged