Search: Clicking outside now closes overlay
Automattic/jetpack pull request #22690
Opened 2022-02-05 00:15 UTC by jsnmoon

Fixes #18937.

#### Changes proposed in this Pull Request:
Adds an event handler on the window checking for clicks outside the search overlay.

#### Does this pull request change what data or activity we track or use?
None.

#### Testing instructions:

* Apply this change to a site with a Jetpack Search subscription and Instant Search enabled.
* Perform a site search `e.g. `/?s=page`.
* Click outside the overlay.
* Ensure that the overlay closes as expected.

2022-02-08 04:00 UTC, kangzj commented on projects/packages/search/src/instant-search/components/overlay.jsx
> +			window.addEventListener( 'click', closeWithOutsideClick );
```suggestion
			window.removeEventListener( 'click', closeWithOutsideClick );
```
Am I right?

2022-02-08 04:01 UTC, kangzj reviewed
It works as described, good job 👍  One potential typo and suggested a change.

2022-02-08 22:44 UTC, jsnmoon commented on projects/packages/search/src/instant-search/components/overlay.jsx
> +			window.addEventListener( 'click', closeWithOutsideClick );
Good catch!

2022-02-08 23:04 UTC, kangzj requested changes
I noticed when you open and close the overlay for several times, it causes the browser to hang. Profiled the process, it seems the click event is taking longer each time.

![image](https://user-images.githubusercontent.com/1425433/153089987-7bdd3468-0b64-4442-b9d7-35a5f59a0c4b.png)

Possibly this is related - we should get the element dynamically instead of storing a static handle even it saves some calculations - the element could be destroyed and re-rendered which is causing objects not released?

2022-02-09 00:40 UTC, jsnmoon commented
> I noticed when you open and close the overlay for several times, it causes the browser to hang. Profiled the process, it seems the click event is taking longer each time.
>
> Possibly this is related - we should get the element dynamically instead of storing a static handle even it saves some calculations - the element could be destroyed and re-rendered which is causing objects not released?

Good catch. I'm not able to replicate, but it might have been caused by the `resultsContainer` value never getting garbage collected upon rapid summon/dismissal of the search overlay. I went ahead and tweaked the click event handler logic.

2022-02-09 01:27 UTC, kangzj approved these changes, later dismissed
Good job it works perfectly and code looks good to me 👍

2022-02-09 22:35 UTC, annacmc approved these changes
Works great for me 👍

2022-02-09 23:26 UTC, kangzj approved these changes

2022-02-09 23:34 UTC, jsnmoon commented
Hi @jeherve, just wanted to make sure https://github.com/Automattic/jetpack/pull/22461 is working as expected. In this PR, we're making a minor enhancement to the Search package, resulting in a version bump. This version bump is then propagated to Jetpack's composer.json, which triggers the `Jetpack and packages` section of the required review check.

2022-02-10 15:25 UTC, anomiex commented
> (major, minor, or patch)

Major or minor, but not patch as a patch bump would not result in a change the "0.8.x-dev" pseudo-version.

Unfortunately the check works on the file level, so we can't specify that certain changes to Jetpack's `composer.json` are ok while others are not.

2022-02-10 16:56 UTC, jeherve approved these changes

2022-02-10 16:56 UTC, merged