Jetpack: improve the performance of the disconnect dialog
Automattic/jetpack pull request #22922
Opened 2022-02-16 18:06 UTC by jim-coffey

The plugins page load is slow with Jetpack activated - it has been suggested that a lot of time is spent on the PHP side initialising state for the React disconnect modal.

#### Changes proposed in this Pull Request:

1. This PR stops using the main Jetpack app's PHP initial state helper, and instead fetches the data it needs async from the React side.
2. Reduced the size of the redux store and state required by the app - saves 100+Kb raw, 10Kb Gzipped

This is aimed all at improving the performance and load time of the wp-admin plugins page - no longer making all the requests that were being made for the full blown React initial state.

The loading of data is not necessary to allow the user to disconnect.

Slow user data fetching will prevent tracking events on the dialog clicks, but that usually won't happen and I'm not sure we should make the user wait before they can disconnect in those rare cases where fetch requests are slow.

Also, slow requests for connected plugins, or site benefits result in the following fallback display:
<img width="718" alt="fall_back" src="https://user-images.githubusercontent.com/8742105/154708831-08de4c10-be67-4716-9688-523c4f3ff2fa.png">

As a result, I don't think it's worth trying to show any busy text or spinners. The data loads in the background before opening the modal, and the data isn't critical to allow the user to disconnect, and the fallback display looks good anyway.

#### Jetpack product discussion

p1HpG7-ere-p2#comment-52144

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Performance testing will be done separately to ensure this PR is worthwhile - but basic navigation/refreshing of the admin Plugins page should certainly not take any longer to load than usual, even if there is no immediately obvious speed increase.

We should perform some regression testing to ensure the disconnect modal works as it did previously from the Plugins page.

- the modal from Jetpack dashboard Managing site connection **should remain unchanged.**
- note that the disconnect modal shown on the plugins page disconnects immediately and refreshes the page without showing the reason for disconnect, and thank you steps.
- the plugins page disconnect modal may show placeholders while it waits for data to be fetched (emulate a slow network if necessary)
- otherwise, the plugins page disconnect modal should behave as before

2022-02-18 22:48 UTC, travisw submitted a review, later dismissed
This looks good to me and I think is ready for Crew to review. I left a couple comments/questions.

Functionality-wise, it all still works well.
FWIW, I ran Lighthouse tests and do see a nice performance boost. I used a Pressable site.

### Before
<img width="629" alt="Screen Shot 2022-02-18 at 12 07 06 PM" src="https://user-images.githubusercontent.com/690843/154771296-6771536c-ffff-41bd-8024-7efb7531cf36.png">
<img width="620" alt="Screen Shot 2022-02-18 at 12 06 34 PM" src="https://user-images.githubusercontent.com/690843/154771310-31274a32-6031-479a-a975-2a1d9e3bc285.png">

### After
<img width="624" alt="Screen Shot 2022-02-18 at 12 10 29 PM" src="https://user-images.githubusercontent.com/690843/154771349-661b6c40-53c2-42ae-8c49-becb8684b148.png">
<img width="624" alt="Screen Shot 2022-02-18 at 12 10 38 PM" src="https://user-images.githubusercontent.com/690843/154771359-31727bdf-e4e6-458d-a4f2-ceafadca0f02.png">

2022-02-21 09:48 UTC, jim-coffey commented on projects/plugins/jetpack/_inc/client/state/plugins-store.js
> +/**
Fair point :thumbsup:

2022-02-21 09:49 UTC, jim-coffey commented on projects/plugins/jetpack/_inc/client/state/licensing/reducer.js
>   * @param {object} action
Agreed, I actually tried to remove these, but the `jetpack build plugins/jetpack` build was still failing - I might try just clearing things down and re-building from scratch.

2022-02-21 10:42 UTC, jeherve requested changes
Could you rebase one last time so we can review and merge?

2022-02-21 11:50 UTC, jim-coffey commented on projects/plugins/jetpack/_inc/client/state/plugins-store.js
> +/**
Done

2022-02-21 11:51 UTC, jim-coffey commented on projects/plugins/jetpack/_inc/client/state/licensing/reducer.js
>   * @param {object} action
Re-built and removed these changes.

2022-02-21 11:51 UTC, jim-coffey commented
> Could you rebase one last time so we can review and merge?

Responded to small review comments, rebased, re-tested.

2022-02-21 18:07 UTC, jeherve approved these changes
This looks good, this should be ready to merge! I would only recommend adding some documentation, but this can be done in a follow-up PR.


*******


Could you add a section in https://github.com/Automattic/jetpack/blob/update/disconnect-dialog-initial-state/projects/plugins/jetpack/_inc/client/README.md about the new store? I worry that it may get confusing in the future, when we won't necessarily remember why this was built that way.

2022-02-21 18:08 UTC, merged

2022-02-22 10:12 UTC, jim-coffey commented
r240480-wpcom