Google Fonts: update the method used to preconnect Fonts source domain.
Automattic/jetpack pull request #23322
Opened 2022-03-09 09:10 UTC by jeherve

Follow-up from #23045
Fixes #23306

#### Changes proposed in this Pull Request:

Instead of manually outputting a link to the `head`, let's rely on a Core filter, `wp_resource_hints`, to take care of that for us.
Let's take that opportunity to ensure we only do that when the Webfonts API is supported on the site.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* See #23045 for the basics.
* Enable the module and check that Google fonts are available.
* Enable and disable the Gutenberg plugin and make sure no errors are logged.

2022-03-10 04:36 UTC, creativecoder approved these changes
This works great. TIL about `wp_resource_hints`!

2022-03-10 04:41 UTC, creativecoder requested changes
Spoke too soon 🙂. This works great for adding the preconnect link, but we still need a check before adding the filter.

2022-03-10 04:41 UTC, creativecoder commented on projects/plugins/jetpack/modules/google-fonts.php
> +add_filter( 'wp_resource_hints', '\Automattic\Jetpack\Fonts\Google_Fonts_Provider::font_source_resource_hint', 10, 2 );
If Gutenberg is disabled, I'm seeing `PHP Warning:  Invalid argument supplied for foreach() in /Users/Grant/Automattic/Sites/wordpress-develop/src/wp-includes/general-template.php on line 3346`, as the `font_source_resource_hint` method is not available to hook into.

2022-03-14 21:30 UTC, kraftbj approved these changes

2022-03-14 21:34 UTC, merged

2022-03-15 22:13 UTC, creativecoder commented
Sorry for the delay in me getting back to this... thanks for taking care of it!