Add/post purchase page
Automattic/jetpack pull request #23617
Opened 2022-03-25 05:44 UTC by eAdnan007

Fixes #23319

#### Changes proposed in this Pull Request:

* The changes are on top of #23482
* This adds the landing page after boost was upgraded successfully.

#### Jetpack product discussion
pc9hqz-iD-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Go to 'Boost dashboard'
* Add `#/purchase-successful` to the URL
* Check the design on different screen sizes. dVyv3AO1fXG0gprXywMuMh-fi-2130%3A7342

2022-03-29 12:35 UTC, karthikax requested changes
Great work 🎉  A few suggestions:

- Margin's from all the `p` elements are gone. Changing to master fixes this. May need to look into why this is happening.
- container width in Figma is `1129px` and in diff is `1080px`. Does not seem like an important change though.
- There is a substantial spacing between `Dedicated email support` and `Continue` button in the design. This seems like a nice change to make.

2022-03-30 11:53 UTC, eAdnan007 commented
> * Margin's from all the `p` elements are gone. Changing to master fixes this. May need to look into why this is happening.

Can you try a hard refresh after building?

> container width in Figma is 1129px and in diff is 1080px. Does not seem like an important change though.

I was aiming it to match the other upgrade pages of related products.


> There is a substantial spacing between Dedicated email support and Continue button in the design. This seems like a nice change to make.

Improved

@karthikax

2022-04-01 03:50 UTC, thingalon submitted a review, later dismissed
👍 Great work! Looks just like the designs. The code is nice and clean too.

2022-04-01 03:50 UTC, thingalon commented on projects/plugins/boost/app/assets/src/css/main/common.scss
>    }
😲 I had no idea scss could do this sort of thing

2022-04-01 11:21 UTC, karthikax approved these changes
> Can you try a hard refresh after building?
Looks like this also exists in `master` now. Unrelated to this PR.

Looks good to me to proceed. 👍

2022-04-01 11:22 UTC, merged

2022-04-01 11:27 UTC, eAdnan007 commented
r242957-wpcom