PHPCS: SAL (part 3)
Automattic/jetpack pull request #23787
Opened 2022-04-05 08:48 UTC by coder-karen

This PR partially fixes the issue at #21967

#### Changes proposed in this Pull Request:

* This PR updates the SAL files to meet PHPCS standards:
  * "projects/plugins/jetpack/sal/class.json-api-site-jetpack-base.php" (not complete)
  * "projects/plugins/jetpack/sal/class.json-api-site-jetpack.php" (not complete)
  * "projects/plugins/jetpack/sal/class.json-api-token.php" (not complete)

#### Jetpack product discussion

n/a.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* For each file, test features that may be impacted by that file.
* Also, you can use the WordPress.com developer console to test an endpoint such as the WP.COM API GET request for `/sites/{blog_id}/posts/{post_id}` - for a sandboxed WPcom site and a sandboxed Jetpack site. A breaking change will affect the output, whereas it should work fine otherwise.
* We're primarily checking for any broken experiences or PHPCS errors.

2022-05-18 16:49 UTC, samiff approved these changes
Looks like the majority of this is doc comments & formatting so I don't foresee any hiccups with it. Let me know if you need any help with the wpcom diff 👍

2022-05-18 16:49 UTC, samiff commented on projects/plugins/jetpack/sal/class.json-api-site-jetpack.php
> +	 * Retrieves a Jetpack option's value, given the option name. Firs
```suggestion
	 * Retrieves a Jetpack option's value, given the option name.
```

2022-05-18 16:49 UTC, samiff commented on projects/plugins/jetpack/sal/class.json-api-site-jetpack-base.php
> +		if ( isset( $main_network_site ) ) {
```suggestion
		if ( $main_network_site ) {
```

2022-05-18 16:49 UTC, samiff commented on projects/plugins/jetpack/changelog/update-phpcs-sal-pt3
> +PHPCS updates to bring in line with WordPress standards.
```suggestion
Type: other

PHPCS: cleanup SAL files.
```

2022-05-18 16:50 UTC, samiff requested changes
Whoops hit the wrong status on the last review.

2022-05-19 09:02 UTC, coder-karen commented
Thank you Sami for the review! Applied all of the suggestions.

2022-05-19 18:05 UTC, samiff approved these changes

2022-05-20 10:36 UTC, merged