Improve Extensibility of VideoPress Privacy Setting filter by adding the embedded post id.
Automattic/jetpack pull request #23949
Opened 2022-04-14 16:12 UTC by pgk

Fixes #

#### Changes proposed in this Pull Request:

*

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2022-04-21 08:59 UTC, thedebian commented on projects/plugins/jetpack/modules/videopress/class.videopress-ajax.php
> +		if ( false === $embedded_post_id ) {
filter_input may also return null, you could either check empty( $embedded_post_id ) or use the options array with default => 0 like

`$embedded_post_id = filter_input( INPUT_POST, 'post_id', FILTER_VALIDATE_INT, array( 'options' => array( 'default' => 0 ) );`

2022-04-21 09:02 UTC, thedebian requested changes

2022-04-21 09:02 UTC, thedebian commented on projects/plugins/jetpack/modules/videopress/class.videopress-ajax.php
> +		if ( false === $embedded_post_id ) {
filter_input may also return null, you could either check empty( $embedded_post_id ) or use the options array with default => 0 like

`$embedded_post_id = (int) filter_input( INPUT_POST, 'post_id', FILTER_VALIDATE_INT, array( 'options' => array( 'default' => 0 ) );`

2022-04-21 14:53 UTC, thedebian requested changes
Another slight change (I think), apart from that, code is 👍, I still need to test it, but it'll be done ASAP

2022-04-21 14:53 UTC, thedebian commented on projects/plugins/jetpack/modules/videopress/class.videopress-ajax.php
> +		if ( empty( $guid ) && ! $this->is_valid_guid( $guid ) ) {
```suggestion
		if ( empty( $guid ) || ! $this->is_valid_guid( $guid ) ) {
```

2022-04-22 08:37 UTC, pablohoneyhoney commented
Neat!

[Left a few notes in P2](https://videop2.wordpress.com/2022/04/20/introducing-the-jetpack-video-privacy-setting/).

- [ ] Can we please take a look at the private message to be more intentional in its design @evilluendas?

- [ ] The text below the privacy selector could be dynamic and contextual to the selected privacy setting. The default state shall ideally be instructional of the interaction and also tell you what the site setting is currently.

- [ ] And the tab title probably would be clearer if it's Video Privacy, or something in those lines. </p>

- [ ] There's also a strange spinner when loading the video in the editor that could be updated to [the latest wp spinner](https://wordpress.github.io/gutenberg/?path=/story/components-spinner--default).

2022-04-26 13:02 UTC, thedebian submitted a review, later dismissed
Worked well ! 👍 :shipit:

2022-05-03 15:00 UTC, thedebian approved these changes
Re-approved !

2022-05-10 10:13 UTC, merged

2022-05-17 12:53 UTC, pgk commented
r245781-wpcom