Protect: Add notifications
Automattic/jetpack pull request #24117
Opened 2022-04-27 16:06 UTC by leogermani

#### Changes proposed in this Pull Request:

* Adds notifications to the menu item and the admin bar

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Activate Protect
* Set the response_type to `complete_green`
* Confirm you don't see anything in the Protect menu item neither in the admin bar
* Set the response_type constant to `complete`
* Confirm you see notifications in the menu item and in the admin bar
* Confirm the numbers displayed match the total number of vulneratbilities
* Confirm that clicking on the admin bar takes you to the Protect page

![Captura de tela de 2022-04-27 13-06-17](https://user-images.githubusercontent.com/971483/165562629-09812f3a-dada-4b16-a39a-4ead0c75877c.png)

2022-04-27 16:40 UTC, renatoagds commented
What do you think about calling this folder `assets` instead of `css`?

2022-04-28 12:15 UTC, renatoagds reviewed
There's some lint errors happening

2022-04-28 12:35 UTC, leogermani commented
FIxed

2022-04-28 14:46 UTC, retrofox commented on projects/plugins/protect/src/class-jetpack-protect.php
> +		$total_vuls = Status::get_total_vulnerabilities();
Getting Fatal here

```
[28-Apr-2022 14:45:20 UTC] PHP Fatal error:  Uncaught Error: Class "Status" not found in /usr/local/src/jetpack-monorepo/projects/plugins/protect/src/class-jetpack-protect.php:42
Stack trace:
```

```suggestion
		$total_vuls = Protect_Status::get_total_vulnerabilities();
```

2022-04-28 14:49 UTC, retrofox requested changes
I'm requesting changes because of
* PHP Fatals. Commits suggested.
* The icon doesn't look very well compared with the rest
<img width="268" alt="image" src="https://user-images.githubusercontent.com/77539/165780115-6f15fdf1-41ad-49f6-957d-e75f6eb7dc66.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/77539/165780203-5fa3ce75-d8dc-49be-a6ed-80a7fdca63cc.png">

2022-04-28 22:13 UTC, leogermani commented
@retrofox Can we merge this and create another issue to fix the icon aligment?

2022-04-28 22:14 UTC, retrofox approved these changes
LGTM

2022-04-28 22:27 UTC, retrofox approved these changes
LGTM

2022-04-28 22:31 UTC, merged