Unit Tests: fix all PHPCS errors
Automattic/jetpack pull request #24416
Opened 2022-05-18 15:15 UTC by jeherve

#### Changes proposed in this Pull Request:

* No changes in functionality, just fixing PHPCS errors.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Not much to test here. Do the tests pass?

2022-05-18 19:17 UTC, sdixon194 requested changes
Looks god! Just two small things.

2022-05-19 08:34 UTC, jeherve commented on projects/plugins/jetpack/tests/php/bootstrap.php
> +if ( '1' != getenv( 'JETPACK_TEST_WOOCOMMERCE' ) ) { // phpcs:ignore Universal.Operators.StrictComparisons.LooseNotEqual
Yeah, you're right. Fixed in f4b6cb64d86c64b09409c77a4f7dac96b02d6d97

2022-05-19 13:03 UTC, sdixon194 submitted a review, later dismissed

2022-05-19 13:04 UTC, sdixon194 commented
Ready to go! Just will need a master/merge after the release.

2022-05-20 15:03 UTC, jeherve commented
@sdixon194 I had to fix merge conflicts so your review was dismissed. Do you think you could approve again? 

Thank you!

2022-05-20 15:08 UTC, sdixon194 approved these changes

2022-05-20 15:19 UTC, merged