[Boost] - Improve the Modal Messages
Automattic/jetpack pull request #24747
Opened 2022-06-14 20:33 UTC by mikemayhem3030

WIP PR to apply DRY coding principles and tidy up the pop out messages components.

2022-06-17 13:49 UTC, mikemayhem3030 commented on projects/plugins/boost/app/assets/src/css/main/dashboard.scss
> +.jb-feature-toggle__content h3:focus-visible, .jb-connection__title:focus-visible {
This changed since my fix for the blue outline part of the code

2022-06-17 13:49 UTC, mikemayhem3030 commented on projects/plugins/boost/app/assets/src/css/main/dashboard.scss
> +
Styling for the dismiss this modal link below the CTA button

2022-06-23 03:38 UTC, thingalon requested changes
Looking mostly good. Got some bits to tidy up, and there is a bit of a tricky merge ahead. Let me know if you need help :)

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/admin/class-admin.php
> +				}
I would prefer we make sure that `get_show_score_prompt()` guarantee that its return type is an array so that its callers don't have to check.

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/admin/class-admin.php
>  	}
This function needs a rename; it no longer returns a boolean indicating whether a score prompt should be shown.

I also think it needs to ensure its output is always an array of dismissed score prompts - so it should check if it gets a `false` back out of the option (from previous versions of boost) and turn that into an array containing the expected dismissed "rate our plugin" score prompt.

You don't need to worry about the "decrease score" prompt being dismissed from previous versions, as we haven't released a version with that in it yet :)

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte
> +			showPrevScores = didScoresChange( $scores ) && ! $scores.isStale;
This is new; we previously haven't been showing previous speed scores on a decrease. However, now that we're addressing it I think I'm ok with this, but wanted to note it's a change.

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/api/speed-scores.ts
> +export function scoreChangeModal( scores: SpeedScoresSet ) {
This approach seems nice and clear :)

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/api/speed-scores.ts
> +			ctaLink: 'https://wordpress.org/support/plugin/jetpack-boost/#new-topic-0',
🤔 We have premium support for users on a paid plan. See: `pages/settings/sections/Support.svelte` which shows a support section on the page if the user has premium support, and `utils/paid-plan.ts` where the URL for premium support is. 

I'd be tempted to update `paid-plan` to export the support URL as a const so that you can use it as your ctaLink here if they have paid support :)

2022-06-23 03:38 UTC, thingalon commented on projects/plugins/boost/app/admin/class-admin.php
Just a heads up - a lot of this has been moved into a new `class-config.php` file in a [recent PR](https://github.com/Automattic/jetpack/pull/24808) we urgently squeezed through. If you need help with merging, let me know.

2022-06-25 10:17 UTC, eAdnan007 reviewed
Just a small suggestion

2022-06-25 10:17 UTC, eAdnan007 commented on projects/plugins/boost/app/assets/src/js/api/speed-scores.ts
> +		current.desktop !== noBoost.desktop
Do we want an or operation here instead? What it one remained the same while the other changed dramatically. I think we should consider any change.

2022-08-05 06:25 UTC, thingalon approved these changes
Thanks for working through the feedback @mikemayhem3030 :)

2022-08-05 06:25 UTC, merged