Search: Fix search pricing request before site is connected
Automattic/jetpack pull request #24826
Opened 2022-06-23 07:48 UTC by kangzj

#### Changes proposed in this Pull Request:
The PR fixes a regression introduced by #24795. `get_pricing_from_wpcom` would be called before site is connected, meaning we wouldn't be able to `wpcom_json_api_request_as_blog`.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Create a fresh JN site
* Go to a site not connected
* Ensure search pricing is correct on page `/wp-admin/admin.php?page=jetpack-search`
* Ensure search pricing is correct in My Jetpack `/wp-admin/admin.php?page=my-jetpack#/add-search`
*

2022-06-23 13:21 UTC, leogermani requested changes
It tests well for me. I've just add memoization to the method to avoid it making to requests to wpcom on one request.

Then I realized that the Search package is using it but is not explicitly addin My Jetpack as a dependency. I think we need to do that.

2022-06-26 21:27 UTC, kangzj commented on projects/packages/my-jetpack/src/products/class-search.php
> +		static $pricing = null;
It's unusual but the pricing changes with record count, so probably we'll need to take that in account? @leogermani

2022-06-26 23:18 UTC, kangzj commented
Thanks for the review @leogermani 

>  I've just add memoization to the method to avoid it making to requests to wpcom on one request.

Good catch! Added memoize with parameter to avoid cached return doesn't reflect the record_count parameter.

> Then I realized that the Search package is using it but is not explicitly addin My Jetpack as a dependency. I think we need to do that.

Good catch. Added thanks!

2022-06-27 13:42 UTC, leogermani approved these changes

2022-06-27 13:43 UTC, merged