Protect: Changelog and Readme updates for 1.0.2 release
Automattic/jetpack pull request #25171
Opened 2022-07-22 17:27 UTC by miguelxpn

#### Changes proposed in this Pull Request:

* This is creating the changelog for the new 1.0.2 release for Jetpack Protect.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Nothing to test really.

2022-07-25 08:10 UTC, coder-karen requested changes

2022-07-25 08:10 UTC, coder-karen commented on projects/js-packages/babel-plugin-replace-textdomain/CHANGELOG.md
> +
A quick suggestion here is to make sure there aren't any blank changelog entries - in cases like this it's generally just package dependency updates so you can copy-paste the previous entry:
```suggestion
## [1.0.12] - 2022-07-22
### Changed
- Updated package dependencies.
```
There are a number of other packages with blank entries too.

2022-07-27 08:29 UTC, coder-karen submitted a review, later dismissed

2022-07-27 10:02 UTC, jeherve requested changes
We'll most likely need to update the stable tag here as part of this PR:
https://github.com/Automattic/jetpack/blob/protect/1.0.2-changelog-readme/projects/plugins/protect/readme.txt#L7

It can be updated to 1.0.1, the current stable, and then it will be updated to 1.0.2 as part of the release process in a few hours.

2022-07-27 10:02 UTC, jeherve commented on projects/plugins/protect/readme.txt
> +- Updated package dependencies.
This should probably be removed from the readme.txt file; it's not very useful for end-users to know.

2022-07-27 10:02 UTC, jeherve commented on projects/plugins/protect/readme.txt
> +- Fix protect admin toolbar icon display when Jetpack enabled and connected
```suggestion
- Admin toolbar: ensure the toolbar icon is properly displayed, even when the Jetpack plugin is enabled and connected.
```

2022-07-27 10:02 UTC, jeherve commented on projects/plugins/protect/readme.txt
> +- Minor bug fix - added isset() checks for report data properties
```suggestion
- General: avoid PHP notices when fetching reports about your site.
```

2022-07-27 10:17 UTC, coder-karen approved these changes

2022-07-27 10:51 UTC, jeherve commented
Closing in favor of #25290. This PR is a bit out of date, it misses the changes introduced in #25279.

2022-07-27 10:51 UTC, closed without merging