(WIP) Search Config Page: fix overlapping Admin Menu issue
Automattic/jetpack pull request #25328
Opened 2022-07-29 10:59 UTC by mpkelly

Fixes [#64369](https://github.com/Automattic/wp-calypso/issues/64369)

#### Changes proposed in this Pull Request:
Make a rule in`masterbar/admin-menu/admin-menu.css` more specific, so it takes precedence over a rule in the`edit-widgets` package, which currently means that the Admin Menu obscures some of the content on the Jetpack Search Config page. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

You will need **Jetpack Search** enabled on an Atomic site with **Jetpack Beta** installed. 

1. First verify there is an issue by navigating to `wp-admin/admin.php?page=jetpack-search-configure`
2. Make sure the Admin menu is expanded and you should see that it obscures part of the content section as noted in [#64369` ](https://github.com/Automattic/wp-calypso/issues/64369). You should see something like this:
![image](https://user-images.githubusercontent.com/6851384/181716709-42fbbb60-7d35-4d1b-8fee-091080f41126.png)
3. Next go to Jetpack Beta and choose to manage the Jetpack plugin. Switch to the branch used in this PR
![image](https://user-images.githubusercontent.com/6851384/181717793-e34f5642-4146-45a8-8c41-ca86fdb3179a.png)
4. Return to  to `wp-admin/admin.php?page=jetpack-search-configure` and verify that the issue is resolved. Also verify that the new CSS selector is present in Dev Tools
![image](https://user-images.githubusercontent.com/6851384/181718731-0398a7f6-fdec-4c75-9550-c4465d9eb842.png)
![image](https://user-images.githubusercontent.com/6851384/181718793-ea0b79e2-a7ac-49ad-b2e2-a0ac43c06e04.png)

In addition, you can check that the change works for `rtl` mode CSS (auto-generated); and behaves correctly when the menu is collapsed.

2022-07-29 12:24 UTC, daledupreez requested changes
I tested this and it looks like there is an issue with the _auto_folded state, where `.autofold` is true, but `.folded` is not. I think this creeps in between the 960px and 782px breakpoints when you expand and then collapse the left nav.

<img width="948" alt="Screenshot 2022-07-29 at 14 17 14" src="https://user-images.githubusercontent.com/3376401/181757376-eb1d9aad-03fd-4b77-8da3-3993ca052c39.png">

2022-07-31 10:05 UTC, mpkelly commented
Thanks @daledupreez. On closer inspection, this bug is more difficult than it looks. I think any selectors that use class `.auto-fold` to control the `left` value are problematic, as this class means "automatically managed" and doesn't tell you anything about the width of the nav. I will need to look at this further tomorrow. Maybe it will require a further change to set something on the body or menu element when the menu is collapsed or expanded.

2022-08-01 12:37 UTC, daledupreez commented
I took a closer look today and it looks like the behaviour depends on whether we're seeing the menu from WordPress Core or from WordPress.com. When we're looking at the core menu (which is more likely for Atomic sites), I think we can rely on the existing CSS `sticky-menu` class, which seems to be getting added when the left nav is collapsed, and removed when the left nav is expanded. When we're in nav unification, I think we can assume that the left nav is either present at full width, or is completely retracted (and not visible).

I _hope_ that proves helpful in terms of working through this.

2022-08-17 03:40 UTC, mpkelly commented
Closing. Fixed already by https://github.com/Automattic/jetpack/pull/25331

2022-08-17 03:40 UTC, closed without merging