Add: Support for honoring DNT in Google Analytics
Automattic/jetpack pull request #25423
Opened 2022-08-09 16:34 UTC by chrisbliss18

#### Changes proposed in this Pull Request:
Implement support for the Google Analytics feature to honor the DNT header sent by browsers as outlined in #17176. To enable support for honoring the DNT header, filter `jetpack_honor_dnt_header_for_wga` to `true`.

The changes will affect the following:
* Jetpack

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
* TODO

#### Does this pull request change what data or activity we track or use?
* No

#### Testing instructions:
1. Disable any plugins or theme features that add a Google Analytics tracking code.
2. Activate and fully connect Jetpack.
3. Activate the Google Analytics feature (this may require upgrading your Jetpack plan).
4. Go to Tools > Marketing, scroll to the Google section, and enable the "Add Google" toggle.
5. Enter a valid value in the "Google Analytics Measurement ID" input and save the Google settings.
6. Add the following code to the bottom of the `projects/plugins/jetpack/jetpack.php` file:
```
add_filter( 'jetpack_honor_dnt_header_for_wga', function() { return true; } );
```
7. Ensure that the browser you are testing with has DNT disabled. Instructions for controlling DNT: [Chrome](https://support.google.com/chrome/answer/2790761), [Firefox](https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature), [Safari](https://appletoolbox.com/safari-do-not-track-settings/), [Edge](https://aboutdevice.com/enable-or-disable-do-not-track-dnt-on-microsoft-edge-browser/). You can verify if DNT is enabled or disabled in your browser by visiting [this site](https://allaboutdnt.com/) and looking at the top-right of the page. It will either say "Do Not Track is ON" or "You are being tracked". Note: If you have any privacy or ad-blocking add-ons/extensions installed on your browser, these may also modify DNT. If you run into any testing issues, first confirm that you disable anything that may add or remove the DNT header regardless of the browser setting.
8. Visit the home page of your testing site, view the page source, and confirm that the Google Analytics tracking code is present. You should see output similar to the following before the `</head>` tag:
```

<script async src='[https://www.googletagmanager.com/gtag/js?id=G-123](view-source:https://www.googletagmanager.com/gtag/js?id=G-123)'></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag() { dataLayer.push( arguments ); }
	gtag( 'js', new Date() );
	gtag( 'config', "G-123" );
			</script>

```
9. Ensure that the browser you are testing with has DNT enabled.
10. Visit the home page of your testing site, view the page source, and confirm that the Google Analytics tracking code is no longer present.

2022-08-10 17:23 UTC, sergeymitr requested changes
Everything looks good, just a couple of minor things I noticed.

2022-08-10 17:23 UTC, sergeymitr commented on projects/plugins/jetpack/modules/google-analytics/classes/class-jetpack-google-amp-analytics.php
> +	 * Checks if its AMP request, if WooCommerce is available, if DNT is disabled, if there's tracking code and in tracking is enabled.
It looks like "in" was supposed to be "if", it might be worth fixing while you're there.

2022-08-10 17:23 UTC, sergeymitr commented on projects/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-options.php
> +		return (bool) self::get_option( 'honor_dnt' );
```suggestion
		return (bool) static::get_option( 'honor_dnt' );
```

2022-08-10 17:28 UTC, chrisbliss18 commented on projects/plugins/jetpack/modules/google-analytics/classes/class-jetpack-google-amp-analytics.php
> +	 * Checks if its AMP request, if WooCommerce is available, if DNT is disabled, if there's tracking code and in tracking is enabled.
Good catch. I'll fix that.

2022-08-10 17:37 UTC, chrisbliss18 commented on projects/plugins/jetpack/modules/google-analytics/classes/class-jetpack-google-amp-analytics.php
> +	 * Checks if its AMP request, if WooCommerce is available, if DNT is disabled, if there's tracking code and in tracking is enabled.
Fixed in the latest commit.

2022-08-10 17:37 UTC, chrisbliss18 commented on projects/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-options.php
> +		return (bool) self::get_option( 'honor_dnt' );
Fixed in the latest commit.

2022-08-11 00:16 UTC, sergeymitr approved these changes
Works like a charm 👍

2022-08-11 18:24 UTC, merged

2022-08-11 18:50 UTC, chrisbliss18 commented
r250559-wpcom