Protect: add the ability to ignore threats for paid plan users
Automattic/jetpack pull request #26571
Opened 2022-10-02 19:24 UTC by nateweller

Fixes #

#### Changes proposed in this Pull Request:

*

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2022-10-05 16:15 UTC, singerb commented on projects/plugins/protect/src/js/components/ignore-threat-modal/index.jsx
> +						'By ignoring this threat you confirm that your have reviewed the detected code and assume the risks of keeping a potentially malicious file on your site. If you are unsure please request an est
`your` -> `you`.

Beyond that, did this language come from the designs? Do we need to be quite so severe here? AFAIK we're not in Calypso, but maybe I missed that.

2022-10-05 16:15 UTC, singerb commented on projects/plugins/protect/src/js/components/ignore-threat-modal/index.jsx
> +						'By ignoring this threat you confirm that your have reviewed the detected code and assume the risks of keeping a potentially malicious file on your site. If you are unsure please request an est
Also, as your screenshot demonstrates, the `potentially malicious` part is not always accurate. If we don't want to tailor this based on the threat, we should do something like `potentially malicious or vulnerable`.

2022-10-06 15:33 UTC, nateweller commented on projects/plugins/protect/src/js/components/ignore-threat-modal/index.jsx
> +						'By ignoring this threat you confirm that your have reviewed the detected code and assume the risks of keeping a potentially malicious file on your site. If you are unsure please request an est
This text is taken directly from the design, which is copied from the Calypso confirmation:

<img width="894" alt="Screen Shot 2022-10-06 at 9 26 58 AM" src="https://user-images.githubusercontent.com/10933065/194354625-4b3df0ed-32a0-44d9-9742-dd7df28a289d.png">

<img width="673" alt="Screen Shot 2022-10-06 at 9 29 48 AM" src="https://user-images.githubusercontent.com/10933065/194355090-db373875-c46f-4c60-8c31-13095496ccfe.png">

I've updated the message via https://github.com/Automattic/jetpack/pull/26571/commits/441458dc03c091177f2a16ed2d11f7753ae0ba0a to fix the typo, and include the `or vulnerable` text to make it more widely applicable.

2022-10-06 17:49 UTC, singerb commented on projects/plugins/protect/src/js/components/ignore-threat-modal/index.jsx
> +						'By ignoring this threat you confirm that your have reviewed the detected code and assume the risks of keeping a potentially malicious file on your site. If you are unsure please request an est
Yep, I actually found that later in the day by accident when I was searching for Codeable stuff. It's fine to match it here.

2022-10-06 22:06 UTC, miguelxpn requested changes

2022-10-06 22:06 UTC, miguelxpn commented on projects/plugins/protect/src/class-jetpack-protect.php
> +				'methods'  => \WP_REST_SERVER::EDITABLE,
We should probably add a capabilities check here to make sure the user is authenticated.

2022-10-11 00:47 UTC, merged