Jetpack plugin: Integrate Stats package
Automattic/jetpack pull request #26640
Opened 2022-10-05 11:03 UTC by fgiannar

**TBA**

Fixes #

#### Changes proposed in this Pull Request:

**Stats options**
* deprecated `stats_get_options`
* deprecated `stats_get_option`
* deprecated `stats_set_options`
* deprecated `stats_set_option`
* deprecated `stats_upgrade_options`

**Tracking pixel**
* Building the tracking pixel data and adding it to the footer is now handled by `Automattic\Jetpack\Stats\Tracking_Pixel`
* removed `stats_array`
* deprecated `stats_add_to_footer`
* deprecated `stats_render_footer`
* deprecated `stats_render_amp_footer`
* deprecated `stats_build_view_data`

**XMLRPC endpoints**
* Stats related XMLRPC endpoints are now handled by `Automattic\Jetpack\Stats\XMLRPC`
* removed `stats_xmlrpc_methods`
* deprecated `stats_get_blog`
* removed `stats_esc_html_deep`

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p9dueE-5Rd-p2

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

TBA

2022-10-06 05:56 UTC, darssen reviewed
I reviewed the code and everything looks good.
Prior to getting some more detailed test instructions, I tested the test-case-reminder steps and everything is working fine. Scripts are showing for amp and non-amp views. Also, Jetpack plugin Dashboard as well as wordpress.com/stats are displaying the views.

2022-10-06 11:50 UTC, darssen requested changes
I have been testing with the updated instructions and have the following comments

- Check the suggested test cases by the test-case-reminder bot  :heavy_check_mark: 

- Play around with the Jetpack plugin's stat settings and make sure they are respected :x: 
    - Pages viewed by an editor with the editor toggle enabled in the **Count logged in pages viewed from** section, are not being tracked. Info seems to be there in HTML but Stats are not being updated. It works fine in `trunk`
- Make sure we track pageviews with [Infinite Scroll enabled](https://jetpack.com/support/infinite-scroll/) :warning: When Infinite Scroll is enabled, stats are tracked. Not sure what is expected or if there is any specific stats to be checked here.
- Make sure we track [Carousel](https://jetpack.com/support/carousel/) views :warning:  When Carousel Views are enabled, stats are tracked. Not sure what is expected or if there is any specific stats to be checked here.
- Pay extra attention to the tracking data we send and make sure the jp version is present as before (j param). As you might note the stats package is not longer adding this to the default data we are tracking, as its plugin agnostic. The Jetpack plugin is adding this parameter now via the stats_array filter :heavy_check_mark: 
- Make sure to compare all the different places we show stats related data with trunk with the Stats module enabled AND disabled (you can disable the module by visiting wp-admin/admin.php?page=jetpack_modules): :heavy_check_mark:

2022-10-06 17:25 UTC, anomiex reviewed
Looks ok from a code perspective. One inline comment, which may be ignored if you don't like it.

Haven't tested it myself, looks like someone else is already on that. 🙂

2022-10-06 17:25 UTC, anomiex commented on projects/plugins/jetpack/3rd-party/class.jetpack-amp-support.php
> +		if ( ! has_action( 'wp_footer', array( 'Automattic\Jetpack\Stats\Tracking_Pixel', 'add_to_footer' ) ) ) {
You could make this a little clearer if you want by using `::class`.
```suggestion
		if ( ! has_action( 'wp_footer', array( Stats_Tracking_Pixel::class, 'add_to_footer' ) ) ) {
```

2022-10-07 09:05 UTC, darssen approved these changes
I was able to properly test the Carousel and I can see stats for the different images.
Infinite scroll testing is something that is evading me, but changes here should not impact it.

Amazing job!!

2022-10-07 09:05 UTC, merged