Add/stats package readme documentation
Automattic/jetpack pull request #26759
Opened 2022-10-11 17:13 UTC by darssen

#### Changes proposed in this Pull Request:

* Updated Readme for Stats Package

#### Jetpack product discussion

1203070774179820-as-1203101231018815/f

#### Does this pull request change what data or activity we track or use?

No
#### Testing instructions:

N/A

2022-10-11 17:15 UTC, darssen commented on projects/packages/stats/README.md
> +- **v**:
Not sure how to name this parameter

2022-10-12 06:38 UTC, fgiannar commented on projects/packages/stats/README.md
> +- **v**:
(internal) Used to distinguish self-hosted sites from the ones hosted on WordPress.com. Enum: `ext, wpcom`

2022-10-12 06:42 UTC, fgiannar requested changes
Looks great, thanks for working on this! I believe we can :shipit: as soon as the conflicts are resolved :)

2022-10-12 08:09 UTC, fgiannar approved these changes, later dismissed
LGTM!

2022-10-12 08:54 UTC, darssen commented on projects/packages/stats/README.md
> +- **v**:
Thanks

2022-10-12 12:37 UTC, fgiannar approved these changes, later dismissed
LGTM!

2022-10-12 12:38 UTC, fgiannar approved these changes
Re-approving

2022-10-12 13:02 UTC, merged