Jetpack: add custom validity for input type URL
Automattic/jetpack pull request #27138
Opened 2022-10-27 23:40 UTC by CGastrell

Use browser's native support for HTML input element validation with custom text. Inputs type URL never specify any expectation on the value, yet the URL is considered invalid unless it includes protocol (http/https).

Fixes #27119 

#### Changes proposed in this Pull Request:
- use `setCustomValidity` to change the hint text shown when trying to submit a form and a required URL input is not filled correctly

Before:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/157240/198417115-5ab2045a-6992-4265-861a-c9bd25f515f5.png">

After:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/157240/198417150-8f77ae29-42dc-4f0d-9144-bf22d77ff0f9.png">

Note: this change is a "fix", but native support will override the value once the input is changed. This works as a better hinting for the user, further customization would require a more complex solution

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Insert a form and add a "Website" input (lately renamed to "URL Field"). Try submitting the form with different values on the website field.

2022-11-07 12:51 UTC, digitalwaveride requested changes
Thank you Christian!
Not sure if related to this PR but there is something off on the submission view -> `"`:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/5120357/200311273-02b2dbd5-1856-4937-b9b1-3283dafe626e.png">


A little other thing I noticed:
When typing a url without any "prefix" ... like www.somesite.com I get the error via the "tooltip" 
and it looks like this:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5120357/200311898-a2b67c07-4db1-4528-b89a-19d494aa8b7c.png">

The moment though I start to type something like this "http:/" or "ht:/"
<img width="749" alt="image" src="https://user-images.githubusercontent.com/5120357/200312261-a04db9e7-7063-4064-b21f-d3cc54d370f7.png">

it seems to try to submit, and shows an error like this:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5120357/200311648-0cb266e7-6b5b-4d0e-8006-b4558077c0d8.png">


Regarding the copy of the error text:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/5120357/200314724-2f7897a9-3e9d-4a82-ab0d-a21548dd7fd0.png">

I personally find it a bit hard to read, and in these cases like to give users an example that they can mimic:

`Please enter a valid URL - https://www.example.com`

2022-11-11 13:22 UTC, digitalwaveride submitted a review, later dismissed
Perfect! Works as advertised!
Thanks Christian!!! 🚀

2022-11-11 18:20 UTC, samiff requested changes, later dismissed
It's a shame that there isn't a simple function like `is_email` to leverage 🙂

A couple thoughts that come to my mind here:

1. If we do go the regex route, perhaps we can abstract that functionality to a shared helper function somewhere as it'd seem quite useful to have around (and tested). I tried looking to see if we already did that somewhere, though the closest I found was using [FILTER_VALIDATE_URL](https://www.php.net/manual/en/filter.filters.validate.php) which isn't perfect as it will not work for internationalized domain names (IDNs)
2. This PR won't as-is won't work for IDNs, example: https://παράδειγμα.test
3. Is there a great reason to validate the URL field type to begin with? As a user, entering `example.com` and then having to enter `http://example.com` to be able to submit the form feels nagging. Does the validation to URL spec provide much value to the website owner I wonder?

2022-11-11 18:20 UTC, samiff commented on projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
> +					'%^(?:(?:https?|ftp)://)?(?:\S+(?::\S*)?@|\d{1,3}(?:\.\d{1,3}){3}|(?:(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)(?:\.(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)*(?:
For my own curiosity, was there an external source for this regex?

2022-11-12 20:13 UTC, CGastrell commented
@samiff completely agree with you, yet I’d stick to a more constrained
scope:

- improve the default validation message browsers offer for the `type=url`
inputs, as it’s not useful enough
- we’re on a long plan to improve overall UX regarding forms/inputs, and
we’ll surely take over all validations eventually (as opposed to rely on
browsers’ default behavior)


I’ll get back at the source of the URL regex, I’m sure it came from SO, but
thanks for reminding me of quoting this kind of things.

On Fri, Nov 11, 2022 at 15:21 Samiff ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> It's a shame that there isn't a simple function like is_email to leverage
> 🙂
>
> A couple thoughts that come to my mind here:
>
>    1. If we do go the regex route, perhaps we can abstract that
>    functionality to a shared helper function somewhere as it'd seem quite
>    useful to have around (and tested). I tried looking to see if we already
>    did that somewhere, though the closest I found was using
>    FILTER_VALIDATE_URL
>    <https://www.php.net/manual/en/filter.filters.validate.php> which
>    isn't perfect as it will not work for internationalized domain names (IDNs)
>    2. This PR won't as-is won't work for IDNs, example:
>    https://παράδειγμα.test
>    3. Is there a great reason to validate the URL field type to begin
>    with? As a user, entering example.com and then having to enter
>    http://example.com to be able to submit the form feels nagging. Does
>    the validation to URL spec provide much value to the website owner I wonder?
>
> ------------------------------
>
> In projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
> <https://github.com/Automattic/jetpack/pull/27138#discussion_r1020454818>:
>
> > @@ -4030,6 +4030,15 @@ public function validate() {
>
>  		}
>
>
>
>  		switch ( $field_type ) {
>
> +			case 'url':
>
> +				if ( ! is_string( $field_value ) || empty( $field_value ) || ! preg_match(
>
> +					'%^(?:(?:https?|ftp)://)?(?:\S+(?::\S*)?@|\d{1,3}(?:\.\d{1,3}){3}|(?:(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)(?:\.(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)*(?:\.[a-z\x{00a1}-\x{ffff}]{2,6}))(?::\d+)?(?:[^\s]*)?$%iu',
>
>
> For my own curiosity, was there an external source for this regex?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Automattic/jetpack/pull/27138#pullrequestreview-1177703733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABGMOA7GEC4KOMWG3RSNALWH2FBLANCNFSM6AAAAAARQRVG4E>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>
-- 
Christian Gastrell

2022-11-14 19:56 UTC, CGastrell commented
@samiff 

I've created #27396 to keep track of your comment regarding an improvement for IDNS support both at code and UX levels.

Meanwhile, I've updated the PR so it allows for more flexible URLs (still no IDNS support), using `type=text` on the frontend but parsing as `type=url` on backend with custom regex validation (allowing URLs without protocol)

2022-11-15 20:49 UTC, samiff approved these changes
I'm a tiny bit hesitant on the loss of IDN support for the URL field with this PR, but approving since we have #27396 open and it sounds like there are larger plans for validation forthcoming.

2022-11-16 13:10 UTC, merged