Image Editor: Fix image edits not persisting or restoring
Automattic/jetpack pull request #27224
Opened 2022-11-02 01:34 UTC by vykes-mac

Fixes #https://github.com/Automattic/wp-calypso/issues/69441

#### Changes proposed in this Pull Request:

* Add `e` to filename suffix in `Jetpack_Media::generate_new_filename` , this suffix is used to determine if the image is an edited image or not. 
* Add a method `restore_original` to reconstruct the file information of the original media
* Check if we should restore file or create an edit, calypso sends a `media_url` for restorations and a `media_file` for edits or new uploads

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2022-11-03 19:37 UTC, sejas reviewed
@vykes-mac, I've tested it on simple sites and it works good !!

I have two questions:
1. Where is the code that  determines if an image is edited or not by reading the `e` suffix added `Jetpack_Media::generate_new_filename` ? I couldn't find it and seems a bit funky.
2. There is another variable `REVISION_HISTORY_MAXIMUM_AMOUNT` equal to `0` in the `class.media.php`. Should we updated to `5` too ?
 https://github.com/Automattic/jetpack/blob/4958ed49369ccd2ace947a0c6d786eafff7347bf/projects/plugins/jetpack/_inc/lib/class.media.php#L26

2022-11-03 22:32 UTC, vykes-mac commented
@sejas 

> Where is the code that determines if an image is edited or not by reading the e suffix added

The code is located in the `wpcom-media` plugin, a filter method `wpcom_wp_get_attachment_url_force_guid` determines what url to return if the file is edited or not using a regex pattern for edited media. This works in conjunction with wp-admin, when u edit a media there an `e` is added to the filename suffix, the filename pattern ensure that it works in both wp-admin and calypso it seems.

> There is another variable REVISION_HISTORY_MAXIMUM_AMOUNT equal to 0 in the class.media.php. Should we update it to 5 too ?

We don't have to, the one define in `class.wpcom-json-api-edit-media-v1-2-endpoint.php ` takes precedence when that endpoint is called.

2022-11-04 12:42 UTC, fgiannar requested changes
Many thanks for working on this!

I tested this with both a Simple and a JP site and getting a few errors/warnings for Simple sites, while it results in an error for JP sites.
Please checkout the more detailed review in D91355

2022-11-04 19:31 UTC, vykes-mac commented
@fgiannar Thanks for the feedback!

> I noticed the following errors when testing the restore functionality on a simple site:

The warning occur because the `Jetpack_Media::remove_items_from_revision_history` was removing the original media also from the `blogs.dir`. I have added logic to not remove the original file.

Also if the file is an old file that does not exist in` blog.dir` when you edit it the edited version will be added to `blog.dir` then when you restore it will delete the edited version then throw the warning, it's the same behaviour in `wp-admin`. 

> Testing on a JP site also fails (restoring an image in Calypso), however I reproduced the same behaviour in trunk:

Restore doesn't work with Jetpack sites because it's looking for `files['media']` in `class.wpcom-json-api.php` to process edits, however calypso sends only `media_url` for restoration and `media_file` for edit/croping

2022-11-07 11:04 UTC, fgiannar approved these changes
> The warning occur because the Jetpack_Media::remove_items_from_revision_history was removing the original media also from the blogs.dir. I have added logic to not remove the original file.

Thanks for fixing this!

> Also if the file is an old file that does not exist in blog.dir when you edit it the edited version will be added to blog.dir then when you restore it will delete the edited version then throw the warning, it's the same behaviour in wp-admin.

Tried with a new image file and can confirm I don't get these warnings 👍 

> Restore doesn't work with Jetpack sites because it's looking for files['media'] in class.wpcom-json-api.php to process edits, however calypso sends only media_url for restoration and media_file for edit/croping

Is there a corresponding bug where we track this? Ideally we should support restores for Jetpack sites in Calypso, aka support restores via the Jetpack API in general. Or at least, hide the functionality in Calypso if it's decided for certain reasons that we don't.

2022-11-07 18:23 UTC, vykes-mac commented
> Is there a corresponding bug where we track this? 

There is no issue related to this bug at the moment as for as I know, We should probably create one. I've been looking into it and it seems to require more effort. Think we should go ahead with this PR and create an issue for the jetpack sites fix.

2022-11-07 20:05 UTC, merged