Update Jetpack Search readme
Automattic/jetpack pull request #27341
Opened 2022-11-10 03:50 UTC by robfelty

This updates the WordPress.org plugin readme to reflect the new pricing with the free tier.

#### Testing instructions:
Validated the readme with the[ wordpress.org validator](https://wordpress.org/plugins/developers/readme-validator/) - it passed.
I also previewed using [wpreadme](https://wpreadme.com/) and it looks fine there too

2022-11-10 17:23 UTC, gibrown requested changes, later dismissed
Let's also update the author info in https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/search/jetpack-search.php#L4

Similar to what Boost is doing: https://github.com/Automattic/jetpack/blob/a1e5f2edeaf82f5c7021ed39a8b39764ccbd61a4/projects/plugins/boost/jetpack-boost.php

(e.g. "Automattic - Jetpack Search team" )

2022-11-10 17:23 UTC, gibrown commented on projects/plugins/search/readme.txt
Let's change the excerpt text also. Right now we aren't using much of the space available: https://wordpress.org/plugins/search/jetpack+search/

Something like:

Easily add instant search and filters to your website or WooCommerce store. Advanced algorithms that boost your search results based on traffic to your site.

2022-11-10 17:23 UTC, gibrown commented on projects/plugins/search/readme.txt
> +From real-time search faceting , to instant search results, Jetpack Search has all the features and options for best site search usability and results.
Maybe "filtering and faceting".

I think "facets" are not a very well known term.

2022-11-10 17:23 UTC, gibrown commented on projects/plugins/search/readme.txt
> +Jetpack Search is free to use for sites with up to 5000 documents and 500 search requests per month. Beyond that, we offer tiered pricing to fit the needs of your site.
"tiered pricing that grows with your site." ???

2022-11-10 17:23 UTC, gibrown commented on projects/plugins/search/readme.txt
>  Tags: search, jetpack
Remove "jetpack" and add some tags: "filter, woocommerce search, ajax search, product search"

2022-11-10 23:11 UTC, kangzj commented
I'll add these changes in 1.3.0 release, so feel free to close this one 😄

2022-11-11 08:35 UTC, robfelty commented
@kangzj @gibrown  - it doesn't look like the readme changes made it into the 1.3.0 release - see https://wordpress.org/plugins/jetpack-search/

2022-11-12 01:38 UTC, kangzj commented
Hi @robfelty, I held the readme changes because the new pricing is not live yet. And as discussed in Slack, we are going to release another version of the Search plugin (probably 1.3.1) first thing next week, so let push forward with this PR 😄 Sorry for the confusion.

We might also want to change the plugin description in `plugins/search/jetpack-search.php` as noted by @gibrown .

Thanks for your work.

2022-11-13 21:09 UTC, gibrown commented on projects/plugins/search/jetpack-search.php
>   * Author: Automattic
Change to: Author: Automattic - Jetpack Search team

per p1HpG7-iZ6-p2

2022-11-13 21:27 UTC, merged