Unlock content immediately for posts with the subscriber access level
Automattic/jetpack pull request #27433
Opened 2022-11-16 03:48 UTC by romarioraffington

Fixes  https://github.com/Automattic/wp-calypso/issues/69664

#### Changes proposed in this Pull Request:

We do not immediately unlock a post with the subscriber access level. Instead, we send a verification email. This is not an ideal user experience. This PR gives immediate access to subscribers after subscribing once the post has the subscriber access level.

To accomplish this we unlock content when the query params with the `blogsub=confirming` and `subscribe=success`. The former query param is displayed for WPCOM sites and the later for Jetpack sites. 

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

**Jetpack**
* Go to your post marked for "All Subscribers"
* Checkout and select the "Free" option
* Notice the content is unlocked immediately

**WPCOM**
* Rsync code to WPCOM
* Go to your post marked for "All Subscribers"
* Checkout and select the "Free" option
* Notice the content is unlocked immediately

2022-11-16 13:37 UTC, artpi requested changes
I see where this approach is going.

You tapped into the return of the current subscribe block flow to capture these parameters and unlock the content.
This will work short-term, but won't work with setting up the cookie for when somebody navigates from the site and back.

The flow would work like so:

1. Click on subscribe
2. Modal opens
3. Choose free option
4. Modal closes
5. The old subscribe form submits
6. Redirects to WPCOM
7. Subscribes user, sends confirmation email
8. Redirects back with query string
9. This PR is intercepting this query string and unlocking content based on it's contents.

What I think should be happening:

1. Click on subscribe
2. Modal opens
3. Choose free option
4. This PR should change how this free option behaves. It should subscribe user inside the modal and redirect with a valid JWT token (with blog_sub=confirming) that in turn will unlock content

2022-11-16 13:37 UTC, artpi commented
I'm open to discussion!

2022-11-17 14:08 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php
> +			if ( self::POST_ACCESS_LEVEL_SUBSCRIBERS === $access_level ) {
I have modified all that logic in [this PR](https://github.com/Automattic/jetpack/pull/27352). Do you mind to wait and rebase on it? It should be minimal work compared to the other way around ....

2022-11-17 14:10 UTC, millerf approved these changes
LGTM- added a comment about merging

2022-11-18 13:54 UTC, artpi commented on projects/plugins/jetpack/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php
> +				return in_array(
Yes, that is what I was thinking about!

2022-11-21 19:05 UTC, merged