Contact Form: Include new Patterns
Automattic/jetpack pull request #27510
Opened 2022-11-18 23:13 UTC by jcheringer

Fixes #27469

#### Changes proposed in this Pull Request:
* Include new patterns in the Forms category
* The new patterns are shown here: pcsBup-sa-p2

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a Post and navigate to the Patterns tab inside the Block Library
* Check if the new patterns are available under the Forms category

2022-11-25 20:10 UTC, digitalwaveride requested changes
Thanks a ton João!

Looks good! Noticed one glitch though:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/5120357/204050953-e6427396-b8df-4df9-aabd-9dd69eb5c53d.png">

The "newsletter signup with background" pattern, there is an issue with the "white background":

<img width="826" alt="image" src="https://user-images.githubusercontent.com/5120357/204051113-4c8b281c-8642-4f63-8031-f5c06a331b22.png">

2022-11-25 21:58 UTC, jcheringer commented
Thanks for testing it @digitalwaveride
My last commit should fix the issue.

2022-11-28 13:21 UTC, CGastrell reviewed
Everything looks good, nice! 

One concern though: most images seem to be coming from the media library of one of our AT sites, could we get the CDN url for those?

2022-11-28 14:02 UTC, jcheringer commented
That's a good suggestion, @CGastrell.
I can change the images' URLs, but I don't know how to get the CDN URL.
Can I have some guidance?

2025-08-19 06:43 UTC, closed without merging