WAF: Add Waf_Manager Class
Automattic/jetpack pull request #28106
Opened 2022-12-28 22:36 UTC by nateweller

Fixes #

#### Changes proposed in this Pull Request:

*

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

#### Does this pull request change what data or activity we track or use?

#### Testing instructions:

* Go to '..'
*

2023-01-19 21:04 UTC, dkmyta submitted a review, later dismissed
With the exception of the random fatal I couldn't replicate consistently regarding the failure to write to the allow list (that may not necessarily be directly related to these changes), with all suggested updates applied, everything looks great and appears to continue to work nicely.

There is also currently one WAF-related post-connection test failing that will require some attention.

2023-01-19 21:04 UTC, dkmyta commented on projects/packages/waf/src/class-waf-manager.php
> +		if ( ! self::is_allowed_mode( JETPACK_WAF_MODE ) ) {
Looks like `is_allowed_mode()` is still currently a `Waf_Runner` method.

After updating that, however, I was hit with a separate fatal:
```
PHP Fatal error:  Uncaught Exception: Failed writing allow list file to: /var/www/html/wp-content/jetpack-waf/rules/allow-ip.php in /usr/local/src/jetpack-monorepo/projects/packages/waf/src/class-waf-rules-manager.php:312
```
This may have just been a product of making changes on the fly to the WAF package without installing after the updates as I couldn't replicate it consistently. In summary, this happened on a fresh site (no existing WAF options) after installing/activating Jetpack, connecting my user, activating the Firewall, and fixing the initial fatal.

2023-01-19 21:04 UTC, dkmyta commented on projects/packages/waf/src/class-waf-manager.php
> +		delete_option( self::MODE_OPTION_NAME );
Another `Waf_Runner` constant.

2023-01-19 21:04 UTC, dkmyta commented on projects/packages/waf/src/class-waf-manager.php
> +		add_option( self::SHARE_DATA_OPTION_NAME, true );
This also appears to be a `Waf_Runner` constant.

2023-01-19 21:04 UTC, dkmyta commented on projects/plugins/protect/src/class-jetpack-protect.php
> +				'isEnabled'   => Waf_Manager::is_enabled(),
We'll need to add a top-level `use` statement for this new class:
```
use Automattic\Jetpack\Waf\Waf_Manager;
```

2023-01-27 00:47 UTC, nateweller commented
@dkmyta Thanks for the initial review! I've rebased on `trunk` and made some updates.

The only notable differences from your last review should be:
1. Moved all option names into `Waf_Manager` - no need for them to be in `Waf_Runner`.
2. Moved the new `automatic_rules_available()` method from `Waf_Runner` to `Waf_Manager`.

Otherwise everything should be the same :+1:

2023-01-27 00:51 UTC, nateweller commented
^ Also merged in a README update, which Miguel approved here: #28107

2023-01-27 18:02 UTC, dkmyta requested changes
I think perhaps rebasing has reintroduced the initial issues with the `Waf_Manager` using `self::` for `Waf_Runner` methods - in particular `is_allowed_mode()`.

2023-02-25 02:15 UTC, nateweller commented
Going to close this and come back to it after we have finished updating the WAF with improved error handling and test coverage.

2023-02-25 02:15 UTC, closed without merging