[Paid Nesletters] tests for paid newsletters regressions
Automattic/jetpack pull request #28966
Opened 2023-02-15 10:33 UTC by millerf

Fixes #

## Proposed changes:

* Added PHPunit test

### Other information:

- [X] Have you written new tests for your changes, if applicable?
- [X] Have you checked the E2E test CI results, and verified that your changes do not break them?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Run docker `jetpack docker up -d`
* Run PHP unit testsuite `jetpack docker phpunit -- -c tests/php.multisite.xml --testsuite=premium-content`

2023-02-15 13:27 UTC, artpi approved these changes, later dismissed
This is ok, however we are missing a test

- subscriber is a paid subscriber
- `comments_open` default is false
- Filter should default to false

2023-02-15 13:27 UTC, artpi commented on projects/plugins/jetpack/tests/php/modules/premium-content/test_class.jetpack-premium-content.php
> +		update_post_meta( $plan_id, 'jetpack_memberships_product_id', $this->product_id );
Where is this meta used?

2023-02-15 13:30 UTC, millerf commented on projects/plugins/jetpack/tests/php/modules/premium-content/test_class.jetpack-premium-content.php
> +		update_post_meta( $plan_id, 'jetpack_memberships_product_id', $this->product_id );
copy/paste issue...

2023-02-15 13:48 UTC, millerf commented on projects/plugins/jetpack/tests/php/modules/premium-content/test_class.jetpack-premium-content.php
> +		update_post_meta( $plan_id, 'jetpack_memberships_product_id', $this->product_id );
@artpi this is actually used in https://github.com/Automattic/jetpack/blob/94ddae8284758db97529fad30752b9e11a556bb1/projects/plugins/jetpack/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php#L237

Stack call:
```
- class-token-subscription-service.php:238, Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service::validate_subscriptions()
- class-token-subscription-service.php:94, Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service->visitor_can_view_content()
- access-check.php:99, Automattic\Jetpack\Extensions\Premium_Content\current_visitor_can_access()
- test_class.jetpack-premium-content.php:152, WP_Test_Jetpack_Premium_Content->test_access_check_current_visitor_can_access_regular_users()
TestCase.php:1548
```

2023-02-15 13:59 UTC, millerf commented
> This is ok, however we are missing a test
> 
> * subscriber is a paid subscriber
> * `comments_open` default is false
> * Filter should default to false

Test was added 👍

2023-02-16 11:07 UTC, artpi commented on projects/plugins/jetpack/tests/php/modules/premium-content/test_class.jetpack-premium-content.php
> +		update_post_meta( $plan_id, 'jetpack_memberships_product_id', $this->product_id );
Ah I remember now

2023-02-16 11:51 UTC, artpi approved these changes, later dismissed
Nice work!

2023-02-17 17:42 UTC, jeherve requested changes
Thanks for adding tests!

For our futureselves, I wonder if that new `modules/premium-content` directory may prove confusing.
When adding new files and directories to `projects/plugins/jetpack/tests/php/`, we try to follow the file structure one may find in `projects/plugins/jetpack`. This way, when a new contributor (or an old one who hasn't looked at that part of the codebase in a while) wants to check on tests for a specific class, function, or method, they can check the matching file in the tests directory.
Do you think you could move those tests to where they match the different methods we're testing here?

One more thing that can help is to add `@covers` in the docblock of each test, for the same reason.

Thank you!

2023-02-20 10:17 UTC, jeherve approved these changes

2023-02-20 10:22 UTC, merged

2023-02-20 10:23 UTC, millerf commented
[THOSE COMMENT DID NOT SEND - ADDING THEM NOW FTR]

> Do you think you could move those tests to where they match the different methods we're testing here?

Sorry I didn't see the `/extensions` folder. Now it should be fine. Do you think I should put it in a sub `_inc/` folder as well?

> One more thing that can help is to add @covers in the docblock of each test, for the same reason.

Didn't know about those. Done 👍