Update/ add useAutoGeneratedChapter hook
Automattic/jetpack pull request #29025
Opened 2023-02-17 14:56 UTC by jhnstn

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/5488
Depends on https://github.com/Automattic/jetpack/pull/29024

## Proposed changes:

* Refactor `edit.tsx` to use a custom hook to determine if a Video chapter was auto generated.
* Add a lib file to fetch video chapter data 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

TBD

2023-02-21 17:49 UTC, fluiddot requested changes

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/blocks/video/edit.tsx
>  	// Store if the chapters file is auto-generated in a local state.
I'm wondering if this comment should be along with the following line in the hooks `useAutoGeneratedChapter`, WDYT?
```
const [ isAutoGeneratedChapter, setIsAutoGeneratedChapter ] = useState( true );
```

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/blocks/video/edit.tsx
> +import useAutoGeneratedChapter from '../../hooks/use-auto-generated-chpater';
Typo:
```suggestion
import useAutoGeneratedChapter from '../../hooks/use-auto-generated-chapter';
```

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/lib/get-chapter/index.ts
> +	if ( isPrivate && ! token ) {
In the previous code this line had the following comment, should we add it back?
```
// Wait for the token when the video is private.
```

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/blocks/video/edit.tsx
> -		}
I'm wondering why we had to catch the `fetch` call using `try-catch` if we already cover the failure of the promise 🤔 .

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/lib/get-chapter/index.ts
> +	const chapterUrl = `https://videos.files.wordpress.com/${ guid }/${ chapter.src }${ queryString }`;
The type of `guid` argument is marked as optional ([reference](https://github.com/Automattic/jetpack/blob/8dbe986d3d5e2c3712e52d2975ce86e99a2a0a80/projects/packages/videopress/src/client/lib/get-chapter/types.ts#L8)) and I understand that is required to compose the request URL, hence I think we would need either to set it as required or check the value before making the request.

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/lib/get-chapter/index.ts
> + * internal dependencies
Typo:
```suggestion
 * Internal dependencies
```

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/hooks/use-auto-generated-chpater.ts
> + */
Seems we don't have internal dependencies imported in this file so we could remove this comment block.

2023-02-21 17:49 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/blocks/video/edit.tsx
> -	// Detect if the chapter file is auto-generated.
This comment is missing in the changes, could we incorporate it along with its associated line?

2023-02-21 18:28 UTC, fluiddot requested changes

2023-02-21 18:28 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/blocks/video/edit.tsx
> +	const chapter = tracks?.find( ( track: TrackProps ) => track.kind === 'chapters' )?.[ 0 ];
I tested the auto-generated chapters and noticed that they weren't working. Seems the cause is in this function as we changed the function to look for chapters from `filter` to `find`. However, we are still trying to get the first item which results in `undefined` always.

Hence, we either keep the usage of `filter`:
```suggestion
	const chapter = tracks?.filter( ( track: TrackProps ) => track.kind === 'chapters' )?.[ 0 ];
```

Or use `find`:
```suggestion
	const chapter = tracks?.find( ( track: TrackProps ) => track.kind === 'chapters' );
```

2023-02-23 20:27 UTC, jhnstn commented
https://github.com/Automattic/jetpack/pull/28945 removes the need for this new hook

2023-02-23 20:27 UTC, closed without merging