Search: Add JITM container
Automattic/jetpack pull request #29106
Opened 2023-02-22 21:39 UTC by dhasilva

Fixes #27501

## Proposed changes:

* Adds a container for JITM on the Search dashboard

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-02-23 09:33 UTC, nunyvega approved these changes
I tested it by modifying the existing `$search_review_jitm`, using this message path: 
`->message_path( '/wp:(jetpack_page_jetpack-search):admin_notices/' )`

It works as expected:
<img width="1383" alt="Screenshot 2023-02-23 at 10 15 51" src="https://user-images.githubusercontent.com/16329583/220865504-881da2d2-e33e-42b7-9551-1dd01d151cb7.png">

2023-02-23 09:57 UTC, nunyvega requested changes
After testing it again, it looks like the container is not working. I see the JITM is not being created inside the container. 

It looks like we're not adding it in the right place, I'll check what's going on

2023-02-23 10:17 UTC, nunyvega commented
This is how it should look with the container:
![image](https://user-images.githubusercontent.com/16329583/220879040-a5e61c2c-637b-4b58-b26e-a23286b8e9e3.png)

I tested adding the container in line 108 ( first in the return of `DashboardPage`) instead of adding it in `MockedSearchInterface`

2023-02-23 19:54 UTC, dhasilva commented
It seems that the placement is correct, but the JITM loads before the page and does not find the container element

ref p1677177566560039-slack-CDLH4C1UZ

2023-02-24 19:43 UTC, nunyvega commented
Let's keep it at the top then to not have to change any loading logic.
@dhasilva  I added the container before the loading checks so the JITM gets the required styling.

2023-02-24 19:44 UTC, nunyvega approved these changes

2023-02-24 21:36 UTC, merged