Inline critical styles and remove the blur effect from the form blocks
Automattic/jetpack pull request #29140
Opened 2023-02-23 21:52 UTC by ice9js

## Proposed changes:

This PR should help fix the issue with shifting form layouts when using outlined or animated style variations, by loading the necessary CSS inline, separately from our main CSS file.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

- Create a post with a contact form or forms.
- Test for either style variation: default, outlined and animated.
- Publish the post.
- When you view the public post, the contact form blocks should no longer be blurred while they're loading.
- While the page is loading, the form inputs and labels should also 'not shift violently.

2023-02-24 20:29 UTC, CGastrell commented
Mmm... not quite as expected, but maybe there's room for improvement.

> While the page is loading, the form inputs and labels should also 'not shift violently.

I wouldn't say they "shifted violently", but the sudden style impact is quite noticeable. Here, load this one https://extraordinary-louse.jurassic.ninja/2023/02/24/forms/, use the devTools to throttle down to Slow 3G (or some similar thing). 

The third one (Animated) is particularly different once styles load. The first one holds a `<select>` which is also another jumpy one.

Maybe we can squeeze more of this kind of solution there, I mean, it is improved. On the other hand, this kind of things on the interwebs is also not so strange and we can't also develop with a slow 3G in mind (otherwise, we'd still give support for IE). So, I think this deserves a bit more love, but I also think we're on the right path.

2023-02-27 21:50 UTC, oskosk commented
@CGastrell can you put a video of what you're witnessing? I only see a slight flickering in the dropdown. Even with 3g it's extremely acceptable and way preferable to the blur. I tested in Safari and Edge, and while it looked like bit more noticeable, it's still uncomparable to the blur

2023-02-27 22:14 UTC, CGastrell commented
> @CGastrell can you put a video of what you're witnessing? I only see a slight flickering in the dropdown. Even with 3g it's extremely acceptable and way preferable to the blur. I tested in Safari and Edge, and while it looked like bit more noticeable, it's still uncomparable to the blur

An improvement indeed, I was just mentioning it's still noticeable. Maybe I forgot to add some "LGTM!", but I also knew this was a first approach towards a more elegant solution, so I was trying to build on that.

As for videos, these are the 3 forms on that page, loading throttled to slow 3g:

https://user-images.githubusercontent.com/157240/221697921-0f1cddac-f362-4f14-b7b6-d9b0368cf1fe.mov


https://user-images.githubusercontent.com/157240/221697929-30a5053b-85de-4473-8944-140095d3cdb0.mov


https://user-images.githubusercontent.com/157240/221697935-fecf5aac-e8f8-4801-8778-a15d0a8f1bd7.mov

2023-02-28 13:27 UTC, jcheringer requested changes
As we discussed offline, I believe that adding default values to the variables will improve things, and it's a simpler solution.
The CSS below is what I've added to `plugins/jetpack/extensions/blocks/contact-form/editor.scss`:

```CSS
:root {
    --jetpack--contact-form--border: 1px solid #8c8f94;
    --jetpack--contact-form--border-color: #8c8f94;
    --jetpack--contact-form--border-size: 1px;
    --jetpack--contact-form--border-style: solid;
    --jetpack--contact-form--border-radius: 0px;
    --jetpack--contact-form--input-padding: 16px;
}
```

2023-03-01 20:45 UTC, closed without merging