Stats: Add image to upgrade notice
Automattic/jetpack pull request #29273
Opened 2023-03-03 08:34 UTC by a8ck3n

Part of #28729.

## Proposed changes:

Adds an image + gradient to the upgrade nudge.

<img width="877" alt="SCR-20230303-mv3" src="https://user-images.githubusercontent.com/40267301/222670158-a652fd57-0f9a-4df9-92f3-08bde3934487.png">

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

- Make sure Odyssey Stats are disabled.
- Visit Jetpack → Stats.
- Confirm the image is present in the upgrade nudge.
- Confirm the image is removed at smaller screen sizes.

**Looking for feedback!**

I'm not super happy with the gap below the image when resizing the screen but I'm unsure of how to remove it and have the image size itself properly. I've tried setting both images via CSS but then neither are drawn. I need something in the HTML to trigger proper layout.

2023-03-03 22:01 UTC, jsnmoon requested changes
These changes look reasonable and test well on my local Jetpack test site. I recommended some styling tweaks and highlighted where we might have accidentally removed two internationalization calls.

I do have a suggestion for simplifying [our background implementation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds), however:

1. Remove `img.stats-odyssey-notice--image`.
2. Apply `width: 100%;` to both `.stats-odyssey-notice--content` and `.stats-odyssey-notice--image-container`.
3. Replace the existing `background-image` rule with `url("/wp-content/plugins/jetpack/images/odyssey-upgrade/background.png"), url("/wp-content/plugins/jetpack/images/odyssey-upgrade/gradient.png")`.

The result should look like the following:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4044428/222837473-f2af43a8-b792-4204-bb40-ce8b7c9f256b.png">

2023-03-03 22:01 UTC, jsnmoon commented on projects/plugins/jetpack/modules/stats.php
> +			<p class="stats-odyssey-notice--content-text">We've added new stats and insights in a more modern and mobile friendly experience to help you grow your site.</p>
What's the reason for removing the `esc_html_e` translation calls for these two lines?

2023-03-03 22:01 UTC, jsnmoon commented on projects/plugins/jetpack/modules/stats.php
>  			border-color: var( --jp-black );
```suggestion
			border-color: var( --jp-gray-5 );
			border-left-color: var( --jp-black );
```

2023-03-03 22:01 UTC, jsnmoon commented on projects/plugins/jetpack/modules/stats.php
> +			padding: 24px 0 27px 18px;
<img width="660" alt="image" src="https://user-images.githubusercontent.com/4044428/222835118-f8450137-7205-46f0-bbb0-105c967a4fd3.png">

```suggestion
			padding: 24px 0 24px 30px;
```

2023-03-03 22:01 UTC, jsnmoon commented on projects/plugins/jetpack/modules/stats.php
> +			font-size: 16px;
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/4044428/222836268-ee46a9d3-33e8-497c-83b4-f8dbee112ce0.png">

```suggestion
			font-size: 24px;
			line-height: 32px;
```

2023-03-06 06:07 UTC, a8ck3n commented on projects/plugins/jetpack/modules/stats.php
> +			<p class="stats-odyssey-notice--content-text">We've added new stats and insights in a more modern and mobile friendly experience to help you grow your site.</p>
Ah! No reasoning behind this. Just a mistake on my part. I was writing the new layouts side-by-side with the old ones (ie: a new function call) and displaying both in the UI so I could compare the results. I overlooked this when cleaning up and removing the old code path.

Thanks for flagging this!

2023-03-06 06:40 UTC, a8ck3n commented
Thanks for the review and suggestions @jsnmoon. Changes incoming!

Regarding the padding and font bits, I was working from the [Notice class](https://github.com/Automattic/jetpack/blob/trunk/projects/js-packages/components/components/notice/style.module.scss) in JS Packages → Components. I should have double-checked against the Figma file once I had things in place though.

2023-03-07 22:54 UTC, jsnmoon approved these changes
Looks great; feel free to ship!

cc @jeffgolenski: The Odyssey Stats screenshot dimensions are 437px x 210px. Should we use a higher-resolution image here, or are we okay with a bit of pixelation?

2023-03-07 22:55 UTC, jsnmoon submitted a review, later dismissed

2023-03-09 06:07 UTC, a8ck3n commented
> Looks great; feel free to ship!
> 
> cc @jeffgolenski: The Odyssey Stats screenshot dimensions are 437px x 210px. Should we use a higher-resolution image here, or are we okay with a bit of pixelation?

@jsnmoon We have higher resolution versions in the original issue.

I downsized them when I thought the max display height would be 210px. We could definitely resize from the original assets again if needed but we probably don't want to use the original assets as is. The gradient image itself was over 3 MB in size. I'll spin up a follow-up issue to review the images though, so we can see if there's a better size/quality trade-off we can hit.

2023-03-09 09:08 UTC, a8ck3n commented
**Update:** I restored the original promo image to address the fuzzy look Jason noted. We're currently still using a scaled version of the gradient though, as I'm not seeing a noticeable difference when restoring the original full size image file.

@jeffgolenski — Let me know if this works for you!

2023-03-09 21:38 UTC, jsnmoon approved these changes
Looks good!

2023-03-09 21:40 UTC, merged