Jetpack: Use the WAF REST API to manage firewall settings
Automattic/jetpack pull request #29299
Opened 2023-03-04 21:19 UTC by nateweller

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-03-14 03:13 UTC, miguelxpn submitted a review, later dismissed

2023-03-14 03:38 UTC, miguelxpn approved these changes, later dismissed

2023-03-15 10:42 UTC, jeherve requested changes
This doesn't quite work for me with the Jetpack plugin. I now see a `false` value instead of the default:

**current stable**

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/426388/225285399-05681894-5eea-4270-ab8d-84d01cea627d.png">

**This branch**

<img width="1065" alt="Screenshot 2023-03-15 at 11 41 31" src="https://user-images.githubusercontent.com/426388/225285434-92a2c11f-93a5-4892-b604-ce06867240d5.png">

2023-03-15 18:23 UTC, nateweller commented
Thanks for catching this @jeherve, fixed via https://github.com/Automattic/jetpack/pull/29299/commits/22e642eec113108fbb866329852e5d5ea126cc26 👍

2023-03-16 09:13 UTC, jeherve approved these changes
This tests well for me now. 🚢

2023-03-16 21:21 UTC, merged