JITM: Add external link icon to CTAs that opens new tab.
Automattic/jetpack pull request #29654
Opened 2023-03-23 12:18 UTC by jkguidaven

Certain JITM CTAs open new tabs, those that do, should have an external link icon. This PR updates the JITM to render external link icon.

**Before**:
<img width="640" alt="Screen Shot 2023-03-23 at 8 17 04 PM" src="https://user-images.githubusercontent.com/56598660/227201294-1e8df1c0-4738-4a3e-9ae7-d84f264813ed.png">

**After**:
<img width="1096" alt="Screen Shot 2023-03-23 at 7 43 54 PM" src="https://user-images.githubusercontent.com/56598660/227201180-f7414e04-ed58-4156-b952-2b654849a941.png">

Fixes https://github.com/orgs/Automattic/projects/587/views/1?pane=issue&itemId=20945705

## Proposed changes:
* Update JITM package to render external link icons when CTA is a link to external url.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-03-27 10:39 UTC, manzoorwanijk commented on projects/packages/jitm/src/css/jetpack-admin-jitm.scss
> +			fill: #fff;
```suggestion
			fill: $white;
```

2023-03-27 10:40 UTC, manzoorwanijk submitted a review, later dismissed
Looks great

2023-03-28 05:22 UTC, jkguidaven commented on projects/packages/jitm/src/css/jetpack-admin-jitm.scss
> +			fill: #fff;
fixed. thanks 👍

2023-03-28 13:25 UTC, jeherve requested changes
this tested well for me in Chrome, Firefox, Edge, and Safari. I could not test the updates to the lists in JITMs, I don't know that we have JITMs currently active with lists.

I left 2 tiny nitpicks below regarding code style, but other than that I think we should be good to go!

2023-03-28 13:25 UTC, jeherve commented on projects/packages/jitm/src/js/jetpack-jitm.js
> +					(externalLink ? EXTERNAL_LINK_ICON : '')
In line with the rest of the file, I think there should be spaces here?

```suggestion
					( externalLink ? EXTERNAL_LINK_ICON : '' )
```

2023-03-28 13:25 UTC, jeherve commented on projects/packages/jitm/src/js/jetpack-jitm.js
> +				var externalLink = envelope.CTA.newWindow && !ajaxAction;
```suggestion
				var externalLink = envelope.CTA.newWindow && ! ajaxAction;
```

2023-03-28 13:26 UTC, jeherve submitted a review, later dismissed

2023-03-28 17:48 UTC, dhasilva commented
This may need a rebase because of https://github.com/Automattic/jetpack/pull/29749, just to be sure.

2023-03-29 05:54 UTC, jkguidaven commented
@jeherve, thanks for fixing the coding style.

I have fixed the conflict. Can I have another approval again so I can merge the PR?  🙏

2023-03-29 08:21 UTC, jeherve approved these changes

2023-03-29 09:20 UTC, merged