Jetpack Social: Add toggle to Social admin page to enable or disable SIG and pick a default template
Automattic/jetpack pull request #29722
Opened 2023-03-27 14:30 UTC by danielpost

## Proposed changes:

This PR adds a toggle to the Social admin page that can be used to enable or disable Social Image Generator. It also adds a button that opens a template picker for choosing a default template.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

1202816441505085-as-1204116019981285/f
1202816441505085-as-1204097909752714/f

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Enable SIG on your site and open the Social admin page.
* Make sure that the toggle matches the screenshot.
* Check that the toggle updates the status by running `( new Automattic\Jetpack\Publicize\Social_Image_Generator\Settings() )->is_enabled();`
* * Check that the template picker updates the default template by running `( new Automattic\Jetpack\Publicize\Social_Image_Generator\Settings() )->get_default_template();`

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1713699/227970283-fda132be-d682-4942-9286-11fa73efa974.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1713699/227970315-71f1ab22-34e1-4340-8019-3f842abb0fed.png">

2023-03-27 15:56 UTC, gmjuhasz requested changes
I think this is close. I do have another issue, if I open a post that was created before this change, on that post the template picker has nothing selected. Even if I select something, saving then reloading shows that none is selected. This also happens on new post, if I save them as draft and reload the page

<img width="1065" alt="CleanShot 2023-03-27 at 17 52 04 png" src="https://user-images.githubusercontent.com/36671565/227995323-7d56fc88-08df-486e-aabc-13cf07257f3c.png">

I am not sure yet what causes it

2023-03-27 22:29 UTC, pablinos reviewed
This looks pretty good to me. The more I think about it, the more I feel we should default SIG to enabled. We could do that by adding `'enabled' => true` to [the default array](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/publicize/src/social-image-generator/class-settings.php#L44). I realise that means someone would have to install Social to turn it off, but currently they'd need to do that to turn it on. I'm not sure which way round is best!

Just one minor thought on how we check for SIG being enabled in the initial state.

2023-03-27 22:29 UTC, pablinos commented on projects/plugins/social/src/class-jetpack-social.php
> +					'isSocialImageGeneratorEnabled' => $publicize->has_social_image_generator_feature() && ( new Automattic\Jetpack\Publicize\Social_Image_Generator\Settings() )->is_enabled(),
This is probably fine, but should we create a helper function that combines these two checks?

Also this removes the panel entirely, so we should probably do things like not register the meta when it's been disabled like this. Maybe we should have a `$publicize->is_social_image_generator_enabled` that can check the plan and the setting, like this, and we can use that where we're currently just checking for the feature.

2023-03-28 07:43 UTC, gmjuhasz approved these changes
For my previous comment:
We investigated that it was an issue with meta saving on trunk, not this pr.

We said that we will create a follow-up for the comments Paul mentioned above.

Other than that, looks good to me.

2023-03-28 07:48 UTC, merged