My Jetpack: Move Search back to a hybrid product
Automattic/jetpack pull request #29946
Opened 2023-04-05 17:33 UTC by lhkowalski

Part of #29906. We are moving the products that have standalone plugins back to hybrid products and then enhancing the status handling on them. This way we can mark them as active or not and push the standalone installation or not, on any given state.

## Proposed changes:

* Turn Search into a Hybrid product again, so we can manage it's status as a module and also as a standalone product
* Fix related tests to accomodate the hybrid product behavior

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-04-05 18:35 UTC, retrofox approved these changes
LGTM

2023-04-05 18:38 UTC, retrofox requested changes
...

2023-04-05 18:40 UTC, retrofox approved these changes
Tested again. LGTM! 🚢

2023-04-06 13:34 UTC, renatoagds approved these changes

2023-04-06 14:26 UTC, merged