CRM: Resolves 3030 - catch PHP 8.1 errors
Automattic/jetpack pull request #29945
Opened 2023-04-05 17:10 UTC by tbradsha

CRM: Resolves Automattic/zero-bs-crm#3030 - catch PHP 8.1 errors

## Proposed changes:

While working on Automattic/jetpack-crm-extensions#601, I realised it only occurred in PHP 8.1. As such, I decided to do a quick sweep of our pages on PHP 8.1, and discovered that along with the original CSV importer issue:

* WP menus were broken and headers prematurely sent if debug was output
* Our task system is using `strftime()` (Automattic/zero-bs-crm#2884, see also Automattic/zero-bs-crm#300)

This PR addresses the first item in two ways:

1. While traditionally one could pass `null` as the parent slug of a submenu page, PHP 8.1 no longer allows that. I tried an empty string [as `wordpress-seo` did](https://github.com/Yoast/wordpress-seo/pull/19191/files), which fixed the original issue but resulted in another error with hidden pages + page titles. Thus I used `jpcrm-hidden` as the parent menu slug.
2. When loading settings, we check if a setting is JSON. If the setting value was `null`, PHP 8.1 would complain, so I put a check to return `false` if the value is null.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

1. Enable full PHP logs.
3. Go to any page (JPCRM or otherwise).

On `trunk` one sees dozens of deprecation notices and the WP menus are broken.

On `fix/crm/3030-catch_PHP_8.1_errors` all is well.

2023-04-06 23:45 UTC, gogdzl requested changes
Thanks for catching that! 
We were generating a huge chunk of messages here.

Just to be through I did some extensive testing and found two more warnings:

1. Enter the tasks main page:
`/wp-admin/admin.php?page=manage-events`
```
Deprecated: Function strftime() is deprecated in /Users/diegorodrigues/git/avengers/jetpack/projects/plugins/crm/includes/ZeroBSCRM.Core.Localisation.php on line 325
```

2. Click edit in any contact:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=contact&zbsid=1`
```
 Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/diegorodrigues/git/avengers/jetpack/projects/plugins/crm/includes/ZeroBSCRM.GeneralFuncs.php on line 148
```

Tried my best to find even more, but couldn't. I think that after these two were good to go!

2023-04-07 12:36 UTC, tbradsha commented
> Enter the tasks main page 

Yes, see my message in the PR description. This one is a bit more complicated.

> Click edit in any contact

I wasn't able to reproduce this one. As best I can trace it back, it's probably caused by a `$this->stripSlashes()` somewhere in `includes/ZeroBSCRM.DAL3.Obj.Contacts.php`, but it'd be good to reproduce if possible. Any help?

2023-04-12 10:46 UTC, cleacos commented
I get the deprecated notice for `includes/ZeroBSCRM.Core.Localisation.php on line 325` this, as was expected, but I don't get the second issue Diego got.

For that second issue that Diego got, it's going to be difficult to replicate it. It seems that it is an array with a null item inside, which is causing the issue. Probably checking whether `$value` is null will fix it.

2023-04-12 15:09 UTC, gogdzl commented
> Click edit in any contact:
> wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=contact&zbsid=1
> ```
>  Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/diegorodrigues/git/avengers/jetpack/projects/plugins/crm/includes/ZeroBSCRM.GeneralFuncs.php on line 148
> ```

It turns out that the issue was caused by this bug I found.
That said, approved!

2023-04-12 15:10 UTC, gogdzl approved these changes

2023-04-12 15:13 UTC, merged