Update/boost score bar to react component
Automattic/jetpack pull request #30037
Opened 2023-04-11 20:58 UTC by CodeyGuyDylan

This PR adds a Jetpack Boost Speed Score Bar component to the components package so it can be used in both the Jetpack Boost and Jetpack plugin

## Proposed changes:
 * Add a Jetpack Boost Speed Score Bar component
 * Make it a storybook component
 * Add tests

## Jetpack product discussion

P2: pbNhbs-4T7-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

1. Checkout these changes
2. Start your local Jetpack environment
3. Run `jetpack install plugins/boost && jetpack build plugins/boost` and have `jetpack watch plugins/boost` going since that is where we will be testing this component
4. Install the Boost plugin and optionally purchase a plan for it
5. Go to `/wp-admin/admin.php?page=jetpack-boost`
6. Add the following imports
```svelte
import { BoostScoreBar } from '@automattic/jetpack-components';
import ReactComponent from '../../../elements/ReactComponent.svelte';
```
7. Go to the file `projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte` and after line 178, insert the following lines of code
```svelte
        <br />
        <br />

        <ReactComponent
            this={BoostScoreBar}
            prevScore={scores.noBoost?.mobile}
            score={scores.current.mobile}
            active={siteIsOnline}
            {isLoading}
            {showPrevScores}
            scoreBarType="mobile"
            noBoostScoreTooltip={__( 'Your mobile score without Boost', 'jetpack-boost' )}
        />

        <ReactComponent
            this={BoostScoreBar}
            prevScore={scores.noBoost?.desktop}
            score={scores.current.desktop}
            active={siteIsOnline}
            {isLoading}
            {showPrevScores}
            scoreBarType="desktop"
            noBoostScoreTooltip={__( 'Your desktop score without Boost', 'jetpack-boost' )}
        />
```
8. Refresh the page and ensure the two bars on the bottom look and act the same as the bars on the top
![image](https://user-images.githubusercontent.com/65001528/231285694-7c6ce7e8-5508-43c8-a9b5-2b2cccaf350d.png)
9. Test out the Refresh button and the tooltip when you hover over the previous score ( to see this, you'll need to run a speed score, turn on some boost features, and then run it again )
10. To see the storybook component, go to `projects/js-packages/storybook` and run `npm run storybook:build && npm run storybook:dev`. The link will be provided once the build is done, but it should be http://localhost:50240/?path=/story/js-packages-components-boost-score-bar--default
11. To run the tests manually, go to `projects/js-packages/components` and run `npm run test components/boost-score-bar`

2023-04-18 17:30 UTC, anomiex commented on projects/js-packages/components/components/boost-score-bar/stories/index.tsx
This will need to be renamed for Storybook 7 (probably to `.../index.stories.tsx`). See 51eaa5009b6b5b2f82806cf609c9a65c1aa684d1 for more info.

2023-05-10 20:48 UTC, CodeyGuyDylan commented
^ Rebase

2023-05-12 21:08 UTC, jboland88 requested changes, later dismissed
The code looks good, I just noticed two things while testing.
When the score bar is loading, the background disappears/ turns white, the previous version retained the red/yellow/green color.

![Screenshot 2023-05-12 at 4 53 23 PM](https://github.com/Automattic/jetpack/assets/18016357/ec563a9b-c352-4a7c-bcfa-f2996ad94451)

I am also having trouble viewing the storybook component? I can view other components in the storybook interface, but the boost score bar just shows a blank screen.

2023-05-12 21:13 UTC, IanRamosC reviewed
Code looks mostly good. I left a few comments about minor improvements, but other than that it looks good. Also, I couldn't really get it to display the extra bars by calling it in the Score.svelte file. I'll try it again later, but I'm leaving my review now so my setup doesn't block you.

2023-05-12 21:13 UTC, IanRamosC commented on projects/js-packages/components/components/boost-score-bar/style.scss
> +		//min-width: 50px;
Can we remove this line since it's commented out?

2023-05-12 21:13 UTC, IanRamosC commented on projects/js-packages/components/components/boost-score-bar/style.scss
> +	.fill-good {
That new James Brown hit: I fill good

2023-05-12 21:13 UTC, IanRamosC commented on projects/js-packages/components/components/boost-score-bar/style.scss
> +		background-color: #069e08;
This color is set as `--jp-green` in the root variables. I think we can use it here as well.

2023-05-12 21:13 UTC, IanRamosC commented on projects/js-packages/components/components/boost-score-bar/style.scss
> +		background-color: #faa754;
I've seen this variable being used in other plugins as `$studio-orange-20`, and I'm wondering if we could add it to the root variables and call it here as well.

2023-05-12 21:13 UTC, IanRamosC commented on projects/js-packages/components/components/boost-score-bar/style.scss
> +		background-color: #d63638;
This one is `--jp-red-50` in `js-packages/base-styles/root-variables.scss`

2023-05-12 21:18 UTC, CodeyGuyDylan commented
> I am also having trouble viewing the storybook component? I can view other components in the storybook interface, but the boost score bar just shows a blank screen.

@jboland88 this probably has to do with renaming the file due to the storybook update, I'll look into this

2023-05-16 18:21 UTC, CodeyGuyDylan commented
> I am also having trouble viewing the storybook component? I can view other components in the storybook interface, but the boost score bar just shows a blank screen.

Looks like changed how defaults work in the new storybook update, got that all fixed up

2023-05-16 22:57 UTC, IanRamosC approved these changes
I was finally able to test it properly. The changes test well.

2023-05-17 14:43 UTC, merged