[RNMobile] Sync VideoPress metadata when post is manually saved
Automattic/jetpack pull request #30131
Opened 2023-04-17 14:57 UTC by SiobhyB

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-04-17 20:32 UTC, SiobhyB commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +			const handlePostSaveEvent = () => {
As noted in [the relevant Gutenberg PR](https://github.com/WordPress/gutenberg/pull/49781), we could potentially connect this to [Gutenberg's isSavingPost selector](https://github.com/WordPress/gutenberg/blob/c475dcb3ffee7627a8e1d2f13f364a7a9b195a61/packages/editor/src/store/selectors.js#L677-L692) in the future. For now, I've proposed this solution in the interest of time and simplicity.

2023-04-18 10:30 UTC, SiobhyB commented on projects/packages/videopress/src/client/block-editor/blocks/video/index.native.ts
These changes are brought in from https://github.com/Automattic/jetpack/pull/30134, in order to avoid a regression that prevented this PR from being built. https://github.com/Automattic/jetpack/pull/30134 should be merged **before** this one.

2023-04-18 11:47 UTC, fluiddot reviewed
Tested different flows in both platforms and confirmed that VideoPress metadata is saved in the below cases:

**iOS:**
- Published post - Tap `Update` button and then close the editor. ✅ 
- Published post - Close editor and save unsaved changes. ✅ 
- Draft post - Tap `Update` button and then close the editor. ✅ 
- Draft post - Close editor and save unsaved changes. ✅ 
- Draft post - Tap `Three dots button/Publish` and open the post again. ✅ 
- Scheduled post - Tap `Update` button and then close the editor. ✅ 
- Scheduled post - Close the editor and save unsaved changes. ✅ 

**Android:**
- Published post - Tap `Update` button and open the post again. ✅ 
- Published post - Close the editor with unsaved changes. ✅ 
- Published post - Tap `Schedule` button and open the post again. ✅ 
- Draft post - Tap `Three dots button/Save` and open the post again. ✅ 
- Draft post - Close the editor and save unsaved changes. ✅ 
- Draft post - Tap `Publish` and open the post again. ✅ 
- Scheduled post - Tap `Schedule` and open the post again. ✅ 
- Scheduled post - Close the editor and save unsaved changes. ✅ 
- Scheduled post - Tap `Publish Now` and open the post again. ✅ 

However, I noticed an issue when previewing a post or switching to HTML mode. It seems unrelated to these changes, so I wouldn't block the PR, but we'd need to track it.

### Preview a post
1. Having a VideoPress block with a video.
2. Change some of the settings that will be synced (e.g. title).
3. Tap on the three dots button.
4. Tap on `Preview`.
5. Close the preview.
6. Open the block settings and observe that the settings changes were discarded.

### Switch to HTML mode
1. Having a VideoPress block with a video.
2. Change some of the settings that will be synced (e.g. title).
3. Tap on the three dots button.
4. Tap on `HTML Mode`.
5. Switch back to Visual Mode.
6. Open the block settings and observe that the settings changes were discarded.

Apart from the above-unrelated issue, the PR looks great to me. I only added a comment that would be great to tackle before approving it.

2023-04-18 11:47 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +	isNative &&
I'd check this condition inside the hook and bail early if it's not the native version. The reason is that is not recommended to call hooks conditionally ([reference](https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)).

2023-04-18 12:51 UTC, SiobhyB commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +	isNative &&
Thanks for calling this out! Fixed in https://github.com/Automattic/jetpack/pull/30131/commits/e1fe619c53edef53dbccce47834fbc3135e658c6.

2023-04-18 13:01 UTC, SiobhyB commented
@fluiddot, thank you for catching those issues with preview and toggle mode! I've gone ahead to create an issue in https://github.com/wordpress-mobile/gutenberg-mobile/issues/5677 and have added it to our project board. 🙇‍♀️

2023-04-18 15:16 UTC, fluiddot reviewed
I re-tested some of the cases shared in my last review. However, I'm trying to test the web version but I'm having trouble to have the VideoPress block registered 🤔.

2023-04-18 15:16 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +		const subscription = subscribePostSaveEvent( handlePostSaveEvent );
Nitpick: Since `handlePostSaveEvent` is only referenced here, I think we can simplify this with the following code.
```suggestion
		const subscription = subscribePostSaveEvent( () => setPostHasBeenJustSavedNative( true ) );
```

2023-04-18 15:16 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +			}
Nitpick: We can use the optional chaining operator here to simplify the code.
```suggestion
			subscription?.remove();
```

2023-04-18 15:16 UTC, fluiddot commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +		setPostHasBeenJustSavedNative( false );
This won't produce any side effect in the web version as `postHasBeenJustSavedNative` will remain `false. However, I'm wondering if we should only execute it in the native version as it's only used there, WDYT?

2023-04-18 15:45 UTC, SiobhyB commented on projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
> +		setPostHasBeenJustSavedNative( false );
Happy to go with your preferences, changed in https://github.com/Automattic/jetpack/pull/30131/commits/011d672780ec4feed58d106ddf27c1edfbd2203d.

2023-04-18 16:03 UTC, fluiddot requested changes
As internally discussed (p1681833498706689/1681831906.251289-slack-C03TA48NSUX), we'd need to move this import to a native file because the package is only available in the native version.

2023-04-19 12:01 UTC, SiobhyB commented
I've gone ahead to move the native functionality to a new `.native.js` file. Note, I opted to go with `js` file as we're making some changes to the web's types. In addition, although we're not currently using any strings in this file on native, the fact we can't import translations from `.ts` files swayed my decision. It felt that using a `.js` version would be the most straightforward and future-proof approach. Open to different opinions, though.

The removal of native-specific functionality from the main file can be found in https://github.com/Automattic/jetpack/pull/30131/commits/f050d65352cffb62cf1ef2b2824168df43c02a82. For the new native file, it was possible to remove a bunch of (currently) unused functionality, as shown in https://github.com/Automattic/jetpack/pull/30131/commits/321d34361653428162d6867454acb35189a98038.

2023-04-19 16:45 UTC, fluiddot approved these changes
LGTM 🎊 !

I tested the web version and worked as expected ✅ . Nevertheless, it would be great to request a second review from web folks to confirm no regressions are introduced.

Regarding the native version, I re-tested some of the cases shared [here](https://github.com/Automattic/jetpack/pull/30131#pullrequestreview-1389792807) in both platforms and worked as expected ✅.

2023-04-19 19:24 UTC, dhasilva approved these changes
No regressions on web version. Nice work!

2023-04-20 16:20 UTC, merged