Jetpack Visual Refresh: Footer
Automattic/jetpack pull request #30279
Opened 2023-04-25 03:05 UTC by nateweller

## Proposed changes:

* Applies RNA styles to the plugin footer

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/orgs/Automattic/projects/587/views/15?pane=issue&itemId=26242471

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Review the footer on React screens (at a glance page, settings screens).
* Review the footer on static screens (about, modules).

## Screenshots

<img width="795" alt="Screenshot 2023-04-24 at 9 02 56 PM" src="https://user-images.githubusercontent.com/10933065/234164172-74b4eb38-bd64-4629-abc9-849a16c25a99.png">
<img width="557" alt="Screenshot 2023-04-24 at 9 01 48 PM" src="https://user-images.githubusercontent.com/10933065/234164174-51bd1a4b-534c-45c6-b586-fb0cbcff5d58.png">
<img width="1247" alt="Screenshot 2023-04-24 at 9 00 44 PM" src="https://user-images.githubusercontent.com/10933065/234164175-3a13a8b7-0068-45ce-b310-ba041d7e5e30.png">

2023-04-26 16:26 UTC, jeffgolenski commented
@nateweller outstanding. send it!

2023-04-26 16:27 UTC, jeffgolenski approved these changes, later dismissed

2023-04-26 16:27 UTC, jeffgolenski commented on projects/plugins/jetpack/_inc/client/components/footer/style.scss
> +	display: flex;
Nice flexin'

2023-04-27 16:46 UTC, dhasilva requested changes
Some pages are displaying a SVG tag in the Privacy link:

![2023-04-27_13-38-06](https://user-images.githubusercontent.com/8486249/234932144-df181d62-c27d-4d93-bcfd-9e91251f361e.png)
![2023-04-27_13-37-24](https://user-images.githubusercontent.com/8486249/234932149-dff7bafb-5e0c-484c-9011-b3d1e42faa64.png)
![2023-04-27_13-36-14](https://user-images.githubusercontent.com/8486249/234932153-9762ecc5-63ab-4d04-9b8b-5ef899ded2f4.png)

2023-04-27 16:49 UTC, dhasilva commented on projects/plugins/jetpack/_inc/client/recommendations/style.scss
> +}
```suggestion
}

```

2023-04-27 19:44 UTC, nateweller commented
@dhasilva Thanks for your prompt review! Fixed it up :+1:

2023-04-27 21:04 UTC, dhasilva approved these changes
LGTM. Nice!

2023-04-27 21:11 UTC, merged

2023-05-01 15:05 UTC, zinigor commented
Cherry picked in https://github.com/Automattic/jetpack/commit/e63eaff87c8f8a860407f75774ba01ea240e636a.