RNA: Settings Fix Up
Automattic/jetpack pull request #30347
Opened 2023-04-27 20:19 UTC by nateweller

Addresses https://github.com/Automattic/jetpack/pull/30204#issuecomment-1520841435

## Proposed changes:

* Updates styles surrounding the setting tabs, based on feedback from https://github.com/Automattic/jetpack/pull/30204#issuecomment-1520841435

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/pull/30204#issuecomment-1520841435

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Go through each item from the linked comment and review the updated setting screens.

## Screenshots

![Screen Shot 2023-04-27 at 14 55 21-fullpage](https://user-images.githubusercontent.com/10933065/234989450-ca8ee3d4-3ce8-49fc-90ad-ec2fad994e5d.png)
![Screen Shot 2023-04-27 at 14 55 29-fullpage](https://user-images.githubusercontent.com/10933065/234989457-9ebbe124-c23e-48c5-9e32-e3b166e9c69c.png)
![Screen Shot 2023-04-27 at 14 55 51-fullpage](https://user-images.githubusercontent.com/10933065/234989462-63fc207f-01e0-4b77-9b10-4805e6761f4b.png)
![Screen Shot 2023-04-27 at 14 55 58-fullpage](https://user-images.githubusercontent.com/10933065/234989468-8f42b8e7-33c8-4e2c-9561-eb7526a6fe26.png)
![Screen Shot 2023-04-27 at 14 56 09-fullpage](https://user-images.githubusercontent.com/10933065/234989471-8264b563-7184-4ec7-ad5a-e555185f5fc1.png)
![Screen Shot 2023-04-27 at 14 56 42-fullpage](https://user-images.githubusercontent.com/10933065/234989477-9af5df5d-bf7c-4d19-b1fb-d0c0bba96291.png)

2023-04-28 14:35 UTC, jeffgolenski approved these changes, later dismissed
Ace work my friend. This checks off every issue I reported in #30204. ship it!

2023-04-28 20:15 UTC, nateweller commented on projects/plugins/jetpack/_inc/client/components/select-dropdown/style.scss
> +}
```suggestion
}

```

2023-04-28 21:38 UTC, sergeymitr requested changes
Hi @nateweller.

Looks great, just a couple minor things I noticed:

- [ ] I think the "external" icon shouldn't get wrapped to the next line:
<img width="1060" alt="Screen Shot 2023-04-28 at 17 29 16" src="https://user-images.githubusercontent.com/1341249/235257441-db2e336e-f97e-49a2-9268-225ed22586e4.png">

- [ ] "Comments -> Color scheme" dropdown still has that blue background:
<img width="1065" alt="Screen Shot 2023-04-28 at 17 34 01" src="https://user-images.githubusercontent.com/1341249/235258100-b0c5d8e0-ea23-49bd-b654-d51f6e2daa7e.png">

2023-04-29 17:23 UTC, nateweller commented
Thanks @sergeymitr! I fixed the dropdown. The external link icon wrapping lines isn't a new issue, so I think we can address it in a different PR.

2023-05-01 00:45 UTC, sergeymitr approved these changes, later dismissed
👍

2023-05-01 15:42 UTC, jeffgolenski commented
@nateweller this isn't a blocker to ship, but I noticed the [privacy settings page](https://github.com/Automattic/jetpack/pull/30204#issuecomment-1523739174) needs the updated toggle. You're good to ship from a design perspective at any time. Whenever we can get that change in is fine!

2023-05-01 20:52 UTC, sergeymitr approved these changes
Looks great!

2023-05-01 20:55 UTC, merged