Jetpack Plugin Visual Refresh: fix responsive css on about and my plan pages
Automattic/jetpack pull request #30359
Opened 2023-04-28 13:22 UTC by bindlegirl

Addressing issues from #30293
https://github.com/Automattic/jetpack/pull/30293#issuecomment-1526359331

## Proposed changes:

* Fix About us page plugin dsplay on small screens
* Fix "View all purchases" & "Activate a product" buttons on small screens 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

no
## Testing instructions:

* Go to My Plan and shrink it to mobile width. Buttons should stay on the same line and 
get evenly spaced.
* Go to About us page and view it on mobile width. Plugin boxes shouldn't display in a 
grid.

2023-04-28 14:29 UTC, jeffgolenski commented
@bindlegirl on the plans page, can you just give the buttons a width of 48% on that small breakpoint? After that, the plans page is good to ship!

<img width="423" alt="Screen Shot 2023-04-28 at 10 28 17 AM" src="https://user-images.githubusercontent.com/214813/235175340-852e57f6-0712-4c12-8b3f-b2831a2c748a.png">

About page is good to go! Thanks so much!

2023-04-28 14:29 UTC, jeffgolenski requested changes, later dismissed
See the comment about the button width, and then we'll be good to ship after that!

2023-04-28 15:07 UTC, bindlegirl commented
Oh yes, that looks much better 😄 
While at it, I fixed another small issue I found (double gray border on smaller screens between plans and products).

2023-04-28 16:37 UTC, jeherve approved these changes
This looks good to me! 👍

2023-04-28 17:13 UTC, merged

2023-05-01 15:02 UTC, zinigor commented
Cherry picked in https://github.com/Automattic/jetpack/commit/904a597900e0ebf41e030962147c9976b6e37cce.