Fix inbox dropdown menu overflow
Automattic/jetpack pull request #30409
Opened 2023-05-02 19:43 UTC by CGastrell

Fix an issue with responses inbox dropdown menu

## Proposed changes:
The dropdown menu was not showing due to some recent CSS changes

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p1683039477761239-slack-C01CSBEN0QZ

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Visit the responses inbox. Verify the kebab dropdown menu on the rows works. Verify rows animation still works correctly (move to trash/spam and back)

2023-05-02 20:07 UTC, digitalwaveride approved these changes, later dismissed
Nice Christian!

Issue is fixed for me!
🚀 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/5120357/235774135-7b205e3b-57e2-4c9a-bdd3-9c6710928137.png">

2023-05-02 20:44 UTC, jcheringer requested changes
I'm seeing a weird behavior when using the `...` menu to move items:

[Screen Recording on 2023-05-02 at 17_42_10.webm](https://user-images.githubusercontent.com/7811225/235781620-58539652-63e5-41c8-a2da-a0eb8928bf23.webm)

2023-05-03 13:27 UTC, CGastrell commented
> I'm seeing a weird behavior when using the `...` menu to move items:
> 

I see it too, but seems unrelated to this change. Worth investigating though.

2023-05-03 13:58 UTC, CGastrell commented
> I'm seeing a weird behavior when using the `...` menu to move items:
> 

Should be fixed now

2023-05-03 14:49 UTC, jcheringer approved these changes
Worked! Thanks! 👍

2023-05-03 15:29 UTC, merged