Introduce Videopress Core JS Package
Automattic/jetpack pull request #30589
Opened 2023-05-10 13:13 UTC by pgk

Creates the VideoPress Core package skeleton. 

The overall idea is to reuse existing [VideoPress JS library code](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/videopress/src/client/lib/resumable-file-uploader) outside of the Jetpack/VideoPress codebase (for example, in themes built on top of Jetpack/VideoPress or integrations).

As a next step, the resumable uploader and the other related parts of the code will be moved to this package.
The uploader code "as-is", needs [get-media-token](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/videopress/src/client/lib/get-media-token) and some other TS types.

Eventually, this would:

* Be deployed as an npm package.
* Contain/replace [videopress/lib](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/videopress/src/client/lib).

## Proposed changes:

* None at this point.

## Jetpack product discussion

pxWta-1PG-p2

## Testing instructions:

* At this point this pr contains only the skeleton generated from `jetpack generate`, so I guess not much functionality to test. But maybe I missed something important on Generate.

* Go to '..'
*

2023-05-10 14:09 UTC, dhasilva commented on projects/js-packages/videopress-core/jsconfig.json
> +	"include": [ "./index.jsx", "./src" ]
There are many TS files in VideoPress, so this probably needs to be `tsconfig.json`

2023-05-10 16:31 UTC, pgk commented
Getting this on build, I'll see about updating my local pnpm https://github.com/orgs/pnpm/discussions/4847

2023-05-10 17:27 UTC, jeherve requested changes

2023-05-10 17:27 UTC, jeherve commented on projects/js-packages/videopress-core/composer.json
> +	"prefer-stable": true
I created the mirror repo, so we now can add this to our project:

```suggestion
	"prefer-stable": true,
	"extra": {
		"autotagger": true,
		"npmjs-autopublish": true,
		"mirror-repo": "Automattic/jetpack-videopress-core",
		"changelogger": {
			"link-template": "https://github.com/Automattic/jetpack-videopress-core/compare/${old}...${new}"
		}
	}
```

2023-05-11 09:19 UTC, pgk commented on projects/js-packages/videopress-core/composer.json
> +	"prefer-stable": true
Thanks, done!

2023-05-11 10:20 UTC, jeherve approved these changes
Let's merge this now, and iterate in follow-up PRs. 👍

2023-05-11 10:23 UTC, merged