Jetpack Boost: Image Size Analysis - Phase 6
Automattic/jetpack pull request #30606
Opened 2023-05-10 16:24 UTC by pyronaur

This is a part of a series of pull requests to create an [image guide dashboard](https://github.com/Automattic/boost-cloud/issues/215).

## Proposed changes:

- Removed ignored images from fake API
- Fixed image counts
- Fixed pagination on navigation
- Added `/:group/:page` to recommendation routes
- Debounced query updates to prevent multiple triggers from params
- Squashed a nasty bug in SyncAction caused by multiple sequential updates 🧯
- Introduced "Don't ignore" option for more control over image handling
- Flushed out "Edit Page" buttons
- UX Improvement: Prevented toggling expand on link/button clicks for better user experience
- Hide pagination when only 1 page is available for a cleaner interface
- Enabled data loading based on URL for faster access to relevant content
- Added spinners and loading states
- Disabled inactive tabs - maybe we'll need a disabled view? Not sure. 
- Moved DataSync that's relevant to the ISA module to the ISA module directory so that everything's in one place

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
N/A

## Testing instructions:
1. Apply patch
2. composer dump
3. `npm run dev`
4. Enable the feature using setting feature flag: `JETPACK_BOOST_IMAGE_SIZE_ANALYSIS` to true
5. Compare the UI to designs

2023-05-11 05:02 UTC, thingalon requested changes
When I click on the "See report in progress" button, I get taken to a broken version of the Boost dashboard. I suspect the new routes are not allowing links to `#image-size-analysis` without `/group/page` in the URL.

2023-05-11 05:02 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/RecommendationsPage.svelte
> +		};
I don't like this sync limitation, as discussed in Slack. However, I don't think that this PR is the right place for me to raise concerns about the limitation of the system.

2023-05-11 05:02 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/Hero.svelte
> +	{@const  lastUpdated = formatter.format( $isaData.data.last_updated ) }
Huh. TIL about `@const`.

2023-05-11 05:02 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/TableRowExpanded.svelte
> +					Ignore
`__()` translatable.

2023-05-11 05:02 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/store/isa-data.ts
> +		.transform( url => url.replace( '&amp;', '&' ) ),
If we leave this in the code, it will bite us later.

2023-05-11 05:02 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/store/isa-data.ts
> +		// because it too is stored over the network.
Yeah, I think moving ignored into this store is starting to make more and more sense.

2023-05-11 07:54 UTC, pyronaur commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/RecommendationsPage.svelte
> +		};
Yeah, this needs a fix, but in another PR

2023-05-11 07:54 UTC, pyronaur commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/TableRowExpanded.svelte
> +					Ignore
This is going to need a followup

2023-05-11 08:17 UTC, pyronaur commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/store/isa-data.ts
> +		.transform( url => url.replace( '&amp;', '&' ) ),
Fixed

2023-05-12 07:31 UTC, thingalon submitted a review, later dismissed

2023-05-12 08:01 UTC, thingalon approved these changes

2023-05-12 08:04 UTC, merged