Fix/crm/3003 client portal fatal error loading endpoints
Automattic/jetpack pull request #30678
Opened 2023-05-12 11:47 UTC by cleacos

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-05-12 16:44 UTC, tbradsha commented
I'm hesitant to merge this without being able to reproduce the original issue. That said, when reviewing let's make sure this change doesn't impact additional endpoints (e.g. Client Portal Pro ones).

2023-05-12 17:20 UTC, cleacos commented
> when reviewing let's make sure this change doesn't impact additional endpoints (e.g. Client Portal Pro ones).

I did and checked it with Client Portal Pro activated, and all good. All plugins are loaded before the WP `init` hook, so any WP `action` added from the extension is ready when the Client Portal is initialized.

2023-05-15 18:07 UTC, gogdzl approved these changes
It works.
The explanation by @cleacos checks out.

I generally dislike fixing something that we cannot replicate properly, but this code will do no harm.

If the problem arises again we can try another approach.

2023-05-15 18:13 UTC, gogdzl requested changes
Actually, Client Portal Pro stopped working with this PR.
Most probably because of load order.

Install Client Portal Pro and check that 'Your files' tab stops working with this PR.

2023-05-16 14:35 UTC, cleacos commented
The Client Portal Pro adds those menus on WP `init` but with the default priority `10`.

- If we initialize the Client Portal module later, with priority `10`, it works.
- If we initialize the endpoints and the shortcode together, in an `init_later` method, with priority `10`, it works.

2023-05-16 14:48 UTC, cleacos commented
I'm going to push the option of delaying the module initialization a bit, priority 10. I tested it and it works well.

2023-05-19 19:12 UTC, gogdzl requested changes
I don't understand how this would help us.

We are moving a bunch of hooks and actions to a completely different load order, and that got me confused.

I also fail to see how this would fix said problem, because the load order wasn't the original problem, and even if it was it's being called in the same priority as before.

I need more information because I didn't fully understand how this solves the problem.

2023-05-23 14:22 UTC, cleacos commented
> We are moving a bunch of hooks and actions to a completely different load order, and that got me confused.

First, we have to  group all of them to be able to add shortcodes and the API endpoints at the same moment to avoid calls to `do_shortcode` without the endpoints initialized:

- `add_shortcode(...)`
- `$this->init_endpoints()`

Then, we have to move that group and initialize it at priority `10` to wait for the Client Portal PRO initialization first (adding the action `add_action - jpcrm_client_portal_register_endpoint`) and then the Client Portal module that will initialize the endpoints and call that action (`do_action - jpcrm_client_portal_register_endpoint`) to add the Client Portal PRO endpoints. That is the reason for moving to priority `10`.

**This is the order currently**

1. init(1): Client Portal initialization
   - add_shortcode
   - add_actions
   - Postpone the endpoints' initialization to init(10). The reason is that it needs Client Portal PRO initialized before it.

2. init(10): Client Portal PRO initialization
   - Add this action `jpcrm_client_portal_register_endpoint` to add its endpoints

3. init(10): Client Portal - init_endpoints()
   - Do the action `jpcrm_client_portal_register_endpoint` to load third parties endpoints (CP PRO)

**This would be the order in this PR:**

1. init(1): Client Portal initialization
   - Group and postpone the whole initialization to init(10).

2. init(10): Client Portal PRO initialization
   - Add this action `jpcrm_client_portal_register_endpoint` to add its endpoints

3. init(10): Client Portal Initialization
   - add_shortcode
   - add_actions
   - init_endpoints
      - Do the action `jpcrm_client_portal_register_endpoint` to load third parties endpoints (CP PRO)

2023-06-14 21:34 UTC, gogdzl approved these changes
Ok, thanks for the in-depth explanation!

Ship it!

2023-06-15 15:52 UTC, merged