WP Super Cache: don't delete child taxonomies during preload
Automattic/jetpack pull request #30830
Opened 2023-05-22 12:33 UTC by donnchawp

The preload system in WP Super Cache allows a site owner to prime the cache by visiting taxonomy archives and post/page URLs.
The original cached page would have to be deleted before the new page was fetched. Unfortunately, the taxonomy loop deleted a taxonomy, and any sub directories which had the effect of deleting the cached pages for child taxonomies.

This PR fixes that by only deleting files in the taxonomy directory, and then deleting the feed and page directories separately.

ref: https://wordpress.org/support/topic/preload-mode-skips-caching-pages-or-deletes-already-cached-pages/

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
To test this you'll need to create child taxonomies on a test blog.
Enable debugging and when it's done, verify that the cache pages for the child taxonomies still exist.

2023-05-23 13:39 UTC, dilirity requested changes
I wasn't able to properly test this, but I discovered something small - details below.

2023-05-23 13:39 UTC, dilirity commented on projects/plugins/super-cache/wp-cache.php
> +						prune_super_cache( $dir . 'page/', true );
If the permalink structure doesn't end with a trailing slash, the path will be incorrect resulting in a PHP warning:
```
PHP Warning:  Undefined array key 0 in /usr/local/src/jetpack-monorepo/projects/plugins/super-cache/wp-cache.php on line 3303
```

I've worked on quite a few websites that have `.php` appended at the end of the post URL.

2023-05-23 14:26 UTC, donnchawp commented on projects/plugins/super-cache/wp-cache.php
> +						prune_super_cache( $dir . 'page/', true );
Thanks, that's a good point. I guess it's better to have //feed/ there.

2023-05-23 14:31 UTC, donnchawp commented on projects/plugins/super-cache/wp-cache.php
> +						prune_super_cache( $dir . 'page/', true );
trailingslashit() helps here of course.

2023-05-24 05:08 UTC, thingalon approved these changes
Ok, looks straightforward to me :)

2023-05-25 06:05 UTC, dilirity approved these changes

2023-05-26 01:57 UTC, merged