Cookie Consent: backend changes to move cookie consent block to template part
Automattic/jetpack pull request #30870
Opened 2023-05-23 14:57 UTC by arcangelini

## Proposed changes:

This echos the cookie consent content into the footer if the template part exists.

More to come...

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-05-24 09:28 UTC, jeherve reviewed
Is there a discussion about this? I'd be curious to learn more about the change!

2023-05-24 09:28 UTC, jeherve commented on projects/plugins/jetpack/extensions/blocks/cookie-consent/cookie-consent.php
> + * @since 12.0
```suggestion
 * @since $$next-version$$
```

2023-05-24 11:03 UTC, arcangelini commented
> Is there a discussion about this? I'd be curious to learn more about the change!

@jeherve we are on our meetup and are working live to make the Cookie Consent a template part rather than a block. This was based of some talks in a P2 - pdDR7T-Cr-p2#comment-803.

There is a front end PR that is soon to come as well. Also, do you have any thoughts on:

```
echo do_blocks( $template_part->content ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```

We had to ignore the linter to get the PR started, but I think maybe this isn't the best option? The problem is if we escape it the template breaks when inserting.

2023-05-26 17:39 UTC, jeherve commented
> I think maybe this isn't the best option? The problem is if we escape it the template breaks when inserting.

Do we escape the contents of the template part earlier on our end? If so, that may be okay / enough.

2023-06-07 15:58 UTC, alshakero commented
Since [the other PR is ready](https://github.com/Automattic/jetpack/pull/30903). Can we get his cleaned up and merged in that PR?

2023-06-07 16:38 UTC, alshakero requested changes

2023-06-07 16:38 UTC, alshakero commented on projects/plugins/jetpack/extensions/blocks/cookie-consent/cookie-consent.php
> +	$template_part_name = 'cookie-consent';
Please rename this to `cookie-consent-block-template-part`

2023-06-08 08:13 UTC, merged

2023-06-08 08:13 UTC, alshakero commented
**Note**: This was merged into https://github.com/Automattic/jetpack/pull/30903.