Jetpack Forms: replace email response template with a basic one
Automattic/jetpack pull request #31026
Opened 2023-05-29 09:29 UTC by donnchawp

Revert the email response template introduced recently due to customer feedback.

This PR replaces the HTML template with a more basic one that doesn't need to be customised, and is similar to what users are used to already.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pcsBup-yo-p2#comment-451

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Apply PR and embed a contact form in a post.
Fill in the contact form.
The site owner should receive the response in a basic email, rather than the new HTML email with images.

2023-05-29 14:49 UTC, CGastrell submitted a review, later dismissed
LGTM! Works fine on .COM

2023-05-29 16:04 UTC, jeherve requested changes, later dismissed

2023-05-29 16:04 UTC, jeherve commented on projects/packages/forms/src/contact-form/templates/email-response.php
> +<p><a href="%3$s">View Responses</a></p>
This wil need to be translated.

2023-05-29 16:04 UTC, jeherve commented on projects/packages/forms/src/contact-form/templates/email-response.php
> +<p><a href="%4$s">Edit</a></p>
This too.

2023-05-30 13:25 UTC, CGastrell approved these changes
:shipit:

2023-05-30 13:32 UTC, merged

2023-05-30 14:12 UTC, anomiex commented
Cherry-picked in c721e2b4b1c4eb65d271bb1a82dc334f09739ad3