Added project versioning suffixes.
Automattic/jetpack pull request #31220
Opened 2023-06-06 18:35 UTC by zinigor

This PR adds conditions to the build step that add suffixes to `alpha` versions based on the GitHub Action run ID. This will allow for the mirror repos to have package versions that are versioned with consecutive numbers.

## Proposed changes:
* Adds alpha suffixes to package versions.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

I have tested the changes on [my fork of the repo](https://github.com/zinigor/jetpack/actions). You can re-run the build and download the artifacts to check the versions.

2023-06-07 15:14 UTC, anomiex reviewed
Works as intended, but some suggestions for improvement inline.

I note this also undoes some of the work we put in in PRs like #18579 and #23867 in avoiding diffs being created for every plugin for every build due to run-specific data being injected.

<details>
<summary>We could avoid that by doing something like `git log -1 --format=%ct ${ t.cwd }` to get the timestamp of the last commit touching the package instead of using the run number. Maybe only for slugs starting with `packages/` since those are the only ones where it matters. Think that's worth the effort?</summary>

More specifically, that could look like this.
```js
let projectRunVersionNumber = projectVersionNumber;
if ( t.project.startsWith( 'packages/' ) && projectVersionNumber.endsWith( 'alpha' ) ) {
    const ts = (
        await t.execa( 'git', [ 'log', '-1', '--format=%ct', '.' ], {
            cwd: t.cwd,
            stdio: [ null, 'pipe', null ],
        } )
    ).stdout;
    if ( ts.match( /^\d+$/ ) ) {
        projectRunVersionNumber += '.' + ts;
    }
}
```
</details>

(Yeah, I know, using `GITHUB_RUN_NUMBER` was my idea in the first place. I can have bad ideas too! 😀)

2023-06-07 15:14 UTC, anomiex commented on tools/cli/commands/build.js
> +								}
This is not necessary, as this comes from the data structure that has already been munged by the code added at line 942 below.

Further, I'm not sure we even _want_ the munged version here. It makes unnecessary diffs in composer.json for everything.

```suggestion
```

2023-06-07 15:14 UTC, anomiex commented on tools/cli/commands/build.js
> +								}
Same as above.

```suggestion
```

2023-06-07 15:14 UTC, anomiex commented on tools/cli/commands/build.js
> +			}
As I mentioned above, I'm not sure we really want to add the run number to `projectVersionNumber` since it has the side effect of changing all the composer.json deps. Possibly we should do this instead:

* A few lines down (around line 959), do like this to set the appended version in a separate variable.
  ```js
  let projectRunVersionNumber = projectVersionNumber;
  if ( process.env.GITHUB_RUN_NUMBER && projectVersionNumber.endsWith( 'alpha' ) ) {
      projectRunVersionNumber += '.' + process.env.GITHUB_RUN_NUMBER + '.' + process.env.GITHUB_RUN_ATTEMPT;
  }
  ```
* Add another member into the `t.ctx.versions` object holding this new variable, so we'd have both the existing `version: projectVersionNumber` and also something like `runversion: projectRunVersionNumber`.
* Line 579 would then change to use the new "runversion" instead of `version`.
  ```js
  versions[ t.ctx.versions[ dep ].name ] = t.ctx.versions[ dep ].runversion;
  ```

2023-06-08 16:31 UTC, zinigor commented on tools/cli/commands/build.js
> +			}
Thank you, I have implemented your suggestions in the latest commit.

2023-06-13 18:48 UTC, anomiex commented on tools/cli/commands/build.js
> +				 ).stdout;
Weird indent here.
```suggestion
				).stdout;
```

2023-06-13 18:55 UTC, anomiex commented on tools/cli/commands/build.js
> +				).stdout;
Apparently prettier is being stupid. Sigh.
```suggestion
				 ).stdout;
```

2023-06-13 18:55 UTC, anomiex commented on tools/cli/commands/build.js
> +				 ).stdout;
It seems Prettier has decided to be stupid here and insist on this space.

2023-06-13 19:40 UTC, anomiex requested changes

2023-06-13 19:40 UTC, anomiex commented on tools/cli/commands/build.js
> +	rl.on( 'line', async line => {
Using `async` here doesn't work right. When the `await` happens `rl` continues processing lines, which can result in a later version line of the changelog getting processed, incorrectly overwriting `projectVersionNumber` with a wrong version before the `git` command finishes.

Probably the best thing to do here would be to move lines 927–937 outside of the event handler entirely, probably to around what's currently line 947.

2023-06-14 16:56 UTC, anomiex approved these changes
Comparing the artifacts between this PR and the corresponding trunk run shows the expected changes now. :ship:

2023-06-14 17:00 UTC, merged