Type check $posts to prevent warning in gzip output stream
Automattic/jetpack pull request #31487
Opened 2023-06-21 14:31 UTC by septemberservices

Fixes #31486

## Proposed changes:
* Type check $posts in wp_cache_post_id() to prevent a warning breaking the gzipped content in some browsers

2023-06-21 14:37 UTC, septemberservices commented
## Does this pull request change what data or activity we track or use?

No.

2023-06-21 15:43 UTC, jeherve requested changes
Thanks for your contribution. I've started the checks that will give you automated feedback about your PR, but wanted to highlight a tiny issue right away.

2023-06-21 15:43 UTC, jeherve commented on projects/plugins/super-cache/wp-cache-phase2.php
> +	if ( is_singular() && ! empty( $posts ) && is_array($posts) ) {
You'll most likely need to add some spacing here to avoid linting errors:

```suggestion
	if ( is_singular() && ! empty( $posts ) && is_array( $posts ) ) {
```

2023-06-22 08:41 UTC, septemberservices commented on projects/plugins/super-cache/wp-cache-phase2.php
> +	if ( is_singular() && ! empty( $posts ) && is_array($posts) ) {
It seems your commit has been added to my repository, resolving the problem. Is that correct?

2023-06-26 17:51 UTC, zinigor approved these changes
Looks good to me, doesn't affect the logic, should be fine.

2023-06-26 17:52 UTC, zinigor commented
@jeherve do you mind taking another look? I don't want to dismiss your review without your approval.

2023-06-27 07:07 UTC, jeherve approved these changes

2023-06-27 07:07 UTC, merged