WIP: 78198 update/claim domain task
Automattic/jetpack pull request #31493
Opened 2023-06-21 18:58 UTC by markbiek

Fixes #78198

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-06-26 13:29 UTC, andres-blanco requested changes
I went through all the test steps and it worked great until I got to the last two steps from the Paid Plan flow.

> * Click on the "Customize your domain" task and go through the process of purchasing a domain.
> * Once the domain purchase is complete, the "Customize your domain" task should be gone from the list.

When I bought a new domain the `Customize your domain task` didn't disappear from the list.

2023-06-26 15:53 UTC, markbiek commented
> I went through all the test steps and it worked great until I got to the last two steps from the Paid Plan flow.
> 
> > * Click on the "Customize your domain" task and go through the process of purchasing a domain.
> > * Once the domain purchase is complete, the "Customize your domain" task should be gone from the list.
> 
> When I bought a new domain the `Customize your domain task` didn't disappear from the list.

I'm not sure what's happening here. I've tested a couple of times and it seems to be working.

Can you double-check that you're applying this PR to the correct Jetpack location? I did notice that it switched from `sun` to `moon` recently.

2023-06-26 18:16 UTC, valterlorran approved these changes
LGTM!
<img width="744" alt="Screen Shot 2023-06-26 at 15 08 33" src="https://github.com/Automattic/jetpack/assets/1234758/c7a2d665-6c01-49e8-bb97-dad52a8df48b">

<img width="781" alt="Screen Shot 2023-06-26 at 15 14 26" src="https://github.com/Automattic/jetpack/assets/1234758/9ba18c1c-e1c2-4735-b5f8-6e50c9db817d">

2023-06-26 18:18 UTC, valterlorran commented
On a side note, I faced a problem selecting a theme, forcing me to skip it. I noticed that we had the siteId in the url, and not the site_slug. I thought that it maybe could cause this problem.

<img width="576" alt="Screen Shot 2023-06-26 at 15 12 58" src="https://github.com/Automattic/jetpack/assets/1234758/97e804f9-b555-486b-8ca7-e33906bc5985">

2023-06-26 18:21 UTC, markbiek commented
> On a side note, I faced a problem selecting a theme, forcing me to skip it. I noticed that we had the siteId in the url, and not the site_slug. I thought that it maybe could cause this problem.
> <img alt="Screen Shot 2023-06-26 at 15 12 58" width="576" src="https://user-images.githubusercontent.com/1234758/248896159-97e804f9-b555-486b-8ca7-e33906bc5985.png">

@valterlorran Do you think that's related to this PR?

2023-06-26 19:04 UTC, valterlorran commented
I don't think so. I will create an issue so we can tackle it.

2023-06-26 19:19 UTC, andres-blanco approved these changes

2023-06-26 19:20 UTC, merged

2023-06-27 03:16 UTC, valterlorran commented
I opened the issue here: https://github.com/Automattic/wp-calypso/issues/78659