Jetpack search: Add default sort by price
Automattic/jetpack pull request #31594
Opened 2023-06-27 08:19 UTC by robfelty

## Proposed changes:
Currently it is only possible to set default sort options to newest, oldest, and relevance. Some WooCommerce users would like to be able to also specify a default sort by price or rating. This adds those options to the UI for the Jetpack Search settings.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
To test, spin up a new site with this branch. Look at the Jetpack Search settings. You should see the option to set the default sort to price and rating. Choose price, and then perform a search, and check that it is sorted by price by default.

2023-06-27 23:13 UTC, jsnmoon requested changes
This enables non-product sites to select a product-based default sort (e.g., rating sort for a minimal result type), resulting in an undesirable UI state (i.e., sort options render as unselected).

I recommend restricting product-based sorting to product result types. To help speed things along, here's [a POC commit](https://github.com/Automattic/jetpack/commit/f6f5668ccc5488bc1234b260eaf740c7125ce3bd) on [a different branch](https://github.com/Automattic/jetpack/compare/add/jetpack-search-default-sort-by-price...add/jetpack-search-default-sort-by-price-2).

Also, this needs a changelogger update (`tools/project-version.sh -f -u 0.38.0-alpha packages/search`).

2023-10-30 15:27 UTC, gibrown commented
Going to re-open this and hope we get some time to go back to it.

2023-11-17 05:13 UTC, kraftbj commented
Refreshed it with latest trunk to make it easier to jump back into.

2024-01-21 04:59 UTC, pehaa commented
A new request for boosting Woo products in search results - 7613492-zd-a8c

2024-01-22 14:08 UTC, robfelty commented
Git did not want to let me push because the branch was so old. I created a new PR here with Jason's suggestions https://github.com/Automattic/jetpack/pull/35167

2024-01-22 14:08 UTC, closed without merging