Boost: cut off image filenames in the IG analysis report at 20 characters to avoid overflow
Automattic/jetpack pull request #31670
Opened 2023-07-03 14:48 UTC by donnchawp

The Image Guide Analysis report lists images, but if the titles of any image are very long they will overflow and break the UI. This PR fixes that by cutting the filename at 20 characters and adding "..." at the end.

Fixes #31430 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

1. On a test site create a post with an image with a filename that is over twenty characters long.
2. Install Jetpack Beta to install Boost "Bleeding Edge".
3. Upgrade to a premium subscription
4. Enable image size analysis by defining the constant JETPACK_BOOST_IMAGE_SIZE_ANALYSIS.
5. Go to the Boost page and enable and run "Image Size Analysis".
6. The report will show the filename of the image cut off at 20 characters and "..." at the end of it.

2023-07-04 11:27 UTC, dilirity requested changes
Thanks for addressing this!

I think this would be better in a util function (`projects/plugins/boost/app/assets/src/js/utils`).

Then the change to the template would just be:

```js
<b>{addEllipsisToString( title, 20 )}</b>
```

2023-07-04 12:30 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/components/RowTitle.svelte
> +	const croppedTitle = truncateString( title, maxTitleLength );
Since the default is 20, you can get rid of `maxTitleLength`.

2023-07-04 12:31 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/utils/truncate-string.ts
> +	}
You can just do:

```js
truncateString( str: string, maxLength = 20 )
```

instead.

2023-07-04 12:39 UTC, donnchawp commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/components/RowTitle.svelte
> +	const croppedTitle = truncateString( title, maxTitleLength );
That's tempting, but it should probably stay, just in case we change the default value in truncateString and suddenly reports look awful again.

2023-07-04 12:45 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/components/RowTitle.svelte
> +	const croppedTitle = truncateString( title, maxTitleLength );
Ahaa! Great thinking!

2023-07-04 12:48 UTC, donnchawp commented on projects/plugins/boost/app/assets/src/js/utils/truncate-string.ts
> +	}
Done, thanks.

2023-07-04 12:48 UTC, dilirity approved these changes

2023-07-04 12:53 UTC, merged

2023-07-11 04:50 UTC, thingalon commented
I think 20 characters is too short in many circumstances. Can we [do this with CSS instead](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)? 

Wrote up a new ticket to switch to CSS name length limiting. https://github.com/Automattic/boost-cloud/issues/300