Stats: Add stats products to My Plan
Automattic/jetpack pull request #31732
Opened 2023-07-07 02:07 UTC by kangzj

Fixes #31713 

## Proposed changes:

* Show Stats products in My Plan

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
n/a

## Does this pull request change what data or activity we track or use?
no

## Testing instructions:

* Go to '..'
*

2023-07-07 17:05 UTC, ederrengifo commented
@kangzj For the icon we are using the chart icon from the WordPress library, just in case is faster to just reuse it, otherwise, I attach the SVG

![chart](https://github.com/Automattic/jetpack/assets/10525007/1800cdfc-dfb2-44e9-824c-9d03718adea5)

2023-07-10 03:58 UTC, kangzj commented
Hi @ederrengifo thanks for providing the Stats icon 👍 

<img width="1088" alt="image" src="https://github.com/Automattic/jetpack/assets/1425433/af3d69d1-b065-4727-b4ca-e97bb48a4490">

It seems to me that it doesn't quite match the other icons. Do you think a dark background one would look better?

2023-07-10 22:36 UTC, kangzj commented
Hi @ederrengifo I had a play with the SVG and how does this look? Feel free to discard or provide another version if this doesn't look right. 

https://github.com/Automattic/jetpack/blob/7043b718ea588bac96ebecd65d2ab9f2d0cbe5a8/projects/plugins/jetpack/images/products/product-jetpack-stats.svg

2023-07-11 00:28 UTC, jsnmoon requested changes
These changes look reasonable, but I noticed that the annual free plan gets stuck in a loading state:
<img width="1059" alt="image" src="https://github.com/Automattic/jetpack/assets/4044428/751a4c5e-cd35-4ad2-bd38-1fb94fac1b0b">

The annual PWYW and monthly commercial plans work as expected:
<img width="1056" alt="image" src="https://github.com/Automattic/jetpack/assets/4044428/2b4f70bd-2159-41c1-99c0-9becf54502c1">

Aside: I also noticed some unexpected behavior in purchasing the paid stats plans that I've noted in pbNhbs-6ZT-p2#comment-16609.

2023-07-11 00:29 UTC, jsnmoon commented
> Hi [Eder] I had a play with the SVG and how does this look? Feel free to discard or provide another version if this doesn't look right.

The updated icon looks great, by the way!

2023-07-11 02:03 UTC, kangzj commented on projects/plugins/jetpack/_inc/client/my-plan/my-plan-header/index.js
> +			case 'is-jetpack-stats-free-plan':
```suggestion
			case 'is-free-jetpack-stats-plan':
```
Fix typo

2023-07-11 02:05 UTC, kangzj commented
@jsnmoon good catch. There was a last minute change which caused a mismatch. Fixed: https://github.com/Automattic/jetpack/pull/31732/commits/fd4b2fa97c5e63c6eb050be33aeae652241ac11a

2023-07-11 18:53 UTC, jsnmoon approved these changes
Looks solid!

2023-07-11 20:01 UTC, merged