[Donation Block] Default to the Stripe Currency on Mount and Display a  ✔️ next to the selected currency
Automattic/jetpack pull request #31795
Opened 2023-07-11 03:35 UTC by romarioraffington

Fixes https://github.com/Automattic/gold/issues/39

## Proposed changes:

*  Display a  ✔️ next to the selected currency
* Default to the Stripe currency on mount.

Please see the video below where the Stripe default currency is USD and the default Donation block currency is EUR ( I changed the default currency for the Donation block attributes to EUR for this test ).

https://github.com/Automattic/jetpack/assets/7076981/e49c5c96-0017-440c-abe3-c8a5c715155c

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Sync changes to WPCOM
* Change the stripe account Currency connected to the site to any currency besides USD. You can also change the default currency for the Donation block to another currency [here](https://github.com/Automattic/jetpack/blob/7b3f2078c25ce86f5f50f96c565ebaeb25728b9e/projects/plugins/jetpack/extensions/blocks/donations/donations.php#L31).
* Add the Donation block to a post
* Select the currency controls
* Notice the Stripe default currency  is selected
* Select a currency and notice that  the ✔️ icon is to the right of the currency

#### Notes

Since we are fetching from the server, the Stripe currency may not appear in the UI until the server response is received. If the stripe currency is in the state, then the stripe currency will be displayed in the currency controls. 

> Default to the Stripe currency on mount.

@millerf, I don't think this approach is very user-friendly at the moment. We should only update the default currency **once only after the first render.**  In order to accomplish this, I suspect we would have to find a way to determine the first render, as we don't want to override the currency that the user has set. LMK if I should spend some more time looking into this or more onto something higher priority

2023-07-12 10:35 UTC, millerf commented
@romarioraffington , as explained in the [task description](https://github.com/Automattic/gold/issues/39), there is already a way [to retrieve the current Stripe currency from the data store](https://github.com/Automattic/wp-calypso/blob/7a62b7d389734da64256173b6c8f6183ef1d3ee8/client/state/memberships/settings/selectors.js#L13).
I might be mistaken, but you should be able to use it without having to reinvent the wheel with `getConnectedAccountDefaultCurrency`. That is adding a lot of complexity...

Please test with `getconnectedAccountDefaultCurrencyForSiteId()` and remove the unecessary code...

2023-07-12 19:39 UTC, romarioraffington commented
> @romarioraffington , as explained in the [task description](https://github.com/Automattic/gold/issues/39), there is already a way [to retrieve the current Stripe currency from the data store](https://github.com/Automattic/wp-calypso/blob/7a62b7d389734da64256173b6c8f6183ef1d3ee8/client/state/memberships/settings/selectors.js#L13). I might be mistaken, but you should be able to use it without having to reinvent the wheel with `getConnectedAccountDefaultCurrency`. That is adding a lot of complexity...
> 
> Please test with `getconnectedAccountDefaultCurrencyForSiteId()` and remove the unecessary code...

The code you linked is in the Calypso repo. 😄

2023-07-13 08:41 UTC, millerf commented
> The code you linked is in the Calypso repo. There isn't a way to do this in Jetpack as the moment 😄

Yes 😅
At least it gives some ideas on where to get the data.

2023-07-17 15:07 UTC, millerf requested changes
I tried to test it on https://bestmemberships.wordpress.com/ and it fails. I have a console error when adding a Donation block...

I am not sure if some changes were not uploaded...

https://github.com/Automattic/jetpack/assets/790558/aa6fa955-2147-4d93-b5f1-08c4e25b8d5b

2023-07-20 11:46 UTC, millerf requested changes
It looks good appart from the extra attributes that seems unecessary.
I haven't tested yet.

2023-07-20 11:46 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
It feels like `hasCurrencyBeenUpdatedByUser` could be deduced by "the current currency is  not null and the current curtrency is different from the stripe currency"

```
hasCurrencyBeenUpdatedByUser = currency!=null && currency!=stripeCurrency

```

So it might not be needed to save it as an extra attribute... What do you think?

2023-07-20 15:46 UTC, romarioraffington commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
When the currency was `null` the Donation block threw an error similar to the one in the video above. I could try again, however.

2023-07-20 18:21 UTC, romarioraffington commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
See the error that is thrown based on the feedback above 

<img width="1730" alt="Screenshot 2023-07-20 at 1 21 06 PM" src="https://github.com/Automattic/jetpack/assets/7076981/c703fa88-7400-4970-b1a2-a0cc26d2dc94">

2023-07-20 18:48 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
> When the currency was null the Donation block threw an error similar to the one in the video above.

Well I am not saying to change the current version to 
```
	if ( ! currency!=null && currency!=stripeCurrency ) {
```

And remove `hasCurrencyBeenUpdatedByUser`

2023-07-20 18:48 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
Does it make more sense?

2023-07-20 20:07 UTC, romarioraffington commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
> > When the currency was null the Donation block threw an error similar to the one in the video above.
> 
> Well I am not saying to change the current version to
> 
> ```
> 	if ( ! currency!=null && currency!=stripeCurrency ) {
> ```
> 
> And remove `hasCurrencyBeenUpdatedByUser`

Okay, if you're not saying to do the above, what are you suggesting?

2023-07-20 21:15 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
> Okay, if you're not saying to do the above, what are you suggesting?

There was a typo. Fixed now.

2023-07-22 09:04 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/donations/edit.js
> +		if ( ! hasCurrencyBeenUpdatedByUser ) {
See https://github.com/Automattic/jetpack/pull/31795/commits/fd1eef7d70b1ce82d1c16a1d8802124542056d45 and further commits.

2023-07-24 13:19 UTC, millerf approved these changes, later dismissed

2023-07-25 13:47 UTC, millerf approved these changes, later dismissed
LGTM

2023-07-25 14:53 UTC, millerf approved these changes, later dismissed

2023-07-25 20:16 UTC, millerf approved these changes

2023-07-25 20:16 UTC, merged