Introduce 'jetpack_woocommerce_analytics_event_props' filter
Automattic/jetpack pull request #32052
Opened 2023-07-25 11:45 UTC by manospsyx

Introduces a filter to modify/append WooCommerce analytics event properties. Will be utilized to add a Woo Express `host` parameter. 

I considered adding a `host` key directly, but decided to take the filter approach to make it easier for others to add props in the future.

Fixes #32050

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-07-25 13:02 UTC, PanosSynetos approved these changes, later dismissed
Thanks @manospsyx - The filter is helpful. I don't see any reason not to introduce this

Let's see what Jetpack Crew has to say

2023-07-25 13:29 UTC, jeherve requested changes

2023-07-25 13:29 UTC, jeherve commented on projects/plugins/jetpack/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-universal.php
> +		$all_props = apply_filters(
I would recommend adding a docblock to that filter, so our [Jetpack codex](https://developer.jetpack.com/) can be automatically updated with some information about the filter. Something like this:
```suggestion
		/**
		 * Allow defining custom even properties in WooCommerce Analytics.
		 *
		 * @module woocommerce-analytics
		 *
		 * @since $$next-version$$
		 *
		 * @param array $all_props Array of standard event props.
		 */
		$all_props = apply_filters(
```

2023-07-25 14:52 UTC, jeherve approved these changes

2023-07-26 06:14 UTC, merged

2023-07-26 06:22 UTC, PanosSynetos reviewed
👌