Use shared component for editor panel icons
Automattic/jetpack pull request #32257
Opened 2023-08-03 09:54 UTC by simison

Use a shared component as Jetpack icon for block editor panels.

Pretty minor but seemed like repeating `showText={ false } height={ 16 } logoColor="#1E1E1E"` everywhere was a bit unnecessary.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Test all affected panels and ensure icons render fine. They seem all to be in post editor's post settings, pre-publish, or post-publish panels.

2023-08-03 10:31 UTC, jeherve requested changes
This looks good to me, it makes sense. I wonder if it would be useful to place `JetpackEditorPanelLogo` in `@automattic/jetpack-shared-extension-utils` instead, so we can use it in standalone plugins as well? Here is what would be a good candidate, for example:
https://github.com/Automattic/jetpack/blob/199afea61f7bc40e15951546faf2d4721622c4ee/projects/plugins/social/src/js/editor.js#L98

2023-08-03 12:39 UTC, simison commented
Thanks! Good idea, implemented in https://github.com/Automattic/jetpack/pull/32257/commits/42f005d892bc5c76e27aa157fd69d3c74b67edbd

2023-08-03 14:27 UTC, jeherve requested changes
It tests well. It does seem like we've lost some margin styling in the process:

```css
.components-panel__icon {
    color: #757575;
    margin: -2px 0 -2px 6px
}
```

**Before**

<img width="293" alt="Screenshot 2023-08-03 at 16 23 33" src="https://github.com/Automattic/jetpack/assets/426388/2d00f960-700d-4c1b-adb6-3f9f4c1c2c75">
<img width="874" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/30587ff8-6c10-42f4-a9ac-93bc54d61ff6">

**After**

<img width="270" alt="Screenshot 2023-08-03 at 16 23 38" src="https://github.com/Automattic/jetpack/assets/426388/42ebd24a-ac52-49ee-89e1-90181eafa29b">
<img width="885" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/d69c05aa-6af9-4fd9-92d1-35d627f734b2">

I think it should be something worth fixing.

2023-08-04 20:46 UTC, simison commented
> It tests well. It does seem like we've lost some margin styling in the process:

Huh; I don't understand what happened? The markup should stay exactly the same, we're passing just SVG to a prop that expects an icon and should style its spacing on its own... so why do we need to pass this thing a left margin for it to work?

Did in https://github.com/Automattic/jetpack/pull/32257/commits/cc6a62cec183b2286dbcc624ef65aa8fd965da4f however.

2023-08-07 12:23 UTC, lezama approved these changes

2023-08-07 12:23 UTC, lezama commented
> Did in https://github.com/Automattic/jetpack/commit/cc6a62cec183b2286dbcc624ef65aa8fd965da4f however.

Looks good now!

<img width="305" alt="Screenshot 2023-08-07 at 09 24 39" src="https://github.com/Automattic/jetpack/assets/104869/b6d6e96d-79f7-47c2-9ec3-40aeb0e3847e">

2023-08-07 12:26 UTC, simison commented
I'm just bothered that I don't understand why that worked. 😅

2023-08-07 12:40 UTC, jeherve approved these changes
This tests well for me now! 🚢

2023-08-07 12:41 UTC, merged