CRM Automations: Add workflow table
Automattic/jetpack pull request #32443
Opened 2023-08-11 23:43 UTC by robertf4

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-08-15 18:01 UTC, gogdzl requested changes
This PR's table:
![image](https://github.com/Automattic/jetpack/assets/37049295/c6541a8b-dc88-42bf-add3-f7400b8131c2)

Figma:
![image](https://github.com/Automattic/jetpack/assets/37049295/3038716a-eb62-49c9-8822-914a1ebdd790)

Should the headers match 100% the Figma file?
Also, the horizontal spacing looks different.

2023-08-15 18:12 UTC, gogdzl commented
Some more issues:

- In the Figma file the header has `studio-gray-60` color.
- There is no sorting indicator in the column headers (I even think that they should be clickable)

2023-08-17 16:03 UTC, robertf4 commented on projects/plugins/crm/src/js/components/automations-admin/components/checkbox/index.tsx
> -	decorative?: boolean;
Removing this as I misunderstood the design 😅

2023-08-17 16:12 UTC, robertf4 commented
@gogdzl I implemented the sorting and addressed the other issues, and this one is ready for another look.

2023-08-17 16:17 UTC, robertf4 commented
Note that sorting by status won't work until the store is implemented because the `active` prop won't actually be updated until then.

2023-08-22 03:02 UTC, gogdzl commented
This PR's table:
![image](https://github.com/Automattic/jetpack/assets/37049295/5c494322-2256-4f94-ad23-26e997dc62db)


Figma:
![image](https://github.com/Automattic/jetpack/assets/37049295/3038716a-eb62-49c9-8822-914a1ebdd790)

Looks good!
Small nitpick would be to match the fonts of the titles, but if that is too complicated it already looks good to me!

2023-08-22 03:03 UTC, gogdzl approved these changes

2023-08-25 20:57 UTC, merged