CRM Automations: Add Bulk Workflow Actions Component
Automattic/jetpack pull request #32448
Opened 2023-08-14 01:12 UTC by robertf4

Fixes https://github.com/Automattic/zero-bs-crm/issues/3209

## Proposed changes:

This PR adds the Bulk Workflow Actions components.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

NtYgueI8oAgiWGHTbHpnjh-fi-1_29

## Does this pull request change what data or activity we track or use?

## Testing instructions:

1. Review the code.
2. Put `add_filter( 'jetpack_crm_feature_flag_automations', '__return_true' );` in an mu-plugin.
3. Visit `/wp-admin/admin.php?page=jpcrm-automations#/automations/test-workflow-bulk-actions`. Check that the "bulk actions" dropdown shows and matches the visuals in the Figma. Note that no functionality is implemented yet. This is waiting on the store implementation.

2023-08-15 18:32 UTC, gogdzl requested changes
When WordPress' menu is not collapsed, the dropdown is unaligned:
![image](https://github.com/Automattic/jetpack/assets/37049295/199588aa-608c-4548-abd3-abbe1ef2de57)


When we collapse it, it works as expected:
![image](https://github.com/Automattic/jetpack/assets/37049295/8051c695-69c4-46d2-b506-729e6244c168)

2023-08-25 17:24 UTC, cleacos commented
**Margins:**

![image](https://github.com/Automattic/jetpack/assets/9832440/4ef820a3-021b-4cb7-b64d-13a3f2db1b58)

**z-index issue:**

![image](https://github.com/Automattic/jetpack/assets/9832440/d27c4b64-7e77-4731-b7f8-1d1e4eb1d143)

Anyway, we can omit the Bulk Actions feature for the first version to be able to move forward, less functionality to implement and it's not needed at the beginning.

2023-08-30 18:03 UTC, gogdzl submitted a review, later dismissed
I fixed some margins, and now LGTM!

@cleacos , could you take a look?
(about the margins you pointed out, I think this component respects its parent div, and this parent should be the one respecting the margins)

2023-09-01 10:07 UTC, gogdzl approved these changes

2023-09-01 15:35 UTC, merged