Social: Add SIG toggle for Jetpack Settings
Automattic/jetpack pull request #32475
Opened 2023-08-15 08:55 UTC by gmjuhasz

This change adds the ability to be able to toggle SIG and select default templates from the Jetpack Settings page. This is needed so people with only the main Jetpack plugin can access this setting too.

<img width="1109" alt="CleanShot 2023-08-15 at 10 48 50 png" src="https://github.com/Automattic/jetpack/assets/36671565/8acce142-1f00-4447-81aa-506cc438d467">

## Proposed changes:

* Restructured the SIG components a bit
* Registering the Social store is now happening in `publicize-components`
* I added 2 new components for opening the template picker with a button, and a generic toggle for SIG. We can use these on the Social admin page too in a next change
* I added these components into _inc under the main Publicize toggle.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

1205142973434174-as-1203857426851211
## Does this pull request change what data or activity we track or use?

No.
## Testing instructions:

* Go to `wp-admin/admin.php?page=jetpack#/sharing` on your site, and compare the looks with the image above
* You should see the SIG toggle and the template picker only if
  * You have the publicize module enabled with the main toggle
  * You have the Advanced plan - the only way currently to have the feature
* Test the functionality
  * Toggling the state you work, and stay the same on refresh
  * Changing templates should stay the same on refresh
  * You can open the Social admin page too, change it there, then refresh the Jetpack settings page to see if the changes went throug.

* A generic sanity testing would be nice too, as the store structure is changed a bit.
  * Create a new post and publicize it.
  * Play with the settings in the editor, you should see no errors.

2023-08-15 10:51 UTC, gmjuhasz commented on projects/plugins/social/src/js/index.js
> -register( store );
Now this gets initialised with using the publicize-components package

2023-08-16 09:14 UTC, jeherve requested changes
This tests well and looks good, nice work! I only left some minor nitpicks.

2023-08-16 09:14 UTC, jeherve commented on projects/plugins/jetpack/changelog/add-sig-toggle-jetpack-settings
> +Added SIG toggle for Jetpack Settings
SIG may not mean much to most folks. How about something like:

```suggestion
Dashboard: add Social Image Generator options to Jetpack Social settings.
```

2023-08-16 09:14 UTC, jeherve commented on projects/plugins/jetpack/changelog/add-sig-toggle-jetpack-settings
> +Type: major
I don't know that I would classify this as a major enhancement. I think enhancement would be enough.

```suggestion
Type: enhancement
```

2023-08-16 09:14 UTC, jeherve commented on projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php
> +	 * @return mixed|null
Should we change this here?

```suggestion
	 * @return array|null
```

2023-08-16 12:27 UTC, gmjuhasz commented on projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php
> +	 * @return mixed|null
Nice catch thanks!

2023-08-16 15:26 UTC, jeherve approved these changes

2023-08-16 15:27 UTC, jeherve commented
I see now that the Social e2e tests are failing. It may be good to make sure it's not caused by this PR?

2023-08-17 07:46 UTC, gmjuhasz commented
> I see now that the Social e2e tests are failing. It may be good to make sure it's not caused by this PR?

Yeah, that was some flaky tests I think, now it's only the Jetpack post-connection test is failing due to timeout, which is also flaky

2023-08-17 07:47 UTC, merged

2023-08-17 07:48 UTC, jeherve commented
> now it's only the Jetpack post-connection test is failing due to timeout, which is also flaky

I'm working on this in #32391, hopefully that will help!