CRM: Automations Quote condition for status changed
Automattic/jetpack pull request #32473
Opened 2023-08-15 01:35 UTC by gogdzl

## Proposed changes:

* This PR adds the quote condition 'Status Changed' and respective tests.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
https://github.com/Automattic/zero-bs-crm/issues/3192

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:

* Run tests by navigating to the CRM directory in your local installation after running `jetpack build plugins/crm`, and then run `composer phpunit -- --testdox --testsuite automation` (note this will currently run all tests as well with a new commit adding tests to this PR).

2023-08-16 12:36 UTC, robertf4 commented on projects/plugins/crm/src/automation/commons/conditions/quotes/class-quote-status-changed.php
> +		throw new Automation_Exception( 'Invalid operator: ' . $operator );
I have the same suggestion here as the previous PR I reviewed: check this at the beginning of the function using `$valid_operators` and then have a default case in the switch that throws an "unimplemented operator exception".

2023-08-16 17:44 UTC, cleacos requested changes
The quote model doesn't have the `status` property. Determining the virtual status of a quote requires performing some checks with the accepted field.

2023-08-16 18:54 UTC, gogdzl commented
> The quote model doesn't have the status property. Determining the virtual status of a quote requires performing some checks with the accepted field.

Thanks a lot for pointing that out! Sometimes quotes do have a status field, but just in some cases ( e.g. sorting ), and they are indeed calculated in the code.

I added a fix for that and everything should be corrected.

2023-08-17 17:10 UTC, cleacos commented on projects/plugins/crm/src/automation/commons/conditions/quotes/class-quote-status-changed.php
> +		return 'quote';
```suggestion
		return __( 'quote', 'zero-bs-crm' );
```

2023-08-17 17:13 UTC, cleacos submitted a review, later dismissed
Cool. The code looks good, and the tests passed. I committed a small change (category translation)

LGTM!

2023-08-17 19:08 UTC, robertf4 approved these changes
I approve this PR, it is the best!

2023-08-17 19:08 UTC, merged