Add Jetpack AI forms section to Forms landing page
Automattic/jetpack pull request #32726
Opened 2023-08-29 02:26 UTC by IanRamosC

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-08-30 18:41 UTC, CodeyGuyDylan requested changes
Functionality looks good and tests well, just a couple comments on the copy

2023-08-30 18:41 UTC, CodeyGuyDylan commented on projects/packages/forms/src/dashboard/landing/index.js
> +										'Need a RSVP form for your event site? Simply ask AI Assistant to prepare a form that includes options for meal preferences, attendance status, or plus-ones.',
This has an orphan in it
![image](https://github.com/Automattic/jetpack/assets/65001528/d6512c69-ac5f-4322-80ed-309598910772)

2023-08-30 18:41 UTC, CodeyGuyDylan commented on projects/packages/forms/src/dashboard/landing/index.js
> +										'Need a RSVP form for your event site? Simply ask AI Assistant to prepare a form that includes options for meal preferences, attendance status, or plus-ones.',
This should start out as `Need an RSVP form`
```suggestion
										'Need an RSVP form for your event site? Simply ask AI Assistant to prepare a form that includes options for meal preferences, attendance status, or plus-ones.',
```

2023-08-30 21:30 UTC, IanRamosC commented
> I noticed when I have AI on the site, the CTA doesn't go anywhere or do anything 🤔

The function to redirect the user to the post page takes some time because it makes a request to the API to create a post, then edit it with the content of an empty form. Could you check if you're redirected to a different page after some time?
Also, if it still doesn't work, can you check if there's any error in the console?

Anyhoo, I can add a loading state to the button in a different PR if that's what's happening.

2023-08-31 17:33 UTC, CodeyGuyDylan commented
> * /wp-admin/admin.php?page=jetpack-forms#/landing

I went ahead and tried again clicking it, and I waited several minutes and nothing is happening 🤔 

I am using the beta plugin btw

2023-09-01 18:58 UTC, CodeyGuyDylan approved these changes
Works for me now, thank you for the fixes!

2023-09-01 19:13 UTC, merged