Add/paid newsletter subscriber count
Automattic/jetpack pull request #32777
Opened 2023-08-30 23:32 UTC by chrismccluskey

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-09-01 13:03 UTC, millerf requested changes
I haven't tested yet, but there is a missing reference [here](https://github.com/Automattic/jetpack/blob/b4c4f21c8374e693f74bdeb83342440d3acb0800/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L203) for `paid_newsletter_subscribers` that should default to 0.

2023-09-05 12:31 UTC, millerf approved these changes
LGTM. Testing it now

2023-09-05 13:44 UTC, millerf commented
Tested on  https://charming-guineafowl.jurassic.ninja/

Counters when starting:
<img width="400" alt="Screenshot 2023-09-05 at 15 01 53" src="https://github.com/Automattic/jetpack/assets/790558/12afc827-a2c9-44b2-afb8-954fcbf15cf5">


After adding a free subscriber I saw the right incrementation.

I then proceeded to pay for a subscription

On my sandbox
```

 > print get_blog_id_from_url('charming-guineafowl.jurassic.ninja')
223158762
 > gpr SELECT * FROM subscription_counts WHERE blog_id=223158762
+-----------------------+-------------------+-----------+-----------+---------+--------------------+
| subscription_count_id | subscription_type | user_type | blog_id   | post_id | subscription_count |
+-----------------------+-------------------+-----------+-----------+---------+--------------------+
| 179123732             | posts             | nonwpcom  | 223158762 |         | 1                  |
| 179123145             | posts             | wpcom     | 223158762 |         | 2                  |
+-----------------------+-------------------+-----------+-----------+---------+--------------------+

 > require 'async-jobs/jobs.php';
 > $job = (object)['data'=>['blog_id'=> 223158762]]

 > jobs_wpcom_subs_update_total_paid_subscribers($job);
\
 > gpr SELECT * FROM subscription_counts WHERE blog_id=223158762
+-----------------------+-------------------+------------+-----------+---------+--------------------+
| subscription_count_id | subscription_type | user_type  | blog_id   | post_id | subscription_count |
+-----------------------+-------------------+------------+-----------+---------+--------------------+
| 179123732             | posts             | nonwpcom   | 223158762 |         | 1                  |
| 179123145             | posts             | wpcom      | 223158762 |         | 2                  |
| 179124282             | newsletter        | wpcom_paid | 223158762 |         | 1                  |
| 179124281             | posts             | wpcom_paid | 223158762 |         | 1                  |
+-----------------------+-------------------+------------+-----------+---------+--------------------+
```

The counter incremented the paid-subscriebrs and the subscribers accordingly


<img width="400" alt="Screenshot 2023-09-05 at 15 19 29" src="https://github.com/Automattic/jetpack/assets/790558/07d4807d-6a55-44ac-9052-e82a3fe8158e">


I then subscribed to a premium-content plan:

<img width="1169" alt="Screenshot 2023-09-05 at 15 27 07" src="https://github.com/Automattic/jetpack/assets/790558/fef726fc-a6b7-4826-82d6-ef30082f545d">


And re-run the script and could not see a new subscriber,...

2023-09-05 22:10 UTC, chrismccluskey commented
This is no longer needed and should not be merged. See 120-gh-automattic/gold for more information.

2023-09-05 22:10 UTC, closed without merging