CRM: Resolves #3316 - better slug generation
Automattic/jetpack pull request #33121
Opened 2023-09-15 19:47 UTC by tbradsha

Resolves Automattic/zero-bs-crm#3316 - better slug generation

## Proposed changes:

In #33096 we solved issues with duplicates and fallback slugs. This PR switches tag slug generation from `$zbs->DAL->makeSlug()` to WP's native `sanitize_key()` (initially I looked at both `sanitize_title()` and `sanitize_title_with_dashes()`, but neither limits to alphanumeric chars + dashes + underscores despite what their docs say).

It also adds a new migration that regenerates tag slugs. I wanted to simplify the logic, but was struggling to do so while covering all scenarios. Feel free to suggest more condensed code! This is the current logic:

```
1. Generate slug:
    * If blank, use `tag` base:
        * If old slug looks like /^tag-\d+$/ and it's not been used, use it.
        * Otherwise, generate a new `tag-N` slug. It'll be unique, as we check the database and increment by one.
    * If not blank:
        * available: use (update db)
        * old slug has correct base and is available: use old slug (already in DB)
        * new and old slug are unavailable: iterate (update db)
2. Store slug in database if it doesn't match its old slug.
3. Cache slug in `$used_slugs`, preventing reuse by other tags.
```

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

Start in `trunk`. Add tags like with a mix of ASCII and non-ASCII chars (e.g. `Product: (ПРОМО ПАКЕТ)`). Also, add some tags with duplicate slugs via the database.

In `trunk`, you'll see duplicate slugs, and the mixed-char labels will have a slug of `tag-N` on most systems.

Then switch to the `fix/crm/3316-better_slug_generation` branch. The migration should run, fixing duplicates and giving the mixed-char tags a slug derived from the ASCII chars (not always pretty, but more unique than `tag-N`).

2023-09-15 21:21 UTC, gogdzl commented
The migration produced some weird slugs.

From:
![image](https://github.com/Automattic/jetpack/assets/37049295/8d6b2bec-c618-4ab8-abb0-2c5c8ee9531b)

To:
![image](https://github.com/Automattic/jetpack/assets/37049295/6611a89d-8d85-4acf-8179-9599eadbfed2)

Worked well for all my quote cat tags:

![image](https://github.com/Automattic/jetpack/assets/37049295/a5757e5a-f64d-4b7d-87bf-f3f069a3f8a8)

2023-09-15 21:22 UTC, gogdzl requested changes
Code looks good, but I left a comment about some weird tags. I don't know if that is the expected behavior or not. (e.g. isn't expected 'Product: First Hoodie' to generate the tag 'product-first-hoodie'?)

2023-09-18 12:48 UTC, tbradsha commented
Rebased.

2023-09-18 12:55 UTC, tbradsha commented
> I left a comment about some weird tags. I don't know if that is the expected behavior or not. (e.g. isn't expected 'Product: First Hoodie' to generate the tag 'product-first-hoodie'?)

This is indeed expected behaviour when using WP's built-in `sanitize_key()`. While we could write our own wrapper or filter that modifies the function, that's somewhat the reason we had the problem in the first place, and I think it best to use the existing function as-is.

As mentioned in the original description, originally I considered `sanitize_title()` and `sanitize_title_with_dashes()`. However, despite the docs claiming they only do alphanumeric, dashes, and underscores, both convert the Cyrillic to `%xx` chars, which are definitely not as friendly to work with.

2023-09-18 18:34 UTC, gogdzl approved these changes
It works as advertised. Nice job, @tbradsha =)

2023-09-18 20:08 UTC, merged