Blogroll: Fix blogroll subscribe on simple site
Automattic/jetpack pull request #33345
Opened 2023-09-27 14:23 UTC by renancarvalho

Fixes https://github.com/Automattic/wp-calypso/issues/82124

## Proposed changes:

* Fixes an issue for logged-out users when trying to subscribe to a blog/site using blogroll
* This fix applies only to simple sites, atomic sites will be handled in another PR.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Apply this branch
* Make sure you have your simple site sandboxed
* Navigate to your simple site using incognito or logged-out user
* Subscribe to a site should work.

2023-09-27 14:44 UTC, heavyweight requested changes
The follow source is not in the safe list. 
There is a notice triggered on subscribe that we need to look into.

2023-09-27 15:56 UTC, renancarvalho commented
> The follow source is not in the safe list. There is a notice triggered on subscribe that we need to look into.

I have also addressed it here D123399-code. Good catch @heavyweight  👍

2023-09-27 19:26 UTC, heavyweight requested changes
Had some time to debug this.

When the source is not the current location			
`<input name="source" type="hidden" value="$current_location">`

If the user is not logged in: Gets redirected to login page.
If the user is logged in: Gets redirected to the [subscriptions management admin page](https://wordpress.com/subscriptions/sites/en).
In both cases the subscription is not created.

We will need to debug this, and hopefully keep the tracking source.

2023-09-28 13:04 UTC, renancarvalho commented
@heavyweight patch, updating the sub-types D123530-code

2023-09-28 14:21 UTC, heavyweight approved these changes

2023-09-28 14:21 UTC, merged