Boost: Remove global state from UpgradeCTA component
Automattic/jetpack pull request #33375
Opened 2023-09-28 09:49 UTC by dilirity

## Proposed changes:

* Moves global state from UpgradeCTA component to parent component (Modules).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-286-p2

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Make sure Upgrade sections work as expected and yearly pricing shows correctly.

### Critical CSS

![CleanShot 2023-09-28 at 12 48 59](https://github.com/Automattic/jetpack/assets/11799079/d8438aba-659d-4995-9fd0-8af507a9e21a)

### Image Size Analysis

![CleanShot 2023-09-28 at 12 47 38](https://github.com/Automattic/jetpack/assets/11799079/b1b261c9-9be9-459b-843c-701d4a5e2995)

2023-10-10 15:48 UTC, donnchawp approved these changes, later dismissed
Works as expected. The price shows in both areas.

2023-10-11 12:12 UTC, pyronaur requested changes

2023-10-11 12:12 UTC, pyronaur commented on projects/plugins/boost/app/assets/src/js/pages/settings/elements/UpgradeCTA.svelte
> +	export let yearlyPricing;
Missing type

2023-10-12 14:08 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/pages/settings/elements/UpgradeCTA.svelte
> +	export let yearlyPricing;
Addressed in 245cafb.

2023-10-13 04:13 UTC, pyronaur approved these changes
👍

2023-10-13 08:39 UTC, merged