Allow Image CDN to proxy HECI images
Automattic/jetpack pull request #33494
Opened 2023-10-06 19:08 UTC by xyu

The backend `Photon_OpenCV` extension actually does build in HEIC support using the following libraries:

```
libheif-decoder.cpp
libheif-decoder.h
libheif-encoder.cpp
libheif-encoder.h
```

What's more it's even allowed by `photon/index.php` because while the `$allowed_types` is currently set as:

```
49	$allowed_types = apply_filters( 'allowed_types', array(
50	        'gif',
51	        'jpg',
52	        'jpeg',
53	        'png',
54	) );
```

`libheif` returns `jpeg` as the type for HECI images:

```
$ wp shell
wp> $i = new Photon_OpenCV();
=> object(Photon_OpenCV)#4849 (0) {
}
wp> $i->readimageblob( file_get_contents( 'img.heic' ) );
=> NULL
wp> $i->getimageformat()
=> string(4) "jpeg"
```

So all we need to do is to allow `heci` extensions to be passed through Photon. In fact we can test this right now and see that it works as expected:
- HEIC: https://xiao.blog/sample.heic
- JPEG: https://i0.wp.com/xiao.blog/sample.heic?w=600

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-10-09 15:22 UTC, jeherve requested changes

2023-10-09 15:22 UTC, jeherve commented on projects/packages/image-cdn/CHANGELOG.md
> +- Added HEIC (`*.heic`) to list of images types allowed to be passed through Photon. [#33494]
We typically do not edit the changelog directly, since when you work on your PR you do not yet know when the change will be released / what version of the package will include your changes. 

Instead, you can run `jetpack changelog add packages/image-cdn` and follow the prompts to add your changelog entry. It will generate a changelog entry file that you can commit and that will be merged alongside your PR. When we next release an update to the Image CDN package, we'll use the different changelog entry files from the different PRs that were merged since the last release to:

1. Decide what version should be released, based on the severity declared in the different changelog entry files.
1. Generate the changelog for that version.

Doing things that way will also fix the failed changelog GitHub Action on your PR.

2023-10-09 15:22 UTC, jeherve commented on projects/packages/image-cdn/src/class-image-cdn.php
> +		'heic', // Photon_OpenCV supports webp with libheif-*, getimageformat() returns jpeg so does not match docblock
Do you think you could add a test for this change, or edit the existing `get_test_image_cdn_validate_image_url_file_types_data_provider` test?

2023-10-09 16:33 UTC, xyu commented on projects/packages/image-cdn/CHANGELOG.md
> +- Added HEIC (`*.heic`) to list of images types allowed to be passed through Photon. [#33494]
Done in 4e4d30187b

2023-10-09 16:38 UTC, xyu commented on projects/packages/image-cdn/src/class-image-cdn.php
> +		'heic', // Photon_OpenCV supports webp with libheif-*, getimageformat() returns jpeg so does not match docblock
Done in 49e965b619

2023-10-10 10:56 UTC, jeherve reviewed
Should we extend this to also allow Jetpack's Search feature to support HEIC?
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/packages/search/src/instant-search/lib/hooks/use-photon.js#L32

Here is how you would go about testing this:

1. Go to Jetpack > Settings > Performance and ensure that Instant Search is active.
2. Click to customize Instant Search and ensure that you are using the expanded mode, where thumbnails are displayed.
3. Search for a post that includes an HEIC image, using the Instant Search interface.
4. You should see the image appear in the search preview.

*********

Should we also extend the WordPress.com REST API to support HEIC?
https://github.com/Automattic/jetpack/blob/d59247968a6ced82775a75e41d0d44c890ec76d8/projects/plugins/jetpack/class.json-api-endpoints.php#L1598
https://github.com/Automattic/jetpack/blob/d59247968a6ced82775a75e41d0d44c890ec76d8/projects/plugins/jetpack/sal/class.json-api-post-base.php#L939
(and maybe in some other places?)
Looking at #32900, I'm guessing maybe we shouldn't, or should only limit it to WordPress.com sites?

2023-10-10 18:21 UTC, xyu commented
> Should we extend this to also allow Jetpack's Search feature to support HEIC?
> 
> https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/packages/search/src/instant-search/lib/hooks/use-photon.js#L32

This makes sense to me added with 2f67f34 

> Should we also extend the WordPress.com REST API to support HEIC?
> 
> https://github.com/Automattic/jetpack/blob/d59247968a6ced82775a75e41d0d44c890ec76d8/projects/plugins/jetpack/class.json-api-endpoints.php#L1598
> 
> https://github.com/Automattic/jetpack/blob/d59247968a6ced82775a75e41d0d44c890ec76d8/projects/plugins/jetpack/sal/class.json-api-post-base.php#L939
> 
> (and maybe in some other places?)
> Looking at #32900, I'm guessing maybe we shouldn't, or should only limit it to WordPress.com sites?

I'm not sure if we should add this to the API endpoints above, currently we kinda only have partial support for HEIC images in that we will _always_ convert HEIC images passed through Photon to JPEG which makes it compatible with all browsers. The downside is even for browsers that support HEIC like Safari we still convert the image which is not exactly what the client asked for. This probably is fine on the front end but I'm not sure if that would make it weird for a REST / programmatic endpoint. I.e. we advertise the URL to an HEIC image that's really a JPEG. What do you think @jeherve?

2023-10-11 10:00 UTC, jeherve approved these changes

2023-10-11 10:00 UTC, merged

2023-10-29 08:36 UTC, inaikem commented
Hi folks, checking in here for an old open ticket here: 7089554-zd-a8c

Can you please confirm if this fix has landed on AT sites yet? Thanks!

2023-10-30 07:56 UTC, jeherve commented
> Can you please confirm if this fix has landed on AT sites yet? Thanks!

It has, yes.