DRAFT: Earn: Rename earn to monestize
Automattic/jetpack pull request #33741
Opened 2023-10-23 19:06 UTC by edanzer

**Trial: No need for review yet and do no merge.**

## Proposed changes:

* Renames Earn page and main nav links from 'Earn' to 'Monetize'

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None.

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Will add if/when ready.

2023-10-24 10:58 UTC, jeherve requested changes
👍 You would have to update `_inc/client/components/navigation-settings/test/component.js` for the tests to pass.

2023-10-24 19:06 UTC, edanzer commented
> 👍 You would have to update `_inc/client/components/navigation-settings/test/component.js` for the tests to pass.

@jeherve - resolve the tests for this. Thanks!

2023-10-24 19:33 UTC, lezama approved these changes

2023-10-25 07:43 UTC, jeherve approved these changes

2023-10-26 17:48 UTC, merged