Boost: Migrate svelte components to react
Automattic/jetpack pull request #33886
Opened 2023-10-31 14:39 UTC by dilirity

WIP

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2023-11-06 17:35 UTC, dilirity commented
> Speed Score feature › Should be able to hover info icon next to overall score and see the detailed overall score description popin 

Tests are broken. Info tooltip no longer works on hover - just on mouse click.

2023-11-08 07:03 UTC, haqadn requested changes
This covers a lot and it looks like it's working well. My recommendation is to organize the files in the proposed structure in the p2. And, I think non-reusable components like Tooltips can live in their parent component folder.

I have noticed a small issue in styles, the icon placement is wrong:

This PR:
![image](https://github.com/Automattic/jetpack/assets/3737780/17b7090e-4393-45ec-a516-f669d15cfbc6)

Trunk:
![image](https://github.com/Automattic/jetpack/assets/3737780/966b04ff-03f3-4559-8e3f-0a47f4ba5468)

2023-11-08 07:03 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/react-components/image-size-analysis/hero/index.tsx
> +				[ styles[ 'fade-in' ] ]: fadeProp,
I think the fade-in effect can be achieved purely with CSS using animation. So, I don't feel very comfortable involving the state in this. Can you try replacing it with [CSS animation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animations/Using_CSS_animations)?

2023-11-08 07:03 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/react-components/image-size-analysis/hero/index.tsx
> +				[ styles[ 'fade-in' ] ]: fadeProp,
Here is an implementation just in case: https://github.com/animate-css/animate.css/blob/main/source/fading_entrances/fadeIn.css

2023-11-08 07:03 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/react-components/recommendation-context/index.tsx
> +export const RecommendationContext = () => {
Considering it is a simple usage of the IconTolltip, I think we can skip putting it in a separate component and place the IconTolltip directly in `Hero`.

2023-11-08 07:03 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/react-components/image-size-analysis/other-group-context/index.tsx
> +const OtherGroupContext = () => {
I think we do not need this component either, just like `RecommendationContext`. But, I think you are using it as a stop-gap until `MultiProgress` is refactored into a react component, in which case, it is ok.

2023-11-08 07:03 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/react-components/score-context/index.tsx
> +const ScoreContext = () => {
Same as `RecommendationContext` and `OtherGroupContext`.

2023-11-08 07:05 UTC, haqadn commented
I think this also breaks an e2e test since `IconTooltip` from RNA needs a click instead of a hover.

2023-11-08 08:57 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/react-components/score-context/index.tsx
> +const ScoreContext = () => {
This will be removed when refactoring MultiProgress, as it holds styles. I've added a todo in MultiProgress about this.

2023-11-08 08:57 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/react-components/image-size-analysis/other-group-context/index.tsx
> +const OtherGroupContext = () => {
This will be moved when refactoring MultiProgress, as it holds styles. I've added a todo in MultiProgress about this.

2023-11-08 08:59 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/react-components/score-context/index.tsx
> +const ScoreContext = () => {
I've also included a todo for this one as well.

2023-11-08 09:02 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/react-components/recommendation-context/index.tsx
> +export const RecommendationContext = () => {
This makes sense - removed!

2023-11-08 09:12 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/react-components/image-size-analysis/hero/index.tsx
> +				[ styles[ 'fade-in' ] ]: fadeProp,
Oh wow! I tried replicating the svelte way via JS and didn't think to use CSS. Thanks!

2023-11-08 10:12 UTC, haqadn requested changes
A couple of suggestions related to organization:

1. Instead of  `react-components/image-size-analysis/hero` we can have `react-components/sections/isa-hero`, which conforms to the flat structure.
2. `react-components/components/score-context` seems only useful for the future "score" section. In which case, it should live under something like `react-components/sections/score/context-tooltip.tsx`.

 
My thoughts regarding sections and components are: 
sections = Single use parts of UI
components = Generic UI elements which can be used by multiple sections
pages = What we mount as a route in navigation

What do you think?

2023-11-08 11:08 UTC, dilirity commented
@haqadn I've addressed the suggestions - thank you for those. I'll leave my comments about the structure in the P2, so we have the conversation in one place.

2023-11-09 05:52 UTC, haqadn approved these changes
:shipit:

2023-11-09 11:13 UTC, merged