Update/vaultpress backup card purchased state
Automattic/jetpack pull request #33927
Opened 2023-11-01 20:22 UTC by CodeyGuyDylan

## Proposed changes:

* Add most recent undoable activity log item to purchased state of VaultPress backup card
* Add undo button
* Add ability to add additional actions to the My Jetpack cards (such as the Undo action) in a dropdown
* Show when activity was last detected

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

P2: p1HpG7-pn9-p2

## Does this pull request change what data or activity we track or use?

Yes, we will be tracking when users click the Undo button and will track the Undo ID within that event

## Testing instructions:

TBD

2023-11-03 15:00 UTC, eeeeeevon2023 commented
<img width="397" alt="Screenshot 2023-11-03 at 9 55 36 AM" src="https://github.com/Automattic/jetpack/assets/128182954/b5c3c2cf-57a7-416b-b9af-231cfeaada4c">

After chatting with @CodeyGuyDylan, we are going to roll with the Gridicons for now because they are a 1 to 1 with the associated icons in the activity log. I will spin up a new project to update them in both places (AL and on the My Jetpack cards) the dev time to change out the icons is prohibitive to getting the MVP out fast.

2023-11-03 15:12 UTC, eeeeeevon2023 commented
Follow up project for design is here https://github.com/orgs/Automattic/projects/702/views/8?pane=issue&itemId=43575113

2023-11-03 15:42 UTC, elliottprogrammer requested changes
Very nice work @CodeyGuyDylan! Tested and everything works as described, except the undo link, and another tiny comment mentioned below in the inline code comments. Very quick, easy fixes I'm sure. 🙂

2023-11-03 15:42 UTC, elliottprogrammer commented on projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card/index.jsx
> +		href: getRedirectUrl( 'jetpack-backup-undo-cta', {
The Undo button is not working for me, it takes me to a blank page. I'm redirected to: `https://cloud.jetpack.com/backup/restore/1699022177.5095`. It's not working because this url is missing the `:site` part. It should be: `https://cloud.jetpack.com/backup/:SITE/restore/1699022177.5095`

2023-11-03 15:42 UTC, elliottprogrammer commented on projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card/index.jsx
> +			undoBackupId,
I believe Tracks property names need to be snake case.  Calypso enforces it, shows a console warning and refuses to send the event. I'm not sure about Jetpack, I'm not seeing a console error, but looking through the codebase all the ones I see are snake_case.

```suggestion
			undo_backup_id: undoBackupId,
```

2023-11-03 19:44 UTC, elliottprogrammer approved these changes
Works great, code looks all good.
LGTM! 👍

2023-11-03 19:55 UTC, merged

2023-11-23 21:33 UTC, dhasilva commented
@CodeyGuyDylan I bisected my way to this PR. It appears to have introduced https://github.com/Automattic/jetpack/issues/34278