Make Contact Form single and multiple choice inputs accessible
Automattic/jetpack pull request #34147
Opened 2023-11-15 19:06 UTC by monsieur-z

Fixes https://github.com/Automattic/jetpack/issues/16685

## Proposed changes:
The _Single Choice_ and _Multiple Choice_ inputs in the _Contact Form_ package have inaccessible markup, as reported in the issue above. This PR does the following:
- It wraps the inputs in a `fieldset`
- It replaces the top `label` by a `legend`
- For each option, it associates the `input` and the `label` by specifying a `for` attribute on the latter

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Spin up a test site with this branch
- Create a new post: visit `/wp-admin/post-new.php`
- Add the _Contact Form_ block to the page
<img width="346" alt="Screenshot 2023-11-15 at 10 20 30 AM" src="https://github.com/Automattic/jetpack/assets/1620183/60e74081-ab82-4141-8771-1c16543defb0">

- Add a or transform the existing fields so that you have both a single choice and multiple choice inputs on the page
<img width="212" alt="Screenshot 2023-11-15 at 1 59 49 PM" src="https://github.com/Automattic/jetpack/assets/1620183/56332561-4970-4cf4-bac8-7cae831249db">

- Open the preview
- Check that the inputs work as expected, look like they do on trunk, and have the proper markup as highlighted above
<img width="685" alt="Screenshot 2023-11-15 at 2 02 15 PM" src="https://github.com/Automattic/jetpack/assets/1620183/fa5aed3f-c0ed-4d79-b23c-2f71dea39f73">

- Repeat the above for the `Outlined` style
<img width="328" alt="Screenshot 2023-11-15 at 2 03 42 PM" src="https://github.com/Automattic/jetpack/assets/1620183/c77d5204-595e-46ad-a61b-9e85166f6b9d">

_Note: it seems that the Animated style doesn't change anything for these 2 inputs except adding some odd padding. I've therefore made the Default and Animated styles similar._

2023-11-15 19:08 UTC, monsieur-z commented on projects/packages/forms/src/contact-form/class-contact-form-field.php
> +	public function render_legend_as_label( $type, $id, $legend, $required, $required_field_text, $extra_attrs = array() ) {
This was duplicated from `render_label` and updated to handle the `legend` tag.

2023-11-15 19:14 UTC, monsieur-z commented on projects/packages/forms/src/contact-form/class-contact-form-field.php
> +		if ( ! empty( $form_style ) && $form_style !== 'default' && ! in_array( $type, array( 'checkbox', 'checkbox-multiple', 'radio', 'consent' ), true ) ) {
I'm not sure why the label is duplicated at the end of the field in some cases. The order of elements should usually be handled in CSS.

I've removed both the single choice and multiple choice inputs from the check: the outline style is fully handled in CSS; the animated style doesn't seem to be implemented anyway; I can't see the Below style in the UI but I've never seen checkboxes or radio buttons with a label below them.

2023-11-15 19:16 UTC, monsieur-z commented on projects/packages/forms/src/contact-form/css/grunion.css
> -.contact-form .is-style-animated .grunion-field-radio-wrap .grunion-radio-options {
The _Animated_ style only add some odd padding at the moment. Let's remove it altogether for now and rework the style later on if needed.

2023-11-15 19:17 UTC, monsieur-z commented on projects/packages/forms/src/contact-form/css/grunion.css
> +	content: "\2713";
I encountered an encoding issue locally. This should be safer.

2023-11-17 05:19 UTC, kraftbj requested changes, later dismissed
I didn't look into it, but the changes here are causing the unit tests to fail.

2023-11-17 18:46 UTC, monsieur-z commented on projects/packages/forms/tests/php/contact-form/test-class.contact-form.php
> -	public function assertCommonValidHtml( $wrapper_div, $attributes ) {
This function used to check both classes and the label. I moved the label check out of it (for checkboxes and radio buttons, the field "label" is a `legend`) and renamed the function.

2023-11-17 18:47 UTC, monsieur-z commented on projects/packages/forms/tests/php/contact-form/test-class.contact-form.php
> +			$n      = $labels->length;
Since the root `label` is now a `legend`, the number of `label`s in the field now matches the number of options.

2023-11-17 18:47 UTC, monsieur-z commented on projects/packages/forms/tests/php/contact-form/test-class.contact-form.php
> +				$item_label = $labels->item( $i );
Same comment as above.

2023-11-21 20:49 UTC, andrii-lysenko approved these changes
The changes look good to me and it works as described. I'm curious what was the idea behind the `Animated` style, but the current change seem reasonable to me.

2023-11-22 14:02 UTC, merged