Boost: Refactor performance-history into react
Automattic/jetpack pull request #34185
Opened 2023-11-17 12:33 UTC by haqadn

## Proposed changes:
* Fixed a width issue on the history graph where the graph wouldn't get smaller if the container shrunk
* Refactor performance history into react and get rid of History.svelte component
* Implemented ErrorNotice component in react which is a dependency of performance history. Fixed broken style while I'm at it.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pc9hqz-2jy-p2

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Check the performance history panel using boost premium and make sure it's working

2023-11-17 14:12 UTC, haqadn commented
Need to move styles inside the module

2023-11-20 13:07 UTC, dilirity requested changes
Great work! I've added a couple of suggestions and maybe a bug?

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/data-sync/Performance_History_Entry.php
> +		$result  = $request->execute();
It is possible for `execute` to return a `WP_Error` instance.

I got the locally while testing:

```
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Undefined property: WP_Error::$data in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 22
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Attempt to read property "_meta" on null in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 22
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Attempt to read property "start" on null in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 22
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Undefined property: WP_Error::$data in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 23
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Attempt to read property "_meta" on null in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 23
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Attempt to read property "end" on null in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 23
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Undefined property: WP_Error::$data in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 24
[20-Nov-2023 11:55:24 UTC] PHP Warning:  Attempt to read property "periods" on null in /usr/local/src/jetpack-monorepo/projects/plugins/boost/app/data-sync/Performance_History_Entry.php on line 24
[20-Nov-2023 11:55:24 UTC] PHP Fatal error:  Uncaught Error: Expected key 'periods' in associative array in /usr/local/src/jetpack-monorepo/projects/packages/wp-js-data-sync/src/schema/types/class-type-assoc-array.php:58
Stack trace:
#0 /usr/local/src/jetpack-monorepo/projects/packages/wp-js-data-sync/src/schema/class-schema.php(88): Automattic\Jetpack\WP_JS_Data_Sync\Schema\Types\Type_Assoc_Array->parse()
#1 /usr/local/src/jetpack-monorepo/projects/packages/wp-js-data-sync/src/class-data-sync-entry-adapter.php(61): Automattic\Jetpack\WP_JS_Data_Sync\Schema\Schema->parse()
#2 /usr/local/src/jetpack-monorepo/projects/packages/wp-js-data-sync/src/class-data-sync.php(124): Automattic\Jetpack\WP_JS_Data_Sync\Data_Sync_Entry_Adapter->get()
#3 /var/www/html/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\WP_JS_Data_Sync\Data_Sync->_print_options_script_tag()
#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin.php(259): do_action()
#7 {main}
  thrown in /usr/local/src/jetpack-monorepo/projects/packages/wp-js-data-sync/src/schema/types/class-type-assoc-array.php on line 58
```

It seems to happen because I'm on local and missing the proper connection, but I guess there could be other cases for end users which I'm not aware of:

```
object(WP_Error)#1741 (3) {
  ["errors"]=>
  array(1) {
    ["missing_token"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
  }
  ["error_data"]=>
  array(0) {
  }
  ["additional_data":protected]=>
  array(0) {
  }
}
```

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.module.scss
> +.performance-history {
I think we're currently using tabs for indentation. Or is this okay? 😅 

I'm not sure if we're following a rule or something.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.module.scss
> +@import "../../../css/main/variables.scss";
😮 Now I feel dumb for not trying to import mixins and variables... They work! Thank you!

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.module.scss
> +.errorNotice {
We haven't discussed class naming. Are we using camelCase throughout?

2023-11-20 13:07 UTC, dilirity commented on projects/js-packages/components/components/boost-score-graph/style.scss
> +    display: grid;
I see this file is using spaces for indentation already. But for other components, I see tabs used.

Not sure if we're going to be strict about this.

Should we use tabs?

2023-11-20 13:07 UTC, dilirity commented on projects/js-packages/components/components/boost-score-graph/uplot-line-chart.tsx
> +	}, [ width, lastDesktopScore, lastMobileScore, periods, range.endDate, range.startDate ] );
I haven't used `useMemo`, so I'm not sure about this, but doesn't it make sense to include the height here as well?

2023-11-20 13:07 UTC, dilirity commented on projects/js-packages/components/components/boost-score-graph/uplot-line-chart.tsx
> +		<div ref={ uplotContainer } className="boost-uplot-container">
I find it kind of weird having a class in this file (that has its own style file), but the style declaration is in another file (imported in index.tsx).

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> +		</DataSyncProvider>
Wohoo, react datasync!

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> +export const usePerformanceHistoryPanelQuery = () => {
I think we can remove the export, since this doesn't seem to be used anywhere else.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> +const performanceHistoryDataSchema = z.object( {
I'm wondering if it's a good idea to move anything store/DS related to its own place. Like it was before `lib/stores/store.ts`?

That way we keep this just for the main component logic.

But on the other hand, we have everything in one place 😅

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> +			<Panel className={ classNames( styles[ 'components-panel' ] ) }>
If its only one class, I don't thing we need `classNames`.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> +					className={ classNames( styles[ 'performance-history-body' ] ) }
Same as above - we're not joining any classes together.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/performance-history/stories/graph-component.stories.tsx
> +		console.log( 'upgrade' );
Forgotten debug? It looks lonely.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/stories/error-notice.stories.tsx
Nice work adding a story for this!

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.tsx
> +		<div className={ classNames( styles.errorNotice ) }>
I see you're using this where you add classes to. To me, it doesn't make sense to use it for just one class.

2023-11-20 13:07 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.tsx
> +import NoticeOutline from '../../svg/notice-outline';
You can use the nice aliases we have 🥳

2023-11-21 12:02 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.tsx
> +		<div className={ classNames( styles.errorNotice ) }>
I didn't realize I can just do: `className={ styles.errorNotice }`

2023-12-05 11:58 UTC, dilirity requested changes, later dismissed
PR needs an update. With the updated Data Sync now merged, the changes made in DataSyncHooks.ts conflict with trunk.

2023-12-05 11:59 UTC, dilirity commented
I also noticed a double GET request when opening the performance history section after it's been collapsed:

![CleanShot 2023-12-05 at 13 59 26](https://github.com/Automattic/jetpack/assets/11799079/b2810b0f-4ec8-4031-8f5d-fcdd9c12b747)

2023-12-05 12:57 UTC, dilirity commented
You are added as an admin for the site. It's https://unrealduck.wpcomstaging.com/wp-admin/

For some reason, this version is showing me stats for further back:
![image](https://github.com/Automattic/jetpack/assets/11799079/5b8d2951-df86-42c3-b4e3-8ad205e53766)


Trunk is showing 30 days back:
![CleanShot 2023-12-05 at 14 56 47](https://github.com/Automattic/jetpack/assets/11799079/b0aa4e5e-7b63-43cf-bbe6-c3881a36d8b4)

2023-12-06 12:14 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.module.scss
> +}
Why is this necessary? It will cause UI differences when this component is later reused.

2023-12-07 10:43 UTC, haqadn commented
After discussing with @dilirity in a dm I realize that the error-notice react component will change the styles for it's usage in module meta, i.e. `CrtiicalCssShowStopperError`. However, they are more complex usage with more svelte inside them and aren't ready to be replaced. So, we decided to merge the error-notice component as is, as it addresses the current usage. We will then update it in relevant PRs that touch the other usage.

2023-12-08 06:33 UTC, thingalon commented on projects/js-packages/react-data-sync-client/src/DataSync.ts
> +			const { nonce } = this.getWindowValue( this.key, z.any() );
I feel like `z.unknown()` would be a better choice for saying "I don't care about this, and won't use it".

2023-12-08 06:33 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/features/error-notice/error-notice.tsx
> +	vars?: Record< string, React.ReactElement< any, string | React.JSXElementConstructor< any > > >;
Would `Record< string, ReactNode >` work here?

2023-12-08 08:44 UTC, thingalon requested changes, later dismissed
Tested, and it works. Most of my comments are nitpicks, but I would like type-strong props on components - especially when there are a lot of them.

2023-12-08 08:44 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/features/performance-history/graph-component/graph-component.tsx
> +} ) => {
![image](https://github.com/Automattic/jetpack/assets/1369626/77c212ac-66a4-4c63-85f3-6f17c4d47647)

IMHO we should be using TypeScript typing on the properties of our components. That way when we use the components, our editor can warn us if we're mis-using them. 

A pattern I like is a `type Props = {}` at the top of the file which documents the props that are used in this component, which is then referenced in the function definition.

2023-12-08 08:44 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> + */
Does this need fixing before merging?

2023-12-11 06:24 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/features/performance-history/performance-history.tsx
> + */
No

2023-12-11 12:17 UTC, pyronaur approved these changes

2023-12-11 12:19 UTC, merged