Boost: Update Settings Page to react
Automattic/jetpack pull request #34714
Opened 2023-12-19 12:28 UTC by dilirity

## Proposed changes:

* Update Settings Page to react.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-2jy-p2

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Make sure that everything on the main Settings page works as expected.

2023-12-19 14:47 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/layout/settings-page/settings-page.tsx
> +	}, [] );
This is so cool! If I kinda want a custom hook now:

```javascript
const useSvelteStore = (svelteStore) => {
	const [ value, setValue ] = useState( svelteStore.get() );
	
	useEffect( () => {
		const unsubscribe = svelteStore.subscribe( value => {
			setValue( value );
		} );

		return () => {
			unsubscribe();
		};
	}, [] );

	return value;
}
```

2023-12-20 04:27 UTC, thingalon commented on projects/plugins/boost/app/assets/src/js/layout/settings-page/settings-page.tsx
> +	}, [] );
I mean if we want to rush to the end of the React migration, there is absolutely nothing magical about Svelte stores. I could write a non-svelte replacement for `writable` in a few lines, we could wrap them into React like so ^ and then we just have a React codebase to tidy up. Just sayin'.

2023-12-20 05:19 UTC, haqadn requested changes
The critical CSS states aren't updating as it generates. The UI get's stuck with the mounted state. I suspect it has something to do with embedding React in Svelte.

It might be worth it to ignore this issue and merge it while fixing it in my PR since it will be all React in there and we won't have to deal with the added complexity. Let me know if that's what you too think we should do.

2023-12-20 10:31 UTC, haqadn approved these changes
As discussed in DM, merging as is even though the critical CSS UI is currently broken. It will be fixed in #34731

2023-12-20 10:34 UTC, merged