Remove jetpack connection banners from non-Jetpack pages
Automattic/jetpack pull request #34768
Opened 2023-12-22 14:40 UTC by jboland88

Fixes #

## Proposed changes:

* This diff removes the Jetpack connection banners from wp-admin pages that are not Jetpack pages.
* The banner currently shows on the wp-admin dashboard and plugins page if Jetpack is not connected (see image below)
![Screenshot 2023-12-22 at 9 36 48 AM](https://github.com/Automattic/jetpack/assets/18016357/b955bf1f-1016-4d2f-bcd9-2e99d67cd9a9)

## Jetpack product discussion

pbNhbs-922-p2#comment-19163

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Apply this patch locally or using the Jetpack Beta plugin. If you are testing on your local install, you may need to reset the Jetpack Options
* DO NOT Connect Jetpack 
* Visit the wp-admin dashboard and plugins page and confirm that the connection banner (shown above) does not appear
* Make sure the full-screen connection component still shows at Jetpack > dashboard and that you can connect the site from here.

2023-12-22 21:04 UTC, elliottprogrammer requested changes
Tested, works great as described. Code looks all good.

However I do see some failing e2e tests checking for the connection banner(s) to be visible, that I believe we should remove/disable.

2023-12-22 22:40 UTC, jboland88 commented
> Tested, works great as described. Code looks all good.
> 
> However I do see some failing e2e tests checking for the connection banner(s) to be visible, that I believe we should remove/disable.

Thanks @elliottprogrammer ! 
I think I've got the pre-connection tests sorted, but some other tests are failing now 🙃 I'll see if I can get those sorted

2024-01-01 23:06 UTC, jboland88 commented
@elliottprogrammer - looks like the post-connect E2E test is failing, but I see this failing on other open, recent PRs, it does not appear to be related.

2024-01-02 01:13 UTC, elliottprogrammer commented
> @elliottprogrammer - looks like the post-connect E2E test is failing, but I see this failing on other open, recent PRs, it does not appear to be related.

Ahh ok, sounds good, thanks for looking into it! 👍

2024-01-02 01:15 UTC, elliottprogrammer approved these changes
LGTM! 👍

2024-01-02 14:04 UTC, merged