Boost: Add sync
Automattic/jetpack pull request #34825
Opened 2024-01-02 08:51 UTC by haqadn

## Proposed changes:
* Add jetpack sync to boost. This will allow us to determine which modules are active and what errors occurred and empower us to provide better support when things go wrong.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?
It enables Jetpack Sync with the default configuration.

## Testing instructions:
* Ensure that options are synced with cache site

2024-01-08 15:42 UTC, dilirity requested changes
Other than two small things, this is looking great! I had no idea adding Sync would look so simple.

2024-01-08 15:42 UTC, dilirity commented on projects/plugins/boost/app/data-sync/Modules_State_Entry.php
> +	public function get_module_option_name( $module_slug ) {
Why is this necessary?

2024-01-08 15:42 UTC, dilirity commented on projects/packages/boost-speed-score/src/class-speed-score-history.php
> +	public function get_option_name() {
Why is this necessary? I don't see it used in the PR.

2024-01-09 05:55 UTC, haqadn commented on projects/plugins/boost/app/data-sync/Modules_State_Entry.php
> +	public function get_module_option_name( $module_slug ) {
Good catch as always!

2024-01-10 12:02 UTC, dilirity approved these changes
Great!

I noticed you removed syncing modules status and that still works.

Any idea when a sync happens after you toggle an option on or off?
I've been trying to get the modules status in the debugger to change (and get the CSS state to update) after making changes on my JN, but it doesn't show up.

![image](https://github.com/Automattic/jetpack/assets/11799079/0ae37b1a-3575-4408-a4d8-26d997a48815)

![image](https://github.com/Automattic/jetpack/assets/11799079/bbca7b01-d58d-47b8-9686-7b76630e183b)

2024-01-11 07:37 UTC, haqadn commented
> Any idea when a sync happens after you toggle an option on or off? I've been trying to get the modules status in the debugger to change (and get the CSS state to update) after making changes on my JN, but it doesn't show up.

> The Sync Listener then listens for these action invocations (during any non-GET request, any request by a logged in user, and when running the Jetpack test suite), captures (serializes) the action and parameters, and adds it to the Sync Queue to be sent to the corresponding WordPress.com cache site by the Sync Sender.
- PCYsg-7Q6-p2

2024-01-11 07:37 UTC, merged

2024-01-12 00:12 UTC, thingalon commented
This has been merged? Have we pinged the right people to get our privacy info updated on jetpack.com?