Add/catch duplicated comment error
Automattic/jetpack pull request #34843
Opened 2024-01-03 21:58 UTC by lupus2k

Fixes https://github.com/Automattic/dotcom-forge/issues/5074

## Proposed changes:
We catch the duplicated comment error message and show it with a custom design (like we are doing when submitting a comment)
This also fixes that in certain cases, the back button is not returning to the comment form.

| Before | After |
| --- | --- |
| https://github.com/Automattic/jetpack/assets/402286/e8d46519-61e6-481d-bc33-5f1c570f096e | https://github.com/Automattic/jetpack/assets/402286/808f4f14-f75a-46dc-ad4c-28926a175b9f |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* You need to enable the `Let visitors use a WordPress.com or Facebook account to comment.` option on `wordpress.com/settings/discussion/:your-site`
* Go to a post
* Comment something
* After reloading, comment the same comment as before
* You should receive a Duplicated comment error with better look.
* The back button should return you to the comment form.
* Test it in Chrome, Firefox, Safari, Brave...

2024-01-08 12:02 UTC, crisbusquets commented
Hi @lupus2k, thanks for the ping!

How can I easily test this? I tried with a site, but I see the old implementation:

<img width="1355" alt="Screenshot 2024-01-08 at 13 02 21" src="https://github.com/Automattic/jetpack/assets/25607244/dad54a6a-42cb-45e3-9a7f-28adb5d8324b">

2024-01-08 15:04 UTC, lupus2k commented
> Hi @lupus2k, thanks for the ping!
> 
> How can I easily test this? I tried with a site, but I see the old implementation:
> 

Hey @crisbusquets, I updated the test site 1 and now it works: https://explorersatomicsub1.wpcomstaging.com/2023/12/26/boost-your-productivity-with-this-keyboard-shortcut-hack

2024-01-08 15:40 UTC, jeherve requested changes

2024-01-08 15:40 UTC, jeherve commented on projects/plugins/jetpack/modules/comments/comments.php
> +					echo esc_html__( 'Duplicate comment detected; it looks as though you&#8217;ve already said that!', 'jetpack' );
```suggestion
				esc_html_e( 'Duplicate comment detected; it looks as though you’ve already said that!', 'jetpack' );
```

2024-01-08 15:40 UTC, jeherve commented on projects/plugins/jetpack/modules/comments/comments.php
> +			<a href="javascript:history.go(-2)"><?php echo esc_html__( '&laquo; Back', 'jetpack' ); ?></a>
```suggestion
			<a href="javascript:history.go(-2)"><?php esc_html_e( '&laquo; Back', 'jetpack' ); ?></a>
```

2024-01-08 15:53 UTC, lupus2k commented on projects/plugins/jetpack/modules/comments/comments.php
> +			<a href="javascript:history.go(-2)"><?php echo esc_html__( '&laquo; Back', 'jetpack' ); ?></a>
Thanks for your suggestions @jeherve

2024-01-09 10:58 UTC, crisbusquets commented
> Hey @crisbusquets, I updated the test site 1 and now it works: https://explorersatomicsub1.wpcomstaging.com/2023/12/26/boost-your-productivity-with-this-keyboard-shortcut-hack

Thank you @lupus!
Is the `Comment sent` text new too?

We should use a smaller font size in both cases, as it doesn't match the UI.
Can we try with the theme's h3 but in regular, and using a color that matches the theme?

2024-01-09 11:16 UTC, Lupus commented
You probably meant to mention @lupus2k, @crisbusquets :)

2024-01-09 11:20 UTC, crisbusquets commented
> You probably meant to mention @lupus2k, @crisbusquets :)

Ouch, yes. Sorry @Lupus 😅

2024-01-09 11:24 UTC, jeherve requested changes, later dismissed
The display looks good, but the back button doesn't seem to work properly. See this screencast for an example:


https://github.com/Automattic/jetpack/assets/426388/443b8ab7-7fa0-4e66-963c-4f5082095006

2024-01-09 14:07 UTC, lupus2k commented
> Is the `Comment sent` text new too?
> 
> We should use a smaller font size in both cases, as it doesn't match the UI. Can we try with the theme's h3 but in regular, and using a color that matches the theme?

The comment sent is new, and only shows when the Subscription modal shows, but in this place, we have a `Submitting comment` message with the same style.
Should we change the styles for all of it? (it's using h1)

2024-01-09 14:08 UTC, lupus2k commented
> The display looks good, but the back button doesn't seem to work properly. See this screencast for an example:

Interesting, I tried to reproduce without error on Chrome and Firefox, which browser are you using?

2024-01-09 14:25 UTC, jeherve commented
This was in Firefox.

2024-01-09 23:48 UTC, lupus2k commented
> This was in Firefox.

I was able to reproduce it, so I updated the PR and now I'm unable to do it.
Can you check using our test site: https://explorersatomicsub1.wpcomstaging.com/2023/12/26/boost-your-productivity-with-this-keyboard-shortcut-hack/

2024-01-10 11:03 UTC, crisbusquets commented
> > This was in Firefox.
> 
> I was able to reproduce it, so I updated the PR and now I'm unable to do it. Can you check using our test site: https://explorersatomicsub1.wpcomstaging.com/2023/12/26/boost-your-productivity-with-this-keyboard-shortcut-hack/

It works for me now too

2024-01-10 11:04 UTC, crisbusquets commented
> The comment sent is new, and only shows when the Subscription modal shows, but in this place, we have a `Submitting comment` message with the same style.
> Should we change the styles for all of it? (it's using h1)

Yes, the same styles for all of it. I think this will make it look better, h1 is way to big for something that should be a relatively small alert-notice.

2024-01-10 12:42 UTC, lupus2k commented
> @jeherve: It works for me on that test site of yours, but I still experience issues with a fresh Jurassic Ninja site, unfortunately.

I'll check with a Jurassic Ninja site + Jetpack Beta plugin?

2024-01-10 12:52 UTC, jeherve commented
> I'll check with a Jurassic Ninja site + Jetpack Beta plugin?

Yup. That's probably the easiest way to test PRs in this repo, with the Jetpack Live Branches tampermonkey script:
https://github.com/Automattic/jetpack/tree/trunk/tools/jetpack-live-branches

2024-01-10 15:20 UTC, lupus2k commented
Hey @jeherve, I updated the PR, and it should work as expected on Jetpack sites & Atomic sites. I tested on Chrome, Safari, Firefox, Opera, and Brave

2024-01-10 16:21 UTC, jeherve approved these changes, later dismissed
It tests well for me now!

2024-01-10 19:59 UTC, lupus2k commented
Hey @crisbusquets, I just updated the PR using `h3`; here is a video with the three messages you can see:

https://github.com/Automattic/jetpack/assets/402286/94150861-4439-45d3-8a9c-7266f79c29a3

Let me know if this looks good to you; you can test it on the following sites with different themes:
- https://explorersatomicsub1.wpcomstaging.com/2023/12/26/boost-your-productivity-with-this-keyboard-shortcut-hack/
- https://explorersatomicsub2.wpcomstaging.com/2023/12/26/unveiling-the-future-a-comprehensive-review-of-the-quantumx-pro-vr-headset/
- https://explorersatomicsub3.wpcomstaging.com/2023/12/26/paradise-found-a-blissful-escape-to-emerald-isle/
- https://explorersatomicsub4.wpcomstaging.com/2023/12/26/5-minute-energizer-quick-workouts-for-busy-days/

2024-01-11 10:34 UTC, crisbusquets commented
> Hey @crisbusquets, I just updated the PR using `h3`; here is a video with the three messages you can see:

Hi @lupus2k !

This looks better, but we should also use the theme font-family and color. If we don't, the interface looks weird. For example, in the second screenshot, both `Deja un comentario` and `Duplicate comment detected; it looks as though you’ve already said that!` are h3, but they don't look the same:

<img width="803" alt="Screenshot 2024-01-11 at 11 29 18" src="https://github.com/Automattic/jetpack/assets/25607244/7f8f3d4e-6f56-4c6d-bac9-93cd1a0920ac">

<img width="680" alt="Screenshot 2024-01-11 at 11 29 56" src="https://github.com/Automattic/jetpack/assets/25607244/61c91256-7a71-4913-9e13-49fa362620f2">

Something like this would look better (I only updated the font-family and font-size, so they match):

<img width="698" alt="Screenshot 2024-01-11 at 11 34 09" src="https://github.com/Automattic/jetpack/assets/25607244/c1e143d5-0bfe-49e5-ba64-9646dadf83b2">


We should also underline the "Back" link, it doesn't look it's clickable.

2024-01-11 18:05 UTC, lupus2k commented
> This looks better, but we should also use the theme font-family and color.

Hey @crisbusquets, the problem here is the message is inside an iframe, so we can't get any of the theme data, since it's running from jetpack.wordpress.com 😞 
Any other suggestion to make it more generic style message besides the back button underline?

2024-01-12 08:36 UTC, candy02058912 submitted a review, later dismissed
Tested on:
✅ Chrome
✅ Firefox
✅ Safari (Can only test logged out comments 🤔 )
✅ Edge

2024-01-12 12:31 UTC, crisbusquets commented
> > This looks better, but we should also use the theme font-family and color.
> 
> Hey @crisbusquets, the problem here is the message is inside an iframe, so we can't get any of the theme data, since it's running from jetpack.wordpress.com 😞 Any other suggestion to make it more generic style message besides the back button underline?

Oh 😢 
Ok, so what about this approach?

<img width="715" alt="Screenshot 2024-01-12 at 13 28 19" src="https://github.com/Automattic/jetpack/assets/25607244/27277413-131d-4fb2-af74-a44be3be8e31">

- align text to left (easier to read)
- removed padding-top from h3
- the div that wraps it is now `vertical-align: top;` instead of middle

For the `Comment sent` message, I think we can align it to the center, because the text is shorter. If this exception adds complexity, let's align it to the left.

2024-01-15 18:40 UTC, lupus2k commented
Hey @crisbusquets, let me know if it looks good to you now, and I'll merge it! 😉

2024-01-16 08:40 UTC, crisbusquets commented
> Hey @crisbusquets, let me know if it looks good to you now, and I'll merge it! 😉

Hi @lupus2k !

There's one minor thing that I don't see: the underline in the "Back" word. Is that possible?

Other than that, the duplicated error message looks better now, thank you :)

2024-01-17 00:25 UTC, DustyReagan approved these changes
Testing well for Atomic in Firefox, Safari, and Chrome.

2024-01-17 00:25 UTC, merged