Launchpad: Add completion logic for the Verify Domain Email task
Automattic/jetpack pull request #35068
Opened 2024-01-16 14:08 UTC by valterlorran

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go
*

2024-01-16 21:24 UTC, markbiek commented
Testing on Simple:

After reverting the change to `wp-content/admin-plugins/domains/management.php`, I went back to Customer Home and refreshed and the `Verify the email address for your domains` was still incomplete.

<img width="710" alt="CleanShot 2024-01-16 at 16 23 49@2x" src="https://github.com/Automattic/jetpack/assets/917632/1994f057-ecab-42b4-9fde-d4d835b7e37f">

2024-01-16 22:04 UTC, sixhours commented
Testing on an Atomic site, I've confirmed I'm seeing the legacy task list layout come back in the API, but it doesn't contain the task:

<img width="792" alt="Screenshot 2024-01-16 at 4 06 12 PM" src="https://github.com/Automattic/jetpack/assets/2124984/74d6c3f8-b1d0-4ceb-8290-18bf0dac1f99">

I'm going to try this again tomorrow because I feel like I must be missing/messing up one of the steps. Man these are hard to test. :D

2024-01-17 15:10 UTC, valterlorran commented
Thanks, folks, for testing; I have fixed the code. Somehow, I lost one of my changes that prevented the task from showing.

2024-01-17 16:22 UTC, markbiek commented
This still isn't working for me on Simple. There's a screen recording in p1705508531199409/1705498573.659499-slack-C0Q664T29

2024-01-17 17:21 UTC, markbiek commented
Noting the conversation that @valterlorran , @sixhours , and I just had.

From my side, I had two test domains that still needed verification but _weren't_ associated with the site I was testing this PR on.

It seems like this code shows the "Verify the email address for your domains" task if _any_ domain _anywhere_ in your account requires verification, not just the domains for the current site.

And I think that explains why the task was never marked as complete for me.

2024-01-19 14:42 UTC, andres-blanco commented
It's working for me on Simple. Going to try it out on AT now

2024-01-19 15:31 UTC, andres-blanco requested changes
This is working fine, left a small nit to improve a conditional

2024-01-19 15:31 UTC, andres-blanco commented on projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php
> +	if ( ! isset( $wpcom_launchpad_config[ $option ] ) ) {
Probably worth rewriting this condition as `! is_array( $wpcom_launchpad_config ) || ! isset( $wpcom_launchpad_config[ $option ] )` as options can be set from anywhere

2024-01-19 16:29 UTC, markbiek commented
I was also able to get this working on Simple!

2024-01-19 17:13 UTC, andres-blanco approved these changes
LGTM!

2024-01-19 17:38 UTC, merged