Boost: Update dismissed alerts store
Automattic/jetpack pull request #35080
Opened 2024-01-17 05:01 UTC by haqadn

Fixes #33402

## Proposed changes:
* Use a combined `dismissed_alerts` store to handle score prompt dismissals.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
No

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Test if the previous state of speed score dismissals is kept in this version.
* Test that the dismissals work and PopOut is displayed without any issues.

You will have to rig the speed scores to test this. For that I usually manually [change this line](https://github.com/Automattic/jetpack/blob/d39cf216407f688b6111595e0e628c11e0819f8b/projects/packages/boost-speed-score/src/class-speed-score.php#L312) to something like:

```php
		$response = array(
			'status' => 'success',
			'scores' => [
				'current' => ['mobile' => 80, 'desktop' => 80],
				'noBoost' => ['mobile' => 100, 'desktop' => 100],
				'isStale' => false,
			]
		);
		return rest_ensure_response( $response );
```

2024-01-17 14:42 UTC, dilirity commented
I can't get the "score increased" popup to show. I only get the "score decreased" popup.

2024-01-17 15:27 UTC, dilirity requested changes
Awesome work on this!

One small change and I couldn't get the "score increased" popup to show. I only get the "score decreased" popup.

After that, it should be ready for merge!

2024-01-17 15:27 UTC, dilirity commented on projects/plugins/boost/compatibility/score-prompt.php
> +	$new_value = get_option( 'jetpack_boost_ds_dismissed_alerts' );
If there are no dismissed alerts when this runs, `get_option` should return `false`.

2024-01-17 15:27 UTC, dilirity commented on projects/plugins/boost/compatibility/score-prompt.php
> +$old_value = get_option( 'jetpack_boost_ds_dismissed_score_prompt', get_option( 'jb_show_score_prompt' ) );
I love this!

2024-01-17 15:27 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/speed-score/speed-score.tsx
> +			<PopOut scoreChange={ showScoreChangePopOut } />
Nice thinking moving the state to the popup itself!

2024-01-18 05:15 UTC, haqadn commented on projects/plugins/boost/compatibility/score-prompt.php
> +	$new_value = get_option( 'jetpack_boost_ds_dismissed_alerts' );
Addressed in a03afbb

2024-01-18 06:19 UTC, haqadn commented
> Awesome work on this!
> 
> One small change and I couldn't get the "score increased" popup to show. I only get the "score decreased" popup.
> 
> After that, it should be ready for merge!

It does show up for me. Try this plugin to mock speed scores and make sure you have not previously disabled the alert.

[e2e-mock-speed-score-api.zip](https://github.com/Automattic/jetpack/files/13972789/e2e-mock-speed-score-api.zip)

2024-01-18 09:52 UTC, dilirity approved these changes
Thanks for the plugin! I got it to show.

Thanks to the plugin I discovered a bug that isn't caused by this PR. Let's merge this, and we'll address the bug in another PR.

Here's the ticket for the bug - https://github.com/Automattic/jetpack/issues/35102

2024-01-18 10:12 UTC, merged