Firewall Settings: Add Protect Flows
Automattic/jetpack pull request #35185
Opened 2024-01-23 01:02 UTC by nateweller

The purpose of this PR is to introduce Jetpack Protect as the primary method of activating and managing the Jetpack Firewall.

## Proposed changes:

* Display an "activate" prompt for users who have neither the WAF nor Jetpack Protect activated. This leads them through the My Jetpack install/interstitial flow and lands on the firewall settings screen.
* Display a link to the Jetpack Protect firewall settings screen for users who have Jetpack Protect installed.
* (Unchanged) Display existing settings controls for users that already have the Firewall activated on a Jetpack-only site.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p2-peb6dq-20F

## Does this pull request change what data or activity we track or use?

Yes – adds "protect" as a possible event feature value to the existing upgrade banner tracking.

## Testing instructions:

* TBD

## Screenshots

Firewall disabled, Protect uninstalled:

<img width="919" alt="Screenshot 2024-01-22 at 5 14 00 PM" src="https://github.com/Automattic/jetpack/assets/10933065/2c492388-3374-4d52-a1c4-f69713e6bb69">

Protect installed, any Firewall state:
<img width="922" alt="Screenshot 2024-01-22 at 5 16 38 PM" src="https://github.com/Automattic/jetpack/assets/10933065/f6f7d4ab-97e3-4bdf-86de-f734b5ce64da">

2024-02-02 02:34 UTC, miguelxpn commented
I love the branch name!

2024-02-06 21:01 UTC, nateweller commented on projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js
> +			);
Added alternate plugin names here so the feature check works in development. 
- In typical production sites, the plugin will be `jetpack-protect/jetpack-protect.php`.
- In the monorepo docker setup, the plugin will be `protect/jetpack-protect.php` due to the "protect" plugin directory symlink.
- Protect may be active via Jetpack Beta, which is `jetpack-protect-dev/jetpack-protect.php`

2024-02-06 21:01 UTC, nateweller commented on projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
> -							clickHandler={ clickHandler }
(Delete unused prop)

2024-02-07 04:40 UTC, miguelxpn submitted a review, later dismissed

2024-03-05 18:21 UTC, nateweller commented
Updated with a new custom redirect approach after some changes were made in My Jetpack before I could get this merged. Could use another top-to-bottom review, apologies! Thank you!

2024-03-06 19:33 UTC, dkmyta requested changes
If the WAF isn’t yet an active module (on initial activation of Jetpack on a clean install for example), we allow users to use legacy settings, do we want this or to only allow users who have previously activated the WAF module to have access?
<img width="1039" alt="Screenshot 2024-03-06 at 10 42 43 AM" src="https://github.com/Automattic/jetpack/assets/43220201/0619752c-e0a1-4e67-8461-e0b9f8816913">

I was not redirected back to the settings as expected after following the activation flow as described in step 3 of the testing instructions. Instead after connecting I was redirected to `/wp-admin/admin.php?page=jetpack#/dashboard`. 

After returning to the settings page, and clicking `Activate` from the Firewall section, I was routed to `#/add-firewall` but it was just a blank page with the following console warnings/errors:
```
Warning: Failed prop type: The prop `isFetching` is marked as required in `ProductDetailTable`, but its value is `undefined

Uncaught TypeError: setProduct is not a function
```

As an extra note, I think we should also have someone more familiar with the My Jetpack package give this a quick look after we approve - I see a review from Agora was requested but I am not sure they are responsible for this anymore.

2024-03-06 19:33 UTC, dkmyta commented on projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
> +import { useProduct } from '../../hooks/use-product';
Looks like the import doesn't exist and is defined previously, I believe we can remove this and just default to using the original `useProduct` import? This should resolve the build and ESLint errors in the PR checks.

2024-05-22 06:17 UTC, nateweller commented
Ready for another review! PR description updated. The notes:

* New approach to accomplish a custom redirect for firewall-centric Protect activation flows, adding a child class that extends the `Protect` product with a custom return value for `get_manage_url()`.
* Includes an adjustment to the connection/checkout/redirect handling in My Jetpack to fix the redirect URL.

2024-05-31 20:10 UTC, nateweller commented
Another update, some feedback on extending product classes: p1717089889789209-slack-CDLH4C1UZ

May need a different, different approach. I wanted to define this on the server side to keep things clean, but if we can't do that with the existing patterns then I start to lean towards coding in some sort of exception or override on the client side, specific to the Protect interstitial. Perhaps a `?feature=firewall` query parameter or similar that overrides the redirect URL of the Protect product when present.

2024-08-20 01:27 UTC, closed without merging