Ensure block comments are always sanitized on save and render
Automattic/jetpack pull request #35246
Opened 2024-01-25 12:09 UTC by heavyweight

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-01-25 15:37 UTC, alshakero commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/class-verbum-comments.php
> +		add_filter( 'comment_text', array( $this, 'render_verbum_blocks' ) );
How are we ensuring this will only apply to Verbum comments? I know we exclude P2 and forums, but this filter will run in other places as well.

2024-01-26 07:09 UTC, heavyweight commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/class-verbum-comments.php
> +		add_filter( 'comment_text', array( $this, 'render_verbum_blocks' ) );
The filter to remove blocks in the Gutenberg class never executed even if it did, the payload can be posted via our text editor and later rendered in calypso. I agree it's safer to target the filtering, will give it a go now to get to the middle ground

2024-01-26 11:55 UTC, alshakero commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/class-verbum-comments.php
> +		add_filter( 'comment_text', array( $this, 'render_verbum_blocks' ) );
I don't mean this way, I mean this filter will run in unexpected places outside our scope. Check this example below, the Tumblr tipping field is a comment filed on wp.com simple site, this filter may run against it even though we never test that.

p1698351357360729-slack-C04NARZL78D

2024-01-26 14:05 UTC, alshakero requested changes, later dismissed
it seems we're losing the Blockquote body for some reason, only the body is remaining.

2024-01-30 06:14 UTC, agrullon95 commented
Followed the testing instructions and used the block example provided (```<!-- wp:paragraph {} --><!-- wp:latest-posts --><!-- /wp:paragraph -->```). I was able to verify that it was filtered out in the posted comment when GB was enabled. I also tested some allowed blocks such a blockquote (nested block quotes as well) , embed, and lists to verify they're not filtered out.

We can discuss scoping these changes to Verbum on slack (https://github.com/Automattic/jetpack/pull/35246#discussion_r1467570738).

2024-02-07 22:19 UTC, agrullon95 submitted a review, later dismissed

2024-02-08 10:54 UTC, escapemanuele approved these changes
Tested on both Atomic and simple and it's working great 👍

2024-02-08 11:05 UTC, merged

2026-11-11 17:05 UTC, dmsnell reviewed
@heavyweight not sure who to ping, but there is some decent follow-up available here that would be nice to do.

2026-11-11 17:05 UTC, dmsnell commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/assets/class-verbum-block-utils.php
> +		return ltrim( $output );
with the introduction of `WP_Block_Processor` in WordPress 6.9.0, this function would be best rewritten to avoid the full parse and allocation.

```php
$processor = new WP_Block_Processor( $content );
$output    = '';
$at        = 0;

while ( $processor->next_block() ) {
	if ( $processor->opens_block( $allowed_blocks ) ) {
		continue;
	}

	$depth   = $processor->get_depth();
	$here    = $processor->get_span();
	$output .= substr( $content, $at, $here->start - $at );

	if ( WP_Block_Processor::VOID === $processor->get_delimiter_type() ) {
		$at = $here->start + $here->length;
		continue;
	}

	while ( $processor->next_token() && $depth > $processor->get_depth() ) {
		continue;
	}
	
	$here = $processor->get_span();
	$at   = $here->start + $here->length;
}

if ( 0 === $at ) {
	return $content;
}

if ( $at < strlen( $content ) ) {
	$output .= substr( $content, $at );
}

return $output;
```

for the normative cases where only allowed blocks are present, this will essentially perform no allocation and it will return the reference-identical input. for cases where blocks are pruned, it will avoid all of the costly JSON parsing and memory copying to fill the parse tree.

2026-11-11 17:05 UTC, dmsnell commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/assets/class-verbum-block-utils.php
> +		$content = wp_unslash( $content );
why is the content unslashed here but then never re-slashed?
it would be more ideal to require that callers unslash appropriately to avoid the confusion, then this function need not unslash anything.

2026-11-11 17:05 UTC, dmsnell commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/assets/class-verbum-block-utils.php
> +		}
with the `WP_Block_Processor` approach below, this condition isn’t necessary or helpful

2026-11-11 17:05 UTC, dmsnell commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/assets/class-verbum-block-utils.php
> +			$comment_content .= $block->render();
there is a minor memory advantage to seeing `$block = null` after this line. it frees memory allocated during `render()`, which can be high.

See Core-63588

2026-11-11 17:28 UTC, heavyweight commented on projects/packages/jetpack-mu-wpcom/src/features/verbum-comments/assets/class-verbum-block-utils.php
> +			$comment_content .= $block->render();
@arcangelini could you take a look?