Jetpack Boost: Abortable DataSync
Automattic/jetpack pull request #35253
Opened 2024-01-25 15:17 UTC by pyronaur

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-01-25 15:27 UTC, dilirity requested changes
This works great! I wasn't able to break it.

A note and the linter ain't happy.

2024-01-25 15:27 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/lib/utils/debounce.ts
> -import { useDebouncedCallback } from 'use-debounce';
`use-debounce` package can be removed.

2024-01-25 16:17 UTC, dilirity approved these changes
:shipit:

2024-01-25 16:22 UTC, merged

2024-01-29 04:23 UTC, thingalon commented
Cherry-picked to 3.0.0 in 2739aec3b1.