Initial
Automattic/jetpack pull request #35277
Opened 2024-01-26 13:42 UTC by alshakero

This is the main PR towards SSO improvements. It's a place to merge PRs into, please do not push anything to it that is not updating it against trunk.

## Proposed changes:
Includes the following PRs:
- https://github.com/Automattic/jetpack/pull/35158
- https://github.com/Automattic/jetpack/pull/35272

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-01-30 07:36 UTC, jeherve commented
Is there a p2 post where I could find out more about this project? I'm curious what y'all have in mind for this feature :)

2024-01-31 22:38 UTC, agrullon95 commented
> Is there a p2 post where I could find out more about this project? I'm curious what y'all have in mind for this feature :)

@jeherve - You can read more about this project here: 
- Design/Kick-off thread: pdDR7T-1jU-p2
- Project proposal / feedback requested thread: pdDR7T-1ja-p2

2024-02-01 08:27 UTC, jeherve commented
Thank you!

2024-02-06 10:30 UTC, heavyweight commented on projects/plugins/jetpack/modules/sso.php
> +				'New users will receive an invite to join WordPress.com, so they can log in securely using <a class="jetpack-sso-admin-create-user-invite-message-link-sso" rel="noopener noreferrer" target="_blan
Minor whine, but we could improve this to return support documentation based on the user's locale. For example https://jetpack.com/es/support/sso/ for spanish users

2024-02-06 10:34 UTC, heavyweight requested changes, later dismissed
I'm unable to edit my profile.
wp-admin/profile.php

<img width="1913" alt="Screenshot 2024-02-06 at 11 33 26" src="https://github.com/Automattic/jetpack/assets/7000684/46cb359b-a173-493d-b4c8-c000627fed00">

<img width="1489" alt="Screenshot 2024-02-06 at 11 35 27" src="https://github.com/Automattic/jetpack/assets/7000684/936685da-b1f1-4bb3-893d-84beae316b6d">
Probably related

@agrullon95 : I'm working on this issue.

2024-02-06 10:36 UTC, heavyweight commented
> I'm unable to edit my profile. wp-admin/profile.php
> 
> <img alt="Screenshot 2024-02-06 at 11 33 26" width="1913" src="https://private-user-images.githubusercontent.com/7000684/302590873-46cb359b-a173-493d-b4c8-c000627fed00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTU5NzAsIm5iZiI6MTcwNzIxNTY3MCwicGF0aCI6Ii83MDAwNjg0LzMwMjU5MDg3My00NmNiMzU5Yi1hMTczLTQ5M2QtYjRjOC1jMDAwNjI3ZmVkMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTAzNDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGEzNjEwZmI0YmRiYTlmZTE5MmI4ZDk3YzEyZGQwYmQ4OWYwMDBkNjkwYWI2MDQyNDAzNGZiYWJkNGJkMDdlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bAEABmMqY3MgiQ6YH5HwsZyZicr8CUKXBFsQV_zrG8A">

<img width="1489" alt="Screenshot 2024-02-06 at 11 35 27" src="https://github.com/Automattic/jetpack/assets/7000684/936685da-b1f1-4bb3-893d-84beae316b6d">
Probably related

2024-02-06 10:57 UTC, heavyweight commented
https://github.com/Automattic/jetpack/assets/7000684/502a8544-cd62-4c20-ad01-123207c100b6

Created a new admin, visited the invitation link, and created my wp.com account. After that, I got redirected to the admin ui where I had that weird state as in the video. After logging in with wp.com again it got fixed.

2024-02-06 11:04 UTC, heavyweight commented
> Screen.Recording.2024-02-06.at.11.53.11.mov 
> Created a new admin, visited the invitation link, and created my wp.com account. After that, I got redirected to the admin ui where I had that weird state as in the video. After logging in with wp.com again it got fixed.

To reproduce you will probably need to enable the classic admin setting in https://wpcalypso.wordpress.com/
<img width="680" alt="Screenshot 2024-02-06 at 11 59 00" src="https://github.com/Automattic/jetpack/assets/7000684/7e9f4aa6-d1e2-4c4e-abd6-2ba1055be36e">

2024-02-06 11:20 UTC, heavyweight commented
<img width="1629" alt="Screenshot 2024-02-06 at 12 05 05" src="https://github.com/Automattic/jetpack/assets/7000684/2d8121ab-3e16-4e3d-bf5e-344576362e35">
After creation the admin should manually send the invite? For the first admin user I created I think it was sent out automatically, but after that I only got the non-wpcom email and the functionality to invite the user by clicking the button

2024-02-06 11:22 UTC, heavyweight commented
> <img alt="Screenshot 2024-02-06 at 12 05 05" width="1629" src="https://private-user-images.githubusercontent.com/7000684/302600978-2d8121ab-3e16-4e3d-bf5e-344576362e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTg3MTQsIm5iZiI6MTcwNzIxODQxNCwicGF0aCI6Ii83MDAwNjg0LzMwMjYwMDk3OC0yZDgxMjFhYi0zZTE2LTRlM2QtYmY1ZS0zNDQ1NzYzNjJlMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTEyMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY3MzhmZDRkODFiMWQ4YThiNTI4MjlmMWFkMTM4OWFmNjdhZmVlMGNlYzlhMDk4YTdiYmE4Zjk4Njg4ZjEzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l51FCer8ODhlroZeVYIOOJo279NvAMMs0d1Ls-vTKgo"> After creation the admin should manually send the invite? For the first admin user I created I think it was sent out automatically, but after that I only got the non-wpcom email and the functionality to invite the user by clicking the button

Might be related
<img width="1488" alt="Screenshot 2024-02-06 at 12 21 51" src="https://github.com/Automattic/jetpack/assets/7000684/0700f954-5ed3-4853-85fe-4708258107ae">

2024-02-06 11:47 UTC, heavyweight commented
When we have a user with pending invite, if we delete him we should also "invalidate" the invite. Sure he could create a wp.com account but after he does that he should not be the admin on our site.
Imagine if I enter the email of my ex by mistake. I will panic for sure and delete the user. But after she creates her wpcom account she can come and take over my site 😈.

2024-02-07 07:40 UTC, heavyweight commented
I found where the notice came from.
In `send_wpcom_mail_user_invite` we try to find the user's locale:
`$locale  = get_user_locale( $user->ID )`
But for new users, this is the object shape: 
```
array(
   'user_login' => 'kokopapata8',
   'role' => 'administrator',
   'user_email' => 'k.papazov+8@gmail.com',
   'user_url' => '',
   'first_name' => 'koko',
   'last_name' => 'papata',
   'locale' => '',
   'comment_shortcuts' => '',
   'use_ssl' => 0,
   'user_pass' => 'H4X0R',
)
```

2024-02-07 12:03 UTC, heavyweight commented
When creating a new user if there is an error, the values of the language selector and custom message will be lost.
You can reproduce this by submitting with an existing email or username and having all the form values filled.

2024-02-07 14:25 UTC, heavyweight commented
https://github.com/Automattic/jetpack/assets/7000684/4464be44-d018-40dd-8d0e-de45cdc2ab87

The bottom two users were created before. I can invite, but can't revoke the invite. The first user is a user I created recently and it is working for him as expected

2024-02-07 14:32 UTC, heavyweight commented
Tested visiting the invite link for a user that was deleted and thus with revoked permission.
<img width="1728" alt="Screenshot 2024-02-07 at 15 31 24" src="https://github.com/Automattic/jetpack/assets/7000684/8df68203-c31b-4a61-8d37-dd077682723b">
We can probably make some improvements here, but I don't see this as a blocker

2024-02-07 14:36 UTC, heavyweight commented on projects/plugins/jetpack/modules/sso.php
> +		wp_die();
We probably don't need this since it will be never reached

2024-02-07 14:40 UTC, escapemanuele commented
> Tested visiting the invite link for a user that was deleted and thus with revoked permission.

Yes, I wouldn't make this blocking for this PR. Might be worth to address in the future as you said.

2024-02-07 21:39 UTC, heavyweight commented
Noticed some inconsistencies with the locale settings.
What happens now is that the site language value is read and used when sending out the emails.
I changed the site language from `en` to `es` and created a user. The wp email was in `es` but the wpcom one was in `en`.
<img width="1398" alt="Screenshot 2024-02-07 at 22 29 22" src="https://github.com/Automattic/jetpack/assets/7000684/905c0bc4-d700-472c-bec3-c27b7f986107">
Then I created a user with `en` language selected
<img width="719" alt="Screenshot 2024-02-07 at 22 28 34" src="https://github.com/Automattic/jetpack/assets/7000684/72ddb164-ef4d-43bd-a14b-e22eb3759568">
And got this
<img width="1398" alt="Screenshot 2024-02-07 at 22 29 22" src="https://github.com/Automattic/jetpack/assets/7000684/e1d5cfd8-84db-4e4a-ac16-e164634a0a84">
Seem that our first wpcom email was possibly reading stale cache value.
It also seems the user locale setting is ignored for wp and wcom emails.

2024-02-16 09:59 UTC, heavyweight approved these changes
Re-tested and didn't find any issues

2024-02-16 11:14 UTC, renancarvalho approved these changes
Tested and did not locate any issues as well, I think we are good to go! 👍

2024-02-16 12:41 UTC, merged