SSO: Implement users table user invite revoking
Automattic/jetpack pull request #35272
Opened 2024-01-26 03:43 UTC by agrullon95

Fixes #

## Proposed changes:

* These changes build on the users table improvements from: https://github.com/Automattic/jetpack/pull/35158.
* The logic to revoke user invites has been added to the users table row actions for each user that has a 'pending invite'.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

On an Atomic, JN, or whatever non-simple site, install Jetpack.
Make sure SSO is on, it should be on by default.
Go to the users table (`wp-admin/users/php`).
It should have the status of the user's connection "Connected", "Invite", or "Pending invite".
Clicking "Invite" should invite the user and change their status to "Pending invite".
If you haven't already, add and invite a few new users to your site.
While in this state, change the nonce in the URL to something incorrect, no notices should render.
Click back to get the correct nonce back.
Change the jetpack-sso-invite-user query param value to something that is not success or failed. No notice should render.
Inspect a non-invited user's "Invite" button and change the user_id hidden field to something incorrect, invite the user, you should get a nice error.

2024-01-26 13:41 UTC, alshakero requested changes
Love it. Really clean.

2024-01-26 13:41 UTC, alshakero commented on projects/plugins/jetpack/modules/sso.php
> +			}
This should be moved up before checking if the invite exists.

2024-01-26 13:41 UTC, alshakero commented on projects/plugins/jetpack/modules/sso.php
> +						'jetpack-sso-revoke-user-invite-error' => 'invalid-invite-revocation',
Missing nonce.

2024-01-26 13:41 UTC, alshakero commented on projects/plugins/jetpack/modules/sso.php
> +		if ( ! current_user_can( 'create_users' ) ) {
The permission should be `promote_users` I think.

2024-01-26 13:41 UTC, alshakero commented on projects/plugins/jetpack/modules/sso.php
> +		if ( current_user_can( 'create_users' ) && $has_pending_invite ) {
Should probably be `promote_users`. Creating an invitation only requires that anyways.

2024-01-26 15:01 UTC, alshakero commented on projects/plugins/jetpack/modules/sso.php
> +					return;
Can go.

2024-01-26 15:22 UTC, agrullon95 commented on projects/plugins/jetpack/modules/sso.php
> +		if ( current_user_can( 'create_users' ) && $has_pending_invite ) {
Updated to `promote_users`. Aligns better with usage in endpoint: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Svaivgr%2Svaivgr%2Qhfref.cuc%3Se%3Q94217699%2325-og

2024-01-26 15:23 UTC, agrullon95 commented on projects/plugins/jetpack/modules/sso.php
> +					return;
Removed this default case.

2024-01-26 15:24 UTC, agrullon95 commented on projects/plugins/jetpack/modules/sso.php
> +						'jetpack-sso-revoke-user-invite-error' => 'invalid-invite-revocation',
Added missing nonce.

2024-01-26 15:43 UTC, crisbusquets commented
I'll check this now, @agrullon95!

2024-03-25 10:12 UTC, escapemanuele commented
Is it ok to close this @agrullon95 ?

2024-03-25 14:08 UTC, agrullon95 commented
> Is it ok to close this @agrullon95 ?

@escapemanuele - Yes, im closing this now.

2024-03-25 14:08 UTC, closed without merging