Boost: Fix initial score
Automattic/jetpack pull request #35327
Opened 2024-01-30 09:25 UTC by haqadn

## Proposed changes:
On a fresh install like every other time, boost shows two scores (with and without boost). But, both scores are computed for the same state of the site, with no modules being in effect. This comparison is confusing. So, this PR changes the initial score measurement to only return a single score with no `no-boost` score to avoid comparison.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None

## Does this pull request change what data or activity we track or use?
None

## Testing instructions:
* Setup boost on a new site
* Make sure there is no `no-boost` score on initial load
* Make sure there is a `no-boost` score present if you dispatch a speed score request after enabling the modules.

2024-02-01 05:13 UTC, thingalon requested changes
Is it worth updating `maybe_dispatch_no_boost_score_request` so it only dispatches the request if any performance modules are enabled?

2024-02-01 05:13 UTC, thingalon commented on projects/packages/boost-speed-score/src/class-speed-score-request.php
> +	public function get_active_modules() {
Can we rename this to `get_active_performance_modules`, given it doesn't just return the active modules any more?

2024-02-12 07:08 UTC, haqadn commented
> Is it worth updating `maybe_dispatch_no_boost_score_request` so it only dispatches the request if any performance modules are enabled?

I don't think it is worth it. We ultimately will need to request this no-boost score when they do enable a module and as we store them differently based on URL. Things may change between when the request was dispatched and when the scores are calculated, so we will need this module check before returning the results to UI anyway.

2024-02-13 06:00 UTC, thingalon approved these changes

2024-02-13 06:01 UTC, merged