Jetpack Sync: Avoid detecting invalid image size
Automattic/jetpack pull request #35532
Opened 2024-02-08 04:48 UTC by trakos

Fixes #

## Proposed changes:

* Ignore image size inferred from media URL if it's longer than 5 characters.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

panfyZ-3dY-p2#comment-8279

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

Run the updated unit tests

```
jetpack docker phpunit -- --filter=WP_Test_Jetpack_PostImages
```

2024-02-08 09:32 UTC, robfelty requested changes
Thanks for fixing Piotr. This looks like a good improvement to me. Thanks for adding tests as well. I think the second test needs a small fix. Other than that, looks good.

2024-02-08 09:32 UTC, robfelty commented on projects/plugins/jetpack/tests/php/media/test-class.jetpack-post-images.php
> +		$s = "<img src='img-851958915511220-220.jpg' />";
I think the second `-` should be an x
```
$s = "<img src='img-851958915511220x220.jpg' />";
```

2024-02-08 15:00 UTC, trakos commented on projects/plugins/jetpack/tests/php/media/test-class.jetpack-post-images.php
> +		$s = "<img src='img-851958915511220-220.jpg' />";
You're right, thanks for catching that! I've updated the test.

2024-02-09 16:58 UTC, robfelty approved these changes
Looks great! Thanks for fixing the test.

2024-02-09 17:01 UTC, merged