Add support for WP Super Cache and Boost Cache
Automattic/jetpack pull request #35598
Opened 2024-02-12 13:07 UTC by millerf

Fixes https://github.com/Automattic/gold/issues/322

## Proposed changes:

* Add support for WP Super Cache and boost Cache
  * Do not cache page when Memberships token is there ( or subscriber is "authenticated")
  * Add token to cache keys to prevent serving the cache (public page) when Memberships token is there.

### Other information:
 - The check for is_auth() doubles on WPSC cache keys as it also checkes if the user if properly authenticated on WPCOM
 - It all boils down to use WPSO to:
   - only cache public page when user is not authenticated
   - only serve the cache when user is not authenticated / Memberships token is not available
     
## Slack discussion

p1707741384893309/1707737397.873219-slack-C016BBAFHHS

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Spin a new Jurassic Ninja instance with the link below  
* Add a plan and a paid-subscriber-only or subscriber-only page
* Add WPSC and Boost cache plugin
* Access the public page
* Subscribe 
* Access the same page
-> You should see the paywalled content (public content is not served)
* Open an incognito page
-> You should see the public content (paid content is not cached and served)

2024-02-12 13:37 UTC, donnchawp commented on projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php
> +		define( 'DONOTCACHEPAGE', true );
Just on the off chance that another plugin has defined that constant already, it might be better to put an is_defined() check there too.

2024-02-12 13:40 UTC, donnchawp requested changes
I haven't tested this, but the code looks ok apart from adding a defined() check on the DONOTCACHEPAGE constant.

2024-02-12 13:41 UTC, millerf commented on projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php
> +		define( 'DONOTCACHEPAGE', true );
Good one. Thanks!

2024-02-12 14:01 UTC, millerf commented
> I haven't tested this

I'll let @Automattic/zap test it, as they previously [had a PR](https://github.com/Automattic/jetpack/pull/35506) and must already have a testbed.

2024-02-12 14:17 UTC, donnchawp approved these changes
Looks good to me!

2024-02-12 20:12 UTC, n3f commented
@millerf I also haven't tested, but it appears that this wouldn't solve the issue @katiebethbrown is seeing (that site doesn't even have any paid content so there is no memberships cookie ever involved -- which makes me think it's a zap or apex issue -- but I wanted to point that out).

2024-02-13 11:47 UTC, millerf commented
> @millerf I also haven't tested, but it appears that this wouldn't solve the issue @katiebethbrown is seeing (that site doesn't even have any paid content so there is no memberships cookie ever involved -- which makes me think it's a zap or apex issue -- but I wanted to point that out).

@n3f  Even subscribers-only posts use the token...

But I referenced that issue in case they wanted to use some cache on other projects. But I guess batcache (nananannanana) is enough..

2024-02-14 20:38 UTC, n3f commented
Can't install WP Super cache.  I assume this is because it's already running?

![image](https://github.com/Automattic/jetpack/assets/6354169/ed542337-6c50-447d-958f-9f2043a83ca3)

2024-02-15 10:52 UTC, simison commented
> Add WPSC and Boost cache plugin

When testing, remember to also enable cache after activating the plugin:

<img width="733" alt="Screenshot 2024-02-15 at 12 36 49" src="https://github.com/Automattic/jetpack/assets/87168/3f12077d-72ef-48ae-8ff9-944d0103e20e">
<img width="875" alt="Screenshot 2024-02-15 at 12 37 46" src="https://github.com/Automattic/jetpack/assets/87168/3f6dbcb7-6872-4d82-a48b-58c188c389e0">

Both Boost and WP Super cache plugins come already installed with Jetpack Docker setup, and respect the same constant.

2024-02-15 13:44 UTC, simison commented
Kind of elaborate to test, but I confirmed cache leaking, and confirmed this fixed it.

Here's the same page leaking between logged in user (yet they aren't subscribed) in Chrome, and another user in another browser (Firefox):

<img width="855" alt="Screenshot 2024-02-15 at 15 33 58" src="https://github.com/Automattic/jetpack/assets/87168/92ec9aca-5c21-4c13-9505-f57d17f6997e">
<img width="1769" alt="Screenshot 2024-02-15 at 15 33 04" src="https://github.com/Automattic/jetpack/assets/87168/fe4c9f98-32eb-4e6b-96c7-270c954861b6">
<img width="2150" alt="Screenshot 2024-02-15 at 15 30 33" src="https://github.com/Automattic/jetpack/assets/87168/016405b8-b5bf-4795-ac64-5a0619180a77">

They both get served the same cached content which got generated when logged-in subscriber visited the page first, thus their email got stored in the cache.

Then with the PR, I cleared out caches, and now Super cache sees the cookie and tells not to cache the page:

<img width="1099" alt="Screenshot 2024-02-15 at 15 38 14" src="https://github.com/Automattic/jetpack/assets/87168/1ecc8259-5d67-465e-bc54-bc8f388ebc0f">

<img width="1422" alt="Screenshot 2024-02-15 at 15 33 36" src="https://github.com/Automattic/jetpack/assets/87168/f7ee9af2-ee6d-41a9-b8ce-cb46a80a8b19">

And another user sees cached content without email:

<img width="1420" alt="Screenshot 2024-02-15 at 15 38 41" src="https://github.com/Automattic/jetpack/assets/87168/2efb1635-c11c-442b-84f4-3ef6e8328ed3">
<img width="1389" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/71ae74bd-ad9b-4a80-aaac-16ef8685ffce">

2024-02-15 13:44 UTC, simison approved these changes
Looking good and tests well. Good job!

2024-02-15 13:45 UTC, simison commented
Note that I didn't test Jetpack boost. 

@donnchawp will Jetpack Boost respect `wpsc_add_cookie` as well? I know it respects the constant already.

2024-02-15 14:02 UTC, simison commented
> Can't install WP Super cache. I assume this is because it's already running?
>
> ![image](https://github.com/Automattic/jetpack/assets/6354169/ed542337-6c50-447d-958f-9f2043a83ca3)

@n3f Jurassic Tube and Atomic sites use Batcache (see mu-plugins from Plugins UI), and that prevents other cache plugins from working. You'll need to somehow disable those or test locally.

2024-02-15 14:11 UTC, millerf commented
Oh, I forgot Jurassic Ninja now uses Atomic.

Thanks a lot for testing this properly @simison .

2024-02-15 14:13 UTC, millerf commented
@donnchawp  Let me know if it needs revisit, but I was under the impression that you said this approach would support Jetpack Boost as well.

2024-02-15 14:24 UTC, merged

2024-02-15 22:52 UTC, donnchawp commented
@simison Boost Cache uses all the cookies in the cache key, so any cookies you add to the browser will generate a new cache file.