CRM: 3431 - PHP fatal on empty Woo fees
Automattic/jetpack pull request #35802
Opened 2024-02-20 22:24 UTC by tbradsha

Resolves Automattic/zero-bs-crm#3431 - PHP fatal on empty Woo fees

## Proposed changes:

Originally I suspected this was related to HPOS, but it turned out to be unrelated. Basically WooCommerce allows one to save an empty string as a fee value, and while PHP generally casts when doing math operations, it doesn't cast an empty string.

This PR explicitly sets the value of an empty fee to `0`. I considered casting, but I prefer the explicit logic here.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

1. Ensure WooSync invoice creation is enabled.
2. Create an order with a fee.
3. Save the order.
4. Edit the fee and delete the fee value (don't put `0` as the value, but delete the value so the `0` placeholder shows).
5. Update the order.

In `trunk`, one gets a PHP fatal.

In the `fix/crm/3431-PHP_fatal_on_empty_fees` branch, the fee is handled gracefully.

2024-02-21 06:15 UTC, gogdzl commented
Could only replicate by manually editing the database and set `_fee_amount` in table `wp_woocommerce_order_itemmeta` to an empty value.

<img width="887" alt="image" src="https://github.com/Automattic/jetpack/assets/37049295/5431a2ff-2f70-488a-9740-4302acb6d206">

2024-02-21 06:21 UTC, gogdzl commented
Still getting error 500:

```
Fatal error: Uncaught Error: Unsupported operand types: int * string
in /Users/diegorodrigues/Local/monorub/app/public/wp-content/plugins/woocommerce/includes/class-wc-order-item-fee.php on line 93

Call stack:

    WC_Order_Item_Fee::calculate_taxes()
    wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1760
    WC_Abstract_Order::calculate_taxes()
    wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1922
    WC_Abstract_Order::calculate_totals()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync-job.php:1220
    Automattic\JetpackCRM\Woo_Sync_Background_Sync_Job::woocommerce_order_to_crm_objects()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync-job.php:717
    Automattic\JetpackCRM\Woo_Sync_Background_Sync_Job::add_update_from_woo_order()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync-job.php:435
    Automattic\JetpackCRM\Woo_Sync_Background_Sync_Job::import_orders_from_store()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync-job.php:358
    Automattic\JetpackCRM\Woo_Sync_Background_Sync_Job::import_page_of_orders()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync-job.php:299
    Automattic\JetpackCRM\Woo_Sync_Background_Sync_Job::run_sync()
    /jetpack/projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-background-sync.php:299
    Automattic\JetpackCRM\Woo_Sync_Background_Sync::sync_orders()
    /jetpack/projects/plugins/crm/modules/woo-sync/admin/woo-sync-hub/main.page.php:478
    jpcrm_woosync_render_hub_page_debug_mode()
    /jetpack/projects/plugins/crm/modules/woo-sync/admin/woo-sync-hub/main.page.php:65
    jpcrm_woosync_render_hub_page()
    wp-includes/class-wp-hook.php:324
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-admin/admin.php:259
```

2024-02-21 06:24 UTC, gogdzl commented
Order 311 is composed by items 26, 27 and 28

<img width="609" alt="image" src="https://github.com/Automattic/jetpack/assets/37049295/c30b7042-22a5-4bab-8066-4c8150f90875">


<img width="985" alt="image" src="https://github.com/Automattic/jetpack/assets/37049295/7f918b14-bd48-4aca-93c7-45b172157f75">

2024-02-21 06:24 UTC, gogdzl requested changes
Left comments.

2024-02-21 17:34 UTC, tbradsha commented
Reported the Woo bug here: #44859

2024-02-21 17:49 UTC, tbradsha commented
There isn't a graceful way to handle errors, and it's not a priority to build one, so for now we'll catch the error and ignore it: 4d04772

2024-02-23 13:55 UTC, gogdzl approved these changes
Looks good to me!

Thanks for reporting the bug we've found to the Woo team, and going the extra mile trying to gracefully fail on CRM.

2024-02-23 13:56 UTC, merged