Boost: Disable Page Cache on Atomic
Automattic/jetpack pull request #35864
Opened 2024-02-22 14:04 UTC by dilirity

Fixes #35856

## Proposed changes:

* Disable Page Cache feature toggle;
* Add a notice explaining why feature is disabled.

![CleanShot 2024-02-22 at 16 04 01](https://github.com/Automattic/jetpack/assets/11799079/d37eeff8-8747-45fc-ae53-6089b3e464f0)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup on Atomic and make sure the feature can't be enabled and notice is properly visible.

2024-02-22 15:07 UTC, donnchawp requested changes
Nice! Good to see the greyed out toggle button and the warning. I would change the text of the warning though as the user may not know what "Atomic" is.

2024-02-22 15:07 UTC, donnchawp commented on projects/plugins/boost/app/assets/src/js/pages/index/index.tsx
> +								<p>{ __( 'Atomic sites already have caching enabled.', 'jetpack-boost' ) }</p>
Looks great, but I would change the warning message:
```suggestion
								<p>{ __( 'Your website already has a page cache running on it powered by WordPress.com.', 'jetpack-boost' ) }</p>
```

2024-02-22 15:23 UTC, donnchawp approved these changes
Looks great!

2024-02-22 15:48 UTC, merged

2024-02-22 16:14 UTC, dilirity commented
Cherry picked b488a1b for beta 3.1.0.

2024-02-23 01:20 UTC, thingalon commented
Beautiful. THanks @dilirity