Contact Form: refactor endpoints to use forms package
Automattic/jetpack pull request #36087
Opened 2024-02-29 20:40 UTC by monsieur-z

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/35653

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- TBD

2024-03-04 19:53 UTC, monsieur-z commented
WPcom tests are passing now: D140622-code

2024-03-07 16:50 UTC, sergeymitr commented
The code looks reasonable, but I didn't find a way to test it either.
I'm wondering about passing that deprecated class to the feedback post type [here](https://github.com/Automattic/jetpack/blob/a244c2791cbe5b2a213016ebba34aa90832cc341/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L370), should we replace it with `Contact_Form_Endpoint`?

2024-03-07 19:03 UTC, monsieur-z commented
> I'm wondering about passing that deprecated class to the feedback post type [here](https://github.com/Automattic/jetpack/blob/a244c2791cbe5b2a213016ebba34aa90832cc341/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L370), should we replace it with `I'm wondering about passing that deprecated class to the feedback post type [here](https://github.com/Automattic/jetpack/blob/a244c2791cbe5b2a213016ebba34aa90832cc341/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L370), should we replace it with Contact_Form_Endpoint?`?

I'd like to keep logging the deprecation warnings for the next one or two releases, so I'd say let's still use reference the deprecated class in the feedback post type.

2024-03-08 13:43 UTC, sergeymitr requested changes
I tried to test the methods manually, and looks like `Contact_Form_Endpoint` requires the post type passed as an argument:
```
Too few arguments to function WP_REST_Posts_Controller::__construct()
#0 /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/contact-form/class-grunion-contact-form-endpoint.php(44): WP_REST_Posts_Controller->__construct()
```

2024-03-11 15:59 UTC, monsieur-z commented
Thanks for spotting this @sergeymitr. I should have double checked 🤦

2024-03-11 18:57 UTC, sergeymitr approved these changes
Tested it manually by running this code:
```php
require_once ABSPATH . '/wp-content/plugins/jetpack/modules/contact-form/class-grunion-contact-form-endpoint.php';
$obj = new \Grunion_Contact_Form_Endpoint('feedback');
var_dump($obj->get_items_permissions_check(12345));
```

Works well as far as I can tell.

2024-03-11 20:16 UTC, merged