Boost: Add prefix and comments to page cache filters
Automattic/jetpack pull request #36209
Opened 2024-03-06 10:06 UTC by dilirity

## Proposed changes:

* Add prefix to filters, to have a unified naming convention across Boost;
* Update some filter names;
* Add docblock comments to filters.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Review comments and make sure they make sense.

2024-03-06 10:55 UTC, donnchawp requested changes

2024-03-06 10:55 UTC, donnchawp commented on projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/Request.php
> +		 * @param array $bypass_patterns An array of regex patterns that define URLs to be bypassed from caching.
```suggestion
		 * @param array $bypass_patterns An array of regex patterns that define URLs that bypass caching.
```

2024-03-06 10:57 UTC, donnchawp approved these changes
Looks great!

2024-03-06 11:04 UTC, merged

2024-03-11 09:42 UTC, haqadn commented
Cherry-picked to 3.1.1 [19f13b2](https://github.com/Automattic/jetpack/commit/19f13b27cea23143bf8956be388a4f58d7382f2b)