Add async site connection to Missing Connection notice
Automattic/jetpack pull request #36550
Opened 2024-03-23 03:16 UTC by IanRamosC

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-03-26 19:11 UTC, jboland88 requested changes
This tested well and is looking good - I really like how it works.

I think we need to add the TOS copy to the connection banner before we merge this.
Other feedback is non-blocking.

2024-03-26 19:11 UTC, jboland88 commented on projects/packages/my-jetpack/_inc/hooks/use-notification-watcher/use-site-connection-notice.ts
> +		);
With the site connection message - we need a way to include our TOS copy on the banner to indicate that clicking on the connection button is agreeing to our TOS.

We discussed handling that in another small PR - let's merge that together with this one before it goes into trunk.

2024-03-26 19:11 UTC, jboland88 commented on projects/packages/my-jetpack/_inc/context/notices/types.ts
> +			isLoading?: boolean;
Now that we have control of the notice component, could we customize the loading state to say "Connecting...." for this action? 

Maybe a custom loading text prop?

2024-03-26 19:11 UTC, jboland88 commented on projects/packages/my-jetpack/_inc/hooks/use-notification-watcher/use-site-connection-notice.ts
> +			priority: NOTICE_PRIORITY_HIGH + ( siteIsRegistering ? 1 : 0 ),
Nice touch here.

2024-04-06 00:44 UTC, IanRamosC commented
Closing in favor of #36771

2024-04-06 00:44 UTC, closed without merging