Fix/php error in inspect plugin
Automattic/jetpack pull request #36813
Opened 2024-04-09 23:28 UTC by enejb

This PR fixes a minor PHP warning that I was seeing while running the Inspect plugin. 

## Proposed changes:
* Adds the `private $namespace;` so that PHP stops complaining. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-04-10 08:07 UTC, jeherve approved these changes

2024-04-10 08:08 UTC, jeherve requested changes
I originally approved this, but I see now that one of the tests is failing. Could you update the Phan configuration as explained here, so we can merge the PR?
https://github.com/Automattic/jetpack/actions/runs/8623600766/job/23637087379?pr=36813

Thank you!

2024-04-22 17:06 UTC, enejb commented
I hope I fixed the issue @jeherve ! Thanks for catching it!

2024-04-22 17:10 UTC, jeherve approved these changes

2024-04-22 17:12 UTC, merged