Fix/launch task completion
Automattic/jetpack pull request #36839
Opened 2024-04-10 22:40 UTC by nelsonec87

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-04-12 18:28 UTC, valterlorran requested changes

2024-04-12 18:28 UTC, valterlorran commented on projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php
> +function wpcom_launchpad_is_site_launched() {
We should also check if the status is already complete, so we don't need always to check the option:
https://github.com/Automattic/jetpack/blob/ff17b59347cd29f9113174420ced10c7526670f4/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L1058-L1061

2024-04-15 19:52 UTC, nelsonec87 commented
Rebased to keep the PR "up-to-date"

2024-04-16 15:35 UTC, sixhours approved these changes
This is working for me!

2024-04-16 15:51 UTC, valterlorran approved these changes
LGTM!

2024-04-16 19:24 UTC, merged