Scheduled Updates: Only validate schedule when logging
Automattic/jetpack pull request #36961
Opened 2024-04-17 18:52 UTC by obenland

Removes all other schedule_exists checks to simplify clearing logs after a schedule was deleted. This will also help with moving non-schedule operations in the rest api endpoint to action callbacks in #36835.

## Proposed changes:

* Removes is_valid_schedule() in favor of inline check and removal of checks in `get()` and `clear()`
* Updates usage of log functions in the rest api endpoint.
* Updates tests to correspond to the new return values.
* Fixes phan errors in logs tests file.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Coming soon

2024-04-17 19:21 UTC, obenland commented
@TimBroddin In terms of testing instructions—anything beyond this?

> Run the unit tests 
> —https://github.com/Automattic/jetpack/pull/36676

2024-04-22 14:53 UTC, TimBroddin approved these changes
Looks good to me!

2024-04-22 15:52 UTC, TimBroddin requested changes
Going to do a full test tomorrow 👍

2024-04-22 15:54 UTC, TimBroddin approved these changes
Go ahead!

2024-04-22 18:03 UTC, merged