Social: Standardize social rest endpoints.
Automattic/jetpack pull request #37510
Opened 2024-05-23 11:49 UTC by spsiddarthan

Broken down from https://github.com/Automattic/jetpack/pull/37390
## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-05-23 19:44 UTC, pablinos reviewed
We should decide on the foreach loop https://github.com/Automattic/jetpack/pull/37390#discussion_r1612211253, and there's something a bit odd with the external ID happening. For me, with LinkedIn and Tumblr, it's always set to 1, which is my user ID on the site (I think) but shouldn't the user ID for the connection be my WPCOM user ID?

![CleanShot 2024-05-23 at 20 29 28@2x](https://github.com/Automattic/jetpack/assets/96462/44330da0-4732-4f33-817b-7c9dc7feece5)

2024-05-24 02:41 UTC, spsiddarthan commented
>there's something a bit odd with the external ID happening. For me, with LinkedIn and Tumblr, it's always set to 1

It is happening for all services, not just Facebook and LinkedIn. It's happening in WPCOM in `get_publicize_connections`  of `class.jetpack-xmlrpc-server.php`. We should patch WPCOM, but it seems to have been that way for a while now.

2024-05-24 05:42 UTC, manzoorwanijk commented on projects/packages/publicize/src/class-rest-controller.php
> +		return rest_ensure_response( $publicize->get_connection_for_user( (int) $connection_id ) );
Here the body can be
```json
{
    "code": "authorization_required",
    "message": "This user is not authorized to modify this publicize connection.",
    "data": 403
}
```

2024-05-24 05:43 UTC, manzoorwanijk requested changes
We need to handle the response for create, update and delete requests.

2024-05-24 06:37 UTC, spsiddarthan commented
>We need to handle the response for create, update and delete requests.

Delete won't work when sandboxed for different reasons, but it has `make_proper_response` already. 

I have implemented it for the CREATE and PUT requests as well.

2024-05-24 06:57 UTC, manzoorwanijk approved these changes
Now it works fine. Thank you for making the changes

2024-05-24 06:57 UTC, merged