Add mechanism to track previously working plugins
Automattic/jetpack pull request #37537
Opened 2024-05-24 17:12 UTC by CodeyGuyDylan

## Proposed changes:

* Adding a frequently updated array that tracks what plugins were active before user or site disconnection

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

P2: pbNhbs-aGl-p2#comment-22247
PT: pbNhbs-akp-p2

## Does this pull request change what data or activity we track or use?

No, I don't think we'll need to be adding any tracks for this

## Testing instructions:

TBD

2024-05-28 21:08 UTC, jboland88 requested changes, later dismissed
Overall, I like this approach to the problem 👍 

I had a few comments for small improvements.

In testing, I noticed that most of the other products that were previously active are now gone from the historically active array. Since they have a `site_connection_error` status,  I was expecting them to still show? For example, should stats still be in the array after the site gets disconnected since it was previously working?

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +		set_transient( self::UPDATE_HISTORICALLY_ACTIVE_JETPACK_MODULES_KEY, true );
It would be nice to set an expiration on this transient so it gets cleaned up after a certain amount of time - just in case :) Maybe 5 minutes?

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +		self::update_historically_active_jetpack_modules();
Instead of calling this here, what if we added a new `add_action` call similar to the one that is invoking this function so that the array is updated for loads of the My Jetpack page?

```
add_action( 'load-' . $page_suffix, array( __CLASS__, 'update_historically_active_jetpack_modules' ) );
```

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +			'jetpack_before_unlinking_user',
Curious here, is it critical that we hook before the user is unlinked?

With the transient approach that updates the historically active modules on the next load, the array will be updated after the user has been unlinked in either case.

Wondering if checking for the actual unlink event would have the same effect here? 🤔

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +		}
I think this is a nice approach with the transient check. It should prevent updating the array (and doing related fetches) during the connection/ disconnection routines that can trigger it.

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +		\Jetpack_Options::update_option( 'historically_active_modules', $historically_active_modules );
Nitpick - I'd suggest adding `array_unique` here to remove any possible duplicates

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +				$historically_active_modules = array_diff( $historically_active_modules, array( $product_slug ) );
I think you'll need to call `array_values` around `array_diff`. `array_diff` returns a keyed array with non-sequential keys. It looks like that's coming back as an option in the JS instead of an array.

2024-05-28 21:08 UTC, jboland88 commented on projects/packages/my-jetpack/src/class-initializer.php
> +			'user_connection_error',
Out of scope for this PR, but it would be good to define PHP constants for these statuses.

2024-05-29 18:44 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +			'jetpack_before_unlinking_user',
My intent here was to make sure we captured the active plugins before unlinking the user. If we do it after, we could potentially miss out on recording some plugins that were active before they disconnect. 

In this case, I guess we'd need to update the actual array in realtime like we do with the `jetpack_activate_module` action as well. But that could hold up runtime 🤔 let me know what you think

2024-05-29 18:45 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +			'user_connection_error',
I agree! I could potentially handle that in a separate PR in this project

2024-05-29 18:45 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +				$historically_active_modules = array_diff( $historically_active_modules, array( $product_slug ) );
Ah nice catch, I'll get that updated

2024-05-29 18:47 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +		\Jetpack_Options::update_option( 'historically_active_modules', $historically_active_modules );
I don't think that'd be possible with the way it is setup, I only add to the array if the slug doesn't already exist in it. What do you think? I could see adding it as a safety net, but wanted to try and make this as efficient as possible seeing how often it is being called

2024-05-29 18:49 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +		set_transient( self::UPDATE_HISTORICALLY_ACTIVE_JETPACK_MODULES_KEY, true );
It should get cleaned up as soon as `wp-admin` is loaded, and if it hasn't been cleaned up, that means the array should be updated right? I don't mind adding an expiration though, we do update this array a lot so missing out on one if it's been an extended period of time shouldn't mess with too much

2024-05-29 18:51 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +		self::update_historically_active_jetpack_modules();
Nice improvement! Thank you 😄

2024-05-29 18:53 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +		self::update_historically_active_jetpack_modules();
Actually would hooking into the `my_jetpack_init` be just as good/better?

2024-06-05 20:09 UTC, IanRamosC reviewed
It works as expected. Just left a few comments - and noticed that you've pushed updates in the meantime

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +	 * This array will conxsist of any plugins that were active at one point in time and are still enabled on the site
minor typo here in "consist"

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +			'user_connection_error',
I agree. It's quite nice to see them categorized like this as well

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +		// whether it be by uninstalling the plugin, disabling the module, or not renewing their plan.
Aren't there modules where `inactive` is the default value?

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +			// If the module is active and not aready in the array, add it
another minor typo here

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +		\Jetpack_Options::update_option( 'historically_active_modules', $historically_active_modules );
This will be called quite often, but not in a way that would affect performance, but I agree that it's mostly a safety net.
Not a problem to add that either, if we want to be future-proof and confirm that that option doesn't end up with lots of duplicates.

2024-06-05 20:09 UTC, IanRamosC commented on projects/packages/my-jetpack/src/class-initializer.php
> +		self::update_historically_active_jetpack_modules();
That sounds good to me.

2024-06-05 21:31 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/class-initializer.php
> +		// whether it be by uninstalling the plugin, disabling the module, or not renewing their plan.
Yes I guess the comment should be updated to say something like "in which the user willingly has the module disabled whether it be by default, uninstalling the plugin, disabling the module, or not renewing their plan"

2024-06-05 21:40 UTC, IanRamosC approved these changes
✅ 
<!-- I am Groot -->

2024-06-06 14:32 UTC, merged