My Jetpack: fix Stats Learn More link when site is disconnected
Automattic/jetpack pull request #38225
Opened 2024-07-06 03:28 UTC by IanRamosC

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-07-08 17:21 UTC, CodeyGuyDylan requested changes
This breaks a couple cards that are also have the `needs_first_site_connection` status. For example, when I click on the Akismet "Learn More" CTA, I am now taken to the Stats interstitial. Same for Creator and AI

https://github.com/Automattic/jetpack/assets/65001528/e9d8c60e-c0f4-4496-92ac-d00e7c942c30

2024-07-08 21:13 UTC, IanRamosC commented
> This breaks a couple cards that are also have the `needs_first_site_connection` status. For example, when I click on the Akismet "Learn More" CTA, I am now taken to the Stats interstitial. Same for Creator and AI

You're right, it was not the right code lol

2024-07-09 17:54 UTC, CodeyGuyDylan approved these changes, later dismissed
Tests well, thanks for the fix!

2024-07-10 13:44 UTC, CodeyGuyDylan approved these changes

2024-07-10 14:11 UTC, merged