Jetpack: Add block and allow list toggles to WAF settings
Automattic/jetpack pull request #38267
Opened 2024-07-09 21:38 UTC by dkmyta

### Description
Updates the Jetpack WAF security settings UI to allow the IP block and allow lists to be toggled independently.

## Proposed changes:

* Makes use of the new `jetpack_waf_ip_allow_list_enabled` / `jetpack_waf_ip_block_list_enabled` settings, replacing `jetpack_waf_ip_list`
* Removes the individual manual rules setting and adds independent toggles for each IP list
* Modifies sections dependent on the original setting

### Other information:
- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

- https://github.com/Automattic/jetpack-scan-team/issues/1263

## Does this pull request change what data or activity we track or use?

- No

## Testing instructions:

* Go to '..'
*

2024-07-15 20:21 UTC, nateweller commented
Similar to https://github.com/Automattic/jetpack/pull/38265, what do you think about using this PR to also de-duplicate the allow list?

We could place the allow list as a separate card below the WAF and BFP cards, keeping/revising the description included with the BFP allow list.

2024-07-18 23:10 UTC, nateweller commented on projects/plugins/jetpack/_inc/client/security/allowList.jsx
> +			updateWafIpAllowList: allowList => dispatch( updateWafIpAllowList( allowList ) ),
```suggestion
```

Unused

2024-07-18 23:14 UTC, nateweller requested changes
The `updateWafIpAllowList` and `allowListInputState` logic can be removed ([ie](https://github.com/Automattic/jetpack/pull/38361/files#diff-dc55cc89684ee98e3f25ecd33da14efb5e1930db38f926620f03671ab54177f2)), it is not necessary now that we aren't duplicating the list on the page - we can just use `updateWafSettings` and `getWafSettings` :+1:

2024-07-19 16:19 UTC, dkmyta commented
>we could just use updateWafSettings and getWafSettings, in addition to tracking the current text input value in local component state

Very good point! Updated accordingly 👍🏻

2024-07-19 20:24 UTC, nateweller approved these changes
LGTM! We should wait on https://github.com/Automattic/jetpack/pull/38395 to merge though :+1:

2024-07-19 21:10 UTC, merged