Add/newsletter card
Automattic/jetpack pull request #38418
Opened 2024-07-19 01:18 UTC by IanRamosC

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-07-22 19:24 UTC, CodeyGuyDylan requested changes
Tested mostly well, I left a few comments that i think are important enough to address or talk about before merging 😄

2024-07-22 19:24 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/_inc/components/product-cards-section/newsletter-card.jsx
> +		[ PRODUCT_STATUSES.MODULE_DISABLED ]: {
With [this PR](https://github.com/Automattic/jetpack/pull/38390) we've gone towards allowing the user to "Activate" the module/plugin from My Jetpack if at all possible. Could we possibly continue that trend here? Would the activate function work here or is there a reason we need to have the user do it from the settings page?

2024-07-22 19:24 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/_inc/components/product-cards-section/index.tsx
> +	Exclude< JetpackModule, ExcludedModules >,
Nice improvements with the excludes, thanks!

2024-07-22 19:24 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/_inc/components/product-cards-section/newsletter-card.jsx
> +import { __ } from '@wordpress/i18n';
Since this is a brand new file, what do you think about converting it to TypeScript since we are heading that direction in My Jetpack?

2024-07-22 19:24 UTC, CodeyGuyDylan commented on projects/packages/my-jetpack/src/products/class-newsletter.php
> +			$status = Products::STATUS_NEEDS_PURCHASE_OR_FREE;
This status has been replaced with STATUS_NEEDS_ACTIVATION in the PR I linked to in a previous comment FYI, you might want to rebase and update that so there are no issues with an undefined constant 😄

2024-08-07 16:27 UTC, crisbusquets commented
Just a note that we also need to update the emails we send when the user upgrades:

<img width="1124" alt="Screenshot 2024-08-07 at 18 27 16" src="https://github.com/user-attachments/assets/7296e30e-85d3-453a-ae50-89a5358883e8">

Should I create a new issue for this, @IanRamosC ?

2024-09-04 20:56 UTC, pkuliga commented
Hi @IanRamosC, I just came across this and I'm wondering, what is the status of this work?

Are we giving up on it or still want to move it forward?

2024-09-13 14:59 UTC, crisbusquets commented
Paused until Nov.
Context: p1726211355297409-slack-C02LK1W8T4Z.

2025-01-14 00:49 UTC, closed without merging