WPCOMSH: plugin-dance improvements
Automattic/jetpack pull request #38423
Opened 2024-07-19 11:32 UTC by TimBroddin

## Proposed changes:
- Does no longer disable/enable plugins that are also not disabled by `deactivate-user-plugins`
- More robust error handling (when a plugin does not like to be enabled again the command no longer breaks)
- Two strategies:

| Name | Description |
|-|-|
| `one-by-one` (default) | Tries to disable/enable every plugin one by one until the site is healthy. |
| `disable-all` | Will start with disabling all user plugins, and then re-enabling them one by one. |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:
- This command is a pain to test 😃
- Rsync it to your site, and make sure everything is setup to test (`define( 'JETPACK_AUTOLOAD_DEV', true );`): 

`jetpack rsync wpcomsh yoursite.wordpress.com@sftp.wp.com:htdocs/wp-content/mu-plugins/wpcomsh`

- SSH into your site and create two plugins that don't fail:

`mkdir htdocs/wp-content/plugins/plugin1`
`nano htdocs/wp-content/plugins/plugin1.php`
```
<?php
/**
 * Plugin Name: PHP 8.1 Fatal
 * Description: This plugin demonstrates a fatal error in PHP 8.1+ but works in PHP 7.4 on all pages
 * Version: 1.0
 * Author: Tim Broddin
 */

function php_version_fatal_init() {
	return true;
}

// Use the 'init' hook to run on all page loads
add_action('init', 'php_version_fatal_init');

``` 
`mkdir htdocs/wp-content/plugins/plugin2`
`nano htdocs/wp-content/plugins/plugin2.php`

```
<?php
/**
 * Plugin Name: PHP 8.1 Fatal
 * Description: This plugin demonstrates a fatal error in PHP 8.1+ but works in PHP 7.4 on all pages
 * Version: 1.0
 * Author: Tim Broddin
 */

function php_version_fatal_init2() {
	return true;
}

// Use the 'init' hook to run on all page loads
add_action('init', 'php_version_fatal_init2');
```

- Visit https://yoursite.wordpress.com/_cli
- Activate these plugins= `plugin activate plugin1` & `plugin activate plugin2`
- Now edit both plugins and paste in something that would give a fatal. For example change `return true;` to `return true ? false : true ? 'a' : 'b';`
- If you want you can now visit your site & confirm that it is broken.
- Do the plugin dance: `--skip-theme --skip-plugins wpcomsh plugin-dance`
- Confirm that the site works again
- Change the two plugins to `return true;` again.
- Reactivate them: `plugin activate plugin1` & `plugin activate plugin2`
- Change both plugins to fatal again.
- Do the plugin dance with another strategy: --skip-theme --skip-plugins wpcomsh plugin-dance --strategy=disable-all`

2024-07-19 13:46 UTC, obenland requested changes, later dismissed

2024-07-19 13:46 UTC, obenland commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +				return;
How about putting that at the top of the function?

2024-07-19 13:46 UTC, obenland commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +					WP_CLI::log( sprintf( 'ℹ️ Deactivating %s to find the breaking plugin.', $plugin_to_deactivate['name'] ) );
I wonder if that's needed. The plugin name is captured in the result log next.

2024-07-19 13:46 UTC, obenland commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +					return;
I think we should re-activate all plugins at this point

2024-07-22 10:38 UTC, ouikhuan commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +						return;
The return is probably not needed since `WP_CLI:error` terminate the process?

2024-07-22 10:38 UTC, ouikhuan commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +								'launch'     => true,  // needed for exit_eror => false.
Small `exit_error` typo here in the comment.

2024-07-22 10:38 UTC, ouikhuan commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +								'launch'     => true, // needed for exit_eror => false.
Small `exit_error` typo here in the comment.

2024-07-22 10:38 UTC, ouikhuan commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +							'launch'     => true, // needed for exit_eror => false.
Small `exit_error` typo here in the comment.

2024-07-22 14:15 UTC, ouikhuan commented on projects/plugins/wpcomsh/class-wpcomsh-cli-commands.php
> +								'launch'     => true,  // needed for exit_erorr => false.
Little typo

2024-07-23 03:41 UTC, ouikhuan approved these changes
I tried to force the `reactivate-user-plugins` and since there's a broken plugin, I think the behavior is expected. Also tested with other scenarios and all works as expected. Thanks for handling the feedback!
```
$ wp --skip-theme --skip-plugins wpcomsh plugin-dance --strategy=disable-all
ℹ️ Skipping akismet.
ℹ️ Skipping classic-editor.
ℹ️ Deactivating all user plugins.
  - skipping 'akismet'
  - skipping 'classic-editor'
  ✔ deactivated 'plugin2'
  ✔ deactivated 'plugin1'
  ✔ deactivated 'rest-api-console'
  ✔ deactivated 'jetpack-mu-wpcom-plugin-dev'
  ✔ deactivated 'wp-approve-user'
  ✔ deactivated 'crash-test'
❌ Site health check failed after deactivating all plugins. Something non-plugin related is causing the issue. Trying to reactivate all plugins.
The following will be reactivated:
  - cron-log
  - jetpack-beta
  - jetpack-protect
  - plugin2
  - plugin1
  - rest-api-console
  - jetpack-mu-wpcom-plugin-dev
  - wp-approve-user
  - crash-test
Do you wish to proceed? [Y/n] y
  ✔ activated 'cron-log'
  ✔ activated 'jetpack-beta'
  ✔ activated 'jetpack-protect'
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /srv/htdocs/wp-content/plugins/plugin2/plugin2.php on line 11
xargs: sudo: exited with status 255; aborting
```

2024-07-23 05:59 UTC, merged