Protect: Refactor useProtectData hook
Automattic/jetpack pull request #38637
Opened 2024-07-31 03:14 UTC by nateweller

The intention of this PR is to enable the ability to access assorted threat counts, ultimately to disable status filters that have no related threats under the current selected category.

Also improves performance and usability of the hook.

## Proposed changes:

* TBD

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* TBD

2024-08-02 18:03 UTC, dkmyta requested changes
On a fresh JT instance, without an upgrade, I can see that the initial Protect status report has been generated (properly set in the `jetpackProtectInitialState` var, JPDB, and in the `jetpack_protect_status` option), however, the `Summary` and `ThreatsList` components are empty:
 
![Screen Shot on 2024-08-02 at 10-56-48](https://github.com/user-attachments/assets/76d58163-206f-4851-8ae7-e7876da1bc1a)

2024-08-02 20:55 UTC, nateweller commented
Looks like the issue is that the hook is now only providing the extensions that have threats, I will fix that up.

The flash of the error state appears to be on the project branch, will make a PR or issue for that as well.

2024-08-02 21:40 UTC, nateweller commented
@dkmyta PR has been updated with a fix :+1:

2024-08-06 21:46 UTC, dkmyta requested changes
Code is clean and initial testing in a functioning environment shows it works. 

I noticed something though that may be related to the current updates or may be more related to the prior addition of `scanError` selector and related adjustments. Manually setting the `error` var in `useProtectData` and visiting the `ScanHistoryRoute` component displays the `ErrorScreen`. Similarly, setting the `scanError` selector to return an error works. However, simulating an action error, for example updating my `hosts` file to point at `public-api.wordpress.com` but not running my sandbox to make `wpcom` requests fail provides for some unexpected results. First the `ScanRoute` component displays an empty list, with some relevant data missing:
![Screen Shot on 2024-08-06 at 14-39-06](https://github.com/user-attachments/assets/a924757e-fca1-409b-abf1-0904c56acd6e)

Then shortly after (likely after the first status poll) the error display:
![Screen Shot on 2024-08-06 at 14-39-30](https://github.com/user-attachments/assets/204da04e-409a-47b1-95f2-328d35b28073)

The `ScanHistoryRoute` performs similarly. I can see in both cases that the `status` and `scanHistory` initial state variables are populated correctly with error details so it would seem this maybe be more related to the frontend handling of such data.

Perhaps this is not the best way to generate an actual error but I think it does uncover that there is an issue.

2024-08-06 21:46 UTC, dkmyta commented on projects/plugins/protect/src/js/routes/scan/index.jsx
> +	const { lastChecked, error, hasRequiredPlan } = useProtectData();
Mistakenly added after a rebase?

2024-08-06 21:46 UTC, dkmyta commented on projects/plugins/protect/src/js/routes/scan/history/status-filters.jsx
> +				disabled={ ! numIgnored }
This is great idea but an interesting things happens when you manually visit the URL for a disabled filter (eg. `#/scan/history/ignored` when there are no ignored threats):
![Screen Shot on 2024-08-06 at 14-22-41](https://github.com/user-attachments/assets/a4f9b692-f809-4466-88cc-157cc21476a2)

2024-08-07 16:45 UTC, dkmyta commented
Not specific to these changes, but similar to the issue with the filters routes, we'll need to redirect `#/scan/history` and `/ignored` or `/fixed` to `#/scan` if a user does not have an upgrade. Currently, when visiting these routes without a paid plan is possible and the page is blank and we're hit with a bunch of console errors attempting to access an undefined `threats` property.

2024-08-07 18:23 UTC, nateweller commented
@dkmyta Added a `PaidPlanGate` component that we can wrap around any route that requires a plan: https://github.com/Automattic/jetpack/pull/38637/commits/ea7906583f4b5e21b57b13a63daaf3a0dcdf9c21

2024-08-07 19:26 UTC, nateweller commented on projects/plugins/protect/src/js/routes/scan/history/status-filters.jsx
> +				disabled={ ! numIgnored }
Resolved via https://github.com/Automattic/jetpack/pull/38637/commits/442ccb41b009fe6e724e6a98b00483aa27a78319

2024-08-08 16:12 UTC, dkmyta commented on projects/plugins/protect/src/js/routes/scan/index.jsx
> +
Can this scenario ever occur on its own or will `scanInProgress` always be set when `statusIsFetching` is? If it can occur, then I think we need to update the display, as it is currently:
![Screen Shot 2024-08-08 at 09 12 18](https://github.com/user-attachments/assets/74909018-af14-4ed8-ab7f-03e6fd383bde)

2024-08-09 01:34 UTC, dkmyta approved these changes
Looking good!

2024-08-09 01:35 UTC, merged