Jetpack: Add WAF settings notice and Protect CTA
Automattic/jetpack pull request #38741
Opened 2024-08-06 16:53 UTC by dkmyta

Fixes #
Adds a info notice to the WAF settings that include Protect CTA

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

- https://github.com/Automattic/jetpack-scan-team/issues/1307

## Does this pull request change what data or activity we track or use?

- No

## Testing instructions:

* Checkout this branch and start Jurassic Tube
* Install/activate Jetpack
* Proceed to the WAF settings and verify that the notice displays
* Verify that the toggles are still accessible and functional
* Ensure that the Get Protect Buttons CTA redirect to the `#/add-protect` My Jetpack route
* Install Protect and verify that the Jetpack WAF settings now display a message that the Firewall setting are only available in Protect

2024-08-06 17:09 UTC, dkmyta commented on projects/plugins/jetpack/_inc/client/security/waf.jsx
> +						'The settings for the Firewall will be moved to Jetpack Portect in Jetpack version 13.9.',
Version 13.9 was mentioned in task description, but this will likely need to be updated once the actual version is confirmed.

2024-08-19 20:35 UTC, nateweller commented on projects/plugins/jetpack/_inc/client/security/waf.jsx
> +						'The settings for the Firewall will be moved to Jetpack Protect in Jetpack version 13.9.',
```suggestion
						'The settings for the Firewall will be moved to Jetpack Protect in Jetpack version 13.10.',
```

2024-08-19 20:47 UTC, nateweller requested changes
Works well and looks good! Will need to bump the version number in the message now that Jetpack 12.9 has already been released, and needs a fresh rebase or trunk merge.

2024-08-20 01:25 UTC, nateweller approved these changes

2024-08-20 16:33 UTC, merged