CRM: Add the order capability to the API events endpoint.
Automattic/jetpack pull request #38838
Opened 2024-08-12 15:23 UTC by cleacos

Fixes https://github.com/Automattic/zero-bs-crm/issues/3476

## Proposed changes:

This PR adds the result `order` capability to the `events` endpoint.

Example of a request:

- http://jetpackcrm.local/zbs_api/events/?api_key=jpcrm_pk_e75f7369e0e92cf88c323963fbf265d2611b2139&api_secret=jpcrm_sk_b6095358cfd10c7f85e1cae3be0bce0436b828f4&page=1&perpage=2&order=ASC
- http://jetpackcrm.local/zbs_api/events/?api_key=jpcrm_pk_e75f7369e0e92cf88c323963fbf265d2611b2139&api_secret=jpcrm_sk_b6095358cfd10c7f85e1cae3be0bce0436b828f4&page=1&perpage=2&order=DESC

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:
- Check the code
- Activate the API module
- Configure your API secret keys
- With some already added events (schedule item), call the API endpoint with these parameters
   - page: 1
   - perpage: 1
   - order: ASC and DESC
- You will see the result in different order

2024-08-13 10:36 UTC, coder-karen requested changes, later dismissed
This works well for me.

To avoid the phan errors though, it looks like the same changes made in `api/events.php` need to be made in` quotes.php`, `invoices.php`, `customer_search.php`, and `transactions.php` (removing the use of the `list` function, using `$pagination` to store the ` jpcrm_api_process_pagination` result and retrieving values from that.

And `tools/fixup-project-versions.sh` should fix that linting error.

2024-08-14 15:12 UTC, cleacos commented
Thanks for the review @coder-karen. I'll apply the same for the rest of the API endpoints.

2024-12-12 18:28 UTC, bobmatyas commented
@cleacos Noting here that we had a user who requested the API docs be updated once this capability is released:

https://wordpress.org/support/topic/jetpack-crm-api/#post-18184393

2025-01-10 17:32 UTC, gogdzl commented
I've addressed @coder-karen's suggestion.

2025-01-10 18:46 UTC, tbradsha commented
Discussed this with @gogdzl and we expanded this to do the following:
* Make the default sort `DESC`
* Add an `order` param to `customer_search`, `invoices`, `events`, `quotes`, and `transactions` endpoint
* Switch to DAL calls on those endpoints

2025-01-10 18:48 UTC, tbradsha approved these changes
Tested the following:
* `customer_search`: ASC ✅ DESC ✅ Default DESC ✅
* `invoices`: ASC ✅ DESC ✅ Default DESC ✅
* `transactions`: ASC ✅ DESC ✅ Default DESC ✅
* `events`: ASC ✅ DESC ✅ Default DESC ✅
* `quotes`: ASC ✅ DESC ✅ Default DESC ✅

2025-01-10 18:49 UTC, gogdzl commented
After addressing to @coder-karen's suggestion, @tbradsha decided to give more suggestions over slack DM's, which I've addressed here as well.

Over the scope changes that were included:

- Changing from legacy function call to a DAL call in invoices and transactions
- Refactoring the process pagination method
- Add order to invoices, transactions, customers and quotes
- General code refactor

2025-01-10 18:51 UTC, gogdzl approved these changes

2025-01-10 18:51 UTC, merged