Jetpack Newsletter Settings: Improve sender information and reply-to IA
Automattic/jetpack pull request #38833
Opened 2024-08-12 14:08 UTC by crisbusquets

Fixes https://github.com/Automattic/jetpack/issues/38827

## Proposed changes

Improve Sender Information and Reply-To information architecture, so that it's clear that both actions change something in the preview that now appears below.

### Current
<img width="1061" alt="Screenshot 2024-08-12 at 11 24 16" src="https://github.com/user-attachments/assets/79bd3a95-2f65-439f-a5df-dc25d2708c6a">

### Proposal
<img width="1085" alt="Screenshot 2024-08-12 at 16 07 07" src="https://github.com/user-attachments/assets/8e8725ec-3247-4828-861e-2918b7d5f943">

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Go to Jetpack → Settings → Newsletter
* Scroll down to `Sender name and reply-to settings`
* Update the input and radio button
* Ensure the "Preview" updates accordingly
* Test it sending a newsletter

2024-08-13 14:57 UTC, keoshi submitted a review, later dismissed
Looks and works perfectly in my testing. Even supports emoji! 🚀

2024-08-14 09:09 UTC, pkuliga requested changes
Looks good!

Added one issue that needs to be addressed before the merge.

Thanks!

2024-08-14 09:09 UTC, pkuliga commented on projects/plugins/jetpack/_inc/client/newsletter/email-settings.jsx
> +						) }
In this case, the "Preview" label will not be translated, it needs to be inside the `__` function.

Something like this:
```php
__( 'Preview: %1$s <%2$s>', 'jetpack' ),
```

You can check how it was before.

2024-08-14 09:20 UTC, simison commented on projects/plugins/jetpack/_inc/client/newsletter/email-settings.jsx
> +						) }
_"placeholder is the user entered value for From Name"_ could be "Site name or user entered replacement value", might be clearer for translators who don't have more context where this translation is coming from.

2024-08-14 14:25 UTC, crisbusquets commented
@pkuliga @simison I addressed the suggestions. It should work now :)

2024-08-14 15:43 UTC, pkuliga approved these changes, later dismissed
Thanks!

2024-08-16 15:24 UTC, crisbusquets commented
@foleynotrose I've added this to HE inbox.
This PR updates the information architecture, making the Preview more visible and clarifying that the two elements above it have an impact on it.

2024-08-23 09:01 UTC, pkuliga approved these changes

2024-08-23 09:01 UTC, merged

2024-08-27 15:43 UTC, foleynotrose commented
@StefMattana sorry I'm a little behind in my inbox reviewing, and it looks like this one has already shipped. Can you look it over and see if there are any docs changes that are needed?

2024-08-27 16:14 UTC, StefMattana commented
The only Sender-related documentation we have [is here](https://jetpack.com/support/newsletter/customize-the-newsletter-experience/#sender-name), and isn't very granular so it doesn't guide the user to any step-by-step actions. I don't think this change needs any documentation update - @crisbusquets would you agree with me? 

@foleynotrose I took the chance to create a JEDI card for that page: https://github.com/Automattic/jedi-jetpack-enhancements-of-docs-for-ai/issues/328

2024-09-05 10:27 UTC, crisbusquets commented
> @crisbusquets would you agree with me?

Thanks for checking this, @StefMattana ! Yes, I agree. We don't need to update anything for now.