Classic Theme Helper: Remove Settings link and add Jetpack version checks
Automattic/jetpack pull request #38872
Opened 2024-08-14 05:33 UTC by chrisbliss18

Fixes https://github.com/Automattic/vulcan/issues/388

## Proposed changes:
* Remove the placeholder Settings page link as we will not use a settings page on the initial release of this plugin.
* Added example Jetpack version checking to the feature class loaders. These will be updated with appropriate versions before release.
* Cleaned up whitespace in main plugin file.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [X] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [X] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
Details about these changes can be found in this issue: https://github.com/Automattic/vulcan/issues/388

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
* Verify that the placeholder settings page link is no longer present on the Classic Theme Helper Plugin's listing in the WordPress admin plugins' page.
* Review the version checks added to the feature class loaders in `classic-theme-helper-plugin.php` and verify that they will work to only initialize each class when the Jetpack version is high enough.

2024-08-14 08:45 UTC, coder-karen requested changes
Thanks for looking at this. I left a comment about the Constants class - with that changed it tests well.

As an aside though, maybe not for this PR, I wonder if we should add a notice if Jetpack gets deactivated and the CTH plugin is active (on the plugins page for example) to say that Jetpack needs to be active for CTH features to work 🤔

2024-08-14 08:45 UTC, coder-karen commented on projects/plugins/classic-theme-helper-plugin/classic-theme-helper-plugin.php
> +	$jp_plugin_version = Constants::get_constant( 'JETPACK__VERSION' );
In testing I get a fatal error - `PHP Fatal error: Uncaught Error: Class "Constants" not found (on line 53 of classic-theme-helper-plugin.php)` - same issue as Phan is reporting as well.

If I change this to:
```
if ( class_exists( 'Automattic\Jetpack\Constants')) {
	$jp_plugin_version = 'Automattic\Jetpack\Constants::get_constant( 'JETPACK__VERSION' );
}
```
... and the same in `init_packages_init`, then the fatal is prevented and I can see that the settings link is now gone, plus in testing I could confirm that Featured Content that I tested loaded via the plugin.

If I deactivate the Jetpack plugin, I also now get no errors, the features just don't load.

2024-11-13 06:28 UTC, fgiannar commented
@coder-karen Do you perhaps know if the current PR is still relevant or should be closed?

2024-11-13 08:09 UTC, coder-karen commented
I believe it is still relevant. I moved the issue itself into the next sprint so we can hopefully discuss next steps.

2025-03-15 00:50 UTC, closed without merging