Connection: Load connection JS bundle via connection PHP package
Automattic/jetpack pull request #38877
Opened 2024-08-14 10:44 UTC by manzoorwanijk

Extracted out of #38330 

### Problem

For publicize (Social), the JS code that gets bundled in Jetpack takes precedence over Social even if Social is the latest version. This is not the case with PHP packages, for which we always load the latest version regardless.

This mismatch of PHP and JS code often results in bugs.

Also, bundled JS code makes it difficult to fix a bug in Jetpack given the monthly release cycle. Thus, we decided to bundle the publicize JS code into publicize package to ensure that the latest version of the  publicize JS code is loaded both in Jetpack and Social.

Now, to be able to externalize publicize, we also need to externalize connection js code to avoid it getting bundled into publicize code and fix some API call errors due to duplicate instances of connection bundle both in publicize bundle as well as in the plugins (Jetpack and Social)

#### Benefits
- JS Code for connection will always be in sync with its PHP package
- Plugins will have smaller js bundles

## Proposed changes:

* Bundle connection JS code inside connection PHP package
* Let connection PHP package handle the registration or script for the connection bundle
* Externalize that connection bundle for all the plugins/packages
* The connection bundle will now be available via `window.JetpackConnection` just like `@wordpress/*` packages are available via `window.wp.*`

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pdrWKz-1Mq-p2

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Just do a smoke test of the pages that rely on Jetpack connection

2024-08-14 11:25 UTC, manzoorwanijk commented
I will fix up versions once this gets an approval to avoid noise in the PR.

2024-08-19 09:59 UTC, coder-karen requested changes, later dismissed
👋 I gave this a spin, testing different scenarios related to connection. One thing I noticed was that both on disconnecting and connecting Jetpack, with this PR applied the related modals seemed to be missing styling. So it looks like the way CSS styles are applied may be affected in some way via this PR. Examples here:
Connection:
<img width="500" alt="Screenshot 2024-08-19 at 10 53 01" src="https://github.com/user-attachments/assets/3187086d-8968-4da1-b927-3a02fcac3923">
Disconnection (bottom part of modal):
<img width="500" alt="Screenshot 2024-08-19 at 10 56 46" src="https://github.com/user-attachments/assets/b0bbd516-4efe-439b-bcd4-08cdd39e8dbb">

2024-08-19 10:05 UTC, manzoorwanijk commented
Thank you for giving this a test...

> 👋 I gave this a spin, testing different scenarios related to connection. One thing I noticed was that both on disconnecting and connecting Jetpack, with this PR applied the related modals seemed to be missing styling. So it looks like the way CSS styles are applied may be affected in some way via this PR.

Did you run `jetpack build packages/assets packages/connection plugins/jetpack` before loading that page?

2024-08-19 10:28 UTC, manzoorwanijk commented
> 👋 I gave this a spin, testing different scenarios related to connection. One thing I noticed was that both on disconnecting and connecting Jetpack, with this PR applied the related modals seemed to be missing styling. So it looks like the way CSS styles are applied may be affected in some way via this PR.

I have fixed the issue for connection screen. I assumed that all our scripts are registered via `Automattic\Jetpack\Assets::register_script` and enqueued via `Automattic\Jetpack\Assets::enqueue_script` which automatically takes care of loading the styles, but I noticed that it's not the case with admin page styles and thus had to explicitly add connection CSS as a dependency.

2024-09-02 16:34 UTC, anomiex commented on projects/packages/connection/webpack.config.js
> +			consumer_slug: 'identity_crisis',
We should probably update this to something like
```suggestion
			consumer_slug: 'connection_package',
```
Or move it out of the shared config and into the separate configs below.

2024-09-02 18:19 UTC, anomiex commented
@coder-karen If the issues you found are fixed, I think this is good to go. Do you have time to check it again? Otherwise I'll try to test it.

2024-09-02 18:20 UTC, anomiex approved these changes

2024-09-03 04:29 UTC, merged