Synced Order Data: Adds filtering for filtered order data
Automattic/jetpack pull request #38955
Opened 2024-08-19 15:35 UTC by ibndawood

TBA

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-08-19 23:48 UTC, rawdreeg commented
@ibndawood, Could also applying `jetpack_sync_post_meta_whitelist` [here] (https://github.com/Automattic/jetpack/blob/31dac9b1f9762fb4ee42d8be29bafd20dcebf664/projects/packages/sync/src/modules/class-woocommerce-hpos-orders.php#L234) be an option?

It's already used to extend  WooCommerce::$wc_post_meta_whitelist here: https://github.com/Automattic/jetpack/blob/31dac9b1f9762fb4ee42d8be29bafd20dcebf664/projects/packages/sync/src/modules/class-woocommerce.php#L88C16-L88C48

2024-08-20 04:42 UTC, ibndawood commented
Thank you, @rawdreeg, for the suggestion. Adding a field to the whitelist alone is not enough. We also need to add the field assignment inside the `filtered_order_data` method. I reckon that we can simply add a filter to the result of `filtered_order_data` method instead of adding filters in two places.

2024-08-20 04:45 UTC, rawdreeg commented
> Thank you, @rawdreeg, for the suggestion. Adding a field to the whitelist alone is not enough. We also need to add the field assignment inside the `filtered_order_data` method. I reckon that we can simply add a filter to the result of `filtered_order_data` method instead of adding filters in two places.

Very good point. Thanks, @ibndawood

2024-08-20 07:46 UTC, darssen requested changes
Hi @ibndawood! 

I think the filter can be a good solution to be able to extend the HPOS data to be synced. Added couple of inline minor comments

2024-08-20 07:46 UTC, darssen commented on projects/packages/sync/src/modules/class-woocommerce-hpos-orders.php
> +		 * @since x.x.x
```suggestion
		 * @since $$next-version$$
```
[Package version annotations](https://github.com/Automattic/jetpack/blob/c94dd7e291080ead12f4a94252075592668bca65/projects/packages/README.md#package-version-annotations)

2024-08-20 07:46 UTC, darssen commented on projects/packages/sync/src/modules/class-woocommerce-hpos-orders.php
> +		return apply_filters( 'jetpack_sync_filtered_order_data', $filtered_order_data, $order_object );
Do you think changing the name to `jetpack_sync_filtered_hpos_order_data` since we are in the `WooCommerce_HPOS_Orders` module will help with clarity?

2024-08-20 07:53 UTC, ibndawood commented on projects/packages/sync/src/modules/class-woocommerce-hpos-orders.php
> +		return apply_filters( 'jetpack_sync_filtered_order_data', $filtered_order_data, $order_object );
Thank you, @darssen, for the suggestion. This is a good recommendation. I've implemented it here: https://github.com/Automattic/jetpack/pull/38955/commits/cd116d6cb3cef6cb7eddee9d46b097c5d6dff506

2024-08-20 07:56 UTC, darssen approved these changes
LGTM :+1:

2024-08-20 08:11 UTC, merged