Protect: Add formatting help text to IP list controls
Automattic/jetpack pull request #39448
Opened 2024-09-18 21:18 UTC by nateweller

## Proposed changes:

* Adds a help text snippet below the IP list text inputs, describing the supported formatting.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Related to https://github.com/Automattic/jetpack/pull/39425

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Review the UI and confirm it matches the screenshot below

## Screenshots

<img width="822" alt="Screenshot 2024-09-18 at 3 17 36 PM" src="https://github.com/user-attachments/assets/aeb5211f-99ad-488c-a090-2a8c304bb42c">

2024-09-20 13:51 UTC, ArSn requested changes
Small typo there, rest looks good.

2024-09-20 13:51 UTC, ArSn commented on projects/plugins/protect/src/js/routes/firewall/index.jsx
> +									'IPv4 and IPv6 supported. Separate IPs with commas, spaces, or new lines. To specify a range, use CIDR notation (i.e. 12.12.12.0/24) or enter the low value and high value separated by a dash
```suggestion
									'IPv4 and IPv6 supported. Separate IPs with commas, spaces, or new lines. To specify a range, use CIDR notation (i.e. 12.12.12.0/24) or enter the low value and high value separated by a dash (i.e. 12.12.12.0–12.12.12.255).',
```

2024-09-20 13:51 UTC, ArSn commented on projects/plugins/protect/src/js/routes/firewall/index.jsx
> +										'IPv4 and IPv6 supported. Separate IPs with commas, spaces, or new lines. To specify a range, use CIDR notation (i.e. 12.12.12.0/24) or enter the low value and high value separated by a das
```suggestion
										'IPv4 and IPv6 supported. Separate IPs with commas, spaces, or new lines. To specify a range, use CIDR notation (i.e. 12.12.12.0/24) or enter the low value and high value separated by a dash (i.e. 12.12.12.0–12.12.12.255).',
```

2024-09-20 19:49 UTC, nateweller commented
@ArSn Thanks, applied the typo fix :+1:

2024-09-21 02:19 UTC, ArSn approved these changes
Almost missed this. LGTM. 👍🏻

2024-09-21 19:57 UTC, merged