Change/at a glance unify connection ctas
Automattic/jetpack pull request #39535
Opened 2024-09-25 20:32 UTC by CodeyGuyDylan

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-09-25 20:40 UTC, CodeyGuyDylan commented
I see the JS tests are failing, I will address that on Friday when I am back 😄

2024-09-26 13:52 UTC, keoshi requested changes, later dismissed
Everything looks great except for the CTA in the Site connection card. The card doesn't align with others in large desktop views or small mobile devices.

Tried to illustrate as best as possible in the following video:

https://github.com/user-attachments/assets/cbbc0f5f-1eed-46df-a64b-9a701b7124a7

2024-09-26 19:49 UTC, IanRamosC reviewed
Other than what @keoshi mentioned above, the padding in these cards make them unaligned
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/c3c2c981-eb0e-4622-a5eb-5c1751789a32">

2024-09-27 20:06 UTC, IanRamosC approved these changes
Looks good. Thanks for fixing the CSS issues.

2024-09-27 20:08 UTC, merged