WAF: Ensure mode is set during activation
Automattic/jetpack pull request #39690
Opened 2024-10-08 19:06 UTC by nateweller

## Proposed changes:

* Moves the functionality that ensures certain options exist from the `on_waf_activation` method (which runs on module activation) into the generic `Waf_Runner::activate` method.
* Fixes the case where a site has no "mode" option set, preventing the firewall from falling back into "silent" mode.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Test the basic WAF functionality.
* With the firewall active, delete the `jetpack_waf_mode` option from your site.
* Change one of the firewall settings.
* Verify the `jetpack_waf_mode` option has been reset to "normal".

2024-10-09 20:01 UTC, dkmyta requested changes
`Waf_Runner::activate` does not appear to run when the settings are updated or the WAF is triggered, it to only runs on plugin (or more specifically WAF module, as you've noted) activation - so if we delete the option it doesn't appear to get re-set by updating settings.

2024-10-28 20:47 UTC, dkmyta submitted a review, later dismissed
Works as described in standard and standalone mode. 

One thing I wanted to make note of to ensure it is the expected behaviour, if I delete WAF mode option but don’t reload the UI and update settings the WAF no longer functions to block test requests. It is also does not reset by simply reloading the Firewall UI but rather only on successful WAF settings updates.

2024-10-29 16:44 UTC, nateweller commented
Thanks for the review @dkmyta 😄 

> One thing I wanted to make note of to ensure it is the expected behaviour, if I delete WAF mode option but don’t reload the UI and update settings the WAF no longer functions to block test requests. It is also does not reset by simply reloading the Firewall UI but rather only on successful WAF settings updates.

This is correct, the change here ultimately just moves the setting of the default mode value from the "on waf _module_ activation" event to the more generic "on waf activation".

2025-01-07 17:42 UTC, kraftbj commented
@nateweller @dkmyta Is this something that's still needed? Could we land it? I updated the branch with trunk.

2025-01-07 22:16 UTC, dkmyta commented
@kraftbj We are holding on merging any changes to the WAF package until we improve our testing infrastructure and formalize a strategy for developing the package, specifically handling backwards compatibility and standalone mode. That project is unfortunately on hold as we focus on some priorities in the short term, but we hope to re-focus in the not so distant future.

2025-02-01 17:32 UTC, closed without merging

2025-02-01 17:32 UTC, nateweller commented
Closing this as the PR is breaking tests and needs changes, and is low priority right now.