Protect: Animate Illustration
Automattic/jetpack pull request #39825
Opened 2024-10-18 20:55 UTC by nateweller

## Proposed changes:

* Adds an animation effect to the "scan in progress" placeholder image for users without `reduced-motion` enabled.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Review the Storybook entry: `cd projects/js-packages/storybook && npm run storybook:dev`
* Review the animated image in Protect by starting a scan.

## Screenshots

![animation](https://github.com/user-attachments/assets/8a24dba5-7d6e-4418-acf7-e7dc1010c6a7)

2024-10-18 20:58 UTC, nateweller commented on projects/plugins/protect/changelog/add-protect-in-progress-animation
> +Adds an InProgressAnimation component
```suggestion
Significance: patch
Type: changed

Animated the "scan in progress" placeholder image
```

2024-10-18 21:36 UTC, dkmyta requested changes
Super nice addition!

We still face some issues with the padding of the `ScanningAdminSectionHero` when compared to the designs. Technically the padding of the `Container` is correct at `56px` but because the `InProgressAnimation` SVG includes some internal padding of its own the spacing gets thrown off a little. 

Images for reference:
![Screen Shot on 2024-10-18 at 14-32-25](https://github.com/user-attachments/assets/6dd56f4d-1624-4603-a35f-ae1c94da496e)

![Screen Shot on 2024-10-18 at 14-34-08](https://github.com/user-attachments/assets/cd380b7c-8b35-425e-ac10-466616a44f57)

2024-10-26 00:22 UTC, nateweller commented
@dkmyta I've updated the PR to apply a vertical padding of `32px` to the header, and ensure the width of the graphic matches the `270px` from the "Protect Meets Core" i1 designs (since the SVG has padding to accommodate the box shadows, the image width is set to `330px`).

2024-10-28 20:54 UTC, dkmyta approved these changes
Looks awesome!

2024-10-29 16:30 UTC, merged