Boost: Add foundation pages UI
Automattic/jetpack pull request #39832
Opened 2024-10-20 14:53 UTC by dilirity

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

## Does this pull request change what data or activity we track or use?

## Testing instructions:

* Go to '..'
*

2024-10-21 08:55 UTC, donnchawp requested changes
Looks great, except the regexp thing. Need to validate a URL, eventually.

2024-10-21 08:55 UTC, donnchawp commented on projects/plugins/boost/app/assets/src/js/features/foundation-pages/meta/meta.tsx
> +			lines.forEach( line => new RegExp( line ) );
We need to change this to a different check, for a URL, maybe.

2024-10-21 08:57 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/foundation-pages/meta/meta.tsx
> +			lines.forEach( line => new RegExp( line ) );
Removed in 755c4df

2024-10-21 09:16 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/foundation-pages/meta/meta.tsx
> +			lines.forEach( line => new RegExp( line ) );
I added it back but updated it to make sure we have at least one item in the list.

2024-10-22 14:09 UTC, haqadn commented on projects/plugins/boost/app/assets/src/js/features/foundation-pages/meta/meta.module.scss
> +}
Is this used?

2024-10-22 14:35 UTC, dilirity commented on projects/plugins/boost/app/assets/src/js/features/foundation-pages/meta/meta.module.scss
> +}
Removed.

2024-10-22 14:46 UTC, merged