Blocks: update remaining child blocks to API version v3
Automattic/jetpack pull request #40685
Opened 2024-12-19 14:39 UTC by jeherve

Fixes #40678

## Proposed changes:

It seems that we had forgotten to update a few of our child blocks in #34120.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Test all the blocks touched by this PR on a site running Gutenberg, and not using Gutenberg.

2024-12-30 09:46 UTC, coder-karen requested changes
Thank. you for following up on this! 

I tested each of the child blocks on Simple, WoA and self-hosted (Jurassic Ninja).

On WoA and self-hosted (both with and without Gutenberg installed and active), I noticed issues with the PR applied in both the Contact Info block and WhatsApp button, but only in the editor.

With the Send a Message block, styles appear to be missing for the button:
<img width="729" alt="Screenshot 2024-12-30 at 09 08 58" src="https://github.com/user-attachments/assets/d2673c02-0877-46c2-ae59-2dca3e650650" />


With the Contact Info block, in both WoA and self-hosted I'm having issues adding content in the editor (the fields appear generally un-editable, and once a few are added, no new fields seem to reappear).

I saw no relevant console errors.

On Simple, everything appeared to work as expected after the change was applied, except I was seeing block validation issues within the Recipe block both before and after the change (so, unrelated). I'll note it down anyway here:

<details>
<summary>One inner block with issues was for recipe details:</summary>

```
Content generated by `save` function:

<div class="wp-block-jetpack-recipe-details"><div class="wp-block-jetpack-recipe-details__detail"><p>Prep Time</p><p itemprop="prepTime" content="PT15M">15m</p></div><div class="wp-block-jetpack-recipe-details__detail"><p>Cook Time</p><p itemprop="cookTime" content="PT30M">30m</p></div><div class="wp-block-jetpack-recipe-details__detail"><p>Servings</p><p itemprop="recipeYield">4</p></div><div class="wp-block-jetpack-recipe-details__detail wp-block-jetpack-recipe-details__detail--print"></div></div>

Content retrieved from post body:

<div class="wp-block-jetpack-recipe-details"><div class="wp-block-jetpack-recipe-details__detail"><p>Prep Time</p><p itemprop="prepTime">15m</p></div><div class="wp-block-jetpack-recipe-details__detail"><p>Cook Time</p><p itemprop="cookTime">30m</p></div><div class="wp-block-jetpack-recipe-details__detail"><p>Servings</p><p itemprop="recipeYield">4</p></div><div class="wp-block-jetpack-recipe-details__detail wp-block-jetpack-recipe-details__detail--print"></div></div>
```

</details>

<details>
<summary>The other inner block with issues was for recipe steps:</summary>

```
Content generated by `save` function:

<ol itemscope itemprop="recipeInstructions" itemtype="https://schema.org/HowTo" class="wp-block-jetpack-recipe-steps"></ol>

Content retrieved from post body:

<ol itemprop="recipeInstructions" class="wp-block-jetpack-recipe-steps"></ol>
```

</details>

2024-12-30 11:53 UTC, coder-karen reviewed
I looked into this some more. With the Send a Message / WhatsApp button block, it looks like wrapping the returned content in a div with blockProps may solve that particular issue: `<div { ...blockProps }>` For that, `useBlockProps` also needs to be imported from `'@wordpress/block-editor'`
and then `const blockProps = useBlockProps();`. Though in my testing the HTML was ever so slightly different, so may need some tweaking.

2025-02-07 15:02 UTC, jeherve commented
> On Simple, I was additionally seeing block validation issues within the Recipe block both before and after the change (so, unrelated). I'll note it down anyway here:

I'm not too worried about those since that's a Beta block. At this point, we could probably remove that block ; it's been marked as a Beta block for a long time and there are no plans to work on that block again any time soon. 

> With the WhatsApp button, styles appear to be missing for the button

I fixed that in 899c7eecb544479c26d23a76e81883ed26bdcebd, thank you!

> With the Contact Info block, in both WoA and self-hosted I'm having issues adding content in the editor (the fields appear generally un-editable, and once a few are added, no new fields seem to reappear).

That's a good one! I can't figure out what's causing this for some reason!

@ellatrix If you have a bit of bandwidth, I'd love to have the eye of an expert on this. Thank you! :)

2025-03-21 15:08 UTC, monsieur-z commented
> That's a good one! I can't figure out what's causing this for some reason!

I've been able to make the email field work by adding the ` { ...blockProps }` props to the `div` wrapper, in its `edit.js` file. Applying the same changes to the other fields should fix the block altogether.

I'm happy to take the PR over if you lack bandwidth, @jeherve. Just let me know.

2025-03-24 14:34 UTC, jeherve commented
@monsieur-z If you have the bandwidth, I would really appreciate it, thank you!

2025-04-02 16:05 UTC, coder-karen approved these changes
This tests well for me now, thanks!

2025-04-04 15:25 UTC, merged

2025-04-04 17:51 UTC, jeherve commented
This was reverted in #42922, because I first needed to update the Calypso tests to match the new DOM structure, in https://github.com/Automattic/wp-calypso/pull/102395