[WIP] Simple Payments
Automattic/jetpack pull request #7511
Opened 2017-07-24 17:25 UTC by artpi

This introduces Simple Payments feature.

## Testing

TBD

(Remeber to do `PaypalExpressCheckout.sandbox = true;`) in console

2017-07-24 17:48 UTC, kraftbj commented
Marking it as a blocker as the Stark team has requested this make it into 5.2, so we need to review and decide before code freeze. The Stark team all willing to address feedback to help make it in on time if @artpi is in his offline hours.

2017-07-24 18:23 UTC, retrofox commented on modules/simple-payments/paypal-express-checkout.js
> +	getEnvironment: function() {
👍

2017-07-24 19:08 UTC, kraftbj commented on modules/simple-payments/simple-payments.css
> +
Should we add this to the concatenation in class.jetpack.php? That's a non-blocker for merge, but should be done or issued so we can get it in there.

2017-07-24 21:34 UTC, zinigor requested changes
I have added several minor comments, will actually test the functionality tomorrow so we can make it until code freeze.

2017-07-24 21:34 UTC, zinigor commented on modules/simple-payments/simple-payments.php
> + * TODO: Once the feature is fully shipped, create a file modules/simple-payments.php with a proper header to turn module on/off.
After a conversation with @rralian it turned out that there is no plan to make this into a module. The way it's done now will be enough to have this code always available. Keep in mind though that users will still be able to restrict loading these files using filters.

2017-07-24 21:34 UTC, zinigor commented on modules/simple-payments/simple-payments.php
> +		if ( ! wp_script_is( 'paypal-express-checkout','enqueued' ) ) {
Minor: missing space after comma.

2017-07-24 21:34 UTC, zinigor commented on modules/simple-payments/simple-payments.php
> +		wp_add_inline_script( 'paypal-express-checkout', "try{PaypalExpressCheckout.renderButton( '{$data['blog_id']}', '{$attrs['id']}', '{$data['dom_id']}', '{$data['multiple']}' );}catch(e){}" );
Paranoid mode: do you think it would be better to use `sprintf` and `esc_js` for all variables here?

2017-07-25 06:52 UTC, artpi commented on modules/simple-payments/simple-payments.php
> + * TODO: Once the feature is fully shipped, create a file modules/simple-payments.php with a proper header to turn module on/off.
Removed this comment

2017-07-25 06:52 UTC, artpi commented on modules/simple-payments/simple-payments.php
> +		if ( ! wp_script_is( 'paypal-express-checkout','enqueued' ) ) {
Done

2017-07-25 06:52 UTC, artpi commented on modules/simple-payments/simple-payments.php
> +		wp_add_inline_script( 'paypal-express-checkout', "try{PaypalExpressCheckout.renderButton( '{$data['blog_id']}', '{$attrs['id']}', '{$data['dom_id']}', '{$data['multiple']}' );}catch(e){}" );
Done

2017-07-25 14:27 UTC, zinigor approved these changes
Tested, works well, changes look good, thanks!

2017-07-25 19:03 UTC, merged

2017-08-08 16:12 UTC, georgestephanis commented on modules/simple-payments/simple-payments.php
> +		wp_enqueue_style( 'simple-payments', plugins_url( '/simple-payments.css', __FILE__ ) );
Why is this enqueueing, rather than just registering?