Sync: Send updated to transients only once
Automattic/jetpack pull request #8611
Opened 2018-01-25 00:05 UTC by enejb

This would make it so that we only send the transient data once and if plugins or theme modify it somehow that we only track the changes at one point.

#### Changes proposed in this Pull Request:
* Plugin can modify the transient that has what needs updating at any point. This helps to make sure that the data only gets set once. 

#### Testing instructions:
* Do the test pass? 
* Set a plugin to update, by modifying wp-includes/version.php file
* Set wp core to update by modifying the plugin file
* Set a theme to update by modifying style.css file

Do you see the events show up in the activity log?

2018-01-25 08:24 UTC, jeherve requested changes
A quick change for the parser.

2018-01-25 08:24 UTC, jeherve commented on sync/class.jetpack-sync-module-updates.php
> +			/**
Could you expand that docblock to include everything the parser needs? Thank you!

2018-01-25 15:53 UTC, lezama commented
wouldn't this just send the first change?

2018-01-25 15:53 UTC, lezama commented
I love the idea :)

2018-01-25 17:47 UTC, enejb commented
> Wouldn't this just send the first change? 
I need to add some tests to this so that it shows that it works as expected. I also think that I should be using a different add_action instead of shutdown here to queue the data. The idea here is that it gets queued before we send it. So we only add the latest available changes to the transiant. 

so if for some reason we do 
update_transient( a ):
update_transient( b ):
update_transient( c ):

we only sync `c`  because we populate the queue the data at end.

2018-01-30 13:44 UTC, lezama submitted a review, later dismissed
~@zinigor @dereksmart 🚢 it~

not yet, I am not convinced about the shutdown hook, needs more discussion with @enejb 😅

2018-01-30 13:46 UTC, lezama reviewed
not yet ready

2018-02-12 23:55 UTC, oskosk commented
@enejb this one needs a rebase

2019-01-16 21:13 UTC, enejb commented
Closing this in favor of https://github.com/Automattic/jetpack/pull/11155

2019-01-16 21:13 UTC, closed without merging