Allow universal analytics (analytics.js) to be used without WooCommerce
Automattic/jetpack pull request #9333
Opened 2018-04-17 20:10 UTC by allendav

Fixes #9129

#### Changes proposed in this Pull Request:

* Adds a filter to allow end users to force-activate Universal Analytics (analytics.js) even if WooCommerce is not present, e.g.

`add_filter( 'jetpack_wga_use_universal_analytics', '__return_true' );`

* Initializes singleton in init action to give time for plugins/themes to use that filter

#### Testing instructions:

* Install and connect Jetpack using this branch
* Install WooCommerce
* Enable Google Analytics Enhanced eCommerce Analytics in Jetpack Settings
* View source to ensure that analytics.js is enqueued in the head tag (at/near the top) (including the ec module request) and your eCommerce events (like Add to Cart) appear in your Javascript console Network tab (turn log preservation on)
* Deactivate WooCommerce
* Verify ga.js is enqueued instead (this is the "legacy" analytics JS)
* Add the filter above to force universal analytics on
* View source to ensure that analytics.js is enqueued in the head tag (at/near the top), including the pageview universal command (but not including the ec module command)

cc @joendotcom @georgestephanis @rtrevellyan 

IMPORTANT NOTE: It is the responsibility of the site owner to ensure their site's privacy policy correctly reflects the use of Google Analytics Universal Analytics when this filter is enabled.

2018-04-24 12:58 UTC, oskosk approved these changes
LGTM!

2018-05-24 12:48 UTC, oskosk commented
@allendav what's the status of this one? Should it be release in 6.2 ?

2018-05-29 20:51 UTC, allendav commented
Sorry @oskosk - lemme refresh this

2018-08-14 12:49 UTC, brbrr commented
> Deactivate WooCommerce
> Verify ga.js is enqueued instead (this is the "legacy" analytics JS)
I wasn't able to reproduce this behavior. After disabling Woo - it still enqueues new `analytics.js` file. So applying that filter didn't make any effect
![9333-1](https://user-images.githubusercontent.com/5654161/44092245-894b49de-9fd8-11e8-9ac3-8873116c4a0e.png)

Although, I was able to enqueue `analytics.js` with provided filter on newly created site _without_ Woo activation.
Steps I followed:
- Create new JN site, connect Premium Jetpack
- enable Google analytics via calypso settings
- Check `<head>` tag on site frontend. make sure legacy `ga` is loaded.
- Add provided filter somewhere (I added it into `jetpack.php` file)
- Check `<head>` tag on site frontend. make sure that new `analytics.js` loaded.

2018-08-23 19:28 UTC, oskosk requested changes

2018-08-23 19:28 UTC, oskosk commented on modules/google-analytics/wp-google-analytics.php
> +			Jetpack_Google_Analytics_Options::enhanced_ecommerce_tracking_is_enabled()
Seems like this filter is defaulting to `true` if enhanced ecommerce is enabled. so the provided filter in the testing instructions would not affect the truthiness we're getting after the step: `Enable Google Analytics Enhanced eCommerce Analytics in Jetpack Settings`.

Please @allendav  clarify. @brbrr comments about not seeing `ga.js` being logged come from this same fact.

2018-08-23 19:33 UTC, oskosk commented
I pushed a commit updating the version of introduction to `6.5.0` for the filters

2018-10-19 21:21 UTC, orenwolf commented
any chance we can get some reviews on this change? We're already using analytics.js on our pages, and it'd be nice to use the jetpack integration rather than having to disable it because it will only give us ga.js options currently.

2018-10-23 17:12 UTC, kraftbj commented
Hi @orenwolf this is in progress, which includes review and conversation about the code change. You can follow along for updates. Currently, it has been initially reviewed and awaiting reply from @allendav  to clarify some things.

2022-03-02 08:38 UTC, closed without merging