Widget: Added option to set DoNotTrack in Twitter Widget
Automattic/jetpack pull request #9359
Opened 2018-04-19 14:43 UTC by stevenlin-x

Fixes #6722

#### Changes proposed in this Pull Request:

* Added option to set DoNotTrack in Twitter Widget

#### Testing instructions:

*

#### Proposed changelog entry for your changes:

2018-04-20 11:37 UTC, jeherve requested changes
I think it may be best to add the attribute a bit later, and make it filterable so one can choose to turn this back to `false` if they want to. 

We have a list of `$data_attribs` just below; you could add it there, and set a default `false` value for that attribute in the `form` function, with a filter there.

What do you think?

2018-04-20 16:27 UTC, stevenlin-x commented
Hi jeherve,

I've also thought about this initially and have noticed the `$defaults = array(` line inside the `form` function, but didn't do it because I thought "$instance" array has fixed index parameters from another source.

As a result, I chose to go with what the original ticket issue suggested.

If you're certain this can work, then I agree setting a default is better than hard coding.

I've made the modification.

2018-04-23 09:05 UTC, jeherve requested changes
I would recommend adding a filter to offer the option to change the default value via code.

For this reason, when the form is being updated in the `update` function, I would recommend making sure the value saved for `dnt` is always a boolean.

2018-04-23 09:05 UTC, jeherve commented on modules/widgets/twitter-timeline.php
> +			'dnt'          => true,
Could you add a filter here, so folks can choose to change that value to false later on?

2018-04-23 16:48 UTC, stevenlin-x commented
@jeherve 

1.) I've added the filter in `form()` and the type & value checks in `update()`

2.) However, I think the type should be changed to string based `'true'` and `'false'`, no? Otherwise, it will run into problems with the `echo ' data-'` line below in `widget()` func. In other words, if it remains a bool, it'll output `"1"` instead.

2018-07-26 16:07 UTC, stevenlin-x commented
I've made a reply above.

2018-09-07 13:01 UTC, jeherve submitted a review, later dismissed
After thinking about this some more, I think we could take a simpler approach to this. I created a PR on your repo here with my ideas:
https://github.com/stevenlin-x/jetpack/pull/1

If you like my approach, you can merge that PR and the changes will automatically be ported to this PR.

Let me know what you think.

2018-12-06 14:02 UTC, jeherve approved these changes
This should now be good to merge! 👍

2019-01-02 16:36 UTC, merged