Improve semantics of form checkboxes for assistive technology
Automattic/jetpack pull request #9982
Opened 2018-08-03 19:34 UTC by pattiereaves

Fixes #

#### Changes proposed in this Pull Request:

* Puts the checkboxes in a list for assistive technology
* Adds a header above the list for assistive technology

#### Testing instructions:

* The checkboxes in the subscription form should be in a list
* That list should have a header which labels the list.
* When viewing the subscription options underneath the comments box on a site, the check boxes should not see bullets.
![image](https://user-images.githubusercontent.com/44990/43659234-37cad834-9710-11e8-83fd-7b3661bf927d.png)

#### Proposed changelog entry for your changes:

Improves the semantic markup of the checkboxes to subscribe to a comment,

2018-08-28 21:52 UTC, zinigor requested changes
This is great overall, thank you! I have added two comments about minor changes that are still needed here.

2018-08-28 21:52 UTC, zinigor commented on modules/subscriptions.php
> +		$unique_id = esc_attr( uniqid( 'jetpack-subscription-form-' ) );
There's no need to call `esc_attr`, you're doing it properly already by escaping late - when using the value for output.

2018-08-28 21:52 UTC, zinigor commented on modules/subscriptions.php
> +		$str = '<div><h4 id="'. esc_attr( $unique_id ).'" class="comment-subscription-form-title">Comment subscription preferences</h4><ul class="comment-subscription-form-list" aria-labelledby="'. esc_att
The "Comment subscription preferences" header needs to be translated, please use the gettext function for this:
```
__( 'Comment subscription preferences', 'jetpack' )
```

2018-08-28 22:39 UTC, pattiereaves commented
@zinigor I made the changes you requested; ready for a new review.

2018-08-29 08:10 UTC, zinigor commented on modules/subscriptions.php
> +		$str = '<div><h4 id="'. esc_attr( $unique_id ).'" class="comment-subscription-form-title">'.__( 'Comment subscription preferences', 'jetpack' ).'</h4><ul class="comment-subscription-form-list" aria
Please make sure the concatenation operator is separated from the strings with a space on both ends. Maybe this long line can be split into several lines too for greater readibility:
```
$str =
    '<div><h4 id="'
    . esc_attr( $unique_id )
    . '" class="comment-subscription-form-title">'
    . __( 'Comment subscription preferences', 'jetpack' )
    // and so on
```

Sorry I didn't notice it right away. The other fixes look good to me, thank you!

2022-03-02 08:38 UTC, closed without merging